### ISSUE TITLE
sammel-issue: Layout - title springen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#1]
@vdick and @dzhwmeisner für den Random-Modus müssen die title fixiert werden und die Hervorhebung sollte weiterhin abwechselnd sein.
Gilt für Seiten: 
- [x] kult05
- [x] kult06
- [x] kult07
- [x] gesch02
- [x] gesch03a
- [x] gesch03b

**Comment by andreaschu** [comment]
siehe zofar-issue [#99](https://github.com/dzhw/zofar/issues/99)

**Comment by dzhwmeisner** [comment]
fixed. need to be tested

**Comment by andreaschu** [comment]
looks good
