### ISSUE TITLE
Sammelissue Rotation + Anderes-Kategorie

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#100]
Bitte für die folgenden pages nochmal prüfen, ob die Items rotieren und falls nicht, sie bitte rotieren lassen. Bei der Prüfung haben sie nicht (immer) rotiert. Sollte in der Itembatterie eine "Anderes-Kategorie" enthalten sein, diese bitte immer an Ende der Skala verankern/nicht rotieren lassen.

Für die Module C1, D1, D3 betrifft das die folgenden Fragen/pages:

- [ ] D1_7 -> rotiert; hier bitte die "Anderes-Kategorie" festnageln.
- [ ] D1_8 -> rotiert; hier bitte die "Anderes-Kategorie" festnageln.
- [x] D1_17
- [x] D1_18
- [x] D1_20
- [x] D1_22
- [x] D1_23
- [x] D1_24 
- [x] D1_25
- [x] D1_27
- [x] D1_28
- [x] D3_11
- [x] D3_12
- [x] D3_21
- [x] D3_22

**Comment by SilinaKowalewski** [comment]
>  - [ ] D1_7 -> rotiert; hier bitte die "Anderes-Kategorie" festnageln.
>  - [ ]  D1_8 -> rotiert; hier bitte die "Anderes-Kategorie" festnageln.

@vdick oder @dzhwmeisner: Habe eine Unit eingefügt um dies zu ermöglichen. Unit bitte im css raus nehmen.

**Comment by karbecke** [comment]
In den Modulen C3, F1, F2, F3 betrifft das prinzipiell die folgende Fragen. Bitte prüfen, ob umgestzt:

- [ ] in C3 keine Frage
- [ ] F1_1 bitte Kategorie "anderes, und zwar:" am Ende der Itembatterie verankern
- [ ] F1_13 bitte Kategorie "ja, anderes Programm und zwar:" am Ende der Itembatterie verankern
- [ ] F2_1 bitte Kategorie "anderes, und zwar:" am Ende der Itembatterie verankern
- [ ] F2_8 bitte Kategorie "anderer Grund und zwar:" am Ende der Itembatterie verankern
- [ ] F2_11
- [ ] F2_14
- [ ] F3_1
- [ ] F3_12
- [ ] F3_19 --> bitte "nein ...." absetzen von "anderes Programm, und zwar:"

**Comment by SilinaKowalewski** [comment]
@karbecke: Soll bei der F3_19 die Kategorie "ja, anderes Programm, und zwar" verankert werden?

**Comment by karbecke** [comment]
Bei F3_19 bitte nur das Item "nein..." etwas absetzen

**Comment by SilinaKowalewski** [comment]
@karbecke: Ohne die Liste zu randomisieren? Oder soll "ja, anderes Programm, und zwar" mit randomisiert werden?

**Comment by karbecke** [comment]
Ja, die Liste bitte nicht randomisieren, nur absetzen

**Comment by SMajer** [comment]
Rotation der Items würde auch folgende Module betreffen: Fairness, Master-Vignetten, Politik, Promotion-Vignetten, Studienanfang:

- [ ] Fairness-Modul: KSM-fai03
- [ ] Fairness-Modul: KSM-fai04
- [ ] Fairness-Modul: KSM-fai05
- [ ] Fairness-Modul: KSM-fai16 --> rotieren, aber "anderer Grund, und zwar:______" immer unten in der Liste
- [ ] Master-Vignetten: KSM-ma07 --> rotieren, aber "anderes, und zwar:"immer unten in der Liste
- [ ] Master-Vignetten: KSM-ma08--> rotieren, aber "anderes, und zwar:"immer unten in der Liste
- [ ] Politik: KSM-pol03
- [ ] Politik: KSM-pol04
- [ ] Politik: KSM-pol05
- [ ] Politik: KSM-pol06
- [ ] Promotion-Vignetten: KSM-phd02--> rotieren, aber "sonstige, und zwar:"immer unten in der Liste
- [ ] Promotion-Vignetten: KSM-phd03--> rotieren, aber "sonstige, und zwar:"immer unten in der Liste
- [ ] Studienanfang: KSM-anf02

**Comment by karbecke** [comment]
- [ ] nicht in E1

**Comment by soheiss** [comment]
@SilinaKowalewski Ich habe fälschlicherweise die Randomisierung bei F2_14 rausgenommen, da soll aber eine rein. Mir ist es zu heiß, die wieder reinzunehmen - ich weiß nicht an welcher Stelle genau. Bitte ergänzt sie also wieder. Randomisiert werden sollen "Landessprache", "Deutsch", "andere Sprache, und zwar". Dabei soll "andere Sprache, und zwar" unten verankert werden.
Entschuldigt bitte die Umstände.
Liebe Grüße
