### ISSUE TITLE
Sammelissue metrische (Einzel-)Skalen nicht vertikal sondern horizontal anordnen

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#101]
Auf einigen pages werden metrische Skalen (vor allem Einzelskalen) vertikal angeordnet. Bitte auch hier horizontal anordnen mit den Skalenendpunkten darüber. Bitte nach dem Drehen darauf achten, dass der Abstand der Skalentitel/-endpunktlabel zu den buttons nicht zu groß ist (#84 ) und dass der Abstand zur Frage/Ausfüllanweisung ebenefalls nicht zu groß ist (#98 ).

Für die Module C1, D1, D3 sind folgenden Fragen/pages betroffen:

- [x] C1_8 
- [x] D1_26
- [x] D3_5

**Comment by karbecke** [comment]
in den Modulen C3, F1,F2,F3 betrifft dies die folgenden Fragen:

- [ ] F1_7
- [ ] F1_15
- [ ] F1_18
- [ ] F2_17

**Comment by lenamzimmer** [comment]
In den Modulen B1 und b2 bitte folgende Fragen anpassen:

- [ ] B1_4b -> Bitte auch die numerische Skalenbeschriftung entfernen und lediglich die Beschriftung der Endpole mit "gar nicht zufrieden" und "sehr zufrieden" stehen lassen.
