### ISSUE TITLE
Sammelissue: Größe Eingabe-/Textfelder

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#102]
Zum Teil passt die Größe der programmmierten Text-/Eingabefelder nicht zur (inhaltlichen) Länge der abgefragten Information. Entsprechend wäre es schön, wenn die Felder grafisch (nicht von der Zeichzahl) etwas angepasst werden könnten.

Für die Module C1, D1, D3 sind folgenden Fragen/pages betroffen:

- [x] D1_1 -> bitte etwas größer ziehen
- [x] D1_2 -> Textfelder für die Prüfungsfächer gerne etwas kleiner ziehen
- [x] D1_5 -> Textfeld für Berufsangabe gerne etwas größer ziehen
- [x] D1_11 -> offenes Eingabefeld gerne etwas kleiner ziehen
- [x] D1_12 -> das Eingabefeld gerne etwas kleiner ziehen und auch etwas weiter nach oben rücken
- [x] D1_21 -> Textfeld gerne etwas kleiner ziehen
- [x] D3_4 -> beide Eingabefelder gerne kleiner ziehen

**Comment by karbecke** [comment]
für die Module C3, F1, F2, F3 betrifft dies folgende Fragen

- [ ] in C3 keine Frage
- [ ]  F1_1 --> bitte etwas kleiner ziehen
- [ ] F1_12 --> bitte etwas kleiner ziehen
- [ ] F1_13 --> bitte kleiner ziehen
- [ ]  F1_19 --> bitte beide Felder etwas größer ziehen und zueinander bündig darstellen
- [ ] F2_7 --> bitte kleiner ziehen
- [ ] F2_10 --> bitte etwas kleiner ziehen und zueinander bündig darstellen
- [ ]  F2_11 --> bitte etwas kleiner ziehen
- [ ] F2_14 --> bitte kleiner ziehen
- [ ] F2_18 --> bitte beide Felder etwas größer ziehen und zueinander bündig darstellen
- [ ] F3_8 --> bitte alle Felder größer ziehen
- [ ] F3_9 --> bitte beide Felder etwas kleiner ziehen und zueinander bündig darstellen
- [ ]  F3_12 --> bitte etwas kleiner ziehen
- [ ]  F3_17 --> bitte beide Felder etwas größer ziehen und die Antwortoptionen voranstellen
- [ ]  F3_19 --> bitte Feld etwas größer ziehen
- [ ] F3_21 --> bitte offene Angabe als großes offenes Kommentarfeld darstellen

**Comment by soheiss** [comment]
Bitte auch für C2 auf folgender Seiten anpassen:

- [ ] C2_12 in max. Darstellung bitte schmaler und kleiner + in min. Darstellung bitte bündig zum Text

Liebe Grüße& vielen Dank
