### ISSUE TITLE
F-Module Anfangsfragen zusammengefasst

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#110]
Die Anfangsfragen in den F-Modulen werden zusammengefasst --> 79c680a ; f060e51; 
 
- F1_1 = F2_1 = F3_1
- F1_2 = F2_2 = F3_2
- F1_3 = F2_3 = F3_3
- F1_4 = F2_4 = F3_5
- F1_5 = F2_5 = F3_6
- F3_4 wird verschoben und ist neu: F3_6

Bitte die folgenden Bedingungen anpassen --> 6f4df6b; 31b3576
- [ ] transition
- [x] Variablennamen

**Comment by SilinaKowalewski** [comment]
In der Frage [F1_1](https://github.com/dzhw/SiD/blob/6f4df6b1f3bf1cf3e8417aa4f4e1051555430da8/Modul-F1_internationale_Studierende.md#f1_1) sind in der Kopfzeile die Variablen doppelt vergeben: 

> aeinnorm1; aeinnorm2; aeinnorm3; **aeinnormando**; **aeinnormando**

Habe hier die Variable "aeinnormand" verwendet.

**Comment by SilinaKowalewski** [comment]
Fragen wurden gelöscht und die Änderungen der Variablen umgesetzt. Die Transition konnten leider noch nicht umgesetzt werden, da hier noch Werte fehlen.
