### ISSUE TITLE
Preloads testen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#113]
@karbecke, hier wie eben besprochen eine Vorlage für die Preload-Liste zum Testen.
[tester_preloads.xlsx](https://github.com/dzhw/SiD/files/3754886/tester_preloads.xlsx)

**Comment by karbecke** [comment]
@andreaschu anbei a) die Tester-Liste sowie b) die Liste mit den HS-Standorten
[Listen HS mit Standorten_SiD_22.10.19.xlsx](https://github.com/dzhw/SiD/files/3760474/Listen.HS.mit.Standorten_SiD_22.10.19.xlsx)
[tester_preloads-1 (2).xlsx](https://github.com/dzhw/SiD/files/3760475/tester_preloads-1.2.xlsx)

**Comment by vdick** [comment]
@andreaschu die Preloads wurden in die Datenbank importiert

**Comment by SilinaKowalewski** [comment]
@karbecke: 

Preloads können nun getestet werden. Auch die Einblendbedingungen der jeweilien Hochschulen funktionieren bereits. Das "Ausblenden" für die Hochschulen, die keinen Standort haben, folgt noch.
