### ISSUE TITLE
C2_3 anlegen

### ISSUE THREAD

**Issue by soheiss** [dzhw/SiD#119]
Die Seite C2_3 existiert nicht - trotz Code. Bitte anlegen

Liebe Grüße& vielen Dank

**Comment by SilinaKowalewski** [comment]
@soheiss: 

Die Frage kann in der Form nicht umgesetzt worden. 
Ein Dropdown-Menü kann nicht mit zusätzlichen Antwortoptionen kombiniert werden. Zudem sind keine Suffixes möglich.

> seit meinem [Drop-Down-Menu Lebensjahre] **Lebensjahr**

Würde einfach mal einen "Vorschlag" programmieren ohne das Suffix. Können dann gerne noch mal persönlich drüber sprechen.

**Comment by SilinaKowalewski** [comment]
> SHOW is IF Zahl der Nennungen von gartmob bis gartka > 1

Ist leider ohne eine Hilfsvariable nicht umsetzbar. Sollte dieses Problem häufiger auftauchen bzw. eine hohe Priorität haben, legt bitte eine Hilfvariable an die "zählt" wie häufig eine Angabe in Frage A_15 gemacht wurde. Und verwendet diese an den entsprechenden Stellen in der PV

**Comment by SilinaKowalewski** [comment]
https://presentation.dzhw.eu/sid/C2_3.html

Hier kann Viktor vielleicht mit css noch etwas am Layout anpassen.

**Comment by andreaschu** [comment]
@vdick bekommst Du "seit meinem " links vor das DD-Menü?

**Comment by soheiss** [comment]
Habe mit Viktor gesprochen, aus dem DDM wird ein offenes Textfeld, s. decf63c

**Comment by soheiss** [comment]
Bitte ohne graue Linie, ist ja Single Choice.
Und kann theoretisch direkt hinter dem Textfeld ein Punkt stehen?
Danke und viele Grüße

**Comment by soheiss** [comment]
Punkt ergänzt (3ed6e74) und Zahlenfeld kleiner gemacht (4304a0c)
