### ISSUE TITLE
C2 Einblendungen, EK, usw.

### ISSUE THREAD

**Issue by soheiss** [dzhw/SiD#121]
In C2 fallen noch folgende Sachen zur technischen Umsetzung an:

- [x] C2_1: Einblendbedingungen für die Items funktionieren nicht (z.B. wird "länger dauernde   Krankheit/chronische Krankheit (z. B. Rheuma, MS, Darmerkrankung)" immer angezeigt). Bitte insgesamt noch einmal überprüfen -> es sollen jene Beeinträchtigungen angezeigt werden, die in SDK-gub01/A_32 angeklickt wurden

- [x] C2_1: Einblendbedingung für die Fragestellung funktioniert nicht. Aktuell werden immer beide Fragestellungen angezeigt.
@soheiss: Siehe Problem aus #119

- [x] C2_2: "nein" als Exklusivkategorie nach oben etwas absetzen und darunter  zur Einleitung der weiteren Items "Ja, und zwar:" einfügen (siehe Programmiervorlage)
@vdick: Kannst du dies bitte ähnlich einer anderen Frage umsetzen? Hatten dieses Problem schon mal in einer anderen Frage und da hast du das super umgesetzt :) 

- [x] C2_9: Einblendbedingung für die Items ist fehlerhaft: Die nicht anzuzeigenden Items werden zwar nicht schriftlich angezeigt, aber es sind dennoch die Zeilen sowie die Skala sichtbar

- [x] C2_11: "Ist mir nicht bekannt." und "Weiß ich nicht mehr." bitte als Exklusivkategorien programmieren und optisch etwas absetzen.
@soheiss: Es kann jeweils nur eine Antwortoption als Exklusivkategorie programmiert werden. Habe nun "Weiß ich nicht mehr." als Exklusivkategorie gesetzt. Kann aber gerne auch "Ist mir nicht bekannt." nehmen. Nur nicht beide. 

- [x] C2_13: Einblendbedinung für Items ist fehlerhaft -> Es sollen nur jene Beratungsangebote angezeigt werden, die in C2_12 mit "habe ich genutzt" markiert wurden.
@soheiss: Bitte die Einblendbedinungen in der Programmiervorlage angeben damit wir sie umsetzten können. 

Liebe Grüße& vielen Dank

**Comment by vdick** [comment]
C2_2 ab nächsten Rollout verfügbar

**Comment by soheiss** [comment]
Habe für das C2_1-Einblendbedingungsproblem eine Hilfsvariable angelegt (A_15) und die Bedingungen angepasst (C2_1): b6d50b6 und 3758cb6

Hoffentlich auch richtig... und ihr macht das in QML, oder?

**Comment by soheiss** [comment]
zu C2_11: Ok und Danke

**Comment by soheiss** [comment]
zu C2_13: Habe ich gemacht und auch tc-Fehler angepasst: 3f0d128

**Comment by SilinaKowalewski** [comment]
@soheiss: C2_13 und C2_12 habe ich angepasst. Bitte nach nächstem Rollout (heute mittag) noch mal prüfen.

**Comment by soheiss** [comment]
Ich musste nochmal grundlegend Filter und Einblendungen überarbeiten sowie ergänzen: e8ee191
und 3065669 - weil ich das leider zu früh comitted habe, gibts zwei Nrn., sorry!!
Bitte umsetzen

Liebe Grüße& vielen Dank!

**Comment by soheiss** [comment]
> 
> 
> @soheiss: C2_13 und C2_12 habe ich angepasst. Bitte nach nächstem Rollout (heute mittag) noch mal prüfen.

Hi @SilinaKowalewski 
Leider passt es noch nicht, musste nochmal die PG anpassen: c8a3e75

**Comment by SilinaKowalewski** [comment]
@soheiss: Habe ich angepasst.
