### ISSUE TITLE
Paradata

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#122]
@andreaschu: Bitte, wenn möglich, Paradaten miterheben (s. Mail 23.10.)

**Comment by SilinaKowalewski** [comment]
@andreaschu: 

Habe diese Variablen angelegt und auf der Index-Seite angesteuert. 
```
<zofar:variable name="width" type="number"/>
<zofar:variable name="height" type="number"/>
<zofar:variable name="isMobile" type="boolean"/>
<zofar:variable name="jsCheck" type="boolean"/>
<zofar:variable name="url" type="string"/>
<zofar:variable name="uas" type="string"/>
```

Reicht das oder sollen noch weitere Variablen angelegt werden?

**Comment by SilinaKowalewski** [comment]
Das hier ist der User Agent String.: `<zofar:variable name="uas" type="string"/>`

 

Ein Zeitstempel wird sowieso in der Survey-History mit erfasst. Ob das clientseitig geschieht oder nicht, wissen @vdick und @dzhwmeisner bestimmt besser als ich :)

**Comment by kastirke** [comment]
@karbecke Hier noch digital die Vorlagen für das Informed Consent mit Paradaten (betrifft Startseite und das Datenschutzblatt)

![Vorlage_Startseite](https://user-images.githubusercontent.com/30147532/67558728-cef54600-f717-11e9-9281-22a4adc4dac9.png)

[Vorlage_Datenschutzblatt_mitParadaten.docx](https://github.com/dzhw/SiD/files/3771288/Vorlage_Datenschutzblatt_mitParadaten.docx)
[Vorlage_Datenschutzblatt_mitParadaten.pdf](https://github.com/dzhw/SiD/files/3771289/Vorlage_Datenschutzblatt_mitParadaten.pdf)

**Comment by kastirke** [comment]
@karbecke Hier die neue PV, damit ihr die Indexseite an Silina kommunizieren könnt (siehe S. 8-10)
[Zofar_Programmieranleitung_2019-10-15.pdf](https://github.com/dzhw/SiD/files/3771293/Zofar_Programmieranleitung_2019-10-15.pdf)

**Comment by kastirke** [comment]
@SilinaKowalewski Nach Besprechung mit karbecke: Die von dir im qml angelegten Variablen reichen aus. Vielen Dank.

**Comment by andreaschu** [comment]
> @SilinaKowalewski Von karbecke kam die Frage, ob die Versionierung der Antworten zur Verfügung stünde. Kannst du dir das hier mal bitte anschauen: dzhw/zofar#252
> 
> Derzeit wird dieser "input correction counter" nicht exportiert und analysiert. Können diese Daten für den SiD-Pretest bereitgestellt werden? Bitte einmal mit Christian und Viktor Rücksprache halte

Ja, das können sie.

**Comment by kastirke** [comment]
@andreaschu Super! @karbecke Du brauchst also nicht weiter zu tun. Bitte erinnere uns vor dem Export, dass eine Art **counter.csv** mitgeliefert werden soll.
