### ISSUE TITLE
Sammelissue: Alle Zusatzmodule und gruppenspezifischen Module

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#123]
Da die Soziodemographie in das Grundprogramm verschoben wurde, endet die Befragung nach den Modulen. Es fehlt noch eine einheitliche Endseite zum Abschluss der Befragung, auf die wir von den Modulen aus weiterleiten können. Für die Programmierung der transitions muss die Endseite angelegt werden. Wer macht das bzw. gibt es so eine Seite schon?

Betrifft die Module:

- Student Services
-  Studienanfang
- Master-Vignetten
- Promotion-Vignetten
- Fairness
- Politik
- internationale Studierende 
- Studierende im Ausland
- Mobilität

**Comment by annamarkn** [comment]
Hat das DZHW bereits einen Standardtext für die letzte Seite?
z.B. "Vielen Dank für Ihre Teilnahme"? ggf. Links zur Projektseite mit Zeitplan einfügen für weiter Infos?
