### ISSUE TITLE
Modul Master-Vignetten: Seitenübergänge korrigiert

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#124]
Betrifft die Seitenübergänge mit Filter auf den Seiten KSM-ma02 und KSM-ma06. Diese hatten bisher nicht jene Fälle berücksichtigt, die die Filterfrage nicht beantwortet haben (SYSMISS). Der Filter/Übergang wurde um diese Option ergänzt (34a4ab1).
@andreaschu @SilinaKowalewski: Bitte kurz prüfen, ob so ok und umsetzen.

**Comment by SMajer** [comment]
Folgende Änderungen wurden im Master_Vignetten-Modul vorgenommen: c0c007f

- [ ] KSM-ma06: Frage ausgetauscht --> Version des DZHW aus B2 wurde übernommen

- [ ] KSM-ma05: transition wurde angepasst - alle, die in Split B2 waren, sollen KSM-ma06 überspringen und auf die folgenden Seiten weitergeleitet werden (gemäß ihrer Intention ein Masterstudium zu absolvieren) . @markusloe & @andreaschu: bitte kurz prüfen, ob das so stimmt.

- [ ] KSM-ma06: transition angepasst (auch mastplan = 3 bekommt Gründe für Promotion KSM-ma07)

- [ ] KSM-ma06: @andreaschu & @SilinaKowalewski : sind die Einblendbedingungen korrekt?

**Comment by andreaschu** [comment]
bei der nächsten Aktualisierung testbar

**Comment by annamarkn** [comment]
- KSM-ma06 Einblendebedingungen funktionieren nicht (neben den Kategorien in den Einblendebedingungen werden fälschlicherweiseauch auch ao1 und ao6 stets angezeigt)

**Comment by andreaschu** [comment]
Scheint so umgesetzt wie in der Programmiervorlage. Bitte diese noch mal prüfen und ggf. anpassen.
ao1 und ao6 haben keine Einblendbedingugen in der PV und werden deswegen immer angezeigt.
