### ISSUE TITLE
Modul Promotion-Vignetten: Seitenübergäng (mit Filter) nicht definiert

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#125]
Der Seitenübergang mit Filter auf der Seite "mvig2[deck][vignr]" ist unvollständig. Personen, die die Filterfrage (promoplan) nicht beantwortet haben (SYSMISS) müssen auf die Endseite der Befragung weitergeleitet werden. Diese Seite existiert aber noch nicht.

**Comment by andreaschu** [comment]
beim nächsten Update verfügbar

**Comment by annamarkn** [comment]
Konnte nicht getestet werden, weil bei nach der Beantwortung der notwendigen Angabe in "A_49A" (promoplan) für die Filterführung auf "mvig2[deck][vignr]" erscheint folgendes:

![image](https://user-images.githubusercontent.com/56629202/67783563-b7e18b80-fa6a-11e9-83ba-6f873f4b1d09.png)
