### ISSUE TITLE
Modul Politik- inhaltliche Änderungen

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#127]
Folgende Änderungen wurden im Modul Politik umgesetzt (d832e7e)
Bitte nachdem das Instrument geupdated wurde die Aufgabe abhaken.

- [x] KSM-pol01: Einleitungstext ergänzt (d832e7e)

- [x] KSM-pol02: Skalenbeschriftung geändert (d832e7e)

- [x] KSM-pol03: Fragetext angepasst + Skalenbeschriftung geändert (d832e7e)

- [x] KSM-pol05: neue Kategorie "kann ich nicht beurteilen" eingefügt + Fragetext angepasst (Professor*innen statt Hochschulen) (d832e7e)

- [x] KSM-pol06: Fragetext angepasst ("wie" aus Text entfernt) (d832e7e)

- [x] KSM-pol07: Itemstext angepasst (Übungskursleiter/in) (d832e7e)
@vdick ich habe hier einfach ein "\" eingebaut. Ist mglw. falsch.

**Comment by andreaschu** [comment]
Änderungen umgesetzt. Ist bei der nächsten Aktualisierung testbar.

**Comment by SMajer** [comment]
Alles korrekt umgesetzt, aber beim Testen sind neue Probleme aufgefallen (2c68ef4):

- [ ]  KSM-pol01 Abstand zwischen Einleitungssatz und Frage vergrößern

- [ ] KSM-pol03: Punkte hinter den Items entfernen

- [ ] KSM-pol05 + KSM-pol07: Im Fragebogen wird statt bspw. Professor*innen Professor\*innen angezeigt. Manchmal funktioniert die Schreibweise in den templates (\* damit es nicht kursiv geschrieben wird) und manchmal nicht. Wie muss man das in den tempaltes umsetzen?

**Comment by andreaschu** [comment]
>  KSM-pol05 + KSM-pol07: Im Fragebogen wird statt bspw. Professor*innen Professor\*innen angezeigt. Manchmal funktioniert die Schreibweise in den templates (* damit es nicht kursiv geschrieben wird) und manchmal nicht. Wie muss man das in den tempaltes umsetzen?

Oh, verstehe. Es wird in GitHub kursiv angezeigt, wenn es zwei * in einer Zeile gibt - ein Anfangs- und Endzeichen. Der Text dazwischen wird kursiv. 
Hier überschneiden sich unsere Layout-Tags mit denen von Markdown. Das müssen wir (Zofar) mal klären und ggf. die Tags ändern. Aber jetzt wissen wir erst mal, wie es gemeint ist. Also erst mal mit \* machen.
