### ISSUE TITLE
Modul Studienanfang - Einblendbedingung

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#129]
Es gibt eine Dopplung zwischen KSM-anf02 (neueste version 6853193) und einer Frage im Modul B2-Kultur B2_8a und B2_8b. Hier hatte man sich so geeinigt, dass wir die Frage in der Form des DZHW übernehmen und bei uns nur anzeigen, wenn die Befragten nicht das Modul B2-Kultur durchlaufen haben. Dazu müsste man einen Filter auf KSM-anf01 setzen (GOTO KSM-anf02 if splitvariable=?). 
Ich weiß allerdings nicht, was ich hier eingeben muss.
@andreaschu & @SilinaKowalewski: Wisst ihr hier weiter? Welcher Code ist das, wenn ein Befragter eine Frage nicht gesehen hat (technisches bzw. designbedingtes Missing)?

**Comment by andreaschu** [comment]
Die Split-Variablen sind im [Wiki ](https://github.com/dzhw/SiD/wiki#steuerungs--und-hilfsvariablen) von uns dokumentiert.
Wie die Werte belegt sind, wissen wir nicht. Das weiß @markusloe .

**Comment by SMajer** [comment]
> 
> 
> Die Split-Variablen sind im [Wiki ](https://github.com/dzhw/SiD/wiki#steuerungs--und-hilfsvariablen) von uns dokumentiert.
> Wie die Werte belegt sind, wissen wir nicht. Das weiß @markusloe .

Danke für die schnelle Rückmeldung. Ich bin mir gar nicht sicher, ob ich die Split-Variablen hierfür brauche. Ich benötige doch nur die Information, ob jemand diese Fragen angezeigt bekommen hat oder nicht (= designbedingtes Missing). Diesen Code bräuchte ich meinem Verständnis nach, oder?

**Comment by andreaschu** [comment]
bei der nächsten aktualisierung testbar

**Comment by andreaschu** [comment]
@SilinaKowalewski die Seiten sehen richtig programmiert aus. Schaust Du mal.

**Comment by SilinaKowalewski** [comment]
Seiten werden nun angezeigt! 👍
