### ISSUE TITLE
Modul Promotion-Vignetten: inhaltliche Änderungen

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#130]
Folgende Änderungen wurden im Modul umgesetzt (39d70be).
Bitte entsprechende Aufgabe abhaken, wenn Fagebogen geupdated wurde.

- [x] KSM-phd01: Einleitungssatz eingefügt

- [x] KSM-phd02: Fragetext angepasst + Items angepasst (erstes Item gestrichen) + Itemtext angepasst

**Comment by andreaschu** [comment]
bei der nächsten Aktualisierung testbar
