### ISSUE TITLE
Modul Master-Vignetten - Filter und inhaltliche Änderungen

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#131]
Folgende Änderungen wurden im Modul vorgenommen (0061d63).
Bitte entsprechende Aufgabe abhaken, sobald der Fragebogen geupdated wurde.

- [x] KSM-ma01: Einleitungssatz ergänzt (0061d63)

- [x] mvig[deck][vignr]: Skalenbeschriftung angepasst (wurde allerdings korrekt angezeigt?) (0061d63)

- [x] KSM-ma05: die Reihenfolge der Items in der Fragebogenvorschau entspricht nicht der Reihenfolge im template. Diese Items sollen nicht rotieren, sondern in der angegebenen Reihenfolge abgefragt werden. Bitte prüfen (0061d63)
--> die Items wurden randomisiert. Die Randomisierung wurde rausgenommen.

- [x] KSM-ma05: Skalenbeschriftung angepasst (0061d63)

- [x] KSM-ma07: Frage- und Itemtext angepasst  (0061d63)
@vdick hier wieder "ein\*e" evtl. problematisch/falsch eingebaut
 
- [x] KSM-ma07: Seitenübergang korrekt angelegt (GOTO KSM-ma09), aber funktioniert nicht (man kommt zu KSM-ma08) --> bitte prüfen (0061d63)

- [x] KSM-ma09: Frage- und Itemtext angepasst (0061d63)

**Comment by andreaschu** [comment]
beim nächsten Update testbar
