### ISSUE TITLE
Sammelissue: Smartphone - "Itemkarussell" fehlt

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#136]
Auf folgenden Seiten wir auf dem Smartphone kein "Itemkarussell" angezeigt. Darstellung fehlerhaft:

- [ ] KSM-ma05
- [ ] KSM-ma09

**Comment by andreaschu** [comment]
Bei mir schon.

![grafik](https://user-images.githubusercontent.com/30111489/67581727-d254f580-f748-11e9-8d95-501e45e51d73.png)

**Comment by SMajer** [comment]
> 
> 
> Bei mir schon.
> 
> ![grafik](https://user-images.githubusercontent.com/30111489/67581727-d254f580-f748-11e9-8d95-501e45e51d73.png)
> 
> Oder meinst Du die Item-Counter, also die Zahlen dazwischen?

Bei einer Kollegin wurde nichts angezeigt. Hab es eben nochmal mit meinem Handy getestet, aber bei mir werden die Itemskarussells auf beiden Seiten angezeigt. Ich frage sie nach dem Modell und den Konfigurationen.

**Comment by SMajer** [comment]
Ok, es betrifft den Item-Counter, der hier tatsächlich nicht angezeigt wird.
