### ISSUE TITLE
Sammelissue: Größe der Seite auf Bildschirmskalierung (an Frage) anpassen

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#137]
Bei einigen (vor allem kurzen) Fragen rutscht der blaue Balken mit der Beschriftung (Deutsches Zentrum für Hochschul- und Wissenschaftsforschung GmbH) weit hoch und der untere Teil des Bildschirms ist durch einen großen weißen Streifen geprägt. Eventuell könnte man den Balken fixieren?

Gilt insbesondere für folgende Seiten:

- [ ] KSM-fai01
- [ ] KSM-fai02
- [ ] KSM-fai06
- [ ] KSM-pol01
- [ ] KSM-pol02
- [ ] KSM-pol07
- [ ] KSM-anf01
- [ ] KSM-ma01
- [ ] V22_1 (bis _4) --> sprich die Vignetten bei im Master-Modul
- [ ] KSM-ma02
- [ ] KSM-ma04
- [ ] KSM-ma06
- [ ] KSM-phd01
- [ ] pvig149_1/ _2 --> sprich die Vignetten im Promotion-Modul

**Comment by andreaschu** [comment]
kannst Du mal einen Screenshot machen und Browser und Gerät angeben?

**Comment by SMajer** [comment]
Desktop PC, Windows 7 Professional, 32-Bit System. Bildschirmauflösung 1680x1050. Browser: Firefox, Version 70.0 (32-Bit).

![KSM_fai01_SM_28102019](https://user-images.githubusercontent.com/55697639/67664514-15d97a80-f968-11e9-8830-c41e053489b2.png)
