### ISSUE TITLE
B1_4a und B1_6

### ISSUE THREAD

**Issue by lenamzimmer** [dzhw/SiD#138]
Bitte folgende Anpassungen vornehmen:

Beide Fragen:
- [x] Kästchen bitte so programmieren, dass lediglich Zahlen zwischen 0 und 100 eingetragen werden können.
- [ ] Bitte ans Ende der Spalten jeweils "100 %" in fett schreiben -> ansonsten ist es schwer verständlich, was wir von den Befragten möchten.

B1_6:
- [x] Zeilenbeschriftung: "ich selbst" wird doppelt angegeben. Beschriftung der unteren Zeile heißt (entsprechend der Vorlage) "andere Personen"
- [ ] Option "trifft nicht zu" für "(Stief-)Mutter", "(Stief-)Vater" und "andere Person" fehlt. Bitte Option jeweils am Ende (oder direkt zu Beginn) der Zeilen als Exklusivkategorien ergänzen.

**Comment by SilinaKowalewski** [comment]
@lenamzimmer 
>  Kästchen bitte so programmieren, dass lediglich Zahlen zwischen 0 und 100 eingetragen werden können.

Hierfür benötigen wir noch einen Korrekturhinweis, der eingeblendet wird, falls eine Zahl außerhalb dieses Wertebereichs angegeben wird.

**Comment by SilinaKowalewski** [comment]
>  Option "trifft nicht zu" für "(Stief-)Mutter", "(Stief-)Vater" und "andere Person" fehlt. Bitte Option jeweils am Ende (oder direkt zu Beginn) der Zeilen als Exklusivkategorien ergänzen.

Das ist leider nach wie vor nicht möglich, da hier zwei Fragetypen kombiniert werden müssten.

**Comment by lenamzimmer** [comment]
> 
> 
> @lenamzimmer
> 
> > Kästchen bitte so programmieren, dass lediglich Zahlen zwischen 0 und 100 eingetragen werden können.
> 
> Hierfür benötigen wir noch einen Korrekturhinweis, der eingeblendet wird, falls eine Zahl außerhalb dieses Wertebereichs angegeben wird.

Liebe Silina,

als Korrekturhinweis bitte den folgenden Satz einfügen: "Bitte geben Sie den prozentualen Anteil an (0 bis 100)."

Danke!

**Comment by lenamzimmer** [comment]
> 
> 
> > Option "trifft nicht zu" für "(Stief-)Mutter", "(Stief-)Vater" und "andere Person" fehlt. Bitte Option jeweils am Ende (oder direkt zu Beginn) der Zeilen als Exklusivkategorien ergänzen.
> 
> Das ist leider nach wie vor nicht möglich, da hier zwei Fragetypen kombiniert werden müssten.

Ok, sorry, das hatte ich nicht mehr auf dem Schirm. Dann lassen wir es im Pretest jetzt erst einmal so.
