### ISSUE TITLE
D1_15: Beginn und Ende (Semester) - Antwortoptionen

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#139]
Bei der Frage [D1_15](https://github.com/dzhw/SiD/blob/master/Modul-D1_Bildungsbiographie_individuelle%20Merkmale.md#d1_15) ist bisher unklar, welche Antwortoptionen für `it1 (beginn01 – beginn05, ende01 – ende05): Beginn und Ende (Semester) `existieren sollen. 

Die PV beinhaltet lediglich die Antwortoptionen für beginn01-beginn05 und diese klingen etwas komisch: 

> ao1: (Dropdown bitte absteigend - beginn01 – beginn05): Sommersemester 2020 | Wintersemester 2019/2020 | Sommersemester 2019 | Wintersemester 2018/2019 | … | **Wintersemester 2020**

Werde zunächst die Antwortoptionen der Frage D1_13, sowohl für Beginn als auch für Ende, übernehmen.

**Comment by pbornkessel** [comment]
@SilinaKowalewski 

Das Drop-Down aus D1_13 passt hier nicht. 

Bitte für D1_15 folgende Optionen ins Drop-Down setzen:

infield = Semester (als 0) und dann weiter mit
Sommersemester 2020
Wintersemester 2019/20 
Sommersemester 2019
Wintersemester 2018/19 
Sommersemester 2018
Wintersemester 2017/18 
Sommersemester 2017
Wintersemester 2016/17 
Sommersemester 2016
Wintersemester 2015/16 
Sommersemester 2015
Wintersemester 2014/15 
Sommersemester 2014
Wintersemester 2013/14 
Sommersemester 2013
Wintersemester 2012/13 
Sommersemester 2012
Wintersemester 2011/12 
Sommersemester 2011
Wintersemester 2010/11 
Sommersemester 2010

**Comment by SilinaKowalewski** [comment]
Vielen Dank für die schnelle Antwort. 

Diese Drop-Down gilt dann für Beginn und Ende, richtig?

**Comment by SilinaKowalewski** [comment]
@pbornkessel: 

Für `ao2: -12: : weiß ich noch nicht` fehlt noch eine Variable. Könntest du mir bitte eine nennen?

**Comment by pbornkessel** [comment]
@SilinaKowalewski  
> Für `ao2: -12: : weiß ich noch nicht` fehlt noch eine Variable. Könntest du mir bitte eine nennen?

Nimm mal: stuverlwn

**Comment by SilinaKowalewski** [comment]
@pbornkessel: 

Soll dies eine Antwortoption sein? 
`anderer Abschluss (bspw. Ausländischer Abschluss | Magister) `

Bin etwas verwirrt wegen der Trennstriche

**Comment by pbornkessel** [comment]
@SilinaKowalewski 
> Soll dies eine Antwortoption sein?
> `anderer Abschluss (bspw. Ausländischer Abschluss | Magister) `

ja, "anderer Abschluss" soll die Antwortoption sein. Der Klammerausdruck dient, denke ich, als Beispiel bzw. soll der "|" wahrscheinlich eigentlich ein"," sein.

**Comment by SilinaKowalewski** [comment]
> stuverlwn

Diese Variable benötige ich, nach nem ersten Test, für jede Episode. Würde dann jeweils von stuverlwn01 - stuverlwn05 durchnummerieren
