### ISSUE TITLE
KSM-phd02: transition oder Fragetyp falsch

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#14]
Transition von [ksm-phd02](https://github.com/dzhw/SiD/blob/master/Modul_Promotion-Vignetten.md#ksm-phd02) bezieht sich auf andere Werte als in der Frage angegeben:

promgrund1 kann Werte von 1 "trifft überhaupt nicht zu" bis 5 "trifft voll und ganz zu" annehmen, 
transition scheint von CheckBox (wie in Mehrfachauswahl) auszugehen 
`GOTO KSM-phd03 IF promgrund1 (will nicht promovieren) ==1 (ja)`

**Comment by SMajer** [comment]
> 
> 
> Transition von [ksm-phd02](https://github.com/dzhw/SiD/blob/master/Modul_Promotion-Vignetten.md#ksm-phd02) bezieht sich auf andere Werte als in der Frage angegeben:
> 
> promgrund1 kann Werte von 1 "trifft überhaupt nicht zu" bis 5 "trifft voll und ganz zu" annehmen,
> transition scheint von CheckBox (wie in Mehrfachauswahl) auszugehen
> `GOTO KSM-phd03 IF promgrund1 (will nicht promovieren) ==1 (ja)`

Fehler in der Programmiervorlage. 
Frage@andreaschu: Kann promgrund1 von den übrigen Antwortoptionen getrennt nur mit 2 Antworten (ja vs, nein) dargestellt werden - also unterschiedliche Antwortformate innerhalb derselben Frage kreuzen? Oder müssen hier 2 Fragen programmiert werden: promgrund1 = einfachauswahl ja/nein + neue Frage: promgrund2-13 = mehrfachauswahl Skala 1-5?

**Comment by andreaschu** [comment]
Wenn promgrund1 nicht dieselbe Bewertungs-Skala haben soll wie die anderen Items der Matrix, kann es nicht Teil der Matrix sein. Es müssen also zwei Fragen sein: promgrund1 = Checkbox/ Mehrfachauswahl; promgrund2-12 = **Einfachauswahl**matrix (Einfachauswahl, weil man pro Item nur eine Wahl treffen kann)

**Comment by SMajer** [comment]
habe ich jetzt so im template geändert (siehe 27e3e25)
Jetzt sind es zwei Fragen auf derselben Seite KSM-phd02.

**Comment by SilinaKowalewski** [comment]
Wurde umgesetzt. Bitte prüfen.
