### ISSUE TITLE
D1_16: Fehlende Infos

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#140]
Für die Frage [D1_16](https://github.com/dzhw/SiD/blob/master/Modul-D1_Bildungsbiographie_individuelle%20Merkmale.md#d1_16) fehlen: 

- [ ] Antwortoptionen für die ao1
- [ ] Korrekturhinweis für die Beschränkung der Textfelder

**Comment by pbornkessel** [comment]
@SilinaKowalewski 

Nimm am besten die gleiche Semesterliste wie bei D1_15

Was meinst du genau mit Korrekturhinweis? Sowas wie 
"Bitte geben Sie die Dauer Ihrer Studienunterbrechung in Monaten an (0 bis 99)"

**Comment by SilinaKowalewski** [comment]
Ja, genau. So einen Hinweis meine ich. Dieser ist schon eingebaut.

**Comment by pbornkessel** [comment]
@SilinaKowalewski 

> Ja, genau. So einen Hinweis meine ich. Dieser ist schon eingebaut.

Heißt, es hat sich damit erledigt?

**Comment by SilinaKowalewski** [comment]
Jap :)
