### ISSUE TITLE
A_43: Individualisierung

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#142]
Wann sollen die einzelnen Items eingeblendet werden? Bitte eine Sichtbarkeitsbedinungen **pro Item** schreiben, die dann mit AND oder OR verknüpft werden. 

Bisher würde dann lediglich "Tätigkeit A" angezeigt werden. Laut PV soll aber eben dieses nicht eingeblendet werden werden. Was soll dann hier stehen?

```
SHOW it1 if eaktsens=2

SHOW it1 if eaktsens=2 AND sformdua=1

SHOW it1 & it2 if eaktsens=3

SHOW it1 & it2 if eaktsens=3 AND sformdua=1 :

SHOW it1 & it2 & it3 if eaktsens=4 :

SHOW it1 & it2 & it3 if eaktsens=4 AND sformdua=1 :

av:

kh:

fv:

hv:

fo: It1 den Text “Tätigkeit A” nicht anzeigen
```

**Comment by markusloe** [comment]
SHOW it1 IF eaktsens=2 OR eaktsens=3 OR eaktsens=4
SHOW it2 IF eaktsens=3 OR eaktsens=4
SHOW it3 IF eaktsens=4



Von: SilinaKowalewski [mailto:notifications@github.com]
Gesendet: Dienstag, 29. Oktober 2019 16:28
An: dzhw/SiD
Cc: Lörz, Markus; Assign
Betreff: [dzhw/SiD] A_43: Individualisierung (#142)


Wann sollen die einzelnen Items eingeblendet werden? Bitte eine Sichtbarkeitsbedinungen pro Item schreiben, die dann mit AND oder OR verknüpft werden.

Bisher würde dann lediglich "Tätigkeit A" angezeigt werden. Laut PV soll aber eben dieses nicht eingeblendet werden werden. Was soll dann hier stehen?

SHOW it1 if eaktsens=2







SHOW it1 if eaktsens=2 AND sformdua=1







SHOW it1 & it2 if eaktsens=3







SHOW it1 & it2 if eaktsens=3 AND sformdua=1 :







SHOW it1 & it2 & it3 if eaktsens=4 :







SHOW it1 & it2 & it3 if eaktsens=4 AND sformdua=1 :







av:







kh:







fv:







hv:







fo: It1 den Text “Tätigkeit A” nicht anzeigen

**Comment by markusloe** [comment]
So sollte es funktionieren
