### ISSUE TITLE
F3_7: Einblendbedingungen

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#143]
Bitte für die Frage [F3_7](https://github.com/dzhw/SiD/blob/master/Modul-F3_Mobilit%C3%A4t.md#f3_7) die Einblendbedingungen anpassen. 

Die Bedingungen sollten **pro Item** geschrieben (z.B.:  SHOW q1 IF ainfaus = 2  OR SYSMISS) werden und sich lediglich auf Werte beziehen. Inhaltliche Bedingungen wie "Masterstudierende mit Bachelorabschluss" kann ich leider nicht umgesetzen.

**Comment by markusloe** [comment]
SHOW q1 IF ainfaus = 2 OR SYSMISS
SHOW q2 IF ainfaus=3
SHOW q3 IF ainfaus=4

SHOW it1 IF ainfaus=2 OR ainfaus=3 OR ainfaus=4 OR SYSMISS
SHOW it... IF ainfaus=2 OR ainfaus=3 OR ainfaus=4 OR SYSMISS
SHOW it8 IF ainfaus=2 OR ainfaus=3 OR ainfaus=4 OR SYSMISS

SHOW it9 IF ainfaus=3 OR ainfaus=4
SHOW it... IF ainfaus=3 OR ainfaus=4
SHOW it16 IF ainfaus=3 OR ainfaus=4

SHOW it17 IF ainfaus=4
SHOW it... IF ainfaus=4
SHOW it24 IF ainfaus=4

**Comment by markusloe** [comment]
habe es jetzt mal etwas verkürzt geschrieben

**Comment by markusloe** [comment]
it6, it14 und it22 (Auslandsaufenthalt zwischen Bachelor- und Masterstudium) machen die Episoden unübersichtlich - man könnte aus unserer Perspektive diese Einblendungen auch einfach löschen - die Informationen bekommen wir aus anderen Variablen raus.

**Comment by SilinaKowalewski** [comment]
Super, vielen Dank für die schnelle Rückmeldung! Werde ich direkt einbauen. 

Für die Instruction gilt dann: 

SHOW is1 IF ainfaus = 2 OR SYSMISS
SHOW is1 IF ainfaus=3
SHOW is2 IF ainfaus=4

Richtig?

**Comment by SilinaKowalewski** [comment]
Bzw.: 

SHOW is1 IF ainfaus = 2 OR ainfaus=3 OR SYSMISS
SHOW is2 IF ainfaus=4

;)
