### ISSUE TITLE
transition zu KSM-anf02a und KSM-anf02b fehlen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#144]
entsprechend der Aufteilung von KSM-anf02 in KSM-anf02a und KSM-anf02b (vgl. 84766ec) passt die Weiterleitung von A_49a und A_49b nicht mehr. Dort wird noch auf KSM-anf02 geleitet, die es nicht mehr gibt. 
Wir mussten es für den Test anpassen, damit wir den Fragebogen bauen können. Aber das sollte noch mal überprüft und angepasst werden.

**Comment by linda-dzhw** [comment]
https://github.com/dzhw/SiD/commit/85f86152fcc4c38d6e142182d40cceda78fb13c0

21.02.2020, 12:26
