### ISSUE TITLE
test funktionstest - paradaten

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#145]
im Datensatz fehlt die Variable _uas_. Kannst Du mal schauen und sie hinzufügen?

**Comment by karbecke** [comment]
Dear @SilinaKowalewski, is the variable "uas" integrated?

**Comment by SilinaKowalewski** [comment]
Im Fragebogen ist die Variable angelegt und sollte somit auch in der Datenbank auftauchen.
