### ISSUE TITLE
Funktionstest

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#146]
Hier der Export des Testdatensatzes: 
[sid_export_funktionstest.zip](https://github.com/dzhw/SiD/files/3814136/sid_export_funktionstest.zip)
Eine Übersicht über die exportierten Dateien:
[Zofar_Informationen zum Datenexport.pdf](https://github.com/dzhw/SiD/files/3814138/Zofar_Informationen.zum.Datenexport.pdf)

**Comment by karbecke** [comment]
Reminder: Please export another kind of counter.csv --> see #122

**Comment by andreaschu** [comment]
Das können wir Euch erst für die Daten des Pretest liefern.
