### ISSUE TITLE
Modul: Promotion-Vignetten (first draft)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#16]
fca1034

**Comment by SMajer** [comment]
@andreaschu: Übergänge von Vignetten zu Gründen für (KSM-phd02) bzw. gegen (KSM-phd03) eingefügt. Filter nach Promotionsabsicht (promoplan). Einblendbedingung für unsichere Befragten (promoplan = 3) --> bitte kurz prüfen, ob das so korrekt ist (SHOW promgrund1 if promoplan = 3) siehe: cd6dd24

**Comment by SilinaKowalewski** [comment]
Modul programmiert. Bitte prüfen.

**Comment by SMajer** [comment]
Startseite mit Einleitungstext eingefügt und Text vor Vignette angepasst (8bdcc22). 
@SilinaKowalewski @andreaschu Frage zu Überleitung von Startseite KSM-phd01 zu Vignetten pvig1[deck][vignr]: Wie muss die Überleitung lauten? GOTO V[deck]_1 if IF h_deck==[deck]?

**Comment by andreaschu** [comment]
in dem Fall muss sie lauten:
`GOTO  pvig[deck]_1 IF h_deck_phd==[deck]`

**Comment by SMajer** [comment]
> 
> 
> in dem Fall muss sie lauten:
> `GOTO pvig[deck]_1 IF h_deck_phd==[deck]`

Transition eingefügt. Wird noch nicht angezeigt (Startseite + Übergang).
