### ISSUE TITLE
Änderungen Modul A Grundprogramm

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#161]
18.02.2020
16:27 Uhr

4db8dc2

**Comment by mcehrhardt** [comment]
Fortsetzung

4b59f80

10:35 Uhr

**Comment by karbecke** [comment]
#164

**Comment by mcehrhardt** [comment]
970cbe7

15:13 Uhr
Fortsetzung

**Comment by karbecke** [comment]
3e44d31

09:10
21.02.2020

**Comment by karbecke** [comment]
9f31c4d

10:08 Uhr

**Comment by karbecke** [comment]
45f8c58

bis inkl. E9b

12:58 Uhr
21.02.2020

**Comment by karbecke** [comment]
90ef837
bis inkl. A_26 

16:23 Uhr
21.02.2020

**Comment by karbecke** [comment]
cae07d4

bis inkl. A_36

24.02.
10:06 Uhr

**Comment by karbecke** [comment]
bf949ec

24.02.
16:20 Uhr

bis inkl. N_6

**Comment by karbecke** [comment]
677e523

24.02.
17:37 Uhr

bis Ende
