### ISSUE TITLE
Modul B

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#167]
**(1) Zeitpunkt des Pretest-IST-Standes:**
Am Dienstag, den **18.02.** wurden B1 und B2 tagsüber auf den QML-Programmierstand gebracht (fertig zwischen 15.30 und 15.45 Uhr).
--> siehe GitHub-History

**(2) Zeitraum der Überarbeitung des SOLL-Standes**
Am Mittwoch, den **19.02.** wurden B1 und B2 tagsüber auf den aktuellen Stand gebracht.
--> siehe GitHub-History

**Modul B1/ SOLL-Stand**
[B1_Modul_Geschlechtersegregation.docx](https://github.com/dzhw/SiD/files/4230336/B1_Modul_Geschlechtersegregation.docx)

**Modul B2/ SOLL-Stand**
[B2_Modul_Kulturelle Rahmenbedingung.docx](https://github.com/dzhw/SiD/files/4230339/B2_Modul_Kulturelle.Rahmenbedingung.docx)

**Comment by andreaschu** [comment]
Bitte nicht so große Issues und unbedingt die Commit-Nummer schreiben.
Ich habe dieses Issue aufgeteilt in die Issues #174 und #175 und schließe dieses Issue.
