### ISSUE TITLE
Modul: Master-Vignetten (first draft)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#17]
74345b3
(updated: 5a077cb)

**Comment by andreaschu** [comment]
@SMajer : first draft des Vignetten-Moduls ist fertig. 
Hinweis zum testen: Zufallszuteilung erfolgt auf index-page (mindesten bis /offer klicken). Von /KSM-anf05 wird auf Vignetten weitergeleitet. Von den Vignetten wird auf /E1_1 weitergeleitet

**Comment by andreaschu** [comment]
Fragen ab [ksm-ma02](https://github.com/dzhw/SiD/blob/master/Modul_Master-Vignetten.md#ksm-ma02) noch nicht programmiert.
Sinnvoller eine eigene questionnaire.xml zu benutzen oder in Template als Postfix?

**Comment by andreaschu** [comment]
@SMajer der Zufallswert der Hilfsvariable h_deck wird auf Seite SDK-scr01 angezeigt.

**Comment by SMajer** [comment]
> 
> 
> Fragen ab [ksm-ma02](https://github.com/dzhw/SiD/blob/master/Modul_Master-Vignetten.md#ksm-ma02) noch nicht programmiert.
> Sinnvoller eine eigene questionnaire.xml zu benutzen oder in Template als Postfix?

Diese Frage würde ich gerne an eine/n Programmierer/in weiterleiten, ich kann das leider nicht beurteilen.

**Comment by SilinaKowalewski** [comment]
Beide Optionen würden eigentlich gleich gut funktionieren. 

Werde aber eine eigene questionnaire.xml anlegen um es etwas übersichtlicher zu halten.

**Comment by SilinaKowalewski** [comment]
Zusätzliche Fragen wurden programmiert. Bitte prüfen.

**Comment by SMajer** [comment]
@andreaschu + @SilinaKowalewski : Work in progress. Seitenübergänge eingefügt und Seitenzahlen angepasst (KSM-ma07 auf 2 Seiten gesplittet)- Zuweisung der Vignetten scheint zu funktionieren.
Fortschritt/Änderungen siehe: abf4fa6

**Comment by SilinaKowalewski** [comment]
Vignetten geupdated.

**Comment by SMajer** [comment]
> 
> 
> Vignetten geupdated.

Vignetten ok (neues Layout + Zuweisung (vier Vignetten aus einem Deck) funktioniert).  
ABER: Weiterleitung von "mvig[deck][vignr]" auf KSM-ma02 funktioniert nicht? @andreaschu , @SilinaKowalewski ?

**Comment by SilinaKowalewski** [comment]
Habe die Übergänge nun noch mal angepasst. Der Sprungt von V[deck]_4 auf KSM-ma02 sollte nun funktionieren.

**Comment by SMajer** [comment]
> 
> 
> @SMajer kann das issue geschlossen werden?

Ja, das hat sich erledigt.
