### ISSUE TITLE
Modul C

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#170]
**(1) Zeitpunkt des Pretest-IST-Standes:**
C1: bis 20.02. ca. 11:45 Uhr
C2: bis 20.02. 11.30 Uhr
C3: bis 20.02.

--> siehe GitHub-History

**(2) Zeitraum der Überarbeitung des SOLL-Standes**
C1: ab 20.02.12.55 Uhr bis 15.20 bzw. 24.02.2020
C2: ab 20.02. 12.00 Uhr bzw. 21.02.2020
C3: ab 21.02./24.02.2020 

--> siehe GitHub-History

**Modul C1/ SOLL-Stand**
[C1_Modul_Kind.docx](https://github.com/dzhw/SiD/files/4243881/C1_Modul_Kind.docx)

**Modul C2/ SOLL-Stand**
[C2_Modul_Beeinträchtigt.docx](https://github.com/dzhw/SiD/files/4243883/C2_Modul_Beeintrachtigt.docx)

**Modul C3/ SOLL-Stand**
[C3_Modul_Migration.docx](https://github.com/dzhw/SiD/files/4243885/C3_Modul_Migration.docx)

**Comment by andreaschu** [comment]
Bitte nicht so große Issues und unbedingt die Commit-Nummer schreiben.
Ich habe dieses Issue aufgeteilt in drei Issues #171, #172 und #173 und schließe dieses Issue.
