### ISSUE TITLE
E2: Studienanfang: Änderungen des Fragebogens

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#178]
- [x] template an aktuelle Fragebogenversion nach Pretest angepasst: f13a3ed
- [x] Zusätzlich wurden nachträglich Variablennamen korrigiert 5fbd0ca

- **KSM-anf01**: Einleitungstext geändert + transition zu KSM-anf02 angepasst.
- **KSM-anf02**: Seitenbezeichnung geändert (keine Einteilung mehr in KSM-anf02a und b mehr) + 1. und 2. Antwortkategorie geändert + Antwortoption "weiß nicht" geändert + Seite KSM-anf02b gelöscht (s.o.) + Einblendbedingung eingefügt.
- **KSM-anf03**: Items gestrichen (2, 9, 15, 17, 20, 24) + altes Item 6, 10, 13 umformuliert.
- **KSM-anf04**: Frageformulierung angepasst + Formulierung aller Items geändert + Antwortkategorien Benennung der Endpunkte geändert.
- **KSM-anf05**: neue Seite eingefügt (alte Seite KSM-anf05 jetzt Seite KSM-anf07).
- **KSM-anf06**: neue Seite eingefügt (alte Seite KSM-anf06 jetzt Seite KSM-anf08).
- **KSM-anf07**: Fragetext geändert + Item 2 und 5 angepasst + Item 6 gestrichen + Antowrtoption 6 geändert.
- **KSM-anf08**: Fragetext geändert + Antwortoption 6 geändert.

**Comment by SMajer** [comment]
Zusätzlich wurden nachträglich Variablennamen korrigiert 5fbd0ca

**Comment by andreaschu** [comment]
**KSM-anf01**: KSM-anf02a gibt es nicht mehr, wurde zu KSM-anf02 geleitet

**Comment by SMajer** [comment]
@andreaschu: Stimmt! transition wurde im template angepasst: c5c5a12

**Comment by meyerja** [comment]
@andreaschu @SilinaKowalewski : b8cba72

- neue Seite KSM-anf05 und 06 eingefügt 
- alte Seite KSM-anf05 und 06 jetzt KSM-anf07 und 08
- KSM-anf07 und KSM-anf08: Fragetext und Antwortoptionen geändert
- alte Seite KSM-anf07 und 08 jetzt KSM-anf09 und 10
- neue Seite KSM-anf11 eingefügt

**Comment by christian-fr** [comment]
@meyerja Zum einen werde ich aller Voraussicht nach in Zukunft die Aufgaben von Silina übernehmen, und zum anderen hatten wir ja jetzt alle schon ein wenig Gelegenheit, uns in die Arbeit mit GitHub einzugewöhnen. Vielleicht könnten wir uns nochmal darüber austauschen, wie das Arbeiten in issues für beide Seiten sinnvoll gestaltet werden kann. Also was ihr als Projekt dort braucht und sinnvoll findet - und was für unsere Seite sinnvoll oder hilfreich wäre.

Von meiner Warte aus kann ich z. B. sagen, dass etwas knappere issues angenehmer sind, weil sie sich abarbeiten, abhaken und dann meist relativ zeitnah auch wieder schließen lassen. Das gibt auf der einen Seite das Gefühl, mit Aufgaben oder Problemen vorangekommen zu sein, auf der anderen lässt es die zu bewältigenden Aufgaben vielleicht klarer und konziser erscheinen.

Ich kenne auch die Perspektive aus dem Forschungsprojekt - da will man die Übersicht nicht verlieren und vielleicht greift das issue dort auch größere Problemstellungen auf, die noch länger andauern und sich nicht ganz so einfach und schnell abhaken lassen.

Ab einer gewissen länge werden issues aber tatsächlich unübersichtlich - _und das Risiko steigt, dass eigentlich wichtige Aufgaben darin untergehen und nicht, zu spät oder nicht eurer Intention entsprechend bearbeitet werden können._ Das kann euch später sicherlich auch das Testen von Änderungen erschweren.

Issues, die sich als zu groß und längerfristiger herausstellen, können auch geschlossen und mehrere kleinere Issues zerlegt werden. Durch die Verweise auf andere Issues in den Kommentaren eines issues bietet GitHub großartige Möglichkeiten, den roten Faden dennoch nicht zu verlieren und jederzeit nachzuvollziehen, auf welchen Pfaden sich die Ausgangsprobleme weiterentwickelten.

----------------
Auch bei diesem Issue wäre daher zu überlegen, ob es, sobald die ursprüngliche Aufgabe zufriedenstellend erledigt wurde, geschlossen wird, oder ob es von eurer Seite aus Gründe gibt, es noch weiter offen zu lassen.

-----------

Nun zum eigentlichen Punkt:

Auf der neuen page **KSM-anf05** gibt es eine neue Variable _maßnahm*_ ("*" als Platzhalter, hier: für Ziffern) - ich rate dringend davon ab, (deutsche) Sonderzeichen wie das **ß** in Variablennamen zu benutzen. Ich gehe auch sehr stark davon aus, dass das technisch nicht machbar sein wird.

Ich schlage daher vor, die Variablen in _massnahm*_ umzubenennen.

**Comment by meyerja** [comment]
@christian-fr : In Ordnunng, ich werde die Issues schließen, wenn alles umgesetzt und getestet wurde. Es werden wahrscheinlich ohnehin nur noch kleinere Änderungen vorgenommen. Wenn es sich anbietet, kann ich dazu gerne neue Issues erstellen. 

Danke für den Hinweis, Variablennamen auf KSM-anf05 in massnahm* geändert: fea817b

**Comment by christian-fr** [comment]
> @christian-fr : In Ordnunng, ich werde die Issues schließen, wenn alles umgesetzt und getestet wurde. Es werden wahrscheinlich ohnehin nur noch kleinere Änderungen vorgenommen. Wenn es sich anbietet, kann ich dazu gerne neue Issues erstellen.

Danke :)

> Danke für den Hinweis, Variablennamen auf KSM-anf05 in massnahm* geändert: [fea817b](https://github.com/dzhw/SiD/commit/fea817b2969dd1d1e1b739ebe128f7a652f7861e)
> 
>     * [x]  in QML übernommen (#250)

Ist im aktuellen rollout schon drin.

**Comment by meyerja** [comment]
@christian-fr : 

- [ ] Weiterleitung von KSM-anf01 auf KSM-anf02 funktioniert nicht (durch "weiter" klicken nicht möglich, nur durch eintippen in Adresszeile im Browser möglich) 

- [ ] KSM-anf03: Reihenfolge der Items nicht in der aktuellen Version des templates (letzte Änderungen wurden nicht übernommen)

- [ ] KSM-anf10: Item 10 wurde geändert: d09f1b8
