### ISSUE TITLE
Update B1_Geschlecht

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#18]
Update [B1_Geschlecht](https://github.com/dzhw/SiD/blob/master/Modul-B1_Geschlecht.md) 16.09.2019

- [x] Please program PV B1_Geschlecht

**Comment by karbecke** [comment]
New Update B1_Geschlecht 19.09.2019

- [ ]  Please program PV B1_Geschlecht

**Comment by SilinaKowalewski** [comment]
Das Modul B1_Geschlecht wurde aktualisiert. 

Die Fragen [B1_6](https://github.com/dzhw/SiD/blob/master/Modul-B1_Geschlecht.md#b1_6) und [B1_7](https://github.com/dzhw/SiD/blob/master/Modul-B1_Geschlecht.md#b1_7) können in der Form allerdings nicht programmiert werden und wurden daher nicht bzw. abgeändert programmiert. Werde hierfür noch mal ein Issue anlegen. 

Bitte checkt aber zunächst du programmierten Fragen.
