### ISSUE TITLE
Verschobene Fragen

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#181]
Liebes ZOFAR-Team,
einige Fragen wurden im Laufe der weiteren Fragebogenentwicklung in andere Modul verschoben.
Damit für euch keine doppelt Arbeit entsteht (durch Löschung und dann Neuprogrammierung), findet ihr nachstehend eine Auflistung aller verschobenen Fragen sowie das Modul in welches diese verschoben wurden.

B2_5 verschoben nach N
D1_9 verschoben nach A (Grundprogramm)
D1_18 verschoben nach Modul B2
D1_27 verschoben nach D3
D1_28 verschoben nach D3
D3_1 verschoben nach N
F3_23 verschoben nach N
F3_24 verschoben nach N

Liebe Grüße

**Comment by markusloe** [comment]
zur Infor N befindet sich am Ende von A (Grundprogramm)

**Comment by andreaschu** [comment]
Bitte als Kommentar an die jeweilige Stelle schreiben. In einem Issue ist es an der falschen Stelle und wird übersehen, wenn wir an der Bearbeitung anderer Issues arbeiten.

![grafik](https://user-images.githubusercontent.com/30111489/75438784-dbeda480-5958-11ea-8549-7cd4f3214099.png)

![grafik](https://user-images.githubusercontent.com/30111489/75438562-713c6900-5958-11ea-848f-c5de187b4c4d.png)
