### ISSUE TITLE
E2: Master-Vignette: Änderung des Fragebogens

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#183]
- [x] template an aktuelle Fragebogenversion nach Pretest angepasst: 609e2d1
- [x] Zusätzliche Änderung Seite KSM-ma08: Gender-Stern eingefügt 874e33f
- [x] Zusätzliche Änderung Seite KSM-ma06: Variablenname gelöscht und Seite KSM-ma08: Itemlabel geändert be89f2f
- [x] OK, haben wir angepasst. Bitte prüfen, ob das so richtig ist. 7c98d7e
- [x] Stimmt, sorry. transition wurde nochmal wie von dir vorgeschlagen angepasst b0d64e7

- KSM-ma01: Einleitungstext geändert.

- KSM-ma05: Einen Variablennamen geändert (Umlaut geändert) + Antwortkategorien geändert (Endpunkte umbenannt) + transition angepasst.

- KSM-ma06: Fragetyp geändert + Fragetext geändert + Instruktion geändert + Item 1 gelöscht + Einblendbedingungen angepasst + Items- und Antwortoptionen verändert/getauscht + transition gelöscht.

- KSM-ma07: Fragetext geändert + Items geändert.

- KSM-ma08: Seite komplett gelöscht.

- KSM-ma09: neue Seite KSM-ma08 + Fragetext und Antwortkategorien angepasst. Gender-Stern ergänzt.

**Comment by SMajer** [comment]
Zusätzliche Änderung Seite KSM-ma08: Gender-Stern eingefügt 874e33f

**Comment by SMajer** [comment]
Zusätzliche Änderung Seite KSM-ma06: Variablenname gelöscht und Seite KSM-ma08: Itemlabel geändert be89f2f

**Comment by andreaschu** [comment]
@SMajer KSM-ma06 wird so nicht funktionieren. Das sind zu viele Spalten mit zu langen Überschriften.
Eventuell die Einkommensangaben als DropDown-Listen bauen?

**Comment by andreaschu** [comment]
```
tr: GOTO KSM-ma06 
GOTO KSM-ma07 IF sabsan = 6 OR sabsan = 7 OR sabsan = 8 OR sabsan = 9 
GOTO KSM-ma07 IF sabsan = 5 AND sabslaja <>1
```

Wenn alle Befragten zu KSM-ma06 geleitet werden sollen, sind alle weiteren Bedingungen irrelevant, weil die erste immer gilt. Bitte noch mal checken und korrigieren.

**Comment by SMajer** [comment]
> 
> 
> @SMajer KSM-ma06 wird so nicht funktionieren. Das sind zu viele Spalten mit zu langen Überschriften.
> Eventuell die Einkommensangaben als DropDown-Listen bauen?

@andreaschu: Wie müsste das dann umgesetzt werden? Dazu muss man eine Liste einbauen, aber in der Programmieranleitung wird das nicht näher erläutert.

**Comment by SMajer** [comment]
> 
> 
> ```
> tr: GOTO KSM-ma06 
> GOTO KSM-ma07 IF sabsan = 6 OR sabsan = 7 OR sabsan = 8 OR sabsan = 9 
> GOTO KSM-ma07 IF sabsan = 5 AND sabslaja <>1
> ```
> 
> Wenn alle Befragten zu KSM-ma06 geleitet werden sollen, sind alle weiteren Bedingungen irrelevant, weil die erste immer gilt. Bitte noch mal checken und korrigieren.

@andreaschu: Ich finde die transition "GOTO KSM-ma06" auf Seite KSM-ma05 nicht.

**Comment by SilinaKowalewski** [comment]
> @andreaschu: Ich finde die transition "GOTO KSM-ma06" auf Seite KSM-ma05 nicht.

@SMajer: So sieht die aktuelle Programmiervorlage der Seite KSM-ma05 aus.
![image](https://user-images.githubusercontent.com/48087320/75982384-d2c77f00-5ee6-11ea-86dc-02cc77164173.png)

Die Darstellung ist leider etwas unübersichtlich. Wenn du die Transition in der PV entsprechend umsetzt können wir das in der Programmierung übernehmen. Aktuell macht die Transition aber nicht so viel Sinn.

**Comment by SilinaKowalewski** [comment]
> @andreaschu: Wie müsste das dann umgesetzt werden? Dazu muss man eine Liste einbauen, aber in der Programmieranleitung wird das nicht näher erläutert.

Es reicht, wie in der Programmiervorlage beschrieben, wenn bei dem Fragetyp angegeben wird, dass es sich um eine Einfachauswahl mit Dropdown-Menü handelt. Dann können wir die bestehende Liste der Antwortoptionen entsprechend abändern und die Frage wird deutlich entzerrt.

**Comment by SilinaKowalewski** [comment]
KSM-ma06: 

Die Sichtbarkeitsbedingungen für die Items lautet akutell: 
```
vc: 
SHOW lohnsta1 and lohnsta2 and lohnphd if sabsan = 3 AND sabslaja = 1
SHOW lohnba and lohnma and lohnphd if sabsan = 1
```

Welche der beiden Bedingungen soll denn für "lohnphd" gelten? Falls beide gelten sollen, müssen diese or oder and verknüpft werden?

**Comment by SMajer** [comment]
> 
> 
> > @andreaschu: Ich finde die transition "GOTO KSM-ma06" auf Seite KSM-ma05 nicht.
> 
> @SMajer: So sieht die aktuelle Programmiervorlage der Seite KSM-ma05 aus.
> ![image](https://user-images.githubusercontent.com/48087320/75982384-d2c77f00-5ee6-11ea-86dc-02cc77164173.png)
> 
> Die Darstellung ist leider etwas unübersichtlich. Wenn du die Transition in der PV entsprechend umsetzt können wir das in der Programmierung übernehmen. Aktuell macht die Transition aber nicht so viel Sinn.

@SilinaKowalewski: Stimmt, macht nicht viel Sinn. Wir haben das mal versucht anzupassen b430278

**Comment by SMajer** [comment]
> 
> 
> > @andreaschu: Wie müsste das dann umgesetzt werden? Dazu muss man eine Liste einbauen, aber in der Programmieranleitung wird das nicht näher erläutert.
> 
> Es reicht, wie in der Programmiervorlage beschrieben, wenn bei dem Fragetyp angegeben wird, dass es sich um eine Einfachauswahl mit Dropdown-Menü handelt. Dann können wir die bestehende Liste der Antwortoptionen entsprechend abändern und die Frage wird deutlich entzerrt.
> 
> Zudem würde ich vorschlagen eine Default-Kategorie mit aufzunehmen. Das heißt, die Kategorie die anzeigt werden soll, wenn der Proband noch nichts ausgewählt hat. Zum Beispiel: "Netto-Gehalt einer Vollzeitstelle". Das wurde bisher bei Drowdowns ähnlich umgesetzt (z. B. F1_10)
> 
> Angegeben würde diese Kategorie dann so: ao0: 0: Netto-Gehalt einer Vollzeitstelle

@SilinaKowalewski: OK, haben wir angepasst. Bitte prüfen, ob das so richtig ist. 7c98d7e

**Comment by SilinaKowalewski** [comment]
@SMajer: Eure Anpassungen ändern leider nichts an dem Problem. Wohin sollen die Probanden denn nach dieser Seite hingeleitet werden? 

Da bei einer Weiterleitungsbedingung immer die erste angewendet wird die zutrifft, würden hier nach wie vor alle Probanden zur KSM-ma06 geführt werden. Zudem sollten die Transitions auf KSM-ma07 zusammengelegt werden. Das könnte dann zum Beispiel so aussehen: 


> GOTO KSM-ma07 IF (sabsan = 6 OR sabsan = 7 OR sabsan = 8 OR sabsan = 9) OR (sabsan = 5 AND sabslaja <>1)
> GOTO KSM-ma06 IF ELSE

**Comment by SMajer** [comment]
> GOTO KSM-ma07 IF (sabsan = 6 OR sabsan = 7 OR sabsan = 8 OR sabsan = 9) OR (sabsan = 5 AND sabslaja <>1)

@SilinaKowalewski : Stimmt, sorry. transition wurde nochmal wie von dir vorgeschlagen angepasst b0d64e7

**Comment by meyerja** [comment]
@SilinaKowalewski : Erstes Item bei KSM-ma08 wurde nochmal neu angepasst (andere Formulierung) ddac778

**Comment by meyerja** [comment]
@SilinaKowalewski : 35ac1e4
Hinweis KSM-ma07 ergänzt: Reihenfolge Itemliste randomisieren.

**Comment by meyerja** [comment]
@christian-fr : 

- [ ] KSM-ma06: transition zu Seite KSM-ma07 ergänzt: 5945c90

- [ ] KSM-ma07: kann Item 13 ("anderes und zwar") immer als letztes angezeigt werden, die restlichen Items jedoch in randomisierter Reihenfolge?
