### ISSUE TITLE
E2: Promotion-Vignetten: Änderung des Fragebogens

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#186]
- [x] Template angepasst an den aktuellen Fragebogen 5a111e9
- [ ] Zusätzlich wurden Variablennamen geändert 631eab4
@SMajer und @meyerja hier haben wir keine Änderungen vorgenommen, da nur die transition control geändert wurde
- [ ] Da das Modul am Schluss kommt, sollte die transition auf die Abschlussseite leiten. Korrigiert: c343e27
@SMajer und @meyerja auch das wurde nicht angepasst, da es die Seite so nicht gibt.

- **mvig2[deck] [vignr]**: transition gelöscht

- **KSM-phd02**: tc entfernt + Fragetext geändert + Items geändert + Gender-Stern eingefügt + Nummerierung der Items angepasst + Variablennamen angepasst + vc gelöscht + transition eingefügt

- **KSM-phd03**: Seite gelöscht

**Comment by SMajer** [comment]
Zusätzlich wurden Variablennamen geändert 631eab4

**Comment by andreaschu** [comment]
Ohne Transitions lässt sich der Fragebogen nicht bauen. Sie wurden deshalb noch nicht gelöscht.

**Comment by andreaschu** [comment]
> KSM-phd02: tc entfernt + Fragetext geändert + Items geändert + Gender-Stern eingefügt + Nummerierung der Items angepasst + Variablennamen angepasst + vc gelöscht + transition eingefügt

In der PV gibt es keine transition. Kannst Du das bitte noch mal checken?

**Comment by SMajer** [comment]
Auf KSM-phd02 gibt es eine transition, allerdings auf die falsche Seite. Da das Modul am Schluss kommt, sollte die transition auf die Abschlussseite leiten. Korrigiert: c343e27

Wie müssen die transitions von pvig1[deck][vignr] zu mvig2[deck][vignr] lauten? 
GOTO mvig2[deck][vignr] ?

**Comment by SilinaKowalewski** [comment]
@SMajer: 

Soll denn wirklich von der ersten Promotions-Vignette zur zweiten Master-Vignette weitergeleitet werden? Ich vermute, dass hier aktuell ein kleiner Tippfehler in der Programmiervorlage ist. Vermutlich handelt es sich um eine transition von pvig1[deck][vignr] zu **p**vig2[deck][vignr], oder?

**Comment by SilinaKowalewski** [comment]
Die Darstellung der Vignetten ist etwas generell unübersichtlich, da in der Programmiervorlage für die Master-Vignetten lediglich die Frage mvig[deck][vignr] angelegt ist und für die Promotions-Vignetten hingegen die Fragen pvig1[deck][vignr] und mvig2[deck][vignr]. Das sollten wir am besten anpassen.

**Comment by SMajer** [comment]
> 
> 
> Die Darstellung der Vignetten ist etwas generell unübersichtlich, da in der Programmiervorlage für die Master-Vignetten lediglich die Frage mvig[deck][vignr] angelegt ist und für die Promotions-Vignetten hingegen die Fragen pvig1[deck][vignr] und mvig2[deck][vignr]. Das sollten wir am besten anpassen.

@SilinaKowalewski: Ja, sehr gerne an Master-Vignette anpassen. Wenn dann noch die transitions angepasst werden müssen, machen wir das im Anschluss.

**Comment by SilinaKowalewski** [comment]
> @SilinaKowalewski: Ja, sehr gerne an Master-Vignette anpassen. Wenn dann noch die transitions angepasst werden müssen, machen wir das im Anschluss.

Wie soll denn die zweite Promotions-Vignette heißen? Soll es bei mvig2[deck][vignr] bleiben?

**Comment by SMajer** [comment]
> 
> 
> > @SilinaKowalewski: Ja, sehr gerne an Master-Vignette anpassen. Wenn dann noch die transitions angepasst werden müssen, machen wir das im Anschluss.
> 
> Wie soll denn die zweite Promotions-Vignette heißen? Soll es bei mvig2[deck][vignr] bleiben?

@SilinaKowalewski : pvig2[deck][vignr]

**Comment by SilinaKowalewski** [comment]
> @SilinaKowalewski: Ja, sehr gerne an Master-Vignette anpassen. Wenn dann noch die transitions angepasst werden müssen, machen wir das im Anschluss.

@SMajer: Habe nun die Master-Vignetten aufgesplittet und die zweite Promotions-Vignette umgenannt. Bitte checkt die beiden committs nochmal und fügt die fehlenden Transitions ein.

**Comment by meyerja** [comment]
@SilinaKowalewski @andreaschu : 30fef0a
Hinweis ergänzt (Reihenfolge Itemliste bitte randomisieren)

**Comment by meyerja** [comment]
@christian-fr : 

- [ ] Kann auch hier das letzte Item (Item 18 "sonstige und zwar") immer am Schluss stehen, die restlichen Items jedoch in randomisierter Reihenfolge angezeigt werden?
