### ISSUE TITLE
E3: Politik: Änderung des Fragebogens

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#188]
- [x] template an aktuellen Fragebogen angepasst 736b9a0

- KSM-pol02: Antwortkategorie "weiß nicht" geändert

- KSM-pol03: Items angepasst und Reihenfolge geändert + Item9 (Lobbyismus) wurde gelöscht + Antwortoption 6 wurde angepasst + mv gelöscht

- KSM-pol04: Itemreihenfolge verändert + Items angepasst + Antwortoption 6 angepasst + mv gelöscht

- KSM-pol05: Itemreihenfolge geändert + altes Item 4 gelöscht (Exzellenz) + Antwortkategorie 6 angepasst + mv gelöscht 

- KSM-pol06: Fragetext geändert + Antwortkategorien angepasst

- KSM-pol07: Instruktion geändert + Antwortkategorie (Studentenverbindungen) angepasst

**Comment by meyerja** [comment]
@andreaschu @SilinaKowalewski : 8217d12
- KSM-pol05: Item 4 angepasst
- KSM-pol06: Item 1 angepasst
- KSM-pol07: Item 7 angepasst

**Comment by meyerja** [comment]
@christian-fr : Kann auf der Seite KSM-pol01 das Intro von der Frage abgesetzt werden (eine Zeile Abstand dazwischen)?
