### ISSUE TITLE
E4-Fairness: Änderungen des Fragebogens

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#194]
- [x] template an den aktuellen Fragebogen angepasst 6b7e218

- [x] Zusätzliche Änderung Variablenname auf Seite KSM-fai04 12c046b

- KSM-fai01: Intro ergänzt 

- KSM-fai03: Antwortskala (Endpunkte) geändert + Items angepasst 

- KSM-fai04: Variablenname geändert (Umlaut entfernt) 

- KSM-fai05: Antwortoption ergänzt ("kann ich nicht beurteilen")

- KSM-fai06 bis KSMfai11: Intro geändert

- KSM-fai14: Intro geändert

- KSM-fai06 bis KSM-fai15: transition zu Seiten KSM-fai16 bis KSM-fai25 eingefügt (siehe nächster Punkt)

- KSM-fai16 bis KSM-fai25: pro Split (Fächerkombination) wurde eine neue Seite zur Begründung der Gehaltsunterschiede angelegt (zuvor nur Seite KSM-fai16)

- KSM-fai26 (alte Seite KSM-fai17): Fragetext geändert + zusätzliches Item eingefügt + Antwortoption "weiß nicht" ergänzt

- KSM-fai27 (alte Seite KSM-fai18): zusätzliches Item eingefügt

**Comment by SMajer** [comment]
Zusätzliche Änderung Variablenname auf Seite KSM-fai04 12c046b

**Comment by SilinaKowalewski** [comment]
**KSM-fai06 - KSM-fai16**

- [ ] Hier ist mir nicht ganz klar, wie die Instruction final aussehen soll. Soll der erste Satz abgesetzt werden oder alles bis auf den ersten Satz gelöscht werden? 

- [ ]  @SMajer: Würde es aus deiner Sicht auch reichen eine einzige Frage mit unterschiedlichen Sichtbarkeitsbedingungen zu bauen? Über diese Sichtbarkeitsbedingungen könnten wir dann in Abhängigkeit zu s_fairsplit die Fächerkombination einblenden.

**Comment by SMajer** [comment]
> 
> 
> **KSM-fai06 - KSM-fai16**
> 
>     * [ ]  Hier ist mir nicht ganz klar, wie die Instruction final aussehen soll. Soll der erste Satz abgesetzt werden oder alles bis auf den ersten Satz gelöscht werden?
> 
>     * [ ]   @SMajer: Würde es aus deiner Sicht auch reichen eine einzige Frage mit unterschiedlichen Sichtbarkeitsbedingungen zu bauen? Über diese Sichtbarkeitsbedingungen könnten wir dann in Abhängigkeit zu s_fairsplit die Fächerkombination einblenden.

@SilinaKowalewski : Wenn das möglich ist, kann man gerne nur eine Seite mit Sichbarkeitsbedingungen bauen. Bitte Vorschlag machen vor Umsetzung.
Bei der Instruktion soll nichts gelöscht werden, aber der erste Satz vom übrigen Text abgesetzt werden.

**Comment by SilinaKowalewski** [comment]
Hier mein Vorschlag für die Programmiervorlage. Bei der Erstellung dieser Vorlage ist mir allerdings aufgefallen, dass eine einzige Seite bedeuten würde, dass nur eine einzige Variable angelegt und gefüllt wird. Wenn es wichtig ist, dass die Daten in unterschiedliche Variablen geschrieben werden müssten wir auf dieser Seite zehn einzelne Fragen anlegen und könnten dann auch gleich zehn Fragen schreiben. Das würde sich vom Aufwand nicht groß unterscheiden. 



> ___
> 
> KSM-fai06
> tc:
> 
> vn: faiwige
> 
> qt: Einfachauswahl mit horizontalen Antwortoptionen
> 
> hl:
> 
> in1: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen wirtschaftswissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 43.000 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Geisteswissenschaften verdienen demgegenüber durchschnittlich ca. 35.000 € im Jahr. (SHOW IF s_fairsplit= 1)
> 
> in2: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen ingenieurwissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 47.500 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Geisteswissenschaften verdienen demgegenüber durchschnittlich ca. 35.000 € im Jahr. (SHOW IF s_fairsplit= 2)
> 
> in3: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen der Medizin verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 53.000 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Geisteswissenschaften verdienen demgegenüber durchschnittlich ca. 35.000 € im Jahr. (SHOW IF s_fairsplit= 3)
> 
> in4: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen rechtswissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 46.500 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Geisteswissenschaften verdienen demgegenüber durchschnittlich ca. 35.000 € im Jahr. (SHOW IF s_fairsplit= 4)
> 
> in5: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen der Medizin verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 53.000 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Rechtswissenschaften verdienen demgegenüber durchschnittlich ca. 46.500 € im Jahr. (SHOW IF s_fairsplit= 5)
> 
> in6: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen der Medizin verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 53.000 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Ingenieurwissenschaften verdienen demgegenüber durchschnittlich ca. 47.500 € im Jahr. (SHOW IF s_fairsplit= 6)
> 
> in7: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen der Medizin verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 53.000 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Wirtschaftswissenschaften verdienen demgegenüber durchschnittlich ca. 43.000 € im Jahr. (SHOW IF s_fairsplit= 7)
> 
> in8: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen rechtswissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 46.500 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Wirtschaftswissenschaften verdienen demgegenüber durchschnittlich ca. 43.000 € im Jahr. (SHOW IF s_fairsplit= 8)
> 
> in9: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen ingenieurwissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 47.500 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Rechtswissenschaften verdienen demgegenüber durchschnittlich ca. 46.500 € im Jahr. (SHOW IF s_fairsplit= 9)
> 
> in10: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> 
> Absolvent*innen ingenieurwissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 47.500 € pro Jahr (Bruttojahresgehalt). Absolvent*innen der Wirtschaftswissenschaften verdienen demgegenüber durchschnittlich ca. 43.000 € im Jahr. (SHOW IF s_fairsplit= 10)
> 
> 
> q1: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen wirtschaftswissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Geisteswissenschaften? (SHOW IF s_fairsplit= 1)
> 
> q2: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen ingenieurwissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Geisteswissenschaften? (SHOW IF s_fairsplit= 2)
> 
> q3: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen der Medizin direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Geisteswissenschaften? (SHOW IF s_fairsplit= 3)
> 
> q4: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen rechtswissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Geisteswissenschaften? (SHOW IF s_fairsplit= 4)
> 
> q5: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen der Medizin direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Rechtswissenschaften? (SHOW IF s_fairsplit= 5)
> 
> q6: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen der Medizin direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Ingenieurwissenschaften? (SHOW IF s_fairsplit= 6)
> 
> q7: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen der Medizin direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Wirtschaftswissenschaften? (SHOW IF s_fairsplit= 7)
> 
> q8: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen rechtswissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Wirtschaftswissenschaften? (SHOW IF s_fairsplit= 8)
> 
> q9: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen ingenieurwissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Rechtswissenschaften?(SHOW IF s_fairsplit= 9)
> 
> q10: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent*innen ingenieurwissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent*innen der Wirtschaftswissenschaften? (SHOW IF s_fairsplit= 10)
> 
> 
> is:
> 
> it:
> 
> st:
> 
> ao1: 1: gar nicht gerechtfertigt
> 
> ao2: 2:
> 
> ao3: 3:
> 
> ao4: 4:
> 
> ao5: 5: völlig gerechtfertigt
> 
> mv:
> 
> ka:
> 
> vc:
> 
> SHOW in1 IF s_fairsplit= 1
> SHOW in2 IF s_fairsplit= 2
> SHOW in3 IF s_fairsplit= 3
> SHOW in4 IF s_fairsplit= 4
> SHOW in5 IF s_fairsplit= 5
> SHOW in6 IF s_fairsplit= 6
> SHOW in7 IF s_fairsplit= 7
> SHOW in8 IF s_fairsplit= 8
> SHOW in9 IF s_fairsplit= 9
> SHOW in10 IF s_fairsplit= 10
> SHOW q1 IF s_fairsplit= 1
> SHOW q2 IF s_fairsplit= 2
> SHOW q3 IF s_fairsplit= 3
> SHOW q4 IF s_fairsplit= 4
> SHOW q5 IF s_fairsplit= 5
> SHOW q6 IF s_fairsplit= 6
> SHOW q7 IF s_fairsplit= 7
> SHOW q8 IF s_fairsplit= 8
> SHOW q9 IF s_fairsplit= 9
> SHOW q10 IF s_fairsplit= 10
> 
> av:
> 
> kh:
> 
> fv:
> 
> hv:
> 
> fo:
> 
> tr: GOTO KSM-fai16
> 
> hi:
> 
> ------------------------------------------------------------

**Comment by SMajer** [comment]
> 
> 
> Hier mein Vorschlag für die Programmiervorlage. Bei der Erstellung dieser Vorlage ist mir allerdings aufgefallen, dass eine einzige Seite bedeuten würde, dass nur eine einzige Variable angelegt und gefüllt wird. Wenn es wichtig ist, dass die Daten in unterschiedliche Variablen geschrieben werden müssten wir auf dieser Seite zehn einzelne Fragen anlegen und könnten dann auch gleich zehn Fragen schreiben. Das würde sich vom Aufwand nicht groß unterscheiden.
> 
> > KSM-fai06
> > tc:
> > vn: faiwige
> > qt: Einfachauswahl mit horizontalen Antwortoptionen
> > hl:
> > in1: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen wirtschaftswissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 43.000 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Geisteswissenschaften verdienen demgegenüber durchschnittlich ca. 35.000 € im Jahr. (SHOW IF s_fairsplit= 1)
> > in2: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen ingenieurwissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 47.500 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Geisteswissenschaften verdienen demgegenüber durchschnittlich ca. 35.000 € im Jahr. (SHOW IF s_fairsplit= 2)
> > in3: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen der Medizin verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 53.000 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Geisteswissenschaften verdienen demgegenüber durchschnittlich ca. 35.000 € im Jahr. (SHOW IF s_fairsplit= 3)
> > in4: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen rechtswissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 46.500 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Geisteswissenschaften verdienen demgegenüber durchschnittlich ca. 35.000 € im Jahr. (SHOW IF s_fairsplit= 4)
> > in5: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen der Medizin verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 53.000 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Rechtswissenschaften verdienen demgegenüber durchschnittlich ca. 46.500 € im Jahr. (SHOW IF s_fairsplit= 5)
> > in6: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen der Medizin verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 53.000 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Ingenieurwissenschaften verdienen demgegenüber durchschnittlich ca. 47.500 € im Jahr. (SHOW IF s_fairsplit= 6)
> > in7: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen der Medizin verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 53.000 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Wirtschaftswissenschaften verdienen demgegenüber durchschnittlich ca. 43.000 € im Jahr. (SHOW IF s_fairsplit= 7)
> > in8: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen rechtswissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 46.500 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Wirtschaftswissenschaften verdienen demgegenüber durchschnittlich ca. 43.000 € im Jahr. (SHOW IF s_fairsplit= 8)
> > in9: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen ingenieurwissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 47.500 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Rechtswissenschaften verdienen demgegenüber durchschnittlich ca. 46.500 € im Jahr. (SHOW IF s_fairsplit= 9)
> > in10: Im Folgenden geht es um Gehaltsunterschiede zwischen Absolvent*innen verschiedener Fächergruppen und darum, ob Sie diese Unterschiede als gerechtfertigt empfinden.
> > Absolvent_innen ingenieurwissenschaftlicher Fächer verdienen nach ihrem Abschluss in Vollzeit durchschnittlich etwa 47.500 € pro Jahr (Bruttojahresgehalt). Absolvent_innen der Wirtschaftswissenschaften verdienen demgegenüber durchschnittlich ca. 43.000 € im Jahr. (SHOW IF s_fairsplit= 10)
> > q1: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen wirtschaftswissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Geisteswissenschaften? (SHOW IF s_fairsplit= 1)
> > q2: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen ingenieurwissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Geisteswissenschaften? (SHOW IF s_fairsplit= 2)
> > q3: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen der Medizin direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Geisteswissenschaften? (SHOW IF s_fairsplit= 3)
> > q4: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen rechtswissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Geisteswissenschaften? (SHOW IF s_fairsplit= 4)
> > q5: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen der Medizin direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Rechtswissenschaften? (SHOW IF s_fairsplit= 5)
> > q6: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen der Medizin direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Ingenieurwissenschaften? (SHOW IF s_fairsplit= 6)
> > q7: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen der Medizin direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Wirtschaftswissenschaften? (SHOW IF s_fairsplit= 7)
> > q8: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen rechtswissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Wirtschaftswissenschaften? (SHOW IF s_fairsplit= 8)
> > q9: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen ingenieurwissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Rechtswissenschaften?(SHOW IF s_fairsplit= 9)
> > q10: In welchem Ausmaß finden Sie es gerechtfertigt, dass Absolvent_innen ingenieurwissenschaftlicher Studienfächer direkt nach ihrem Abschluss mehr verdienen als Absolvent_innen der Wirtschaftswissenschaften? (SHOW IF s_fairsplit= 10)
> > is:
> > it:
> > st:
> > ao1: 1: gar nicht gerechtfertigt
> > ao2: 2:
> > ao3: 3:
> > ao4: 4:
> > ao5: 5: völlig gerechtfertigt
> > mv:
> > ka:
> > vc:
> > SHOW in1 IF s_fairsplit= 1
> > SHOW in2 IF s_fairsplit= 2
> > SHOW in3 IF s_fairsplit= 3
> > SHOW in4 IF s_fairsplit= 4
> > SHOW in5 IF s_fairsplit= 5
> > SHOW in6 IF s_fairsplit= 6
> > SHOW in7 IF s_fairsplit= 7
> > SHOW in8 IF s_fairsplit= 8
> > SHOW in9 IF s_fairsplit= 9
> > SHOW in10 IF s_fairsplit= 10
> > SHOW q1 IF s_fairsplit= 1
> > SHOW q2 IF s_fairsplit= 2
> > SHOW q3 IF s_fairsplit= 3
> > SHOW q4 IF s_fairsplit= 4
> > SHOW q5 IF s_fairsplit= 5
> > SHOW q6 IF s_fairsplit= 6
> > SHOW q7 IF s_fairsplit= 7
> > SHOW q8 IF s_fairsplit= 8
> > SHOW q9 IF s_fairsplit= 9
> > SHOW q10 IF s_fairsplit= 10
> > av:
> > kh:
> > fv:
> > hv:
> > fo:
> > tr: GOTO KSM-fai16
> > hi:

@SilinaKowalewski : Ok, ich sehe den Punkt. Sollte so eigentlich funktionieren, da wir nur die fairsplit-Variable brauchen, dann wissen wir, welche Fächerkombination angezeigt wurde. Kann daher gerne so umgesetzt werden.

**Comment by SilinaKowalewski** [comment]
@SMajer: Ich habe die Fragen mal entsprechend umgesetzt. Gleiches gilt eigentlich auch für die Fragen KSM-fai16ff, oder?

**Comment by meyerja** [comment]
@SilinaKowalewski : Genau, für KSM-fai16 bis KSM-fai25 gilt das auch.

**Comment by meyerja** [comment]
@SilinaKowalewski @andreaschu : 25ca211
- KSM-fai04: Item 9 angepasst
- KSM-fai05: Item 3 angepasst

**Comment by meyerja** [comment]
@SilinaKowalewski @andreaschu: 6248b20
KSM-fai27: weitere Antwortkategorie ergänzt (ao9)

**Comment by meyerja** [comment]
@christian-fr : 

- [ ] Kann auf der Seite KSM-fai01 das Intro von der Frage abgesetzt werden (eine Zeile Abstand dazwischen)?

- [ ] KSM-fai06 bis KSMfai15: Intro ist kursiv gedruckt. Können hier nur die Namen der Fachgruppen kursiv gesetzt werden und der Rest nicht kursiv? (Zum Beispiel die Wörter Medizin und Geisteswissenschaften)

- [ ] KSM-fai06 bis KSMfai15: Kann hier im Intro ein Abstand zwischen dem ersten und dem zweiten Satz eingefügt werden (eine Zeile Abstand)?

- [ ] KSM-fai16 bis KSM-fai25: Kann auch hier eine Zeile Abstand nach dem Fragetext eingefügt werden?

- [ ] KSM-fai16 bis KSM-fai25: Können auch hier nur die Fachgruppen kursiv gedruckt werden und der Rest des Satzes nicht kursiv?

- [ ] KSM-fai26: hier wurden zwei Änderungen aus den templates nicht übernommen: Fragetext wurde nicht geändert und zusätzliches Item 8 ("aufgrund von Elternschaft") wurde nicht ergänzt

- [ ] KSM-fai27: Beschriftung der Skalenpunkte ragt in die Kästchen (Layoutproblem)

**Comment by meyerja** [comment]
@christian-fr: Auch hier passt nun alles.
