### ISSUE TITLE
gesch02: title springen, title-Beschriftungen werden nicht angezeigt

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#2]
@vdick:
vgl. #1 random-modus - die title bitte fixieren
Hier fehlen außerdem noch die title-Beschriftungen, es werden nur die values angezeigt.

**Comment by dzhwmeisner** [comment]
fixed. need to be tested.

**Comment by SilinaKowalewski** [comment]
sieht super aus :)
