### ISSUE TITLE
Anleitung pull request

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#202]
Hier die aktualisierte Anleitung zur Arbeit mit pull requests. 

[Prozess_pull_request.pdf](https://github.com/dzhw/SiD/files/4306195/Prozess_pull_request.pdf)

Update: Das Dokument ist auch im Wiki hinterlegt.

**Comment by karbecke** [comment]
sehr gut, vielen Dank!
Damit hat der konsolidierte commit von Modul A nun funktioniert.

@SilinaKowalewski Könntet ihr im Wiki auch die Informationen zur aktuellen Umsetzungphase hinterlegen --> "Übersicht Module--> programmiert"? 
Und: Gibt es darüber hinaus schon einen ersten Rollout, den wir uns anschauen könnten (evtl. Module B oder C?)

**Comment by SilinaKowalewski** [comment]
Eine Übersicht zur Umsetzungsphase werden wir euch auf jeden Fall wieder zur Verfügung stellen. 

Bisher konnte die Befragung aber noch nicht ausgerollt werden, da die Befragung an einigen Stellen noch inkonsistent ist. Das liegt vor allem an gelöschten oder eingefügten Transition die ohne das aktualisierte Grundmodul nicht funktionieren. Sobald wir das Grundmodul aktualisiert haben sollte es aber deutlich weniger Probleme geben. 

Alle weiteren Problemfälle müssen wir dann aber händisch durchgehen und uns eine vorübergehende Lösung überlegen damit wir euch etwas zum Prüfen ausrollen können. Ein paar Tage kann das also noch dauern.
