### ISSUE TITLE
 A - Änderungen des Fragebogens

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#203]
@SilinaKowalewski  @andreaschu Sämtliche Änderungen wurden im Rahmen eines eigenen Modul-A-branch umgesetzt.

- [x] fe1777b

**SOLL-Zusatand Grundprogramm:**

[A_Modul_Grundprogramm.docx](https://github.com/dzhw/SiD/files/4307475/A_Modul_Grundprogramm.docx)

**Comment by christian-fr** [comment]
Wenn das Textfeld auf der page A_12a vom Typ NUMBER sein sollte (bedeutet, dass nur Ziffern eingegeben werden können), fehlt dort noch ein Korrekturhinweis, der angezeigt wird, falls andere Daten eingegeben wurden:


Status quo [in der PV](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_12a):
```
A_12a
[...]
q: Haben Sie Geschwister?
is: Bitte geben Sie auch Ihre Halb- und Stiefgeschwister an.
[...]
ao1: (dsib): 1: nein
ao2: (dsib): 2: Ja, und zwar: ([dsibo], NUMBER, 2-Steller)
[...]
kh:
```

Bitte den Korrekturhinweis ergänzen.

**Comment by christian-fr** [comment]
In den transitions findet sich noch der alte Variablenname _sabsan_ - ich habe den in der Programmierung mal eigeninitiativ auf _sabsano_ geändert, die PV müsste aber auch noch korrigiert werden.


Status quo [der Programmiervorlage](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_25):
```
A_25
[...]
vn: sabsano; sabsanoaa; sabsanoka
[...]
q: Und welchen Abschluss streben Sie als nächstes an?
is: Sollten Sie mehrere Abschlüsse anstreben, beziehen Sie sich bitte auf den zeitlich nächsten.
[...]
ao1: (sabsano): 1: Bachelor
ao2: (sabsano): 2: Master
ao3: (sabsano): 3: Staatsexamen
ao4: (sabsano): 4: Diplom
ao5: (sabsano): 5: Promotion
ao6: (sabsano): 6: kirchliche Abschlussprüfung
ao7: (sabsano): 7: künstlerische Abschlussprüfung
ao8: (sabsano): 8: Anderen Abschluss (bspw. ausländischer Abschluss, Magister), und zwar: [(sabsanoaa), offene Angabe, 80 Zeichen]
ao9: (sabsano): 9: Keinen Studienabschluss, sondern: [(sabsanoka), offene Angabe, 80 Zeichen]
[...]
tr: 
GOTO A_25b if sabsano==5 GOTO A_27 if sabsan=9 
GOTO D1_13 if sabsan=1-8 AND mastersplit=1, 2, 3, 4, 7, 8, 9, 10, 14 
GOTO A_27 if sabsan=1-8 AND mastersplit=5, 6, 11, 12, 13 
GOTO D1_13 if sabsan=MISSING AND mastersplit=1, 2, 3, 4, 7, 8, 9, 10, 14 
GOTO A_27 if sabsan=MISSING AND mastersplit=5, 6, 11, 12, 13
```

**Comment by christian-fr** [comment]
Nur ein Hinweis / z. K.: bei A_25b gibt es keine _ao6_ bzw. keine Antwortoption mit dem Wert "5". Ist jetzt so in der Programmierung umgesetzt.

Status quo [der PV](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_25b):

```
A_25b
[...]
q: Sie haben angegeben, dass Sie die Promotion anstreben: Sind Sie darüber hinaus in einem regulären Studiengang eingeschrieben?
[...]
ao1: (sabsanpr): -11: nein
ao2: (sabsanpr): 1: Bachelor
ao3: (sabsanpr): 2: Master
ao4: (sabsanpr): 3: Staatsexamen
ao5: (sabsanpr): 4: Diplom
ao7: (sabsanpr): 6: kirchliche Abschlussprüfung
ao8: (sabsanpr): 7: künstlerische Abschlussprüfung
ao9: (sabsanpr): 8: Anderer Abschluss (bspw. ausländischer Abschluss, Magister)
```

**Comment by christian-fr** [comment]
Ich werde aus **A_33** nicht so recht schlau.

Einfachauswahl macht hier meiner Ansicht nach schon Sinn, dann beziehen sich aber alle (Einfachauswahl-)Antwortoptionen auf die gleiche Variable - und alle bekommen jeweils einen (distinkten) Wert zugewiesen. Die offene Angabe bekommt dann konsistenterweise einen entsprechend modifizierten Variablennamen. 

Die `[Exklusivkategorie]` ergibt ohnehin nur bei Mehrfachauswahl Sinn und könnte daher hier entfallen.

Mein Vorschlag wäre hier bspw. für _deltjobv_/_deltjobvo_:

```
ao1: (deltjobv):   1: Präfix: Berufsbezeichnung: [(deltjobvo), offene Angabe; 100 Zeichen]
ao2: (deltjobv): -11: nie berufstätig gewesen [Einfachauswahl]
ao3: (deltjobv): -12: weiß ich nicht
```

Und analog für _deltjobm_/_deltjobvm_:

```
ao4: (deltjobm):   1: Präfix: Berufsbezeichnung: [(deltjobmo), offene Angabe; 100 Zeichen]
ao5: (deltjobm): -11: nie berufstätig gewesen [Einfachauswahl]
ao6: (deltjobm): -12: weiß ich nicht
```

------------------------------


Status quo [der Programmiervorlage](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_33):
```
A_33
vn: deltjobv (deltjobvo1; deltjobv1; deltjobv2); deltjobm (deltjobmo1; ddeltjobm1; deltjobm2)
qt: offene Angaben; Einfachauswahl;

[...]

q: Und welchen Beruf übt Ihr Vater/Ihre Mutter hauptberuflich aus?

is: Falls Ihre Eltern zurzeit nicht erwerbstätig sind, geben Sie bitte den jeweils zuletzt ausgeübten Beruf an.

Bitte tragen Sie die Berufsbezeichnung möglichst genau ein, z. B.:
Bankkaufmann/-frau (nicht: Angestellte\*r), Zollbeamtin oder -beamter (nicht: Beamtin oder Beamter), Maschinenbauingenieur\*in (nicht: Ingenieur\*in).

it1: Vater
it2: Mutter
ao1: (deltjobvo1): Präfix: Berufsbezeichnung: [offene Angabe; 100 Zeichen]
ao2: (deltjobv1): -11: nie berufstätig gewesen [Einfachauswahl]
ao3: (deltjobv2): -12: weiß ich nicht [Exklusivkategorie]
ao4: (deltjobmo1): Präfix: Berufsbezeichnung: [offene Angabe; 100 Zeichen]
ao5: (deltjobm1): -11: nie berufstätig gewesen [Einfachauswahl]
ao6: (deltjobm2): -12: weiß ich nicht [Exklusivkategorie]

[...]

fo: „Vater“ und „Mutter“ bitte jeweils in einer extra Zeile positionieren, die linksbündig über den jeweils darunterliegenden Antwortzeilen liegt (siehe Darstellung hierunter):

Vater
Berufsbezeichnung: Eingabefeld
nie berufstätig gewesen-Kästchen
weiß ich nicht-Kästchen

Mutter
Berufsbezeichnung: Eingabefeld
nie berufstätig gewesen-Kästchen
weiß ich nicht-Kästchen
```

**Comment by christian-fr** [comment]
Für den Typ _number_ bei ao1 / _vsbplz_ bitte noch einen Korrekturhinweis ergänzen, der angezeigt wird, falls nicht nur Ziffern eingegeben wurden.


Status quo [der Programmiervorlage](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_37a):

```
A_37a
[..]
vn: vsbplz; vsbort
[...]
q: An welchem Ort haben Sie gewohnt, als Sie die Studienberechtigung (HZB) erhalten haben?
[...]
ao1: (vsbplz): Präfix: Bitte tragen Sie die fünfstellige Postleitzahl ein: [Infield = Postleitzahl; Number, 5-stellig: 01000 TO 99999] (offene Angabe)
ao2: (vsbort): Präfix: Falls Sie die Postleitzahl nicht kennen, geben Sie bitte den Ort an: [Infield = Ort; 60 Zeichen] (offene Angabe)
[...]
kh:
fv:
[...]
```

**Comment by pbornkessel** [comment]
> 
> 
> Wenn das Textfeld auf der page A_12a vom Typ NUMBER sein sollte (bedeutet, dass nur Ziffern eingegeben werden können), fehlt dort noch ein Korrekturhinweis, der angezeigt wird, falls andere Daten eingegeben wurden:
> 
> Status quo [in der PV](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_12a):
> 
> ```
> A_12a
> [...]
> q: Haben Sie Geschwister?
> is: Bitte geben Sie auch Ihre Halb- und Stiefgeschwister an.
> [...]
> ao1: (dsib): 1: nein
> ao2: (dsib): 2: Ja, und zwar: ([dsibo], NUMBER, 2-Steller)
> [...]
> kh:
> ```
> 
> Bitte den Korrekturhinweis ergänzen.

Bitte vorläufig folgenden Korrekturhinweis in GitHub und QML setzen/ergänzen:

kh: (dsib): Bitte geben Sie an, wieviele Geschwister Sie haben (1 bis 12).

Außerdem den Wertebereich bitte auf 1 bis 12 begrenzen.

**Comment by pbornkessel** [comment]
> 
> 
> Für den Typ _number_ bei ao1 / _vsbplz_ bitte noch einen Korrekturhinweis ergänzen, der angezeigt wird, falls nicht nur Ziffern eingegeben wurden.
> 
> Status quo [der Programmiervorlage](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_37a):
> 
> ```
> A_37a
> [..]
> vn: vsbplz; vsbort
> [...]
> q: An welchem Ort haben Sie gewohnt, als Sie die Studienberechtigung (HZB) erhalten haben?
> [...]
> ao1: (vsbplz): Präfix: Bitte tragen Sie die fünfstellige Postleitzahl ein: [Infield = Postleitzahl; Number, 5-stellig: 01000 TO 99999] (offene Angabe)
> ao2: (vsbort): Präfix: Falls Sie die Postleitzahl nicht kennen, geben Sie bitte den Ort an: [Infield = Ort; 60 Zeichen] (offene Angabe)
> [...]
> kh:
> fv:
> [...]
> ```

Bitte vorläufig folgenden Korrekturhinweis in GitHub und QML setzen/ergänzen, falls keine/nicht nur Ziffern eingegeben werden:

kh: (vsbplz): Bitte geben Sie nur Zahlen an.

**Comment by pbornkessel** [comment]
> 
> 
> In den transitions findet sich noch der alte Variablenname _sabsan_ - ich habe den in der Programmierung mal eigeninitiativ auf _sabsano_ geändert, die PV müsste aber auch noch korrigiert werden.
> 
> Status quo [der Programmiervorlage](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_25):
> 
> ```
> A_25
> [...]
> vn: sabsano; sabsanoaa; sabsanoka
> [...]
> q: Und welchen Abschluss streben Sie als nächstes an?
> is: Sollten Sie mehrere Abschlüsse anstreben, beziehen Sie sich bitte auf den zeitlich nächsten.
> [...]
> ao1: (sabsano): 1: Bachelor
> ao2: (sabsano): 2: Master
> ao3: (sabsano): 3: Staatsexamen
> ao4: (sabsano): 4: Diplom
> ao5: (sabsano): 5: Promotion
> ao6: (sabsano): 6: kirchliche Abschlussprüfung
> ao7: (sabsano): 7: künstlerische Abschlussprüfung
> ao8: (sabsano): 8: Anderen Abschluss (bspw. ausländischer Abschluss, Magister), und zwar: [(sabsanoaa), offene Angabe, 80 Zeichen]
> ao9: (sabsano): 9: Keinen Studienabschluss, sondern: [(sabsanoka), offene Angabe, 80 Zeichen]
> [...]
> tr: 
> GOTO A_25b if sabsano==5 GOTO A_27 if sabsan=9 
> GOTO D1_13 if sabsan=1-8 AND mastersplit=1, 2, 3, 4, 7, 8, 9, 10, 14 
> GOTO A_27 if sabsan=1-8 AND mastersplit=5, 6, 11, 12, 13 
> GOTO D1_13 if sabsan=MISSING AND mastersplit=1, 2, 3, 4, 7, 8, 9, 10, 14 
> GOTO A_27 if sabsan=MISSING AND mastersplit=5, 6, 11, 12, 13
> ```

Zur Kenntnis genommen.  
@ alle: Muss von uns in der nächsten Schleife überall entsprechend berücksichtigt und überarbeitet/angepasst werden!

**Comment by pbornkessel** [comment]
> 
> 
>     1. Nur ein Hinweis / z. K.: bei A_25b gibt es keine _ao6_ bzw. keine Antwortoption mit dem Wert "5".
>        Ist jetzt so auch in der Programmierung umgesetzt.
> 
>     2. Es gibt keine transition für den Fall, dass _sabsanpr_ == 1 ist. Dieser Fall muss irgendwo noch ergänzt werden.
>        (Je nachdem, wie dies umgesetzt wird, könnte bei dieser Gelegenheit ggf. auch noch der Abgangsfilter etwas verschlankt werden, indem z. B. gar nicht mehr nach _mastersplit_, sondern nur nach _sabsanpr_ gefiltert wird. Ist aber nur eine Anregung, keine Notwendigkeit.)
> 
> 
> Status quo [der PV](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_25b):
> 
> ```
> A_25b
> [...]
> q: Sie haben angegeben, dass Sie die Promotion anstreben: Sind Sie darüber hinaus in einem regulären Studiengang eingeschrieben?
> [...]
> ao1: (sabsanpr): -11: nein
> ao2: (sabsanpr): 1: Bachelor
> ao3: (sabsanpr): 2: Master
> ao4: (sabsanpr): 3: Staatsexamen
> ao5: (sabsanpr): 4: Diplom
> ao7: (sabsanpr): 6: kirchliche Abschlussprüfung
> ao8: (sabsanpr): 7: künstlerische Abschlussprüfung
> ao9: (sabsanpr): 8: Anderer Abschluss (bspw. ausländischer Abschluss, Magister)
> [...]
> tr:
> GOTO D1_13 if sabsanpr=2-8 AND mastersplit=1, 2, 3, 4, 7, 8, 9, 10, 14 
> GOTO A_27 if sabsanpr=2-8 AND mastersplit=5, 6, 11, 12, 13 
> GOTO D1_13 if sabsanpr=MISSING AND mastersplit=1, 2, 3, 4, 7, 8, 9, 10, 14 
> GOTO A_27 if sabsanpr=MISSING AND mastersplit=5, 6, 11, 12, 13
> ```

Zu 1.: Christian, würdest du das bitte bereits entsprechend in GitHub und QML anpassen und von ao1 bis ao7 sowie von 1 bis 7 korrekt durchnummerieren?

Zu 2.: Zur Kenntnis genommen.
@ alle: Muss von uns in der nächsten Schleife überall entsprechend berücksichtigt und überarbeitet/angepasst werden!

**Comment by pbornkessel** [comment]
> 
> 
> Ich werde aus **A_33** nicht so recht schlau.
> 
> Einfachauswahl macht hier meiner Ansicht nach schon Sinn, dann beziehen sich aber alle (Einfachauswahl-)Antwortoptionen auf die gleiche Variable - und alle bekommen jeweils einen (distinkten) Wert zugewiesen. Die offene Angabe bekommt dann konsistenterweise einen entsprechend modifizierten Variablennamen.
> 
> Die `[Exklusivkategorie]` ergibt ohnehin nur bei Mehrfachauswahl Sinn und könnte daher hier entfallen.
> 
> (Bedenkt bitte zudem, dass eine Einfachauswahl nicht mehr komplett rückgängig gemacht werden kann, sie kann nur noch in eine andere Antwortoption abgeändert werden.)
> 
> Mein Vorschlag wäre hier bspw. für _deltjobv_/_deltjobvo_:
> 
> ```
> ao1: (deltjobv):   1: Präfix: Berufsbezeichnung: [(deltjobvo), offene Angabe; 100 Zeichen]
> ao2: (deltjobv): -11: nie berufstätig gewesen
> ao3: (deltjobv): -12: weiß ich nicht
> ```
> 
> Und analog für _deltjobm_/_deltjobvm_:
> 
> ```
> ao4: (deltjobm):   1: Präfix: Berufsbezeichnung: [(deltjobmo), offene Angabe; 100 Zeichen]
> ao5: (deltjobm): -11: nie berufstätig gewesen
> ao6: (deltjobm): -12: weiß ich nicht
> ```
> 
> Status quo [der Programmiervorlage](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_33):
> 
> ```
> A_33
> vn: deltjobv (deltjobvo1; deltjobv1; deltjobv2); deltjobm (deltjobmo1; ddeltjobm1; deltjobm2)
> qt: offene Angaben; Einfachauswahl;
> 
> [...]
> 
> q: Und welchen Beruf übt Ihr Vater/Ihre Mutter hauptberuflich aus?
> 
> is: Falls Ihre Eltern zurzeit nicht erwerbstätig sind, geben Sie bitte den jeweils zuletzt ausgeübten Beruf an.
> 
> Bitte tragen Sie die Berufsbezeichnung möglichst genau ein, z. B.:
> Bankkaufmann/-frau (nicht: Angestellte\*r), Zollbeamtin oder -beamter (nicht: Beamtin oder Beamter), Maschinenbauingenieur\*in (nicht: Ingenieur\*in).
> 
> it1: Vater
> it2: Mutter
> ao1: (deltjobvo1): Präfix: Berufsbezeichnung: [offene Angabe; 100 Zeichen]
> ao2: (deltjobv1): -11: nie berufstätig gewesen [Einfachauswahl]
> ao3: (deltjobv2): -12: weiß ich nicht [Exklusivkategorie]
> ao4: (deltjobmo1): Präfix: Berufsbezeichnung: [offene Angabe; 100 Zeichen]
> ao5: (deltjobm1): -11: nie berufstätig gewesen [Einfachauswahl]
> ao6: (deltjobm2): -12: weiß ich nicht [Exklusivkategorie]
> 
> [...]
> 
> fo: „Vater“ und „Mutter“ bitte jeweils in einer extra Zeile positionieren, die linksbündig über den jeweils darunterliegenden Antwortzeilen liegt (siehe Darstellung hierunter):
> 
> Vater
> Berufsbezeichnung: Eingabefeld
> nie berufstätig gewesen-Kästchen
> weiß ich nicht-Kästchen
> 
> Mutter
> Berufsbezeichnung: Eingabefeld
> nie berufstätig gewesen-Kästchen
> weiß ich nicht-Kästchen
> ```

Christian, dein Vorschlag würde für uns dann funktionieren, wenn der Button zur Einfachauswahl bei der offenen Angabe der Berufsbezeichnung von Vater und Mutter jeweils 'versteckt' werden könnte und damit in dieser Zeile tatsächlich jeweils nur die offene Angabe sichtbar ist. In den beiden darunter folgenden Zeilen würden anschließend jeweils die beiden Kategorien "nie berufstätig gewesen" und "weiß ich nicht" folgen. 

Ansonsten wäre es für uns auch ein gangbarer Weg, die offene Abfrage jeweils in eine separate Variable zu packen und die beiden folgenden Kategorien (nie berufstätig gewesen; weiß ich nicht) in eine andere Variable/Einfachauswahl (Variable mit distinkten Werten) zu packen. Dann wäre es zwar möglich, eine offene Angabe zu tätigen und gleichzeitig etwas bei der Einfachauswahl auszuwählen, das könnten wir aber im Nachgang plausibilisieren.

**Comment by christian-fr** [comment]
> @christian-fr Wieso wurde der Variablenname von "sabsan" zu "sabsano" geändert?

Auf page **A_25** wird in einer Einfachauswahl eine Variable _sabsano_ abgefragt (siehe PV).

=> Es gibt also eine Variable _sabsano_ in dieser Befragung.

Als offene Angaben innerhalb dieser Einfachauswahl werden auch _sabsanoaa_ und _sabsanoka_ abgefragt (vgl. ebd.).

=> Es gibt also auch die beiden Variablen _sabsanoaa_ und _sabsanoka_

In den transitions von **A_25** taucht nun eine Variable names _sabsan_ auf. Diese Variable findet sich auch **auf vielen anderen pages**, sowohl in **visible conditions** als auch in **transitions**.

Ich finde keine Variable names _sabsan_ in irgendeinem der Module.

**Comment by pbornkessel** [comment]
> 
> 
> > @christian-fr Wieso wurde der Variablenname von "sabsan" zu "sabsano" geändert?
> 
> Auf page **A_25** wird in einer Einfachauswahl eine Variable _sabsano_ abgefragt (siehe PV).
> 
> => Es gibt also eine Variable _sabsano_ in dieser Befragung.
> 
> Als offene Angaben innerhalb dieser Einfachauswahl werden auch _sabsanoaa_ und _sabsanoka_ abgefragt (vgl. ebd.).
> 
> => Es gibt also auch die beiden Variablen _sabsanoaa_ und _sabsanoka_
> 
> In den transitions von **A_25** taucht nun eine Variable names _sabsan_ auf. Diese Variable findet sich auch **auf vielen anderen pages**, sowohl in **visible conditions** als auch in **transitions**.
> 
> Ich finde keine Variable names _sabsan_ in irgendeinem der Module.

@christian-fr Die Variable heißt ursprünglich "sabsan" und mir ist aktuell nicht ersichtlich, wieso und von wem diese in "sabsano" geändert wurde. Daher meine Rückfrage. Ich hatte dich zunächst so verstanden, dass du diese geändert hast, aber wenn ich dich jetzt richtig verstehe, war sie bereits geändert, bevor du in das Modul einestiegen bist.

Daher: Wenn überall sonst in den transitions und visible conditions der verschiedenen Module noch "sabsan" verwendet wird und, wie du sagst, nirgendwo anders eine Variable "sabsan" definiert wird, wäre es gut, wenn wir auch an dieser Stelle (A_25) bei "sabsan" bleiben würden. Könntest du das bitte in QML und GitHub direkt entsprechend umsetzen?

**Comment by christian-fr** [comment]
Im aktuellsten commit wurde die page **A_43** gelöscht, es gibt jedoch noch eine transition von page **A_42**, die auf die gelöschte page verweist.

Diese transition sollte geändert werden.

-------------------

Status quo [der Programmiervorlage](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_42):


```
A_42
[...]
vn: eaktsens
[...]
q1: Sind Sie während der Vorlesungszeit erwerbstätig?
q2: Sind Sie während der Vorlesungszeit neben Ihrem dualen Studium erwerbstätig?
[...]
tr: 
GOTO A_43 IF eaktsens=2 OR eaktsens=3 OR eaktsens=4 
GOTO A_44 IF (eaktsens=1 | k.A.) AND (mastersplit=13) 
GOTO D3_20 IF (eaktsens =1 | k.A. & sformberu=1 | sformdua=1) AND (mastersplit=3, 4, 5, 6, 9, 10, 11, 12, 14) 
GOTO D3_22 IF (eaktsens =1 | k.A. & sformberu!=1 | sformdua!=1) AND (mastersplit=3, 4, 5, 6, 9, 10, 11, 12, 14) 
GOTO D1_9 IF eaktsens=1 | k.A.) AND (mastersplit=1, 2, 7, 8)
```

**Comment by christian-fr** [comment]
Im aktuellsten commit wurde die page **A_9a** gelöscht, es gibt jedoch noch jeweils eine transition von page **A_8** und page **A_8a**, die auf die gelöschte page verweisen.

Diese transitions sollten geändert werden.

-----------------------------------

Status quo [der Programmiervorlage: page **A_8**](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_8)

``` 
A_8
[...]
vn: baufgru (baufgrueuba; baufgrustuba; baufgruerwerb; baufgrutouba; baufgruasylba; baufgrufaman; baufgrufamba; baufgruausba; baufgruandba; baufgruandbao)
[...]
q: Für die Einreise nach Deutschland gibt es unterschiedliche rechtliche Grundlagen. Wie war das bei Ihnen? Als ich nach Deutschland kam, war ich:
[...]
tr: 
GOTO A_8a IF baufgruasylba=1 
GOTO A_8b IF baufgruasylba=0 AND (baufgrufaman=1 OR baufgrufamba=1) 
GOTO A_9a IF (baufgruasylba=0 AND baufgrufaman=0 AND baufgrufamba=0) AND h_split=1 GOTO A_9b IF (baufgruasylba=0 AND baufgrufaman=0 AND baufgrufamba=0) AND h_split=2
```


Status quo [der Programmiervorlage: page **A_8a**](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_8a)

```
A_8a
[...]
vn: asylantrag
[...]
q: Wie wurde über Ihren Asylantrag entschieden?
[...]
tr: 
GOTO A_8b IF (baufgrufaman=1 OR baufgrufamba=1)
GOTO A_9a IF (baufgrufaman=0 AND baufgrufamba=0) AND h_split=1 
GOTO A_9b IF (baufgrufaman=0 AND baufgrufamba=0) AND h_split=2
```

**Comment by pbornkessel** [comment]
> 
> 
> Im aktuellsten commit wurde die page **A_43** gelöscht, es gibt jedoch noch eine transition von page **A_42**, die auf die gelöschte page verweist.
> 
> Diese transition sollte geändert werden.
> 
> Status quo [der Programmiervorlage](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_42):
> 
> ```
> A_42
> [...]
> vn: eaktsens
> [...]
> q1: Sind Sie während der Vorlesungszeit erwerbstätig?
> q2: Sind Sie während der Vorlesungszeit neben Ihrem dualen Studium erwerbstätig?
> [...]
> tr: 
> GOTO A_43 IF eaktsens=2 OR eaktsens=3 OR eaktsens=4 
> GOTO A_44 IF (eaktsens=1 | k.A.) AND (mastersplit=13) 
> GOTO D3_20 IF (eaktsens =1 | k.A. & sformberu=1 | sformdua=1) AND (mastersplit=3, 4, 5, 6, 9, 10, 11, 12, 14) 
> GOTO D3_22 IF (eaktsens =1 | k.A. & sformberu!=1 | sformdua!=1) AND (mastersplit=3, 4, 5, 6, 9, 10, 11, 12, 14) 
> GOTO D1_9 IF eaktsens=1 | k.A.) AND (mastersplit=1, 2, 7, 8)
> ```

@christian-fr  Danke für den Hinweis. Sowas wird es an diversen Stellen geben. Die Transitions werden von uns insgesamt nochmal grundlegend überarbeitet und angepasst.

**Comment by pbornkessel** [comment]
> 
> 
> Im aktuellsten commit wurde die page **A_9a** gelöscht, es gibt jedoch noch jeweils eine transition von page **A_8** und page **A_8a**, die auf die gelöschte page verweisen.
> 
> Diese transitions sollten geändert werden.
> 
> Status quo [der Programmiervorlage: page **A_8**](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_8)
> 
> ```
> A_8
> [...]
> vn: baufgru (baufgrueuba; baufgrustuba; baufgruerwerb; baufgrutouba; baufgruasylba; baufgrufaman; baufgrufamba; baufgruausba; baufgruandba; baufgruandbao)
> [...]
> q: Für die Einreise nach Deutschland gibt es unterschiedliche rechtliche Grundlagen. Wie war das bei Ihnen? Als ich nach Deutschland kam, war ich:
> [...]
> tr: 
> GOTO A_8a IF baufgruasylba=1 
> GOTO A_8b IF baufgruasylba=0 AND (baufgrufaman=1 OR baufgrufamba=1) 
> GOTO A_9a IF (baufgruasylba=0 AND baufgrufaman=0 AND baufgrufamba=0) AND h_split=1 GOTO A_9b IF (baufgruasylba=0 AND baufgrufaman=0 AND baufgrufamba=0) AND h_split=2
> ```
> 
> Status quo [der Programmiervorlage: page **A_8a**](https://github.com/dzhw/SiD/blob/master/Modul_A%20(Grundprogramm).md#a_8a)
> 
> ```
> A_8a
> [...]
> vn: asylantrag
> [...]
> q: Wie wurde über Ihren Asylantrag entschieden?
> [...]
> tr: 
> GOTO A_8b IF (baufgrufaman=1 OR baufgrufamba=1)
> GOTO A_9a IF (baufgrufaman=0 AND baufgrufamba=0) AND h_split=1 
> GOTO A_9b IF (baufgrufaman=0 AND baufgrufamba=0) AND h_split=2
> ```


@christian-fr   Danke für den Hinweis. Sowas wird es an diversen Stellen geben. Die Transitions werden von uns insgesamt nochmal grundlegend überarbeitet und angepasst.

**Comment by karbecke** [comment]
@christian-fr : Wird auf Seite A_15 die Systemvariable "**h_gartcount**" erzeugt --> Summe aus "gartmob" bis "gartka"?

**Comment by christian-fr** [comment]
> 
> 
> @christian-fr : Wird auf Seite A_15 die Systemvariable "**h_gartcount**" erzeugt --> Summe aus "gartmob" bis "gartka"?

Ja, diese Variable wird erzeugt.
