### ISSUE TITLE
C1_7: Variablennamen (dekinbesoe, dekinbesoeo)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#21]
in Programmierung "dkinbesoe" und "dkinbesoeo" statt "d**e**kinbesoe" bzw. "d**e**kinbesoeo"
Welche sind richtig?

**Comment by pbornkessel** [comment]
"dkinbesoe" und "dkinbesoeo" sind richtig. Habe es entsprechend angepasst. 
Bitte einmal kontrollieren [0d5e855](url)
