### ISSUE TITLE
C1_13/ C1_14 alternative Transitions fehlen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#23]
Müssen in [PV](https://github.com/dzhw/SiD/blob/master/Modul-C1_Kind.md#c1_13) noch nachgereicht werden. Im Moment führt ELSE-transition zur end-page.

**Comment by pbornkessel** [comment]
@andreaschu 
@SilinaKowalewski 

Hat sich dieses issue dann durch Markus Transitions #94 erledigt?
