### ISSUE TITLE
E1_6: Abstand der title zu Items zu groß

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#24]
![grafik](https://user-images.githubusercontent.com/30111489/65526662-c4197c80-def1-11e9-9326-3561f9eb8c10.png)

**Comment by vdick** [comment]
fixed, bei nächstem Rollout verfügbar

**Comment by SilinaKowalewski** [comment]
Sieht für die Frage E1_6 nun super aus. 

Gleiches muss allerdings auch für die Frage E1_7 eingebaut werden.

**Comment by vdick** [comment]
@SilinaKowalewski erledigt (nach nächstem build verfügbar)
