### ISSUE TITLE
Anpassungen_B1 für SiD_2020

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#251]
Liebes ZOFAR-Team,
bitte folgende Punkte für Modul_B1 anpassen:

### **Änderung der GitHub-Programmiervorlage durch SiD**
- [x] ZOFAR bitte QML entsprechend commit 6455759 anpassen

#### **Seite B1_4a** 
- [x] Einblendbedingung ist in GitHub korrekt hinterlegt. Im Presenter wird derzeit (07.04.2020) das gesamte Tableau fälschlicherweise ausgeblendet, wenn keine Kinder vorhanden sind (dkinja=1). ZOFAR bitte im Tableau lediglich die Spalte „Kinderbetreuung“ ausblenden, wenn keine Kinder vorhanden sind. (Sind Kinder vorhanden, wird das Tableau aktuell korrekt vollständig eingeblendet.)

#### **Seite B1_8** 
- [x] Änderung vc siehe o.g. commit (6455759)

#### **Seite B1_1**
- [x] bei der offenen Angabe sind mehr als 25 Zeichen möglich --> ZOFAR bitte Zeichenanzahl auf 25 begrenzen (siehe GitHub-Programmiervorlage)
- [x] mv-code in GitHub angepasst --> Umsetzung siehe commit 6455759

#### **Seite B1_3b**
- [x] Ein Item zu viel programmiert bzw. nicht gemäß PV rausgelöscht: "In einer Familie kann auch der Mann für den Haushalt und die Kinder verantwortlich sein, während die Frau Vollzeit erwerbstätig ist." --> ZOFAR bitte dieses Item löschen

#### **Seite B1_4a**
- [x] Bitte Doppelpunkte bei Spaltenüberschriften (Haushaltsbereichen) entfernen (Missverständnis mit PV-Anweisung) --> Umsetzung siehe o.g. commit (6455759)
- [x] Eintragung von Kommazahlen ohne Auslösen der Validation Message möglich und es wird weitergeleitet --> ZOFAR bitte anpassen
~- [ ] Es fehlt die letzte Zeile Summe: 100 % unter jeder Spalte . Ebenso wird nicht die Summe der Spalten geprüft --> ZOFAR bitte anpassen~
> edit christian-fr: wird in issue #256 behandelt

#### **Seite B1_5**
- [x] Zwei Punkte am Satzende --> ZOFAR bitte nur 1 Satzendzeichen

#### **Seite B1_6**
- [x] Validation Message wird nicht ausgelöst, Eingabe von Dreistellern über 100 möglich --> ZOFAR bitte Zahlenbereich von 0-100 begrenzen bzw. „leer“ zulassen
~- [ ] Es fehlt die letzte Zeile Summe: 100 % unter jeder Spalte. Es wäre super, wenn eine solche Information eingeblendet werden würde. Zudem könnte man auch die Summen prüfen --> ZOFAR bitte anpassen~
> edit christian-fr: wird in issue #256 behandelt

~### **Anpassung Layout**~
~#### **Seite B1_3b**~
~- [ ] Abstand Bezeichnung Skalenendpunkte zu Frage etwas vergrößern --> ZOFAR bitte anpassen~
~- [ ] Itemtext ist nicht mittig im jeweiligen weißen/grauen Kasten, sondern klebt stets unten. Bei langen Items ist die Skala nicht zentriert, sondern wird immer in der ersten Zeile angezeigt --> ZOFAR bitte anpassen~
~- [ ] Teilweise wäre mehr Abstand zwischen den Items gut, da diese z. T. sehr lang sind --> ZOFAR bitte anpassen~

~#### **Seite B1_4a**~
~- [ ] Die Spaltenbeschriftungen generell über Eingabefelder zentrieren und nicht über 3 Zeilen laufen lassen --> ZOFAR bitte anpassen~
~- [ ] Abstände der Spaltenbereiche zu Eingabefeldern zu groß --> ZOFAR bitte anpassen~

~#### **Seite B1_5**~
~- [ ] Wort im Text der zweiten Spalte bitte nicht kursiv (Partner*in) --> ZOFAR bitte anpassen~
~- [ ] Item "Treffen wichtiger Entscheidungen " und Skala sind nicht auf einer Höhe --> ZOFAR bitte anpassen~
~- [ ] Ganz allgemein Skala weiter auseinanderziehen --> ZOFAR bitte anpassen~
~- [ ] Bei Verkleinerung des Bildschirms überlappen die Skalenbeschriftungen --> ZOFAR bitte anpassen~

~#### **Seite B1_6**~
~- [ ] Die Spaltenbeschriftungen generell über Eingabefelder zentrieren --> ZOFAR bitte anpassen~
~- [ ] Abstände der Spaltenbereiche zu Eingabefeldern zu groß --> ZOFAR bitte anpassen~
~- [ ] Bei Verkleinerung des Bildschirms überlappen die Skalenbeschriftungen --> ZOFAR bitte anpassen~
~- [x] PV angepasst (Haushaltsbereiche/Spaltenbereiche fett) siehe o.g. commit (6455759)~

> edit christian-fr: Die Layout-Aufgaben würde ich gern in ein neues issue #259 verschieben.

**Comment by karbecke** [comment]
**Noch zu klärende Punkte**:
- [ ] **Seite B1_4a & Seite B1_6** (https://github.com/dzhw/SiD/issues/174)
- Problem: Summenbildung
Hier müssen wir (SiD & ZOFAR) eine gemeinsame Lösung finden:
(1) Variante a: Ist eine validation message (soft forcing) möglich?
(2) Variante b:wenn dies nicht geht: eigene mobile device Seite programmieren

**Comment by christian-fr** [comment]
> 
> 
> **Noch zu klärende Punkte**:
> 
>     * [ ]  **Seite B1_4a & Seite B1_6** (#174)
> 
>     * Problem: Summenbildung
>       Hier müssen wir (SiD & ZOFAR) eine gemeinsame Lösung finden:
>       (1) Variante a: Ist eine validation message (soft forcing) möglich?
>       (2) Variante b:wenn dies nicht geht: eigene mobile device Seite programmieren

Das würde ich gern in einem separaten Issue behandeln #256
