### ISSUE TITLE
KSM-fai27: Beschriftung Skalenpunkte

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#257]
[Kommentar von meyerja:](https://github.com/dzhw/SiD/issues/194#issuecomment-614540201)
> KSM-fai27: Beschriftung der Skalenpunkte ragt in die Kästchen (Layoutproblem)

---------------

> ![grafik](https://user-images.githubusercontent.com/42959832/79467640-45f00500-7ffe-11ea-9959-ba6701831ee2.png)

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by meyerja** [comment]
@christian-fr : Danke, sieht jetzt gut aus.
