### ISSUE TITLE
B1_4a: Matrix wird falsch dargestellt

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#258]
#### Status quo B1_4a:
![grafik](https://user-images.githubusercontent.com/42959832/79467122-b9dddd80-7ffd-11ea-9972-24be6c4072a7.png)

... und so sollte es eigentlich aussehen:

#### Status quo B1_6:
![grafik](https://user-images.githubusercontent.com/42959832/79467213-d67a1580-7ffd-11ea-90c2-de6faccd1895.png)

Der einzige mir ersichtliche Unterschied zwischen den beiden pages ist, dass **B1_4a** mit einer visible condition arbeitet und **B1_6** nicht.

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar
