### ISSUE TITLE
allgemein: fehlende transitions/ fehlende pages

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#261]
Folgende pages tauchen zwar in **transitions** der Programmiervorlage auf, nicht jedoch als **pages in der Programmiervorlage** selbst - hier müssen entweder

1. die transitions geändert werden, die jeweils auf sie verweisen, oder aber
1. entsprechende pages erstellt werden.

- A_49b (Module A, D1)
- A_51a (Module A, D1) 
- D1_10a (Modul A)
- D1_14 (Modul A)
- D1_17 (Modul A)
- D1_5 (Module A, D1) 
- D1_23 (Modul D1)
- D2_1 (Modul A)
- D2_6 (Module A, D1, D3)
- D2_14 (Modul D2)

---------------------

Folgende pages existieren zwar in der Programmiervorlage, sie tauchen im Status quo der Programmierung (16.04.2020) jedoch in keiner der transitions auf, das heißt sie können innerhalb der Befragung nicht durch normale Sprünge erreicht werden. Bitte prüfen, ob die PV korrekt ist:

#### Modul A
- [ ] D2_2
- [ ] D2_6a
- [ ] D2_15
#### Modul D3
- [ ] D3_19
#### Modul D1
- [ ] D1_10
- [ ] D1_15
#### Modul C2
- [ ] C2_0
#### Modul F3
- [ ] F3_8
#### Modul B2
- [ ] B2_7
- [ ] D1_18
#### Modul E1
- [ ] E0_0
#### (Eurostudent VII)
- [ ] p01_01

**Comment by karbecke** [comment]
Liebes ZOFAR-Team,
wie bereits kommuniziert - arbeiten wir aktuell an den transitions und liefern euch diese in fertiger QML-Form. Diese müssen dann nur noch per copy-and-paste übernommen werden. Hierzu werden wir einen eigenen commit + Issue hochladen, sobald wir hiermit fertig sind.
BG
