### ISSUE TITLE
Modul E2 (Master-Vignetten): neue Vignetten, randomisiert

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#262]
Per Mail erhielten wir am 14.04.2020 die Anfrage,
> [...] ob die Vignetten (vignr) innerhalb der decks variieren könnten. [...] Wäre eine Randomisierung innerhalb der decks möglich?

Diese Randomisierung wurde nun für die Master-Vignetten umgesetzt und wird nach dem nächsten Rollout verfügbar sein.

Die Randomisierung wird über eine weitere Preload-Variable erfolgen, der Name kann frei gewählt werden. Zu Testzwecken habe ich eine Variable _temp_random_var_ erstellt, das wird noch abgeändert. 

Die Reihenfolge der Vignetten innerhalb der Decks wird randomisiert, die Reihenfolge je nach _temp_random_var_ ist folgende:

> ![grafik](https://user-images.githubusercontent.com/42959832/79785089-968b9900-8343-11ea-92fc-2d09c6ea47d5.png)

Erläuterung: ein\*e Befragte\*r läuft jeweils die Reihen entlang, startet bei _temp_random_var_ == 14 bspw. mit der Vignette Nr. 3 seines Decks, dann kommen Nr. 1, Nr. 4 und dann Nr. 2, danach **KSM-ma02**. 
Für das Deck Nr. 32 hieße dies bei _temp_random_var_ == 14 folgende Seitenabfolge:
**KSM-ma01**
**V32_3**
**V32_1**
**V32_4**
**V32_2**
**KSM-ma01**

-------------------------

Es gibt nun insgesamt 108 Master-Vignetten-Decks.

------------------------

Zudem gibt es, ebenfalls zu Testzwecken, auf **KSM-ma01** ein zusätzliches Textfeld, in dem der Wert dieser Variablen festgelegt werden kann, bspw. um stichprobenartig die Filterführung zu prüfen. Dieses Textfeld samt Hinweistext wird später entfernt:

> ![grafik](https://user-images.githubusercontent.com/42959832/79785590-655f9880-8344-11ea-8e25-6d77fbde5206.png)

**Comment by meyerja** [comment]
@christian-fr : Können auf Seite KSM-ma01 im Einleitungstext einige Wörter fett gedruckt werden (wie bei den Promotionsvignetten auf Seite KSM-phd01)? Der Text sollte dann so aussehen: 
Es handelt sich um einen Studiengang an einer **staatlichen** oder **privaten Hochschule**, der auf Ihrem angestrebten Bachelorabschluss **fachlich** aufbaut. **Wohnkosten** und **Freizeitmöglichkeiten** entsprechen in etwa Ihrem **jetzigen Studienort**.
