### ISSUE TITLE
SiD-Corona: programming first draft

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#265]
[ÄnderungNachvoll_200504_Fragebogen_Sonderbefragung.docx](https://github.com/dzhw/SiD/files/4609296/AnderungNachvoll_200504_Fragebogen_Sonderbefragung.docx)
[SiD_Kurzbefragung_Veränderung_ZOFAR_PB_ME.XLSX](https://github.com/dzhw/SiD/files/4609297/SiD_Kurzbefragung_Veranderung_ZOFAR_PB_ME.XLSX)
[flow chart](https://github.com/dzhw/SiD/blob/master/SiD_Kurzbefragung_Ablaufpfad_Bild2.png)

**Comment by christian-fr** [comment]
Die Befragung ist ausgerollt:

https://presentation.dzhw.eu/corona-sid

Hinweis: die letzten Änderungen (aus der Mail vom Montag) werden gerade noch umgesetzt und sind daher noch nicht in diesem Rollout enthalten.

**Comment by karbecke** [comment]
Vielen Dank für die Info!
Wir beginnen nun mit der Testung der Online-Umsetzung und geben euch zeitnah eine Rückmeldung.

BG

**Comment by christian-fr** [comment]
@karbecke @markusloe Ich habe unter dem Dateinamen [sid-sonderbefragung.md](https://github.com/dzhw/SiD/blob/master/sid-sonderbefragung.md) eine vorläufige Programmiervorlage für die SiD Sonderbefragung Corona angelegt.

Diese wurde auf Grundlage unserer bereits vorhandenen QML-Programmierung erstellt und soll daher den Status quo der Programmierung abbilden.

Weitere Änderungen sollten dann über dieses Dokument ablaufen.

Nach Kenntnisnahme kann dieses Issue dann geschlossen werden - weiterer Austausch dann am besten in einzelnen Issues, die dem Projekt "SiD-Corona" zugeordnet werden.

**Comment by christian-fr** [comment]
Die Programmierung entspricht nun dem Stand der Mail von Markus vom 11.05.2020.
