### ISSUE TITLE
SiD-Corona: Incentive-Experiment

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#274]
anbei sende ich euch den Versuchsaufbau für das Incentive-Experiment:

[Incentive_Experimente_SiD_Sonderbefragung_2020_05_14.pdf](https://github.com/dzhw/SiD/files/4650774/Incentive_Experimente_SiD_Sonderbefragung_2020_05_14.pdf)

**Comment by karbecke** [comment]
Liebes ZOFAR-Team,

wir haben den Versuchsaufbau nochmals etwas modifiziert. Den finalen Versuchsaufbau seht ihr nun hier:

[Incentive_Experimente_SiD_Sonderbefragung_2020_05_26.pdf](https://github.com/dzhw/SiD/files/4681826/Incentive_Experimente_SiD_Sonderbefragung_2020_05_26.pdf)


Ferner senden wir euch die jeweils zu programmierenden Seiten des Versuchs --> 
[Incentive-Experiment_Endseiten_2020_05_26.docx](https://github.com/dzhw/SiD/files/4681835/Incentive-Experiment_Endseiten_2020_05_26.docx)

**Comment by karbecke** [comment]
Liebes ZOFAR-Team,

wie eben besprochen sende ich euch hier anbei die noch fehlenden Seiten:
- [ ] Gesamt-Fragebogen (Stand: 03.06.2020)
[20200603_Fragebogen_Sonderbefragung.pdf](https://github.com/dzhw/SiD/files/4722780/20200603_Fragebogen_Sonderbefragung.pdf)


- [ ] **1. Programmiervorlage Indexseite**
[Programmiervorlage_Startseite_final.docx](https://github.com/dzhw/SiD/files/4722745/Programmiervorlage_Startseite_final.docx)

- [ ] **2. Informed Consent** --> bitte als Attachement der Indexseite einpflegen:
[Kurzbefragung_Informed_Consent.pdf](https://github.com/dzhw/SiD/files/4722733/Kurzbefragung_Informed_Consent.pdf)

- [ ] **3. Incentive-Experiment-Seiten** 
[Incentive-Experiment_Endseiten_2020_05_26.docx](https://github.com/dzhw/SiD/files/4722762/Incentive-Experiment_Endseiten_2020_05_26.docx)

- [ ] **4. IAB-Seiten** --> bitte nach Incentive-Experiment einfügen
[IAB_Datenverknüpfung.docx](https://github.com/dzhw/SiD/files/4722757/IAB_Datenverknupfung.docx)

**Comment by karbecke** [comment]
Incentive-Gutschein-Codes per Mail an euch gesendet

To-Do

- [ ] Gutschein-Codes einbinden

**Comment by christian-fr** [comment]
@karbecke Im oben verlinkten Dokument [Incentive-Experiment_Endseiten_2020_05_26.docx](https://github.com/dzhw/SiD/files/4681835/Incentive-Experiment_Endseiten_2020_05_26.docx) 

wird auf der **_ersten Seite_** für die Überschrift die Formulierung 

`Vielen Dank für Ihre Unterstützung!`

gewählt, auf **_allen anderen Seiten_** jedoch

`Vielen Dank für Ihre Teilnahme!`

Geschah das absichtsvoll oder ist das ein copy&paste-Fehler?

> ![grafik](https://user-images.githubusercontent.com/42959832/84011077-e1a24f80-a975-11ea-8703-a15eece53256.png)


> ![grafik](https://user-images.githubusercontent.com/42959832/84011104-eebf3e80-a975-11ea-871f-a2439ffc493c.png)

**Comment by christian-fr** [comment]
@markusloe @mcehrhardt Könnt ihr mal nachschauen, ob das Obenstehende Absicht oder ein Versehen ist?

**Comment by mcehrhardt** [comment]
@christian-fr Sehr aufmerksam, danke! Dabei handelt es sich um ein Versehen. Es sollte auf allen Seiten gleich sein und "Vielen Dank für Ihre Unterstützung!" lauten.
