### ISSUE TITLE
SiD-Corona: A_42 transitions Änderungswunsch

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#275]
Bezugnehmend auf #266 :

Im Kommentar ([LINK](https://github.com/dzhw/SiD/issues/266#issuecomment-632627920)) wurde für Seite **A_42** folgender Änderungswunsch formuliert:
> Bei „nein" oder keiner Angabe bitte auf neue Frage CO_24 weiterleiten.

Die Antwortoptionen von **A_42**:

```
q: Waren Sie unmittelbar vor der Corona-Pandemie erwerbstätig?
(eaktsens) ao1: 1: nein
(eaktsens) ao2: 2: ja, mit einer Tätigkeit
(eaktsens) ao3: 3: ja, mit zwei Tätigkeiten
(eaktsens) ao4: 4: ja, mit drei oder mehreren Tätigkeiten
```
Der Status quo der Transitions sieht an dieser Stelle wie folgt aus:
```
tr:
GOTO D3_19 IF eaktsens == 2 OR eaktsens == 3 OR eaktsens == 4
GOTO D3_13
```
> ![grafik](https://user-images.githubusercontent.com/42959832/82806925-1519b000-9e87-11ea-961f-113d1dec2888.png)
--------

Wenn nun, wie gewünscht, von **A_42** statt zu **D3_19** direkt zu **CO_24** gesprungen und sonst keine Transitions geändert werden, können die folgenden pages nicht mehr erreicht werden:

`D3_19, CO_8, CO_9, CO_9a`

Falls die gewünscht ist, würden die o.g. pages entfallen. Andernfalls müssten noch weitere Transitions angepasst werden.

**Comment by karbecke** [comment]
An den transtions arbeiten wir aktuell, ihr bekommt nachher noch einen entsprechenden "transitions-commit".

Hier bitte wie folgt umsetzen:

![transition](https://user-images.githubusercontent.com/46674616/82819931-8e260100-9ea1-11ea-9abd-238a2d517951.PNG)

**Comment by christian-fr** [comment]
Ist mit dem letzten commit der Programmiervorlage obsolet geworden, ich schließe das Issue.
