### ISSUE TITLE
Modul-D3_Wohnen_Finanzen_Baöfg_Erwerb (first draft)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#28]
siehe 21d76e8

**Comment by karbecke** [comment]
Update D3 --> 01.10.2019
Please check 7feb0c8

- [ ] Please program Update D3

**Comment by SilinaKowalewski** [comment]
Update D3 wurde umgesetzt. Bitte prüfen

**Comment by andreaschu** [comment]
Das issue kann dann wohl mal geschlossen werden, oder?
