### ISSUE TITLE
SiD-Corona: experiment open matrix

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#281]
[Experiment_offeneMatrix.pdf](https://github.com/dzhw/SiD/files/4724252/Experiment_offeneMatrix.pdf)

**Comment by andreaschu** [comment]
Es gibt zwei Vorschläge für die Auflösung der Matrix für kleine Geräte:
Um es adäquat zum Carousel zu halten und damit Bei-Effekte zu reduzieren, würde ich es mit der ersten Variante machen (nach Zeilen). 
Aber bevor ich die zweite Variante lösche, gebt doch bitte noch Feedback, @markusloe und @karbecke.

### 1. nach Zeilen
![grafik](https://user-images.githubusercontent.com/30111489/83884053-9ead6580-a744-11ea-8a66-d2dd4029f922.png)

----
### 2. nach Spalten
![grafik](https://user-images.githubusercontent.com/30111489/83884093-ae2cae80-a744-11ea-9da6-18766a9fd637.png)

**Comment by markusloe** [comment]
Ich würde Variante 2 bevorzugen

**Comment by andreaschu** [comment]
@markusloe damit würden sich aber zwei Effekte vermengen. 1. der Darstellungseffekt Carousel vs. down scrolling und 2. der Kontext (Spalten vs. Zeilen). 
Analytisch fänd ich das schwierig, weil es sich nicht auseinanderhalten lässt.

**Comment by markusloe** [comment]
Ok - hatte mir die Vorschläge nur hinsichtlich der Anschaulichkeit angeschaut und nicht mit Blick auf das Experiment...

**Comment by andreaschu** [comment]
Zufallszuteilung (s_split_zeit1) sollte nach dem Lasttest gecheckt werden.
