### ISSUE TITLE
SiD-Corona: Änderungen mit Diskussionsbedarf

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#282]
#### Inhaltliche Prüfung

~- [ ] Eingabe von Kommazahlen (z. B. „2,") in beiden offenen Textfeldern
    möglich, mit anschließender Weiterleitung. Sollte nicht möglich sein
    bitte nur Zahleneingabe zulassen.~
> edit christian-fr: siehe #285 

#### Inhaltliche Prüfung

~- [ ] Eingabe von Kommazahlen (z. B. „2,") im offenen Textfeld möglich~
> edit christian-fr: siehe #285 

#### Inhaltliche Prüfung

~- [x] Bitte Item \"Ich möchte die Form meiner Beeinträchtigung nicht
    nennen." als Exklusivkategorie umsetzen~
> edit christian-fr: funktioniert nicht mit zwei Exklusivkategorien
> edit karbecke: ok

#### Inhaltliche Prüfung

- [x] ~Anscheinend wird die Skala rotiert Bitte keine Rotation.~
> edit christian-fr: Mir ist nicht ganz klar, was damit gemeint ist.
> edit karbecke: ist nun korrekt umgesetzt

#### Layout Prüfung

~- [ ] Bitte die Überschrift „Fachnähe" optisch etwas von den
    Tätigkeits-Items absetzen und optisch ansprechender layouten ( siehe
    Word-Fragebogen)~
> >~christian-fr: Mir ist nicht ganz klar, was genau mit ansprechenderem Layout gemeint ist. Mein letzter Stand ist der aus der Mail von Markus vom 12.05., da sieht die Frage so aus:~
>>> ![grafik](https://user-images.githubusercontent.com/42959832/83020495-d9b6e700-a028-11ea-8fdd-c0503ae9188b.png)

> edit christian-fr: wird von vdick im issue #283 bearbeitet - falls ihm eine Gestaltungsmöglichkeit einfällt, baut er sie ein.

#### Inhaltliche Prüfung

~- [ ] Eingabe von Kommas (z. B. „2,") in offenen Textfeldern möglich, mit
    anschließender Weiterleitung. Sollte nicht möglich sein.~
> edit christian-fr: siehe #285 

~- [ ] Bei mehrfacher falscher Angabe verdeckt der Ausfüllhinweis die
    offenen Felder, sodass eine Korrektur nicht möglich ist.~
> edit christian-fr: siehe #286 

#### Inhaltliche Prüfung

~- [ ] Eingabe von Kommazahlen (z. B. „2,") in den offenen Textfeldern
    möglich, mit anschließender Weiterleitung. Sollte nicht möglich
    sein.~
> edit christian-fr: siehe #285 

#### Inhaltliche Prüfung
~- [ ] Eingabe von Kommazahlen (z. B. „2,") im offenen Textfeld sollte
    nicht möglich sein. Nur ganze Zahlen zulassen.~
> edit christian-fr: siehe #285

**Comment by christian-fr** [comment]
@karbecke @markusloe 
Ich habe die offenen Punkte in eigene Issues gepackt. Bitte nochmal kurz drübergehen und das issue dann ggf. schließen.

**Comment by karbecke** [comment]
geprüft, Issue geschlossen
