### ISSUE TITLE
SiD-Corona: latest commit PV

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#284]
Die Änderungen vom commit a567dc53a66 wurden umgesetzt. Bitte prüfen und das Issue nach Prüfung der transitions schließen.

Bei größerem Änderungsbedarf bitte ggf. ein neues Issue eröffnen und hier verlinken. ("#" + Issue-Nummer)

Untenstehend ein Flowchart, das dem Status quo der transitions in der Programmiervorlage entspricht.

![grafik](https://user-images.githubusercontent.com/42959832/83644680-d506ab80-a5b1-11ea-9b3a-9a77794e9642.png)

**Comment by karbecke** [comment]
@christian-fr wir haben uns die Änderungen nochmal angeschaut und an ein paar Stellen noch folgende Anpassungen vorgenommen: 

--> 5056305

**Comment by karbecke** [comment]
@christian-fr ... und hier noch ein paar wenige weitere Anpassungen:

--> 30e9bff

**Comment by karbecke** [comment]
Bitte die beiden commit-Änderungen anpassen:

- [ ] --> 5056305

- [ ] --> 30e9bff

Vielen Dank!

**Comment by christian-fr** [comment]
Ich würde die transitions von **CO_9a1** folgendermaßen formulieren:
```
	<zofar:page uid="CO_9a1">
	[...]
		<zofar:transitions>
			<zofar:transition target="CO_24" condition="zofar.asNumber(VCO_9a1) == 1"/>
			<zofar:transition target="CO_9a"/>
		</zofar:transitions>
	</zofar:page>
```
Begründung: syntaktisch sehr viel einfacher, und auch einfacher zu lesen.

**Comment by karbecke** [comment]
ok, können wir so machen

**Comment by christian-fr** [comment]
Ist so weit alles umgesetzt, für noch offene / unklare Sachen habe ich jeweils neue issues eröffnet und mich selbst assigned.
