### ISSUE TITLE
SiD-Corona: Eingabe von Kommas und Punkten verhindern

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#285]
Betrifft die pages:
- [x] A_17
- [x] A_12a
- [x] D3_6
- [x] D3_2
- [x] CO_13

**Comment by christian-fr** [comment]
Hinweis: die Eingabe wird per JavaScript unterbunden. Dies funktioniert zwar bei den allermeisten Browsern, die Funktion kann je nach verwendetem Endgerät/Browser jedoch nicht zu 100% garantiert werden.

**Comment by christian-fr** [comment]
Ist erledigt und bereits verfügbar.

**Comment by karbecke** [comment]
passt :-)
