### ISSUE TITLE
SiD-Corona: CO_9a ao's - Diskrepanz zwischen PV und Fragebogen

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#289]
In PV (links) und im letzten Fragebogen (rechts) ist die Reihenfolge von ao1 und ao2 unterschiedlich. Die Programmierung entspricht derzeit der PV.

**Welche soll umgesetzt werden?**

 > ![grafik](https://user-images.githubusercontent.com/42959832/83850888-d4852680-a711-11ea-9028-6b1d5b0cf9ae.png)

**Comment by markusloe** [comment]
Die Variante in der erst nein (ao1) und dann ja (ao2) kommt.

**Comment by christian-fr** [comment]
Okay, wird so übernommen. 
Könnt ihr die PV noch anpassen und das issue dann schließen?

**Comment by karbecke** [comment]
@christian-fr : PV wird mittels branch angepasst, ist also noch nicht direkt ersichtlich. ok?
