### ISSUE TITLE
SiD-Corona: Addon1 ("regular", no incentive)

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#290]
aus issue #266 ([Kommentar von Karsten](https://github.com/dzhw/SiD/issues/266#issuecomment-638010631)) übernommen:

> IAB-Abfrage
> Inhaltliche Prüfung
> - Bitte die IAB-Abfrage entsprechend der übermittelten Vorlage umsetzen (3 Seiten: IAB_1, IAB_2, IAB_3)

**Comment by christian-fr** [comment]
Das Addon1 ist ausgerollt und erreichbar unter:
https://presentation.dzhw.eu/corona-sid-addon1

token: `tester1` bis `tester100`

**Comment by karbecke** [comment]
- [ ] Bitte die Seite IAB_2 als NUMBER anlegen, evtl. auch ein infield-Text in den offenen Feldern vermerken:"Bsp.: 02; Bsp.: 11, Bsp.: 1993)

**Comment by christian-fr** [comment]
Wird in #299 weiter behandelt und daher hier geschlossen.
