### ISSUE TITLE
SiD-Corona: N_10b Responsives Design funktioniert nicht

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#292]
übernommen aus issue #266 
>
>
> Seite N_10b
>
> Responsives Design funktioniert leider nicht -- bitte ändern oder ggf. eine Sonderseite für diese Frage > programmieren (Hinweis: in D2_21 funktioniert das responsive Design).

**Comment by andreaschu** [comment]
ist geändert und kann getestet werden

**Comment by andreaschu** [comment]
ich schließe hier mal.
Layout-Issues zu der Frage sind in https://github.com/dzhw/SiD/issues/304 enthalten.
