### ISSUE TITLE
SiD-Corona: infield-Texte

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#293]
aus issue #266 übernommen
>
>
> ### Seite A_23
> 
> 
>  - Bitte „erstes Studienfach" als Infield-Text im ersten Eingabefeld und „ggf. zweites Studienfach" als Infield-Text im zweiten Eingabefeld. Entsprechend die Präfixe/Überschriften bitte entfernen.
> 
> ### Seite A_28
> 
> - Bitte das Präfix und den Button bei den beiden offenen Eingabefeldern für die Noten jeweils entfernen/verstecken.
> - Beim ersten Eingabefeld bitte „Durchschnittsnote im letzten Semester (z. B. 2,5)" als Infield-Text im Eingabefeld. --> als 'prefix' programmieren
> 
> - Beim zweiten Eingabefeld bitte „Durchschnittsnote insgesamt (z. B. 2,5)" als Infield-Text im Eingabefeld. --> als 'prefix' programmieren
> 
> ### Seite D2_19
> 
> - In beiden Eingabefeldern jeweils „Seiten pro Woche" als Infield-Text programmieren und nicht als Vorsatz.
> 
> ### Seite D3_6
> - Bitte „€ pro Monat in diesem Semester" in field übernehmen und neben
>     dem Fenster nur € einblenden

### corona-sid-addon1:
- add infield-text "Bitte E-Mail-Adresse hier angeben" to question open (mailaddress)

**Comment by vdick** [comment]
fixed und bereits ausgerollt
