### ISSUE TITLE
SiD-Corona: CO_14 instruction

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#295]
Ich habe in der Programmierung bei **CO_14** eine Instruction stehen, die ich in der PV nicht finde:

```
Die folgenden Fragen beziehen sich auf Ihren Gesundheitszustand.
Wie für alle Fragen gilt: Die Beantwortung dieser Fragen ist 
selbstverständlich freiwillig und wir sichern Ihnen Anonymität
und den Schutz Ihrer Daten zu.
```

Könntet ihr mal checken, ob die drin bleiben oder rausfliegen soll?

**Comment by karbecke** [comment]
@christian-fr : Die instruction muss mMn. hier drin bleiben. Ich ergänze dies im branch unserer finalen PV-Änderungen, ist also nocht ad-hoc in der PV sichtbar.

**Comment by mcehrhardt** [comment]
@christian-fr Die Instruction ist von Karsten im Branch ergänzt und soll auf jeden Fall drin bleiben.
