### ISSUE TITLE
SiD-Corona: Name der Befragung / URL

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#297]
Gibt es denn schon eine Festlegung, wie der Name der Befragung in der URL / dem Link sein soll?

Also beispielsweise:

`https://survey02.dzhw.eu/BEFRAGUNGNAME/`

**Comment by mcehrhardt** [comment]
@christian-fr : Unser Vorschlag wäre: "https://survey02.dzhw.eu/**studium-corona**/ " ist das trotz des Minuszeichens möglich?

**Comment by christian-fr** [comment]
Ja, das funktioniert. Minuszeichen und Unterstriche sollten funktionieren.

**Comment by christian-fr** [comment]
@mcehrhardt Wenn es dahingehend keinen weiteren Gesprächsbedarf gibt (sehe zumindest gerade keinen), könnt ihr das Issue gerne schließen.
