### ISSUE TITLE
SiD-Corona: Layout D3_6

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#298]
Mit dieser gibt es zwei Probleme.

## Problem 1 

Es sind Infield-Texte vorgesehen, die Textfelder sind derzeit jedoch zu schmal, um den kompletten infield-Text anzuzeigen - der infield-Text "€ pro Monat" würde beschnitten werden und nicht komplett lesbar sein:

>![grafik](https://user-images.githubusercontent.com/42959832/84016016-fa623380-a97c-11ea-96d1-e51b3a401a27.png)

(Es kann auch bei größer definierten Textfeldern vorkommen, dass sie von Smartphone-Browsers kleiner skaliert werden und dadurch zu wenig Platz für den Infield-Text bieten.)

@karbecke @markusloe 
**Sollen die Textfelder vergrößert werden?**

------------------------
-----------------------

## Problem 2

Es gibt Probleme bei der Smartphone-Ansicht: aufgrund der Zwischenüberschrift (**unit**) "davon entfallen auf" und der dadurch erfolgten Zusammenfassung der restlichen Antwortoptionen/Items wird beim Durchrotieren auf dem Smartphone nur einmal "Gesamteinnahmen" angezeigt, nach einem Klick auf die Pfeile werden die anderen Antwortptionen/Items angezeigt, es kann jedoch nicht zu "Gesamteinnahmen" zurückgesprungen werden.

Abhilfe könnte hier die Trennung in zwei separate Fragen bringen - diese würden in der Desktop-Ansicht (großer Bildschirm) nach minimalem Modifikationsaufwand genau so angezeigt werden wie bisher, in der Smartphone-Ansicht sähe es dann so aus:

> ![grafik](https://user-images.githubusercontent.com/42959832/84022498-a78d7980-a986-11ea-8533-914d882915e0.png)

Da hier der Unit-Text "davon entfallen auf..." an der falschen Stelle angezeigt wird, müsste er stattdessen als eine Art Zwischenüberschrift platziert werden - das Endergebnis wäre dann:

### Smartphone-Ansicht
> ![grafik](https://user-images.githubusercontent.com/42959832/84023163-e1ab4b00-a987-11ea-92af-ad7478c53364.png)

### Desktop-Ansicht
> ![grafik](https://user-images.githubusercontent.com/42959832/84023108-cb04f400-a987-11ea-9ea6-6bac30d093dc.png)

(Layout ist noch nicht optimal, eine Anpassung ergibt aber erst sinn, wenn die Struktur der Seite entschieden ist.)

@karbecke @markusloe 
**Ist diese Anpassung für euch in Ordnung?**

**Comment by mcehrhardt** [comment]
@christian-fr 
Zu Problem 1: Bitte die Textfelder vergrößern, sodass der infield-Text wenigstens in der Desktop-Ansicht lesbar ist.

Zu Problem 2: Die von dir vorgeschlagenen Anpassung ist für uns in Ordnung.

**Comment by christian-fr** [comment]
übernommen aus #283 :
> ### Seite D3_6
> Layout Prüfung
> 
> - Items bitte auf selber Höhe wie offene Textfelder positionieren.
- [ ] erledigt

> 
> - Seite bitte gemäß Word-Vorlage umsetzen
Dieses Layout (Label in der Mitte) lässt sich mit unserem System nicht umsetzen.

> 
> - Zwischenüberschrift „davon entfallen auf..." fehlt
- [ ] Zwischenüberschrift hinzugefügt

> 
> - „im letzten Semester" und „in diesem Semester" bitte fett
> schreiben und über Spalte zentrieren
- [ ] erledigt

> 
> - Item „Gesamteinnahmen" bitte fett schreiben und optisch von
> Zwischenüberschrift „davon entfallen auf..." absetzen
- [ ] erledigt

> 
> - Bitte „€ pro Monat in diesem Semester" in field übernehmen und neben
> dem Fenster nur € einblenden
- [ ] erledigt

**Comment by christian-fr** [comment]
@markusloe @mcehrhardt Bis auf den letzten Punkt konnte alles umgesetzt werden.
