### ISSUE TITLE
SiD-Corona: Addon / IAB - Korrekturhinweise.

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#299]
Vorlage:

> ![grafik](https://user-images.githubusercontent.com/42959832/84032756-145d3f80-a998-11ea-9c4d-d84477b6ae56.png)

Falls die Eingabe auf der page **IAB_2** (bislang: offene Textfelder) validiert werden soll, bräuchten wir noch einen Korrekturhinweis, der dann ggf. angezeigt wird.

Alternativ könnte die Frage auch mit drei Dropdown-Menüs versehen werden. In diesem Fall müsstet ihr uns noch den Wertebereich für die Jahre nennen, der abgedeckt werden soll.

**Comment by mcehrhardt** [comment]
@christian-fr Wir hätten die Abfrage dann gerne per Drop-Down-Menü. Der Wertebereich soll bitte bis 1971 zurückreichen und die letzte Kategorie sollte dementsprechend "1970 und früher" lauten.

**Comment by christian-fr** [comment]
Nur zur Kenntnisnahme: Ähnliches wurde in #290 auch behandelt - dieses Issue hier stellt aber für mich den aktuellen Stand dar.

**Comment by christian-fr** [comment]
Ist ausgerollt und kann getestet werden (bitte nur in Bezug auf dieses Issue / IAB-Seiten, ich erstelle morgen noch ein allgemeines Issue für die Addons)
https://presentation.dzhw.eu/corona-sid-addon1/
token: `tester1` bis `tester100`
