### ISSUE TITLE
SDK-erf01: Seiten-Text

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#3]
Page endet mit 'Vielen Dank!' und leitet in der Befragung dann trotzdem auf SDK-erf03

**Comment by karbecke** [comment]
Seite wird mir nicht mehr angezeigt. Ist das Issue noch aktuell?

**Comment by andreaschu** [comment]
Die Seitennamen haben sich geändert. Bitte schaut, ob es noch aktuell ist und schließt es, wenn es nicht mehr aktuell ist.
