### ISSUE TITLE
SiD-Corona: kleinere Anpassungen (transitions, visible conditions, Inhalt)

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#300]
Liebes ZOFAR-Team,

wie eben besprochen, hier noch ein paar kleinere Anpassungen:

C1_6 (Inhalt)
- ~[x] Bitte den Fragetext korrigieren. Er lautet: "In Anbetracht der besonderen Situation durch die zeitweise Schließung von Kitas, Kindergärten und Schulen: Wie häufig betreuen die folgenden Personen Ihr(e) Kind(er) im aktuellen Semester?“~ (09.06.20, MCE)

~D2_18 (Layout)~
~- [ ] Bitte die "ka"(Anzahl der verfassten Texte) direkt in der Spalte über den Drop-Down-Menüs darstellen~
~> edit mce: @christian-fr / @andreaschu - Gebt ihr Viktor die Info weiter oder soll ich das noch ins Layout-Issue übertragen?~
> edit christian-fr: in issue #302 verschoben

A_28 (transition)

- ~[x] Bitte in transitions ergänzen: <zofar:transition target="D2_5" condition="zofar.asNumber(sabsan) == 5" />~
~> edit christian-fr: ich habe die Reihenfolge der Transitions mal getauscht, da sie sicherlich anders intendiert sind - zuerst die Sprunganweisung mit Bedingung, danach dann die ohne Bedingung. Solltet ihr dann ggf. auch in eurem Branch anpassen:~ (09.06.20, MCE)
~> ```~
~> <zofar:page uid="A_28">~
~> [...]~
~> 	<zofar:transitions>~
~> 		<zofar:transition target="D2_5" condition="zofar.asNumber(sabsan) == 5" />~
~> 		<zofar:transition target="A_49a"/>~
~> 	</zofar:transitions>~
~> ```~
 > edit mce: @christian-fr Danke für den Hinweis. Ist im Branch angepasst.

A_49a (visible condition)

- ~[x] Bitte visible condition anpassen: vc: SHOW it1 (mastplan) IF sabsan==1 OR sabsan==MISSING~ (09.06.20, MCE)

D3_22 (visible condition)

- ~[x] Bitte visible condition anpassen: SHOW zufrvsterw if eaktsens >= 2 OR VCO_9a1 == 2~ (09.06.20, MCE)

**Comment by christian-fr** [comment]
Ist geändert. 
Einen Punkt (D2_18) habe ich in ein neues Issue (#302 ) verschoben.
Einen weiteren (A_28) habe ich oben kommentiert - er ist wie oben beschrieben umgesetzt.

**Comment by mcehrhardt** [comment]
@christian-fr Vielen Dank für deinen Einsatz! Die Punkte sind geprüft und ich schließe das Issue nun.
