### ISSUE TITLE
SiD-Corona: English Translation

### ISSUE THREAD

**Issue by lenamzimmer** [dzhw/SiD#301]
Lieber @christian-fr  ,
anbei findest Du Dein Excel-Dokument mit den ergänzten Übersetzungen. Zusätzlich zu den von Dir bereits markierten fehlenden Übersetzungen, habe ich drei Zeilen korrigiert, in denen falsche Übersetzungen eingegeben waren. Dies betrifft die Zeilen 3, 968 und 1357; die Zeilen sind zusätzlich markiert.
Neben Deinem Excel-Dokument findest Du zwei zusätzliche Word-Dokumente anbei: eines mit der Übersetzung der IAB-Datenabfrage und eines mit der Übersetzung der End-Seite. Ich kann dies auch gerne in Excel nachliefern, wenn Du mir die entsprechenden Zeilen zuschickst.

Vielen Dank für Deine Mühen!

Grüße
Lena

[Engl_Abschlusseite.docx](https://github.com/dzhw/SiD/files/4746162/Engl_Abschlusseite.docx)
[Engl_IAB_Datenverknüpfung.docx](https://github.com/dzhw/SiD/files/4746163/Engl_IAB_Datenverknupfung.docx)
[Kopie von 2020-06-08_Translation_first_draft_CF_LZ.xlsx](https://github.com/dzhw/SiD/files/4746164/Kopie.von.2020-06-08_Translation_first_draft_CF_LZ.xlsx)

**Comment by christian-fr** [comment]
@lenamzimmer Könntest Du bitte mal schauen, ob ihr für diesen Text schon eine Übersetzung habt?


D3_19.t1_0 | #{layout.QUESTION_START}Bitte geben Sie die   Art der Erwerbstätigkeit und deren inhaltliche Nähe zu den Studieninhalten   an.#{layout.QUESTION_END}
-- | --

**Comment by lenamzimmer** [comment]
@christian-fr  Nein, die Frage war nicht Bestandteil der Excel-Liste.
Mein Vorschlag:

#{layout.QUESTION_START}Please indicate the type of employment and the degree to which it is related to your study contents.#{layout.QUESTION_END}

**Comment by lenamzimmer** [comment]
Lieber @christian-fr ,

anbei die addon3 Datei mit den englischen Übersetzungen. 

[2020-06-09_addon3_translation_CF_LZ.xlsx](https://github.com/dzhw/SiD/files/4751892/2020-06-09_addon3_translation_CF_LZ.xlsx)

Mir ist aufgefallen, dass in der Datei jeweils die längeren einleitenden Texte fehlen, also sowohl für die Abschlussseite als auch die IAB Datenverknüpfung.

**Für die Abschlussseite wäre das:**
By taking part in the survey, you are helping politicians, academics and institutions of higher education to not only identify the obstacles students are currently facing, but also come up with suitable measures to address these. You thereby contribute to the general enhancement of the situation of the entire student body.

**Und für die IAB-Datenverknüpfung:**
Finally, we would like to ask you to give us your permission to connect your survey data to extracts from the administrative and social security data of the Institute for Employment Research (IAB). These data are available by default at the IAB in Nuremberg. Linking them to the information provided in the survey would enable us to analyze our survey data with regard to educational and employment biographies. To facilitate the data query and the data linkage, we will kindly ask you for your personal contact details (last name, first name, date of birth). The contact details will be transferred to the IAB and deleted immediately after the data linkage has been completed. If you have not already agreed on being contacted for future surveys, this new data set will not allow for any inference to your person. We guarantee that the obtained data will only be used for scientific research purposes and all data protection regulations are strictly observed. Of course, your consent is voluntary and you can withdraw it at any time.

**Comment by lenamzimmer** [comment]
Lieber @christian-fr ,

hier nun die hoffentlich letzten Änderungswünsche an der englischen Fragebogenversion. Ich habe die entsprechenden Zeilen gelb markiert und zusätzlich ein x in Spalte F "Aktualisierung" eingefügt.

[2020-06-09_translation_002_CF_LZ.xlsx](https://github.com/dzhw/SiD/files/4757403/2020-06-09_translation_002_CF_LZ.xlsx)

Zusätzlich sind mir noch zwei Dinge aufgefallen, die sich nicht in der Exceltabelle vermerken lassen:

- [ ] Bitte in D3_19 die Reste der Programmieranweisung aus der Fragestellung entfernen.

- [ ] In D3_22 wird das Item "your life as a whole" doppelt angezeigt und das Item "the compatibility of study and parenthood?" fehlt stattdessen. In der aktuellen Exceltabelle ist dies allerdings richtig - womöglich ist das Probelma uch schon behoben, nur noch nicht richtig ausgerollt?!

1000 Dank und Grüße!
