### ISSUE TITLE
SiD-Corona: D2_18 layout

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#302]
>
> D2_18 (Layout)
> 
> Bitte die "ka"(Anzahl der verfassten Texte) direkt in der Spalte über den Drop-Down-Menüs darstellen

(nicht wundern - habe den Text zwischenzeitlich zu einer separaten `<zofar:question>` gemacht)

Also den Text der question (`uid="q2"`) "Anzahl der verfassten Texte" verschieben:
> ![grafik](https://user-images.githubusercontent.com/42959832/84049367-a3745280-a9ac-11ea-8af3-a9e484c902a7.png)

**Comment by vdick** [comment]
fexed, ab nächsten Rollout verfügbar

**Comment by mcehrhardt** [comment]
Sieht gut aus, danke! @vdick @christian-fr @andreaschu
