### ISSUE TITLE
SiD-Corona: kleine Layoutanpassungen

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#303]
@vdick Wir haben noch ein paar kleinere Layout-Anpassungen. Diese haben allerdings keine hohe Priorität. 

A_24
- [x] ~Die Zwischenüberschrift "Ja, und zwar:" bitte mit der typischen Umrandung der aos versehen, wie bei anderen Fragen dieses Typs (z. B. bei A_15)~ (10.06.20, MCE)

C1_1

- [x] ~Bitte Verbindungslinie zwischen den aos entfernen~ (10.06.20, MCE)

CO_9a1
- [x] ~Bitte Verbindungslinie zwischen den aos entfernen~ (10.06.20, MCE)

Seite D2_19
- [x] ~Bitte offene Textfelder soweit vergrößern, dass der infield-Text zu lesen ist.~ (10.06.20, MCE)

**Comment by vdick** [comment]
fixed, ab nächsten Rollout verfügbar

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar
