### ISSUE TITLE
SiD-Corona: Probleme im responsiven Design

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#304]
Liebes ZOFAR-Team,
hier, wie besprochen, noch ein Issue zu den Problemen im responsiven Design.
Im **oberen Teil** findet ihr Punkte, die **bis zum Feldstart** angepasst werden sollten, darunter sind Punkte, bei denen eine Änderung schön wäre, allerdings habe diese keine Priorität.
@christian-fr Die drei Punkte, die wir besprochen haben, führe ich hier der Vollständigkeit halber auch nochmal an.

**Seiten, die bearbeitet werden müssen:**

N_9b und N_10b
- [x] ~Bitte,wie besprochen, die Texte "im letzten Semester" und "in diesem Semester" näher an die Items rücken.~ (11.06.20, MCE)

D2_21 edit christian-fr: **Andrea macht das**
- [x] ~Bitte, wie besprochen, die Position von Zwischenüberschrift und Item tauschen. 
 edit christian-fr: unit-texte raus und in question rein - Andrea macht das~ (11.06.20, MCE)

CO_17
- [x] ~Das letzte Item hat eine andere Skala als die restlichen statt „nein, sehr unwahrscheinlich“ bis „ja, sehr wahrscheinlich steht dort „trifft gar nicht zu“ bis „trifft voll und ganz zu“. Bitte anpassen.~ (11.06.20, MCE)

**weitere kleinere Probleme:**

CO_20
- [x] ~Das offene Textfeld des letzten Item „Anderen Finanzierungsquelle(n), und zwar:“ lässt sich aktuell noch nicht ansteuern, sodass dort nichts eingetragen werden kann. Scheinbar liegt das offene Feld über der Ansteuerung der einzelnen Items, sodass beim Anklicken das Item wechselt oder so weit rechts ist , dass es nicht angeklickt werden kann. Bei gedrehter Ansicht löst sich das Problem allerdings auf. Allerdings wäre es gut, wenn das noch anderweitig gelöst werden könnte.~(11.06.20, MCE)

CO_2
- [x] ~Bitte mehr Abstand zwischen den einzelnen Abfragen. Also Absatz/Leerzeile vor „Mündliche Prüfungen wurden …“ und vor „Schriftliche Leistungen (…)“.~

Seite A_25
- [x] ~Das offene Textfeld zum vorletzten Item „Anderen Abschluss (…), und zwar:“ lässt sich im Hochformat noch nicht ansteuern, sodass nichts eingetragen werden kann. Bitte anpassen.~ (11.06.20, MCE)
- [x] ~Die Felder für beide offenen Angaben bitte etwas größer ziehen und Schriftgröße im Feld an andere Textfelder anpassen.~ (11.06.20, MCE)

A_34 und A_32
- [x] Die Spaltenüberschriften „Vater“ und „Mutter“ sind nicht über den Antwortbuttons zentriert.  Bitte anpassen.
- [x] Bei der Verwendung von Tablets stehen die Spalten sehr weit auseinander bzw. die „Vater“-Spalte ist im Vergleich sehr nah an den Items. Außerdem überlappen sich in dieser Ansicht Item 4 und Item 5 (bei A_32). Bitte anpassen, wenn möglich.

A_9b
- [x] ~Bitte die Schriftgröße im Feld an andere Textfelder anpassen/etwas vergrößern.~ (11.06.20, MCE)

A_12a
- [x] ~Das Textfeld für die offene Angabe ist etwas verrutscht (bitte anpassen) und die Schriftgröße im Feld bitte an andere Textfelder anpassen/etwas vergrößern.~ (11.06.20, MCE)

CO_13
- [x] ~Das Textfeld für die offene Angabe ist etwas verrutscht (bitte anpassen) und die Schriftgröße im Feld bitte an andere Textfelder anpassen/etwas vergrößern.~ (11.06.20, MCE)

**Comment by andreaschu** [comment]
> D2_21 edit christian-fr: Andrea macht das
> 
>     Bitte, wie besprochen, die Position von Zwischenüberschrift und Item tauschen.
> 
>     edit christian-fr: unit-texte raus und in question rein - Andrea macht das

ist umgesetzt und kann getestet werden
- [ ] **to do** die Übersetzung muss angepasst werden, weil sich die id's geändert haben

**Comment by mcehrhardt** [comment]
@andreaschu Ich habe es mir gerade angeschaut. Im responsiven Design sieht es gut aus, allerdings scheint sich die Änderung negativ auf die Desktopansicht ausgewirkt zu haben, denn dort sind nun alle Skalenüberschriften in die Zeile des jeweils ersten Items gerutscht. (siehe Screenshot)

![grafik](https://user-images.githubusercontent.com/57707751/84263431-ca06ca80-ab1f-11ea-9159-64efd2a88973.png)

**Comment by christian-fr** [comment]
Übersetzung ist geändert, ab nächstem rollout verfügbar

**Comment by vdick** [comment]
CO_20 ab nächsten Rollout verfügbar

**Comment by mcehrhardt** [comment]
@vdick Klasse! Alle anderen Sachen sind auch schon geprüft. Bei A_32 und A_34 sind die Spaltenüberschriften allerdings noch leicht nach rechts versetzt (auch bei verschiedenen mobilen Geräten). Hat allerdings keine hohe Priorität.

**Comment by vdick** [comment]
@mcehrhardt ab nächsten Rollout verfügbar

**Comment by mcehrhardt** [comment]
@vdick Danke! Sieht gut aus. Ich schließe das Issue nun.
