### ISSUE TITLE
SiD-Corona: A_53 responsive Ansicht

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#307]
- [x] für kleine Bildschirme eine alternative Seite bauen mit zwei multiple choice fragen untereinander 
- [x] Übersetzung hinzufügen/ anpassen

**Comment by andreaschu** [comment]
@vdick , könntest Du hier noch mal schauen:
![grafik](https://user-images.githubusercontent.com/30111489/84363979-c5015400-abcf-11ea-8395-5e3bc0b2c00c.png)

**Comment by andreaschu** [comment]
**A_53a** für große Bildschirme und nur, wenn ssemhs>1

![grafik](https://user-images.githubusercontent.com/30111489/84364239-20334680-abd0-11ea-9db6-91f065f384ff.png)

---
**A_53** für kleine Bildschirme und (unabhängig von Bildschirmgröße) wenn ssemhs==1

![grafik](https://user-images.githubusercontent.com/30111489/84364375-46f17d00-abd0-11ea-90a1-b35730e410a2.png)

**Comment by vdick** [comment]
A_53a ist erledigt und ab nächsten Rollout verfügbar

**Comment by andreaschu** [comment]
die geänderten Weiterleitungs- und Einblendungsbedingungen können getestet werden
