### ISSUE TITLE
SiD-Corona: visible conditions

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#308]
Lieber @christian-fr ,
wie eben besprochen, hier noch ein paar Anmerkungen zu einigen visible conditions sowie ein kleine inhaltliche Änderung.

D2_19
- [x] ~Visible Condition „SHOW ao2 if ssemhs >= 2 **OR ssemhs == MISSING**“ fett markierter Teil funktioniert nicht mehr.~ (11.06.20, MCE)
> edit mce: Fehler meinerseits, aber das eigentliche Problem hat sich auch gelöst.

D3_6
- [x]  ~Bitte folgende Visible Conditions ergänzen:~ (11.06.20, MCE) 
o	~SHOW itb, ao1b, ao2b, ao3b, ao4b, ao5b AND ao6b IF TRUE~ 
o	~SHOW ita, ao1a, ao2a, ao3a, ao4a, ao5a AND ao6a IF ssemhs >=2 OR ssemhs == MISSING~ 
~Ist von uns im Branch (noch nicht hochgeladen) auch für die PV hinterlegt.~ 

A_56
- [x] Visible condition „SHOW ao1b, ao2b, ao3b, ao4b AND ao5b IF ssemhs >=2 **OR ssemhs == MISSING**“ fett markierter Teil funktioniert noch nicht.

D3_22
- [x]  ~Bitte fett markierten Teil in Visible Conditions ergänzen:~ (11.06.20, MCE) 
o	~SHOW zufrvstbe if h_gartcount >= 1 **OR gartka==1**~
~Ist von uns im Branch (noch nicht hochgeladen) auch für die PV hinterlegt.~

CO_23
- [x] ~Bitte ao1 und ao2 ändern in:~ (11.06.20, MCE) 
o	~ao1: 1: vor dem 1. Juni 2020 -> vor dem **15.** Juni 2020~
o	~ao2: 2: nach dem 1. Juni 2020 -> nach dem **15.** Juni 2020~
~Ist von uns im Branch (noch nicht hochgeladen) auch für die PV hinterlegt.~

**Comment by christian-fr** [comment]
Ist übernommen, nach nächstem rollout verfügbar

**Comment by mcehrhardt** [comment]
@christian-fr  dann fehlt nur die vc bei A_56 und dann kann das Issue geschlossen werden.

**Comment by andreaschu** [comment]
@mcehrhardt die vc bei A_56 kann getestet werden
