### ISSUE TITLE
Übergang Hauptbefragung - ADDON-Seiten

### ISSUE THREAD

**Issue by lenamzimmer** [dzhw/SiD#309]
Lieber @christian-fr ,

hier nun der Übergang von der Hauptbefragung zu den ADDON-Seiten:

[Übergang_Hauptbefragung_Addon_LZ_ML.docx](https://github.com/dzhw/SiD/files/4759621/Ubergang_Hauptbefragung_Addon_LZ_ML.docx)

Viele Grüße!
Lena

**Comment by christian-fr** [comment]
Der rollout der aktuellen Addon-Versionen dauert leider noch, ich hatte gestern aber bereits Screenshots des Übergangs zusammengestellt - in der Hoffnung, dass man dort einen guten Eindruck von Seitenabfolge bekommt:
[2020-06-10_Screenshots_end_addons.docx](https://github.com/dzhw/SiD/files/4763583/2020-06-10_Screenshots_end_addons.docx)

**Comment by lenamzimmer** [comment]
Lieber @christian-fr ,

hier nun die Übersetzung der Übergangsseiten für die englische Version!

[Übergang_Hauptbefragung_Addon_LZ_ML_englVW.docx](https://github.com/dzhw/SiD/files/4763807/Ubergang_Hauptbefragung_Addon_LZ_ML_englVW.docx)

**Comment by lenamzimmer** [comment]
Lieber @christian-fr ,

wie bereits per Mail zugesendet, hier noch einmal eine Übersicht der Addon-Pfade:

[ADDONs_Pfade_2020-06-11.docx](https://github.com/dzhw/SiD/files/4764487/ADDONs_Pfade_2020-06-11.docx)

Viele Grüße!
Lena
