### ISSUE TITLE
E1_6: Units funktionieren nicht responsiv

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#31]
Gibt es hier eine Alternative zu Units?

![grafik](https://user-images.githubusercontent.com/30111489/65584689-8ebc6f80-df81-11e9-92ea-2340e3f1de1c.png)

**Comment by SilinaKowalewski** [comment]
Erste Test-Version mit mehreren Fragen gebaut. Nun stehen die Fragen allerdings (auch im responsiven Design) untereinander. Sieht auch nicht so schön aus. 

Fragen eventuell "hintereinander" programmieren. Also auf separaten Seiten?

**Comment by karbecke** [comment]
E1_6b zeigt den Fragetext jeweils vor jedem Antwortblock wieder an-->
![E1_6](https://user-images.githubusercontent.com/46674616/67573047-bb59d780-f737-11e9-9074-c785d5638f89.PNG)

--> könnt ihr die Fragetext-Doppelungen bitte rausnehmen

**Comment by karbecke** [comment]
habe E1_6b im qml-Code angepasst
