### ISSUE TITLE
B2_9b und KSM-ma06

### ISSUE THREAD

**Issue by ParmidaZarei** [dzhw/SiD#313]
Bei dieser Frage sind im Presenter Items und Skala getauscht dargestellt. Bitte umdrehen.
![grafik](https://user-images.githubusercontent.com/57707751/108992885-1851fe80-769a-11eb-915e-f99f2e098bf2.png)

_Originally posted by @mcehrhardt in https://github.com/dzhw/SiD/pull/236#discussion_r581873752_

**Comment by christian-fr** [comment]
@andreaschu Auf kleinen Bildschirmen wird das so glaube ich nichts.

**Comment by SilinaSchirmer** [comment]
Gleiches Problem besteht auch bei [KSM-ma06](https://presentation.dzhw.eu/sid-2021/KSM-ma06.html)

**Comment by andreaschu** [comment]
@mcehrhardt und @karbecke auf der Seite gibt es jetzt mehrere Vorschläge für die Frage. Hier gibt es zwar noch kleine Layout-Bugs, aber es macht erst Sinn das anzugehen, wenn entschieden ist, wie die Frage aussehen soll. Ich denke, für eine Vorstellung was geht, reicht es aus.
Hier noch ein paar Punkte zu den Vorschlägen:
- die erste Lösung ist schwierig für ganz kleine Bildschirme, da es nicht ins Carousel umbricht.
- die zweite Lösung wird für Tablets nicht optimierbar sein. Dazu gibt es zu viele Antwortoptionen und die Label sind zu lang.
- die dritte Lösung geht aus meiner Sicht inhaltlich nicht.
- die vierte und fünfte Lösung sind m.M.n. die besten Alternativen.

**Comment by karbecke** [comment]
- [ ] Bitte die zweite Lösung umsetzen und die Spaltenüberschriften gemäß GitHub-commit anpassen: f8455d1
- [ ] Bitte diese Lösung auf Tablets auch das responsive Design eines Smartphones anzeigen
- [ ] Und bitte die Antwortoption "Hochschulabschluss" noch ergänzen (s. GitHub-Commit oben)

**Vielen Dank**

**Comment by SilinaSchirmer** [comment]
Die abgehakten Änderungen wurden umgesetzt und sind ab dem nächsten Rollout (#386) verfügbar.

**Comment by mcehrhardt** [comment]
Liebe @SilinaSchirmer,

ist geprüft. Bei ao10 hat sich ein Fehler eingeschlichen müsste bitte in "> 10.000" geändert werden.

LG
Marie

**Comment by mcehrhardt** [comment]
@SilinaSchirmer , ich denke, dass mein letzter Kommentar untergegangen ist, weil ich das Label nicht geändert habe.

**Comment by meyerja** [comment]
@SilinaSchirmer : Die Frage taucht genauso auf der Seite KSM-ma06 auf. Bitte alle Änderungen auch für diese Seite übernehmen. Danke :)

**Comment by SilinaSchirmer** [comment]
Die inhaltlichen Änderungen sind am nächstem Rollout (#400) verfügbar.

**Comment by SilinaSchirmer** [comment]
> @SilinaSchirmer : Die Frage taucht genauso auf der Seite KSM-ma06 auf. Bitte alle Änderungen auch für diese Seite übernehmen. Danke :)

@meyerja: Bitte auch im GitHub-Code anpassen.

**Comment by SilinaSchirmer** [comment]
Habe das Issue #407 bzgl. des responsiven Designs erstellt, damit dieses Issue nicht zu lang wird und bald geschlossen werden kann 💯

**Comment by meyerja** [comment]
@SilinaSchirmer : Änderungen sind im GitHub-Code angepasst 7a58053

**Comment by karbecke** [comment]
ok, Issue closed
