### ISSUE TITLE
B1_5: text layout / asterisk

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#319]
QML bitte an Github-Code anpassen: ao2 Gender-Sternchen so verwenden wie bei ao1
![grafik](https://user-images.githubusercontent.com/57707751/109137682-c1136300-7759-11eb-9974-f99ee8098899.png)

_Originally posted by @mcehrhardt in https://github.com/dzhw/SiD/pull/235#r582704774_

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.

**Comment by woisch** [comment]
geprüft
