### ISSUE TITLE
neue Links zum Presentation-Server

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#324]
Wir haben die neue Version ausgerollt, sie ist unter folgenden URLs erreichbar:

https://presentation.dzhw.eu/sid-2021/

http://vmtest.dzhw.local:8080/sid-2021

Die Links im Wiki sind bereits aktualisiert.

**Comment by SilinaSchirmer** [comment]
Links sind im Wiki einsehbar, nehme an ihr habt sie schon gefunden.

Schließe dann dieses Issue.
