### ISSUE TITLE
Modul Fairness_Änderungen AGH

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#33]
0e9bfff

**Comment by andreaschu** [comment]
wurde umgesetzt

**Comment by SMajer** [comment]
Frage @andreaschu @SilinaKowalewski : Die Seiten KSM-fai06 bis KSM-fai15 sollen zufällig auf die Befragten verteilt werden. Also ab KSM-fai05 Split auf die 10 Folgeseiten.
Wie definiere ich eine Hilfsvariable mit Wertebereich 1-10 und weise die Befragten zufällig einem der Werte zu? Finde hierzu kein Beispiel in der Programmieranleitung.

**Comment by SilinaKowalewski** [comment]
Hilfsvariablen müssen auf der Index-Seite der Programmiervorlage angelegt und wie folgt definiert werden: 

- Für einen **50:50 Split mit einmaliger Zuweisung** (der Zufallswert wird den Befragten einmalig zugewiesen und beibehalten): 
` sv: s_split_[name] = 0, 1 (einmalige Randomisierung; 0= 50%; 1= 50 %)`

- Für einen **3er- Split mit einmaliger Zuweisung**
`sv: s_split_[name] = 1, 2, 3 (einmalige Randomisierung; 1= 33%; 2= 33 %, 3= 33%)`
- Für einen **3er-Split mit wiederholter Zuweisung** (bei neuem Laden der Seite erfolgt eine neue Zuweisung)
`sv: s_split_[name] = 1, 2, 3 (wiederholte Randomisierung; 1= 33%; 2= 33 %, 3= 33%)`

- Für einen **80:20 Split mit einmaliger Zuweisung**:
`sv: s_split_[name] = 0, 1 (einmalige Randomisierung; 0= 80%; 1= 20 %)`

**Comment by SilinaKowalewski** [comment]
@SMajer: 

Für dich bedeutet das also: 

> s_split__[name]_ = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 (_einmalige/wiederholte_ Randomisierung; 1= 10%, 2= 10 %, 3= 10%, 4= 10%, 5= 10%, 6= 10%, 7= 10%, 8= 10%, 9= 10%, 10= 10%)

Bitte füge die angepasste Definition auf die Index-Seite der Programmiervorlage ein.

**Comment by SMajer** [comment]
> 
> 
> @SMajer:
> 
> Für dich bedeutet das also:
> 
> > s_split__[name]_ = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 (_einmalige/wiederholte_ Randomisierung; 1= 10%, 2= 10 %, 3= 10%, 4= 10%, 5= 10%, 6= 10%, 7= 10%, 8= 10%, 9= 10%, 10= 10%)
> 
> Bitte füge die angepasste Definition auf die Index-Seite der Programmiervorlage ein.

@SilinaKowalewski : Danke dir! Ist die Indexseite in diesem Fall = die Seite, auf welcher der Split passieren soll, also KSM-fai05?

**Comment by SilinaKowalewski** [comment]
Am einfachsten ist es für uns, wenn die Variablen wirklich auf der "Startseite" der Befragung bzw. der Moduls, also der Seite KSM-fai01  angelegt werden.  

Wenn gewünscht, können wir den Wert der Variable gerne auf der Seite KSM-fai05 einblenden, damit die Funktionalität des Splits leichter getestet werden kann. Die Einblendung würden wir dann für den Live-Betrieb wieder löschen.

**Comment by SilinaKowalewski** [comment]
Ja, genau :)

**Comment by SMajer** [comment]
> 
> 
> Ja, genau :)

OK, habe den Split auf KSM-fai01 eingefügt und die Übergänge auf KSM-fai05 definiert (9c621f0). Bitte bei Gelegenheit prüfen.

**Comment by SMajer** [comment]
@andreaschu @SilinaKowalewski:  KSM-fai06: Skalenbeschriftung gedreht (passend zum Text), siehe b4d8eeb
