### ISSUE TITLE
2021 - Aktualisierung Modul E2 Studienanfang

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#332]
Liebes ZOFAR-Team,

das **Modul E2 Studienanfang** wurde aktualisiert:

- [x] Bitte arbeitet die Änderungen von 5d19527 in die QML ein.

Vier der Fragen existieren bereits in anderen Modulen und wurden an dieser Stelle ebenfalls aufgenommen. Bitte beachten, dass die Variablennamen jedoch nicht identisch sind, sondern jeweils mit dem Zusatz "b" ergänzt wurden. Dabei handelt es sich um die folgenden Fragen: 

- KSM-anf02 existiert bereits als B2_8a2
- KSM-anf03 existiert bereits als D1_29
- KSM-anf04 existiert bereits als D1_7
- KSM-anf05 existiert bereits als D1_8

Ebenso sind uns noch einige notwendige Anpassungen der QML (auf Basis der bereitgestellten presenter-Version) aufgefallen, die im GitHub-Code schon richtig stehen, aber noch in die QML eingearbeitet werden müssten:

- [x] Weiterleitung von KSM-anf01 auf KSM-anf02 funktioniert nicht (durch "weiter" klicken nicht möglich, nur durch eintippen in Adresszeile im Presenter möglich)
- [x] KSM-anf07: Bitte QML an GitHub-Code anpassen --> Derzeit wird kein Fragetext angezeigt.
- [x] KSM-anf11: Bitte QML an GitHub-Code anpassen --> Item 1 ist nicht auf dem aktuellen Stand (akademische Sprach- anstatt Sprache)

Vielen Dank!

**Comment by andreaschu** [comment]
Die Bedingung `SHOW it1 IF sabsan != 1 OR sabsan != 2 ` ist so falsch (da es sonst bei sabsan==1 angezeigt werden würde und bei sabsan==2). 
Ich ändere sie mal um in `SHOW it1 IF sabsan != 1 AND sabsan != 2` 
Bitte auch in der PV korrigieren.

**Comment by SilinaSchirmer** [comment]
Alle Änderungen wurden aktualisiert und sind ausgerollt.

**Comment by meyerja** [comment]
Liebes ZOFAR-Team,

das Modul wurde nochmals aktualisiert.

- [ ] Bitte arbeitet die Änderungen von d04fab7 in die QML ein.

Vielen Dank!

**Comment by andreaschu** [comment]
> Bitte arbeitet die Änderungen von d04fab7 in die QML ein.

Wurde umgesetzt. Ist ab nächstem RollOut verfügbar.

@meyerja bitte das Issue schließen, wenn alle Änderungen hier korrekt umgesetzt sind und für neue Änderungen bitte ein neues Issue aufmachen.
