### ISSUE TITLE
2021 - Aktualisierung Modul E2 Master

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#333]
Liebes ZOFAR-Team,

das **Modul E2 Master** wurde aktualisiert:

Bitte arbeitet die Änderungen von c13434f in die QML ein.

Eine der Fragen existiert bereits in einem anderen Modul und wurde an dieser Stelle ebenfalls aufgenommen. Bitte beachten, dass die Variablennamen jedoch nicht identisch sind, sondern jeweils mit dem Zusatz "b" ergänzt wurden. Dabei handelt es sich um die folgende Frage:

- KSM-ma06 existiert bereits als B2_9b

Ebenso sind uns noch einige notwendige Anpassungen der QML (auf Basis der bereitgestellten presenter-Version) aufgefallen, die im GitHub-Code schon richtig stehen, aber noch in die QML eingearbeitet werden müssten:

- [x] KSM-ma01: Bitte QML an GitHub-Code anpassen -->Teile des Einleitungstext noch nicht fett gedruckt

- [x] KSM-ma06: Bitte QML an GitHub-Code anpassen -->transition zu Seite KSM-ma07 funktioniert nicht

- [ ] ~KSM-ma07: Bitte QML an GitHub-Code anpassen -->Item 13 ("anderes und zwar") immer als letztes angezeigen, die restlichen Items jedoch in randomisierter Reihenfolge~

Vielen Dank!

**Comment by SilinaSchirmer** [comment]
Abgehakte Änderungen wurden umgesetzt und ausgerollt. 

Änderung bzgl. der Rotation wurde in #358 übernommen

**Comment by meyerja** [comment]
Liebes ZOFAR-Team,

das Modul wurde nochmals überarbeitet.

- [ ] Bitte arbeitet die Änderung von  5572179 in die QML ein.

Außerdem sind beim Testen folgende Dinge aufgefallen:

- [ ] Auf Seite KSM-ma02 bitte die Verbindunglinie zwischen den Antwortkategorien entfernen.
- [ ] Darstellung auf Seite KSM-ma06 funktioniert nicht. Antwortkategorien sind nicht lesbar.

Vielen Dank!

**Comment by SilinaSchirmer** [comment]
ab nächstem Rollout (#372) verfügbar
