### ISSUE TITLE
2021 - Aktualisierung Modul E2 Promotion

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#334]
Liebes ZOFAR-Team,

das **Modul E2 Promotion** wurde aktualisiert:

- [x] Bitte arbeitet die Änderungen von 92adf3b in die QML ein.

Ebenso sind uns noch einige notwendige Anpassungen der QML (auf Basis der bereitgestellten presenter-Version) aufgefallen, die im GitHub-Code schon richtig stehen, aber noch in die QML eingearbeitet werden müssten:

- [ ] ~KSM-phd02: Bitte QML an GitHub-Code anpassen -->letztes Item (Item 18 "sonstige und zwar") soll immer am Schluss stehen, die restlichen Items jedoch in randomisierter Reihenfolge angezeigt werden~

Vielen Dank!

**Comment by andreaschu** [comment]
> letztes Item (Item 18 "sonstige und zwar") soll immer am Schluss stehen, die restlichen Items jedoch in randomisierter Reihenfolge angezeigt werden

@dzhwmeisner geht das überhaupt?

**Comment by dzhwmeisner** [comment]
> > letztes Item (Item 18 "sonstige und zwar") soll immer am Schluss stehen, die restlichen Items jedoch in randomisierter Reihenfolge angezeigt werden
> 
> @dzhwmeisner geht das überhaupt?
@andreaschu 
Das geht.
Alle Items ausser der letzen werden in einer Random-Sort Section zusammengefasst.

**Comment by SilinaSchirmer** [comment]
Abgehakte Änderungen wurden umgesetzt und ausgerollt.

Änderung bzgl. der Rotation wurde in #358 übernommen

**Comment by meyerja** [comment]
Liebes ZOFAR-Team,

beim Testen ist folgendes aufgefallen:

- [ ] Leider werden die Vignettentexte nicht richtig angezeigt (Umlaute und € werden durch ein ? dargestellt). Liegt das Problem bei der Vorlage, also der Excel-Tabelle, oder der Programmierung?
- [ ] Nach den Vignetten wird man auf die Seite phd03 weitergeleitet, die es eigentlich nicht mehr gibt. Hierbei handelt es sich um eine alte Version. Die Weiterleitung sollte eigentlich auf die Seite phd02 erfolgen.
- [ ] Darstellung der Seite phd02 leider noch nicht optimal: Skalenbeschriftung hängt zu weit oben im Fragetext drin.

Vielen Dank!

**Comment by andreaschu** [comment]
@meyerja 

1. die Texte waren ein Kodierungsfehler. Der sollte ab dem nächsten Roll-Out korrigiert sein.
2. in der PV gibt es keinerlei Weiterleitungen. Ursprünglich war die Weiterleitung in Abhängigkeit von promoplan zu phd_02 bzw. KSM-phd03. Bitte hier die [PV](https://github.com/dzhw/SiD/blob/master/Modul_E2_Promotion-Vignetten.md) entsprechend ändern und ein neues Issue dafür aufmachen.

```
			target="KSM-phd02" If "(promoplan) ge 3"
			target="KSM-phd03" If "(promoplan)  lt 3
```


3. hierzu gibt es eine allgemeines Layout-Issue. Bitte dort vermerken.
