### ISSUE TITLE
2021 - Aktualisierung Modul E3 Politik

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#335]
Liebes ZOFAR-Team,

das **Modul E3 Politik** wurde aktualisiert:

- [x] Bitte arbeitet die Änderungen von 61ff782 in die QML ein.

Ebenso sind uns noch einige notwendige Anpassungen der QML (auf Basis der bereitgestellten presenter-Version) aufgefallen, die im GitHub-Code schon richtig stehen, aber noch in die QML eingearbeitet werden müssten:

- [x] KSM-pol01: Bitte QML an GitHub-Code anpassen --> Fragetext ist optisch nicht vom Einleitungstext abgesetzt.

Vielen Dank!

**Comment by SilinaSchirmer** [comment]
Änderungen wurden umgesetzt und sind ausgerollt.

**Comment by meyerja** [comment]
Liebes ZOFAR-Team,

beim Testen ist folgendes aufgefallen: 

- [ ] Auf Seite KSM-pol07 bitte die Exklusivkategorie optisch von den restlichen Items absetzen und einen Kasten um die Items setzen. 
- [ ] Die Transition auf der letzten Seite (KSM-pol07) ist nicht auf dem aktuellen Stand. Momentan wird man auf die Seite A_56 weitergeleitet, jedoch soll die Weiterleitung zur Abschlussseite erfolgen. 

Vielen Dank!

**Comment by andreaschu** [comment]
> Die Transition auf der letzten Seite (KSM-pol07) ist nicht auf dem aktuellen Stand. Momentan wird man auf die Seite A_56 weitergeleitet, jedoch soll die Weiterleitung zur Abschlussseite erfolgen.

@meyerja wenn Du noch schreiben könntest, was genau die 'Abschlusseite' ist? Es gibt keine Seite mit diesem Namen.

**Comment by meyerja** [comment]
@andreaschu Die Abschlussseite hat den Namen "end"
