### ISSUE TITLE
2021 - Aktualisierung Modul E4 Fairness

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#336]
Liebes ZOFAR-Team,

das **Modul E4 Fairness** wurde aktualisiert:

- [x] Bitte arbeitet die Änderungen von 37f685f in die QML ein.

Bitte beachten: Zwei der Fragen existierten bereits in ähnlicher Form in anderen Modulen, wurden dort jedoch gelöscht und an dieser Stelle abgewandelt eingefügt. Dabei handelt es sich um die folgenden Fragen:

- KSM-fai28 existierte bereits in ähnlicher Form als N_13
- KSM-fai29 existierte bereits in ähnlicher Form als N_14

Vielen Dank!

**Comment by meyerja** [comment]
Liebes ZOFAR-Team,

beim Testen ist folgendes aufgefallen:

- [ ] Kann bei den Seiten KSM-fai16 bis KSM-fai25 die Exklusivkategorie "Nichts davon." optisch abgesetzt werden und um die restlichen Items ein Kasten gelegt werden?
- [ ] Gleiche Anmerkung für KSM-fai28: auch hier Kasten und Absetzen der Exklusivkategorie möglich?
- [ ] Die Weiterleitung zur Abschlussseite bei KSM-fai28 bzw. KSM-fai29 funktioniert nicht. Derzeit Weiterleitung zur Seite A_56 und nicht zur Abschlussseite.

Vielen Dank!

**Comment by andreaschu** [comment]
@meyerja 
Für das Absetzen der Exklusivkategorien habe ich ein Sammel-Issue erstellt (#375). 
Für die Weiterleitung hier, gilt dieselbe Anmerkung von #335 . Eine Seite mit dem Namen "Abschlusseite" gibt es nicht. Hier müsste die Programmiervorlage geändert werden.

**Comment by meyerja** [comment]
@andreaschu Die Weiterleitung zur Abschlussseite ist bereits in der PV enthalten (GOTO Abschlussseite). Bei den Modulen E2 funktioniert die Weiterleitung zur Seite mit dem Namen "end" obwohl derselbe Hinweis in der PV hinterlegt ist.

**Comment by meyerja** [comment]
- [ ] Auf der Seite KSM-fai05 steht links unten im Moment noch ein Platzhalter für den fairsplit (z.B. Wert "s_fairsplit": 9). Die Splits wurden getestet und funktionieren, daher kann dieser gerne entfernt werden. Danke :)

**Comment by SilinaSchirmer** [comment]
> * [ ]  Auf der Seite KSM-fai05 steht links unten im Moment noch ein Platzhalter für den fairsplit (z.B. Wert "s_fairsplit": 9). Die Splits wurden getestet und funktionieren, daher kann dieser gerne entfernt werden. Danke :)

Ab nächstem Rollout (#386) verfügbar.
