### ISSUE TITLE
Master-Vignetten: KSM-ma07 Einblendbedingungen fehlen 

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#34]
Auf der Seite [KSM-ma07](https://github.com/dzhw/SiD/blob/master/Modul_Master-Vignetten.md#ksm-ma07) ist die Einblendung der Fragen abhängig von einer Einblendbedingungen. Diese fehlt aktuell noch.

**Comment by SMajer** [comment]
@andreaschu + @SilinaKowalewski : Dieses Modul sollen nur Bachelorstudierende ab dem 4. Semester beantworten (IF sabsan = 1 AND ssemhs>=4). Muss ich die Einblendbedingung auf jeder Seite unter "tc:" angeben oder wird an einer anderen Stelle im Fragebogen der Split auf die Module programmiert?
Weitere Änderungen siehe abf4fa6 bzw. Modul_Master-Vignetten.md

**Comment by SMajer** [comment]
@andreaschu: Startseite mit Einleitungstext und Transition auf Vignette eingefügt (8a0a8d5).

**Comment by SMajer** [comment]
> 
> 
> Auf der Seite [KSM-ma07](https://github.com/dzhw/SiD/blob/master/Modul_Master-Vignetten.md#ksm-ma07) ist die Einblendung der Fragen abhängig von einer Einblendbedingungen. Diese fehlt aktuell noch.

@SilinaKowalewski:  Wurde anders gelöst: Auf KSM-ma06 wird auf die folgenden Seiten weitergeleitet (GOTO KSM-ma07 IF mastplan = 4 OR mastplan = 5 GOTO KSM-ma08 IF mastplan = 1 OR mastplan = 2 GOTO KSM-ma09 IF mastplan = 3).

**Comment by SilinaKowalewski** [comment]
@dzhwmeisner: Aufgrund der Änderung mussten die Templates angepasst werden. Bitte erstelle die Vignetten erneut.

**Comment by SMajer** [comment]
> 
> 
> @dzhwmeisner: Aufgrund der Änderung mussten die Templates angepasst werden. Bitte erstelle die Vignetten erneut.

Datei am 27.09 @andreaschu. Ist diese fehlerhaft/unvollständig? Können wir die Datei selbst einbauen/verlinken?

**Comment by andreaschu** [comment]
> Datei am 27.09 @andreaschu. Ist diese fehlerhaft/unvollständig? Können wir die Datei selbst einbauen/verlinken?

Nein, mit _Templates_ ist hier die Vorlage zur automatischen Erstellung der Vignetten gemeint. 
Wir haben mit den aktuellen Excel-Dateien gearbeitet. Ich werde sie gleich hochladen. Grundsätzlich kannst Du das auch.

**Comment by dzhwmeisner** [comment]
Vignetten für den Master-Zweig neu erstellt
