### ISSUE TITLE
Verbindungslinie zwischen Radio buttons entfernen (allg. Layout 1/5)

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#340]
Liebes ZOFAR-Team,

bitte korrigiert das Layout hinsichtlich:

### (1)	Einfachauswahl, die keine Skala ist: bitte _ohne_ optische Verbindungslinie darstellen
_Bsp.: richtig dargestellt:_
![B1_1](https://user-images.githubusercontent.com/46674616/111148109-88fa8580-858b-11eb-9d86-39d9dcfa4818.PNG)

### Bitte das Layout der folgenden Seiten diesbezüglich anpassen:

- [x] [A_8a](http://vmtest.dzhw.local:8080/sid-2021/A_8a.html)
- [x] [A_9b](http://vmtest.dzhw.local:8080/sid-2021/A_9b.html)
- [x] [A_12a](http://vmtest.dzhw.local:8080/sid-2021/A_12a.html)
- [x] [A_17](http://vmtest.dzhw.local:8080/sid-2021/A_17.html) (Urlaubssemester ja/nein)
- [x] [A_25b](http://vmtest.dzhw.local:8080/sid-2021/A_25b.html)
- [x] [A_33](http://vmtest.dzhw.local:8080/sid-2021/A_33.html)
- [x] [A_35](http://vmtest.dzhw.local:8080/sid-2021/A_35.html)
- [x] [A_38b](http://vmtest.dzhw.local:8080/sid-2021/A_38b.html)
- [x] [B1_5](http://vmtest.dzhw.local:8080/sid-2021/B1_5.html)
- [x] [B1_7](http://vmtest.dzhw.local:8080/sid-2021/B1_7.html)
- [x] [B2_10](http://vmtest.dzhw.local:8080/sid-2021/B2_10.html)
- [x] [C2_0](http://vmtest.dzhw.local:8080/sid-2021/C2_0.html)
- [x] [C2_12](http://vmtest.dzhw.local:8080/sid-2021/C2_12.html)
- [x] [D1_16](http://vmtest.dzhw.local:8080/sid-2021/D1_16.html) (Beurlaubung (ja/nein)
- [x] [D2_5](http://vmtest.dzhw.local:8080/sid-2021/D2_5.html)
- [x] [D3_13b](http://vmtest.dzhw.local:8080/sid-2021/D3_13b.html)
- [x] [F3_16](http://vmtest.dzhw.local:8080/sid-2021/F3_16.html)

**Vielen Dank!**

**Comment by vdick** [comment]
ab nächsten Rollout(#346 ) verfügbar

**Comment by woisch** [comment]
Alle geprüft bis auf A_35 (noch nicht umgesetzt).
Prüfe ich nach dem nächsten Rollout und mache dann erst zu.

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by SilinaSchirmer** [comment]
Auch die A_35 wurde nun umgesetzt und ist ausgerollt.

**Comment by woisch** [comment]
A_35 passt jetzt auch. ich schließe jetzt.
