### ISSUE TITLE
2021 - Allgemeine Layoutpunkt 5/5 (Abstand von Titles zu Skala vergrößern)

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#344]
(edit: Issue auf mehrere Issues aufgeteilt)

Abstand von Titles zu Skala vergrößern: 

- [x] [B2_9b](http://vmtest.dzhw.local:8080/sid-2021/B2_9b.html) : Spaltenüberschriften nicht lesbar
- [x] [B2_6 ](http://vmtest.dzhw.local:8080/sid-2021/B2_6.html) : Spaltenüberschriften zu nah an Skalenpunkte
- [x] [D3_21](http://vmtest.dzhw.local:8080/sid-2021/D3_21.html) : Spaltenüberschriften zu nah an Fragetext

~[F1_15](http://vmtest.dzhw.local:8080/sid-2021/F1_15.html) : Spaltenüberschriften "gar nicht sicher" --> "gar" ist nicht komplett lesbar~ --> wurde zu issue #353

~[A_14 ](http://vmtest.dzhw.local:8080/sid-2021/A_14.html) : "nie" bitte mittig über Skalenpunkt zentrieren
[D3_6 ](http://vmtest.dzhw.local:8080/sid-2021/D3_6.html) : Spaltenüberschriften nicht mittig zentriert
[D3_8 ](http://vmtest.dzhw.local:8080/sid-2021/D3_8.html) : Spaltenüberschriften nicht mittig zentriert
[A_56 ](http://vmtest.dzhw.local:8080/sid-2021/A_56.html) : Spaltenüberschriften nicht mittig zentriert
[B1_4a](http://vmtest.dzhw.local:8080/sid-2021/B1_4a.html) : Spaltenüberschriften nicht mittig zentriert
[B1_6 ](http://vmtest.dzhw.local:8080/sid-2021/B1_6.html) : Spaltenüberschriften nicht mittig zentriert
[D1_20](http://vmtest.dzhw.local:8080/sid-2021/D1_20.html) : Spaltenüberschriften nicht mittig zentriert~

-> Wurde zu Issue #351

~[C2_8 ](http://vmtest.dzhw.local:8080/sid-2021/C2_8.html) : Spaltenüberschriften nicht lesbar
[D2_2 ](http://vmtest.dzhw.local:8080/sid-2021/D2_2.html) : Spaltenüberschriften nicht lesbar
[D2_3 ](http://vmtest.dzhw.local:8080/sid-2021/D2_3.html) : Spaltenüberschriften nicht lesbar
[D2_21](http://vmtest.dzhw.local:8080/sid-2021/D2_21.html) : Spaltenüberschriften nicht lesbar
[C2_9 ](http://vmtest.dzhw.local:8080/sid-2021/C2_9.html) : Seite wird nicht angezeigt~ (Anzeige erfolgt über Einblendbedingung)

-> Wurde zu Issue #352

**Comment by vdick** [comment]
ab nächsten Rollout(#346 ) verfügbar

**Comment by SilinaSchirmer** [comment]
@vdick: B2_9b - nun ist die Beschriftung zu tief bzw. zu nah an den Radio-Button

**Comment by karbecke** [comment]
geprüft, es sind noch folgende Punkte offen:

- [ ] **D3_21** --> Spaltenüberschriften zu nah an Fragetext

**Comment by andreaschu** [comment]
> 
> geprüft, es sind noch folgende Punkte offen:
> 
> - [ ] **D3_21** --> Skalenüberschriften zu nah an Fragetext
> - [ ] **N_9c** Skalenüberschriften über Fragetext --> bitte korrigieren
> - [ ] **N_10c** bitte Skalenüberschriften "2" und "4" entfernen
> - [ ] **CO_5** bitte Spaltenüberschriften "2", "3", "4"   entfernen und "(1) gar nicht zufrieden" in "gar nicht zufrieden" sowie "(5) voll und ganz zufrieden" in "voll und ganz zufrieden" ändern
> - [ ] **CO_10** bitte Spaltenüberschriften "2", "3" und "4" entfernen

@karbecke hier gehört aus meiner Sicht nur der erste Punkt in dieses Issue.

**Comment by vdick** [comment]
ab nächsten Rollout (#378 ) verfügbar

**Comment by mcehrhardt** [comment]
Liebe @andreaschu ,

ich packe N_9c dann ins Issue #352. Die anderen Punkte scheinen trotzdem umgesetzt worden zu sein. Danke dafür!

Bei D3_21 haben wir immer noch ein Problem (siehe Screenshot)
![grafik](https://user-images.githubusercontent.com/57707751/112480415-4d736e80-8d76-11eb-9cb8-ca83564991d5.png)
Der erste Skalenpunkt ragt noch in den Fragetext.

Könnt ihr da nochmal schauen,bitte?

**Comment by vdick** [comment]
ab nächsten Rollout (#379 ) verfügbar

**Comment by mcehrhardt** [comment]
Umsetzung geprüft, Issue geschlossen.
LG Marie
