### ISSUE TITLE
rollout 006

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#346]
- [x] #240 ( e738d33)
- [x] #312 (5d19527)
- [x] #315  (c13434f ) (#333)
- [x] #314 (92adf3b) (#334)

**Comment by andreaschu** [comment]
#340

**Comment by ParmidaZarei** [comment]
- [ ] #317 
- [ ] #241

**Comment by andreaschu** [comment]
#337

**Comment by andreaschu** [comment]
https://github.com/dzhw/SiD/issues/323#issuecomment-801990791

**Comment by andreaschu** [comment]
#351
#352
