### ISSUE TITLE
DropDown Menüs "Jahr"

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#347]
An den Dropdownmenüs mit Jahreszahlen bitte folgende Änderungen umsetzen:

- [x] D1_4: Jahr 2021 ergänzt: 4104abe9f45dccadd667773ac37192249f4e2650

- [x] F2_6 : Jahr 2021 ergänzt ab299aef230a9dcf6254fc8ed5caa03192bd0ee3 

- [x] F3_7 (Start des Aufenthalts): Jahr 2021 ergänzt (hier stimmt die Umsetzung aber generell nicht, bitte so wie im Code vermerkt umsetzen 8f0553f9ad5afe34c6667362a2204dd1bac38141 260de65e24809db0e516154ecabdd7c61c351e2e

**Comment by woisch** [comment]
geprüft.

- [ ] Bitte bei F3_7 noch eine ao ergänzen "vor 2009". Betrifft ainfbj1/ainfbj2/ainfbj3.

**Comment by SilinaSchirmer** [comment]
Änderung umgesetzt und ab nächstem Rollout verfügbar.

**Comment by woisch** [comment]
geprüft
