### ISSUE TITLE
Dropdown Menüs Semester

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#348]
An den folgenden Dropdown Menüs zu Semesterangaben bitte Änderungen vornehmen:

- [x] D1_13 ao angepasst 68b03652e77597b755123e8b3f946ea2055b93ba
- [x] D1_15/ D1_16 ao angepasst b93d012e8e1a3c6786a394a8d88dbb38140d1a81
- [x] F1_10: ao angepasst 974d2d5e5dbac009a1f8d4bb8ddb21b711390acb

**Comment by SilinaSchirmer** [comment]
Änderungen wurden umgesetzt und sind ausgerollt.

**Comment by woisch** [comment]
geprüft,
bitte bei F1_10 noch die ao24 "vor Sommersemester 2010" einfügen.

**Comment by andreaschu** [comment]
> bitte bei F1_10 noch die ao24 "vor Sommersemester 2010" einfügen.

Geändert. Ab nächstem RollOut verfügbar.

**Comment by woisch** [comment]
geprüft, ich mache hier zu!
