### ISSUE TITLE
Dropdown Menü Abschlussart 

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#349]
Bitte das folgende Dropdown Menü anpassen:

- [x] D1_15: ao für abs01-abs05 angepasst 829311a3a043dbf5e6e4fa77dddfcd20af0c5c93

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ausgerollt.

**Comment by woisch** [comment]
geprüft, alles ok!
