### ISSUE TITLE
Master-Vignetten: Weiterleitungsbedingungen fehlen

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#35]
Lediglich für die Frage [KSM-ma02](https://github.com/dzhw/SiD/blob/master/Modul_Master-Vignetten.md#ksm-ma02) ist eine Weiterleitung angegeben. Für alle anderen Fragen fehlt diese leider.

**Comment by SMajer** [comment]
Habe Weiterleitungen eingefügt. Siehe abf4fa6 bzw. Modul_Master-Vignetten.md

**Comment by SMajer** [comment]
> 
> 
> @andreaschu: Weiterleitungen eingefügt. Siehe [abf4fa6](https://github.com/dzhw/SiD/commit/abf4fa69e066549d0e5534db2018af678621581a) bzw. Modul_Master-Vignetten.md. Bitte kurzen Blick darauf werfen, ob das Vorgehen korrekt ist.

scheint alles ok zu sein.
