### ISSUE TITLE
Dropdownmenüs Dauer/Monate

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#350]
- [x] F2_6 ao bei Dauer angepasst, Infield-Text geändert, Kategorienüberschrift ergänzen (siehe fo) 8cc4cb724e7bcfefe32454a92c86686ff444750e

- [x] F3_7 ao bei Dauer angepasst (ainfdau1-ainfdau3) fa35ff5db8eb96b2c87f78b09a823e7e05bcbf20 

- [x] D1_16: Infield Text für die Variablen sudau01 / sudau02 / sudau03 / sudau04 / sudau05 anpassen, wie im Code vermerkt: Monate  (aktuell ist "Monat" umgesetzt) 2353fcbac7a0740957a589567bc8083dc7ddb445
- [x] D1_16: ao geändert 2353fcbac7a0740957a589567bc8083dc7ddb445

**Comment by SilinaSchirmer** [comment]
Änderungen wurden umgesetzt und sind ausgerollt.

**Comment by woisch** [comment]
geprüft, alles ok!
