### ISSUE TITLE
ao-Label/Title mittig zentrieren

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#351]
Das gilt für folgende Seiten: 
- [x] [A_14 ](https://presentation.dzhw.eu/sid-2021/A_14.html) ("nie" ist nicht ganz mittig über Skalenpunkt zentriert)
- [x] [D3_6 ](https://presentation.dzhw.eu/sid-2021/D3_6.html) 
- [x] [D3_8 ](https://presentation.dzhw.eu/sid-2021/D3_8.html)
- [x] [A_56 ](https://presentation.dzhw.eu/sid-2021/A_56.html)
- [x] [B1_3a](https://presentation.dzhw.eu/sid-2021/B1_3a.html)
- [x] [B1_4a](https://presentation.dzhw.eu/sid-2021/B1_4a.html)
- [x] [B1_6 ](https://presentation.dzhw.eu/sid-2021/B1_6.html)
- [x] [D1_20](https://presentation.dzhw.eu/sid-2021/D1_20.html)

**Comment by vdick** [comment]
ab nächsten Rollout(#346) verfügbar

**Comment by andreaschu** [comment]
@vdick auf den Seiten A_56 und D3_8 sind die Label noch nicht mittig zentriert.

![grafik](https://user-images.githubusercontent.com/30111489/112310413-d9b56100-8ca4-11eb-870e-9eb9793b4cc4.png)

**Comment by karbecke** [comment]
Umsetzung geprüft; es sind noch folgende Punkte offen:

- [ ] **D3_8** --> "ich bezahle selbst" muss noch mittig zentriert werden
- [ ] **A_56** --> Bitte Spaltenüberschriften zentrieren
- [ ] **B1_4a** --> Bitte Spaltenüberschrift "Erwerbseinkommen" bei "Erwerbs-einkommen" umbrechen (analog zu B1_6)

**Comment by woisch** [comment]
habe mir die 3 Seiten nochmal angeschaut
Die Überschriften A_56 und D3_8 sind bei mir immer noch nicht (ganz) zentriert. Lässt sich das noch optimieren?

![grafik](https://user-images.githubusercontent.com/53002476/114565036-31763500-9c71-11eb-8bcf-cfd7fc515987.png)

![grafik](https://user-images.githubusercontent.com/53002476/114565107-40f57e00-9c71-11eb-87b8-97a046d05ba2.png)

**Comment by vdick** [comment]
@woisch die werden noch optimiert,  ich versuche es morgen zu lösen

**Comment by karbecke** [comment]
@vdick @SilinaSchirmer : Habt ihr für die Überschriften schon eine Lösung erarbeiten können?

**Comment by woisch** [comment]
@vdick: Momentan sind die Spaltenüberschriften gar nicht mehr zu sehen bei A_56. Könntest du da nochmal drauf schauen?

**Comment by vdick** [comment]
@woisch das Problem ist bekannt und wir arbeiten daran

**Comment by vdick** [comment]
ab nächsten Rollout (#504)  verfügbar

**Comment by woisch** [comment]
A_56 ist jetzt wieder in Ordnung!

Bei D3_8 sind die Überschriften auch wieder da, aber noch nicht ganz zentriert, dadurch wirkt es etwas so, als würden beide Überschriften überlappen: 
![grafik](https://user-images.githubusercontent.com/53002476/116206555-37731800-a73f-11eb-99d8-6b8fd8777ce5.png)

**Comment by woisch** [comment]
hier können wir fast schließen, offen ist nur noch die Zentrierung der Überschriften in D3_8..

**Comment by vdick** [comment]
ab nächsten Rollout (#519 ) verfügbar

**Comment by woisch** [comment]
D3_8 ist jetzt ok mit den Überschriften! Danke! closed.
