### ISSUE TITLE
F1_15: Label abgeschnitten bei kleineren Bildschirmen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#353]
![grafik](https://user-images.githubusercontent.com/30111489/111349791-baee1380-8681-11eb-88c1-bca04a6f5a40.png)

**Comment by vdick** [comment]
ab nächsten Rollout(#346 ) verfügbar

**Comment by andreaschu** [comment]
sieht erst mal gut aus. Ich schließe hier.
