### ISSUE TITLE
F1_2: ao-Label für zweite unit einblenden

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#354]
- [x] [F1_2 ](http://vmtest.dzhw.local:8080/sid-2021/F1_2.html) : Spaltenüberschriften bitte auch bei "gegen einen Auslandsaufenthalt" wieder einblenden

**Comment by vdick** [comment]
@andreaschu, @SilinaSchirmer  wenn ich es richtig verstanden habe, sind die schon implementiert. Bitte gegeprüfen und den Status des Issues ändern :)

**Comment by SilinaSchirmer** [comment]
Die Änderungen waren tatsächlich schon umgesetzt.

**Comment by andreaschu** [comment]
sieht aus meiner Sicht gut aus. Ich schließe hier mal.
