### ISSUE TITLE
2021 - Aktualisierung Modul A

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#356]
Liebes ZOFAR-Team,

das Modul A wurde aktualisiert:

- [x] Bitte arbeitet die Änderungen von 79b7fe0 in die QML ein.

Ebenso sind uns noch einige notwendige Anpassungen der QML (auf Basis der bereitgestellten presenter-Version) aufgefallen, die im GitHub-Code schon richtig stehen, aber noch in die QML eingearbeitet werden müssten:

- [x] A_3: Bitte "is" in QML an Github Code anpassen. Das Wort "hier" bitte aus QML entfernen.
- [x] A_8b: Bitte "q" in QML an Github Code anpassen. Das Wort "Sie" bitte in QML aufnehmen und   Leerzeichen vor "…" einfügen. 
- [x] A_12b: Bitte die Dropdown-Menüs für Geschlecht in QML wie im GitHub Code hinterlegt ergänzen.
~- [ ] A_14: Bitte die fo in QML wie im GitHub Code hinterlegt layouten.~
~- [x] A_25: fo bitte umsetzen~
- [x] A_27: Bitte "ao5" in QML an Github Code anpassen
- [x] A_27a: Neu eingefügt, bitte in QML übernehmen. Transitions noch nicht eingefügt
- [x] A_28: Bitte "fo" beachten und die Durchschnittsnote als offene Angabe über die Einfachauswahl "ich habe bisher keine Noten erhalten".
~- [ ] A_32: Bitte "mv" in QML an Github Code anpassen, dabei fo1 beachten -> mv absetzen~
- [x] A_33: Bitte "q" in QML an Github Code anpassen
- [x] A_36: Bitte "ao1" "Geburtsland Vater" /   "Geburtsland Mutter"  in QML an Github Code anpassen
- [x] A_37a: Seite ist in Modul N verschoben
- [x] A_38b: ao1-ao3 ohne Zahl in Klammern davor
~- [x] A_38c: Bitte "ao6" in QML an Github Code anpassen, dabei fo beachten -> ao6 etwas abrücken~
- [x] A_39: Bitte offene Angabe für ao9 einfügen; 
- [x] A_39: ao9 nicht als EK programmieren --> siehe GitHub Code;
- [x] A_39: ao10: Gendersternchen korrekt umsetzen; 
~- [ ] A_39: fo1 noch umsetzen (kleinere Schriftgröße für Beispiele)~
- [x] A_40: Bitte QML an Github Code anpassen
- [x] A_48: Bitte "ao" in QML an Github Code anpassen _> Präfix ergänzen
- [x] A_53: Bitte "q1", "ao1"und ""ao3"   QML an Github Code anpassen

Vielen Dank!

**Comment by SilinaSchirmer** [comment]
A_12b: 
`vc4: SHOW q2 AND is AND ka2-ka4 AND it1-it6 IF dsibanz=missing`

Ich vermute ihr mein hier q3? Würde das einfach mal so umsetzen. Sonst würde die q3 nie angezeigt werden.

**Comment by SilinaSchirmer** [comment]
**A_41:**
`ao1: 1: nein [Exklisivkategorie]`

Da es sich um eine SingleChoice Frage handelt erübrigt sich diese Programmierung...oder sollte es eine MultipleChoice sein?

**Comment by SilinaSchirmer** [comment]
**A_45**:
`vc: SHOW q2 if Internationale Studierende`

Hierfür brauche ich noch eine genaue Sichtbarkeitsbedingung

**Comment by woisch** [comment]
> 
> 
> **A_41:**
> `ao1: 1: nein [Exklisivkategorie]`
> 
> Da es sich um eine SingleChoice Frage handelt erübrigt sich diese Programmierung...oder sollte es eine MultipleChoice sein?

Das soll tatsächlich eine Mehrfachnennung sein (also it2 und it3 können gleichzeitig gewählt werden, aber it1 ist exklusiv)

**Comment by woisch** [comment]
> 
> 
> **A_12b**:
> `vc4: SHOW q2 AND is AND ka2-ka4 AND it1-it6 IF dsibanz=missing`
> 
> Ich vermute ihr mein hier q3? Würde das einfach mal so umsetzen. Sonst würde die q3 nie angezeigt werden.

Ja, das war ein Fehler, q3 ist korrekt. Habe es im Code geändert: b31d7e2423f74f657130bb208b0bd7c281e172ed

**Comment by SilinaSchirmer** [comment]
`- [ ] A_25: fo bitte umsetzen`
Im GitHub Code ist hier keine fo angegeben.

**Comment by SilinaSchirmer** [comment]
> @SilinaSchirmer: Das soll tatsächlich eine Mehrfachnennung sein (also it2 und it3 können gleichzeitig gewählt werden, aber it1 ist exklusiv)

Bitte im Code ändern und Commit teilen. Sonst geht das leider komplett unter.

**Comment by mcehrhardt** [comment]
> 
> 
> `- [ ] A_25: fo bitte umsetzen`
> Im GitHub Code ist hier keine fo angegeben.

Liebe @SilinaSchirmer, da sind wir verrutscht, das galt für A_25b und dort ist aktuell alles korrekt. Kann also ignoriert werden.

**Comment by mcehrhardt** [comment]
> 
> 
> > @SilinaSchirmer: Das soll tatsächlich eine Mehrfachnennung sein (also it2 und it3 können gleichzeitig gewählt werden, aber it1 ist exklusiv)
> 
> Bitte im Code ändern und Commit teilen. Sonst geht das leider komplett unter.
> 
> edit: dann müssen auch drei Variblen angegeben werden, da drei Antwortoptionen.

Liebe @SilinaSchirmer,
ist hier commited 345def0 .

LG
Marie

**Comment by SilinaSchirmer** [comment]
Ab nächstem Rollout (#391) verfügbar. 

Die Layout-Anpassung sollten wir in ein separates Issue übernehmen.

**Comment by woisch** [comment]
@SilinaSchirmer hier kann getestet werden, oder? (das testing-label ist nocht nicht vergeben, daher frag ich)

**Comment by woisch** [comment]
geprüft, bitte noch umsetzen: 26e0bf1b4d2610fc97ca5b1ec38efefddf2771a1

außerdem bitte noch ändern:
- [ ] A_1: Vorsatz bitte streichen ("Um die Befragung...")
- [ ] A_12a: Bitte ao2 entsprechend Github COde als Dropdown programmieren
- [ ] A_12b: is bitte unter q programmieren
- [ ] A_13: vc für is funktioniert nicht
- [ ] A_14: bei Item 4 "usw." entfernen
- [ ] A_17: bitte Felder bei offener Angabe so breit machen, dass Infield Text lesbar ist
- [ ] A_18: Anführungszeichen in is: Das erste Anführungszeichen unten 
- [ ] A_23: fehlerhafte Darstellung der Infield Texte
![grafik](https://user-images.githubusercontent.com/53002476/113279559-8a45e500-92e3-11eb-9920-b834dba6db8e.png)
- [ ] A_24: bitte Doppelpunkt am Ende der ka entfernen
- [ ] A_32: mv  "weiß ich nicht" fehlt in der Umsetzung
- [ ] A_40: Frage als Mehrfachnennung umsetzen mit ao3 als Exklusivkategorie f17c09bfce6074ed90b3a48345a49cd7172ab6aa fdf9e34d34db16ed634a1b386935de3890006221
- [ ] A_40: Der untere Teil der Frage entfällt (Abfrage des Jahres als Dropdown), ist in QML schon entfernt -> Bitte anpassen
- [ ] A_48: Doppelpunkt im Präfix ergänzen: Abschlussnote (z. B. 2,5):
- [ ] A_56: vc1 bis vc4 fubktionieren nicht (sind immer sichtbar)

**Comment by andreaschu** [comment]
@woisch bei A_12a sind genau zwei AOs von denen eine eine offene Angabe enthält, die nicht in eine DropDown-Liste gepackt werden kann. Da bliebe nur noch eine Antwortoption, die im DropDown versteckt wäre.

**Comment by andreaschu** [comment]
> - [ ] A_1: Vorsatz bitte streichen ("Um die Befragung...")

@woisch soll hier die gesamte Instruction weg? Das müsste dann noch in der PV angepasst werden.

**Comment by andreaschu** [comment]
> - [ ] A_13: vc für is funktioniert nicht

Also das ist so programmiert, wie es in der PV steht. Aber ich nehme an, dass die eingeblendet werden soll, wenn man Kinder hat, was aber der Wert 2 ist und nicht 1, oder? 
Ich ändere es mal auf `SHOW is if dkinja==1`. Das sollte dann aber ebenfalls in der PV angepasst werden.

**Comment by mcehrhardt** [comment]
@andreaschu 

für A_12a halten wir nochmal Rücksprache im Team

PV von A_1 geändert (e02d350)

bei A_13 hast du vollkommen recht. Das war mein Fehler und ist geändert (3b0f8ca)

LG,
Marie

**Comment by andreaschu** [comment]
> -[ ] A_40: Frage als Mehrfachnennung umsetzen mit ao3 als Exklusivkategorie f17c09b fdf9e34

@woisch und @mcehrhardt hier fehlen dann noch Variablennamen für ao1 und ao2.

**Comment by mcehrhardt** [comment]
@andreaschu dafür schreibe ich gerade ein separates Issue, aber wir können auch gerne direkt telefonieren, wenn du gerade Zeit hast?

**Comment by mcehrhardt** [comment]
Commit für die fehlenden Variablennamen:  894958c

**Comment by andreaschu** [comment]
die abgehakten Anmerkungen wurden geändert und können getestet werden.

**Comment by mcehrhardt** [comment]
abgehakte Änderungen geprüft, folgende Probleme bestehen  noch:

- [ ] A_8 ka bitte entsprechend fo umsetzen
- [ ] A_12b vcs greifen nicht: Momentan wird unabhängig von der Anzahl der Geschwister immer q3 und nur eine offene Angabe angezeigt
- [ ] A_17 fehlerhafter infield-Text
![grafik](https://user-images.githubusercontent.com/57707751/113715839-3d4e7e00-96ea-11eb-9d03-bdf1ef04a87c.png)

- [ ] A_21 fehlerhafter infield-Text
![grafik](https://user-images.githubusercontent.com/57707751/113715979-62db8780-96ea-11eb-9567-1c5033196f98.png)

- [ ] A_40 die Umsetzung ist schon nah dran, an dem was wir brauchen, danke dafür @andreaschu . Bitte noch die ersten beiden Kästchen ausblenden und "Ich habe keine Noten erhalten." als EK umsetzen.

Vielen Dank und liebe Grüße,
Marie

**Comment by SilinaSchirmer** [comment]
> * [ ]  A_12b vcs greifen nicht: Momentan wird unabhängig von der Anzahl der Geschwister immer q3 und nur eine offene Angabe angezeigt

Sollten wir für die A_12a vielleicht noch einen Infield-Text anlegen? Aktuell würde ja immer direkt der Wert 1 eingetragen, wenn man einfach weiter klickt.

**Comment by SilinaSchirmer** [comment]
> * [ ]   A_12b vcs greifen nicht: Momentan wird unabhängig von der Anzahl der Geschwister immer q3 und nur eine offene Angabe angezeigt
> 

Außerdem wird gar nichts eingeblendet wenn die A_12a missing ist. Zumindest wenn ich das gerade richtig überblicke ;)

**Comment by SilinaSchirmer** [comment]
> * [ ]  A_40 die Umsetzung ist schon nah dran, an dem was wir brauchen, danke dafür @andreaschu . Bitte noch die ersten beiden Kästchen ausblenden [...]

@vdick: Ist das möglich?

**Comment by andreaschu** [comment]
@SilinaSchirmer A_40 ist schon im Issue #404 enthalten und ab dem nächsten RollOut testbar.

**Comment by SilinaSchirmer** [comment]
Auch die anderen Änderungen sind umgesetzt und ab dem nächsten Rollout (#400) verfügbar.

**Comment by andreaschu** [comment]
>  Bitte nochmal A_17 prüfen: Hier scheint der Text von q2 nicht zu stimmen (es muss "Urlaubstrimester" heißen)

Ich hab es korrigiert. Ab dem nächsten RollOut ist es verfügbar.

**Comment by andreaschu** [comment]
> Wird hier nichts angegeben (Missing), wird man automatisch auf die 12b geleitet (weil die Vorauswahl "Ja und zwar" als ja gewertet wird). das ließe sich zwar auch per transition anpassen/verhindern, könnte die Frage hier aber ansonsten nicht so programmiert werden, dass wir eine Einfachauswahl (dsib=ja/nein) haben und neben dem "ja" das Dropdown erscheint?

@woisch das war wohl die ursprüngliche Idee, aber das geht so nicht, weswegen wir das in Absprache mit @mcehrhardt so umgesetzt haben. Die transition habe ich entsprechend angepasst (siehe auch Kommentar im Commit 8714c58). Das wurde aber - soweit ich den Überblick habe - noch nicht von ihr abgenommen.

**Comment by woisch** [comment]
@andreaschu okay, dann weiß ich Bescheid. @mcehrhardt ist diese Woche nicht da, deswegen bin ich hier reingegrätscht (und Marie wird den jetzigen Stand dementsprechend noch nicht abgesegnet haben, vermute ich). 

Dann lasse ich das Issue erstmal offen und wir melden uns nochmal, wenn wir uns abgestimmt haben!

**Comment by woisch** [comment]
> 
> 
> > Bitte nochmal A_17 prüfen: Hier scheint der Text von q2 nicht zu stimmen (es muss "Urlaubstrimester" heißen)
> 
> Ich hab es korrigiert. Ab dem nächsten RollOut ist es verfügbar.

Momentan funktionieren die vcs auf A_17 noch nicht ganz  so, wie geplant:
wenn triroga=2 müsste ich die q2 sehen (Befinden Sie sich aktuell in einem Urlaubstrimester?) Momentan steht da immer noch die q1 (Befinden Sie sich aktuell in einem Urlaubssemester?)

**Comment by andreaschu** [comment]
oh ja, Mist. Da kamen wir uns intern in die Quere. Ich habe es noch mal korrigiert und gerade ausgerollt.

Ist das eigentlich stimmig, dass bei bestimmten Kombis zweit Texte angezeigt werden? Ich habe gerade nicht im Überblick, ob das ein realistisches Szenario ist, das ich da gerade simuliert hab.

![grafik](https://user-images.githubusercontent.com/30111489/114880676-8dbc8e80-9e02-11eb-8289-a7cfcb372113.png)

**Comment by woisch** [comment]
Super! jetzt passt die Einblendung!
Deinen Screenshot habe ich vorhin auch produziert, das ist aber mE eine unlogische Konstellation, die mit unseren Preloads zusammenhängt und in freier Wildbahn ausgeschlossen ist später, die aber beide vcs gleichzeitig aktiviert ;-)

**Comment by woisch** [comment]
das Problem mit 12b habe ich in ein Diskussions-Issue ausgelagert (#444) , damit es nicht verloren geht. hierzu melden wir uns nochmal, wie das gelöst werden soll.

Ich schließe dann jetzt hier.
