### ISSUE TITLE
2021 - Aktualisierung Modul_N

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#357]
Liebes ZOFAR-Team,

(fyi: Den Altstand vom Modul_N, welches aus dem GitHub-Code von Modul A genommen wurde, findet ihr hier: 3c525d2)

das **Modul_N** wurde aktualisiert:

- [x] Bitte arbeitet die Änderungen von f8bca4a und 
- [x] ... 5c12c68 in die QML ein.

Ebenso sind uns noch einige notwendige Anpassungen der QML (auf Basis der bereitgestellten presenter-Version) aufgefallen, die im GitHub-Code schon richtig stehen, aber noch in die QML eingearbeitet werden müssten:

- [x] N_6: Singleitem bitte entsprechend QML vertikal umsetzen
 ~- [ ] N_7: bitte fo beachten und missing etwas absetzen.~
 ~- [ ] N_8: bitte fo beachten und missing etwas absetzen.~
- [x] N_9b: Sind in N programmiert und werden über die transitions in B2 ausgespielt.
- [x] N_10a: mit N_10c überschrieben
- [x] N_10c: bitte neu hinzufügen, bzw wurde N10a entsprechend überschrieben

Vielen Dank!

**Comment by SilinaSchirmer** [comment]
**Nur zur Info: Aktuell lässt wird das Modul_N noch nicht mit ausrollen.** 

Wir haben Modul N aus dem Modul A ausgekoppelt und eine neue QML-Datei hierfür erstellt. Da wir derzeit aber noch auf 20 QML-Dateien beschränkt sind wird die Datei "questionare21", in der das Modul N liegt, ignoriert. @dzhwmeisner wird die Einstellungen aber Anfang der Woche ändern, sodass auch Modul N ganz normal mit ausgerollt werden kann. 

Bis dahin braucht ihr euch also nicht wundern, wenn ihr das Modul nicht findet :)

**Comment by SilinaSchirmer** [comment]
```
ao1: (vsbort): Präfix: Ort: [Infield = Ort; 60 Zeichen] (offene Angabe)

ao2: (vsbplz): Präfix: ggf. PLZ: [Infield = Postleitzahl; Number, 5-stellig: 01000 TO 99999] (offene Angabe
```

Es kann leider nur ein Präfix **oder** ein Infield-Text dargestellt werden.

**Comment by SilinaSchirmer** [comment]
`ao3: (wohnland): Präfix: Land: [infield = Ort; 60 Zeichen]`

Die Angabe des Infield-Textes ist hier trotzdem etwas verwirrend. Vielleicht passt ihr das in der Vorlage an.

**Comment by SilinaSchirmer** [comment]
Ab nächstem Rollout (https://github.com/dzhw/SiD/issues/372) verfügbar

**Comment by koopmann1896** [comment]
Liebe Silina, beim Testen ergaben sich folgende offene Punkte, ansonsten sieht das ja schon alles sehr gut aus :) :

- [ ] N_2: ein Item wurde hinzugefügt und der Fragetext angepasst -> bitte in qml umsetzen  3e7322386fdb82e0f6691bd7392d747e5db5b850
- [ ] N_7 und N_8: missing bitte absetzen, bzw. die Linie nicht durchführen wenn möglich
- [ ] N_9: bitte auf Githubstand bringen: AO "weiß nicht" entfernen
- [ ] N_10: ao13 Exklusivkategorie bitte wenn möglich etwas absetzen
- [ ] CO_4: QML bitte auf Githubstand bringen: es wird ein falscher Fragetext angezeigt, bitte den Text zu Interaktionsmöglichkeiten in Online-Lehrveranstaltungen aus q im Github übernehmen
- [ ] D3_1: Bitte Github in QML umsetzen und Präfix durch Infieldtexte ersetzen.  9760a49f8d1d122dbd4f5d78dc7da2aa9f6c1ac7
- [ ] CO_11:  q  überarbeitet, bitte in qml übernehmen 8cce8730048a117e31e8f89e358e5fdd785036ec
- [ ] CO_19: QML   bitte auf Githubstand bringen: es wird ein falscher Fragetext angezeigt,   bitte den Text zum Studienbezogenen Praktikum übernehmen

**Comment by andreaschu** [comment]
die Änderungen wurden vorgenommen und sind ab dem nächsten RollOut verfügbar.
@SilinaSchirmer übrig bleiben folgende Punkte: 
Kannst Du bitte mal schauen, warum die Missings hier nicht abgesetzt werden?
- [ ] N_7 und N_8: missing bitte absetzen, bzw. die Linie nicht durchführen wenn möglich
- [ ] N_10: ao13 Exklusivkategorie bitte wenn möglich etwas absetzen

Prefix als Infield-Text einblenden:
- [ ] D3_1: Bitte Github in QML umsetzen und Präfix durch Infieldtexte ersetzen.  9760a49f8d1d122dbd4f5d78dc7da2aa9f6c1ac7

**Comment by SilinaSchirmer** [comment]
> [ ] N_7 und N_8: missing bitte absetzen, bzw. die Linie nicht durchführen wenn möglich
> [ ] N_10: ao13 Exklusivkategorie bitte wenn möglich etwas absetzen

@vdick: Könntest du das bitte machen?

**Comment by SilinaSchirmer** [comment]
> [x] D3_1: Bitte Github in QML umsetzen und Präfix durch Infieldtexte ersetzen. [9760a49](https://github.com/dzhw/SiD/commit/9760a49f8d1d122dbd4f5d78dc7da2aa9f6c1ac7)

Ab nächstem Rollout (#379) verfügbar.

**Comment by mcehrhardt** [comment]
offene Punkte in Issue #292 überführt
Isssue geschlossen.
