### ISSUE TITLE
Itemrotation anpassen

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#358]
**Rotation der Items bei folgenden Fragen bitte deaktivieren, und ggf. die geänderte Item Reihenfolge übernehmen:**
Modul D1 2872c24dc9481dab5344d3d97b97565cf80ef8aa
- [x] D1_22 
- [x] D1_23, hier wurde die Item Reihenfolge geändert -> bitte übernehmen 3178a7da29274f096d24cf962a635d1585516824
- [x] D1_24  

Modul D3 e93f9df3c7baea8e7b5094852ea655df0630ab2b
- [x] D3_11, hier wurde die Item Reihenfolge geändert -> bitte übernehmen 
- [x] D3_21
- [x] D1_28 

Modul F1 abc96d68efef056fbaf08905f81e411c0fa690dc
- [x] F1_9, hier wurde die Item Reihenfolge geändert -> bitte übernehmen

- [x] KSM-ma07: Item 13 ("anderes und zwar") immer als letztes angezeigen, die restlichen Items jedoch in randomisierter Reihenfolge
- [x] KSM-phd02: Bitte QML an GitHub-Code anpassen -->letztes Item (Item 18 "sonstige und zwar") soll immer am Schluss stehen, die restlichen Items jedoch in randomisierter Reihenfolge angezeigt werden

**Bei folgender Frage blockweise (immer 6 Items) Rotation einfügen bitte, siehe hi**  :
- [x] D1_29, Reihenfolge der Items wurde geändert a312deaade9c21b06ce220715fea8195e804e5ca
- [x] Items bitte blockweise rotieren in folgen drei Blöcken: (it1-it6) (it7-it12) (it13-it18).

**Comment by meyerja** [comment]
@andreaschu: Kann Reihenfolge der Items und Rotation von D1_29 für KSM-anf03 (Modul E2 Studienanfang) ebenfalls entsprechend direkt mit übernommen werden? Fragen sind ja bis auf den Zusatz "b" bei den Variablennamen identisch.

**Comment by andreaschu** [comment]
> Bei folgender Frage blockweise (immer 6 Items) Rotation einfügen bitte, siehe hi :

@meyerja was ist mit "blockweise rotieren" genau gemeint? Ich fürchte das geht nicht so einfach.

**Comment by koopmann1896** [comment]
> > Bei folgender Frage blockweise (immer 6 Items) Rotation einfügen bitte, siehe hi :
> 
> @meyerja was ist mit "blockweise rotieren" genau gemeint? Ich fürchte das geht nicht so einfach.

Das steht auch nochmal in der hi. Die Items 1bis, 7-12 und 13 bis 18 sollen jeweils als block rotiert werden, also entweder 1-6 als erstes oder 7 bis 13 etc.

**Comment by andreaschu** [comment]
@koopmann1896 ja, vielen Dank. Also sollen die Blöcke rotieren, nicht die Items innerhalb der Blöcke, richtig?
Wir müssen erst mal klären, ob das geht.

**Comment by koopmann1896** [comment]
> @koopmann1896 ja, vielen Dank. Also sollen die Blöcke rotieren, nicht die Items innerhalb der Blöcke, richtig?
> Wir müssen erst mal klären, ob das geht.

exakt, jeweils die 6 Items sollen in ihrer Reihenfolge so als Block bestehen bleiben und diese drei Blöcke dann in ihrer Reihenfolge rotieren.  So wurde es zumindest an uns herangetragen :)

**Comment by andreaschu** [comment]
@vdick laut chris, geht das blockweise Rotieren auch ohne die Section-Lösung. Das würde das Problem von #371 beheben.

> > letztes Item (Item 18 "sonstige und zwar") soll immer am Schluss stehen, die restlichen Items jedoch in randomisierter Reihenfolge angezeigt werden
> 
> @dzhwmeisner geht das überhaupt?
@andreaschu 
Das geht.
Alle Items ausser der letzen werden in einer Random-Sort Section zusammengefasst.

**Comment by andreaschu** [comment]
> Also sollen die Blöcke rotieren, nicht die Items innerhalb der Blöcke, richtig?
> Wir müssen erst mal klären, ob das geht.
> /
> Das steht auch nochmal in der hi. Die Items 1 bis 6, 7 bis 12 und 13 bis 18 sollen jeweils als block rotiert werden, also entweder 1-6 als erstes oder 7 bis 12 etc.

@dzhwmeisner und @vdick noch mal, dass wir über dasselbe sprechen. Es sollen die Blöcke rotiert werden, nicht die Items darin. Geht das überhaupt? Ich kann mir nicht vorstellen wie das mit der Unit-Lösung klappen soll.

**Comment by dzhwmeisner** [comment]
Ich schau es mir an

**Comment by dzhwmeisner** [comment]
> D1_29 Items bitte blockweise rotieren in folgen drei Blöcken: (it1-it6) (it7-it12) (it13-it18).

Im nächsten Rollout verfügbar

Die Darstellungsprobleme der Fragen KSM-phd02,KSM-ma07,D1_29 sind gelöst

**Comment by SilinaSchirmer** [comment]
> * [ ]  D1_24
> * [ ]  F1_9, hier wurde die Item Reihenfolge geändert -> bitte übernehmen

Ab nächstem Rollout (#386) verfügbar.

**Comment by koopmann1896** [comment]
@meyerja Die blockweise Rotation funktioniert jetzt für D1_29, bei KSM-anf03 scheint die nicht umgesetzt, gab es da Änderungen oder ist das noch offen? Ich würde sonst dieses Issue schließen.

**Comment by meyerja** [comment]
@koopmann1896: Dieser Punkt muss für KSM-anf03 noch übernommen werden.

**Comment by SilinaSchirmer** [comment]
@meyerja: Mir ist gerade durch Zufall aufgefallen, dass die Variable `it6: (Intconv2): sich mit rechtlichen Fragen beschäftigen` ,anders als die anderen, groß geschrieben wird. Habe die Variable mal mit einem kleinen i übernommen.

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab nächstem Rollout (#394) verfügbar.

**Comment by meyerja** [comment]
@SilinaSchirmer: Danke :)

**Comment by mcehrhardt** [comment]
@meyerja, schließt du das Issue bitte, wenn du die Umsetzung eurer Seiten prüfen konntest? :)
