### ISSUE TITLE
Variable doppelt (KSM-anf04 / D1_8)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#359]
Hallo, die Variable _stfwando_ wird doppelt verwendet. Einmal im Modul E2 auf Seite KSM-anf04 und einmal im Modul D1 (Bildungsbiographie_individuelle Merkmale) auf der Seite D1_8.
Das ist wohl ein Schreibfehler in der PV. Wir würden im Modul E2 den Namen **stfwandob** verwenden.

<img width="527" alt="image (9)" src="https://user-images.githubusercontent.com/30111489/111608857-f7cd1e00-87d9-11eb-900b-4b0d1cd329ed.png">

**Comment by meyerja** [comment]
@andreaschu: Dann habe ich bei der einen Variable vergessen, den Zusatz "b" anzuhängen. Aber wenn im Modul E2 der Name stfwandob verwendet wird, passt das dann. Vielen Dank :)

**Comment by karbecke** [comment]
@meyerja : Bitte auch im GitHub-Code den Variablennamen noch anpassen ;-) Danke

**Comment by mcehrhardt** [comment]
Ist im Code angepasst von Jasmin angepasst worden.
Schließe das Issue nun für euch.
