### ISSUE TITLE
Modul C3: Migration (first draft)

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#36]
Modul [C3](https://github.com/dzhw/SiD/blob/master/Modul-C3_Migration.md) wurde programmiert. Bitte prüfen.

**Comment by karbecke** [comment]
Hey, was ist das Modulkürzel in der Online-URL? Ich kann es aktuell nicht im Browser direkt ansteuern

**Comment by andreaschu** [comment]
Hallo Karsten,
die Logik ist **Modulkürzel_Seitennummer**, wie z.B.:
https://presentation.dzhw.eu/sid/C3_1.html

Das gilt für die Module, wo die Kürzel in der PV standen. Bei Studiensituation z.B. wussten wir noch nicht, wie die Seitenbezeichnung sein soll. Aber hier klappt es bei mir (siehe Link).

**Comment by karbecke** [comment]
thx
