### ISSUE TITLE
100%-Zeile in openMatrix (nicht ausfüllbar)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#360]
Für die Seiten [B1_4a](http://vmtest.dzhw.local:8080/sid-2021/B1_4a.html) und [B1_6](http://vmtest.dzhw.local:8080/sid-2021/B1_6.html) soll eine Zeile hinzugefügt werden mit dem Eintrag 100%, die zudem nicht ausgefüllt werden soll.
edit: das gilt sicher auch für [D3_8](http://vmtest.dzhw.local:8080/sid-2021/D3_8.html). Oder was soll hier passieren?

@woisch das geht grundsätzlich. Wir müssten dafür noch Variablen hinzufügen und es dann via JavaScript unausfüllbar machen. 
Bitte beachtet, dass die Matrix für mobile Geräte ab width<768 in das Carousel umbricht. Das Carousel bricht nach Items (also nach Zeilen) um, das heißt es würde hier eine Carousel-Seite mit mehreren nichtausfüllbaren Feldern erscheinen in denen 100% steht.

**Comment by woisch** [comment]
@karbecke @koopmann1896 @mcehrhardt 
Wie gehen wir damit um?

**Comment by karbecke** [comment]
wir benötigen dann eine eigene Seite für das responsive Design, in der das funktioniert. Ist das umsetzbar?

**Comment by woisch** [comment]
@andreaschu  wäre der Vorschlag von Karsten umsetzbar?

**Comment by andreaschu** [comment]
> @andreaschu wäre der Vorschlag von Karsten umsetzbar?

Ja, wenn man einzelne offene Fragen untereinander macht. Müssten wir noch mal überlegen, wie genau. Das würde dann in etwa so aussehen:

![grafik](https://user-images.githubusercontent.com/30111489/111664285-e99af400-8811-11eb-90a9-6fdbe3777804.png)

**Comment by vdick** [comment]
B1_4a und B1_6 sind ab nächsten Rollout (#372 ) verfügbar

**Comment by woisch** [comment]
geprüft:

- [ ] B1_6 sieht gut aus. Wäre es hier möglich, in der 100%-Zeile noch ein Label einzufügen (insgesamt) auf höhe der anderen Beschriftungen?
- [ ] B1_6:  Wie oben schon von Karsten geschrieben: Hier bräuchten wir dann am besten eine eigene Seite für die Befragten im responsiven Design, da das Carousel hier nicht optimal ist.

- [ ] B1_4a: Da fehlt die ingesamt-Spalte und die ersten 2 Spalten überlagern sich:
![grafik](https://user-images.githubusercontent.com/53002476/112457057-aaadf680-8d5b-11eb-8865-816d1a658692.png)

**Comment by andreaschu** [comment]
@woisch hast Du den cache geleert? Was hast Du für ein Gerät/ Browser verwendet?
Bei mir sieht es gut aus. 

![grafik](https://user-images.githubusercontent.com/30111489/112462606-8c4af980-8d61-11eb-9f83-3f0de56c108f.png)

**Comment by andreaschu** [comment]
> B1_6 sieht gut aus. Wäre es hier möglich, in der 100%-Zeile noch ein Label einzufügen (insgesamt) auf höhe der anderen Beschriftungen?

Das label ist hinzugefügt (auch für B1_4a) und ab nächstem RollOut verfügbar.

**Comment by woisch** [comment]
> 
> 
> @woisch hast Du den cache geleert? Was hast Du für ein Gerät/ Browser verwendet?
> Bei mir sieht es gut aus.
> 
> ![grafik](https://user-images.githubusercontent.com/30111489/112462606-8c4af980-8d61-11eb-9f83-3f0de56c108f.png)

Habs in Firefox geöffnet und Cache ist auch geleert. Bei mir ist aber noch eine vc aktiv (Kategorie "Kinderbetreuung"). Wenn ich die vc nicht "aktiviere", sieht es bei mir genauso aus wie in deinem Screenshot.

**Comment by vdick** [comment]
ab nächsten Rollout (#379 ) verfügbar

**Comment by woisch** [comment]
B1_4a und B1_6 sehen jetzt gut aus (100%-Spalte)

noch offen (deswegen schließe ich das Issue noch nicht):

- [ ] Umsetzung des responsiven Designs

**Comment by andreaschu** [comment]
@woisch der aktuelle Vorschlag für die responsive Variante ist dieser. Bevor wir das komplett umsetzen, bräuchten wir eine Rückmeldung ob das so gewollt ist. 

<img width="180" alt="B1_4a_r" src="https://user-images.githubusercontent.com/30111489/113332034-f2ff8280-9320-11eb-8efa-34f303fbdc62.png">

**Comment by woisch** [comment]
ja, so haben wir uns das vorgestellt! Das könnt ihr gerne so umsetzen!

**Comment by karbecke** [comment]
geprüft und neues Issue mit offenen Punkten (Pfeile entfernen) angelegt
