### ISSUE TITLE
Modul B1: Layoutpunkte

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#361]
Bitte noch 2 Layoutpunkte umsetzen: 

- [x] B1_4a: Überschrift "Treffen wichtiger   Entscheidungen" zentrieren (wie die anderen)

- [x] B1_6: Überschriften über den Kästchen zentrieren

**Comment by vdick** [comment]
ab nächsten Rollout (#363 ) verfügbar

**Comment by woisch** [comment]
sieht immer noch nicht optimal aus, wurde in eigenes Issue verschoben #366
