### ISSUE TITLE
Modul C2: Layoutpunkte

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#362]
Auf folgenden Seiten überschneiden sich Spaltenüberschriften und Fragetext/Ausfüllanweisung, sodass letztere sowie die Antwortoptionen der Matrix nicht lesbar sind.

- [ ] C2_8
- [ ] C2_9

**Comment by andreaschu** [comment]
Die Seiten und das Problem sind bereits im Issue #341 beschrieben. Bitte erst testen, wenn es ausgerollt ist bevor ein neues Issue aufgemacht wird.
