### ISSUE TITLE
Units ausblenden

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#364]
**Bitte bei folgenden Fragen die Units ausblenden.** 
Sie wurden lediglich eingefügt, damit einzelne Items randomisiert werden können. 

- [x] KSM-ma07
- [x] KSM-phd02

**Comment by vdick** [comment]
ab n#chsten Rollout (#368 ) verfügbar

**Comment by andreaschu** [comment]
Ausgeblendet sind sie. Das Problem mit dem Carousel bleibt.

**Comment by andreaschu** [comment]
auch das Issue schließe ich, weil das Layout gelöst ist und das Carousel-Problem im Issue #358 abgedeckt ist.
