### ISSUE TITLE
Spaltenbeschriftung anpassen

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#366]
- [x]  B1_4a - "Treffen wichtiger Entscheidungen" sieht hier nach wie vor nicht so hübsch aus
- [x]  B1_6 - "Treffen wichtiger Entscheidungen" sieht hier nach wie vor nicht so hübsch aus

**Comment by SilinaSchirmer** [comment]
Viktor hat euch mal eine Beispiellösung für die Beschriftung der Spalten erstellt. Da wir am CSS nichts viel an der Breite der Texte ändern können, würden wir den Text "Erwerbseinkommen" und "Kinderbetreuung" einfach so im QML programmieren, dass er automatisch umbricht. Die Label würde demnach aber auch im Datenexport mit einem Bindestrich dargestellt werden. 

Aussehen würde das ganze dann so. Wäre das für euch in Ordnung? 

![image (1)](https://user-images.githubusercontent.com/48087320/112135347-f894f400-8bcd-11eb-9bc1-cd58736ab676.png)
![image](https://user-images.githubusercontent.com/48087320/112135360-fa5eb780-8bcd-11eb-81f4-833c1db9c736.png)

**Comment by vdick** [comment]
die von @SilinaSchirmer  vorgeschlagene Lösung ist temporär umgesetzt und bereits ausgerollt

**Comment by mcehrhardt** [comment]
Liebe @SilinaSchirmer & lieber @vdick ,

die Lösung wäre ok, könnt ihr bitte die Überschriften noch fett markieren.
Liebe Grüße,
Marie

**Comment by SilinaSchirmer** [comment]
Ab nächstem Rollout (#386) verfügbar,

**Comment by mcehrhardt** [comment]
Umsetzung geprüft, Issue geschlossen.
LG
Marie
