### ISSUE TITLE
Verbindungslinie zwischen RadioButtons entfernen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#369]
- [x] [KSM-ma02](https://presentation.dzhw.eu/sid-2021/KSM-ma02.html)

**Comment by vdick** [comment]
ab nächsten Rollout (#368 ) verfügbar

**Comment by SilinaSchirmer** [comment]
- [ ] VCO_21

**Comment by vdick** [comment]
@SilinaSchirmer VCO_21 gibt es nicht, ich vermute du meinst CO_21?
CO_19, CO_21 ab nächsten Rollout(#378 ) verfügbar

**Comment by mcehrhardt** [comment]
Umsetzungen geprüft, Issue wird geschlossen.
LG
Marie
