### ISSUE TITLE
D3_2: zusätzliche answer option?

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#37]
Was soll die ao2 in der Frage [D3_2](https://github.com/dzhw/SiD/blob/master/Modul-D3_Wohnen_Finanzen_Ba%C3%B6fg_Erwerb.md#d3_2) enthalten?

**Comment by karbecke** [comment]
PV korrigiert f90ec98

**Comment by SilinaKowalewski** [comment]
Wurde umgesetzt.
