### ISSUE TITLE
Bug: KSM-ma07

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#371]
Die Frage KSM-ma07 macht in der responsiven Darstellung an mehreren Stellen Probleme. 

@vdick und ich haben die einzelnen Probleme bereits besprochen. 

![image](https://user-images.githubusercontent.com/48087320/112205628-454fed80-8c15-11eb-89b4-cb0c89c2efe2.png)

**Comment by andreaschu** [comment]
Ich schließe das issue mal, weil es ja im #358 abgebildet ist und nicht nur um das Layout geht.
