### ISSUE TITLE
Layout - Modul C1

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#373]
Liebes ZOFAR-Team,

folgende Layoutpunkte bestehen in C1:

- [x] C1_2 Schriftart und -größe sind anders als bei anderen Fragen
- [x] C1_6 Items sind rechtsbündig statt linksbündig sowie farbliche Hinterlegung der Matrix deutlich länger als Skala/Matrix
- [x] C1_9 Items sind rechtsbündig statt linksbündig, es ist sehr viel Platz zwischen Skalenpunkten und mv nicht abgesetzt
- [x] C1_10 Alle Items sollten linksbündig sein - bisher ist nur it1 linksbündig

C1_7 führe ich hier nicht nochmal auf, da hierfür bereits ein Issue erstellt ist.

Liebe Grüße,
Marie

**Comment by andreaschu** [comment]
Ich füge die Ausrichtung der Item-Label der Liste in dem Sammel-Issue dafür (#342) hinzu.

**Comment by vdick** [comment]
Die farbliche Hinterlegung der MatrixC1_6, wird auch so bleiben, da diese responsive ist und über den gesamten "Content-Bereich" verläuft. Eine Anpassung an die bereits manipulierte Skalenbreite würde zu weiteren Layoutproblemen führen.
Ab nächsten Rollout (#372 )  verfügbar

**Comment by mcehrhardt** [comment]
Liebe @andreaschu & @vdick ,

Umsetzung sind geprüft. Bei C1_2 scheint es nicht geklappt zu haben.

So sieht C1_2 aus:
![grafik](https://user-images.githubusercontent.com/57707751/112483894-bdcfbf00-8d79-11eb-9018-59590ee6a4d9.png)



Und so sieht die Schrift bei C1_1 aus:
![grafik](https://user-images.githubusercontent.com/57707751/112484002-d6d87000-8d79-11eb-9c78-1c4efe79d5d8.png)


Wenn sich C1_2 angleichen ließe, wäre das toll. Ansonsten wäre es gut, wenn wenigstens die Schriftgröße der Frage den aos entsprechen würde.

Vielen Dank!

**Comment by vdick** [comment]
Ich hoffe so sollte es in Ordnung sein, bitte unbedingt  den Cache leeren.
ab nächsten Rollout (#379 ) verfügbar

**Comment by mcehrhardt** [comment]
Umsetzung geprüft, Issue geschlossen.
LG
Marie
