### ISSUE TITLE
Layoutanpassungen - C2_11a

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#374]
- [x] mv/"nicht vorhanden" bitte als erste etwas abgesetzte Spalte platzieren (quasi links von der Spalte "überhaupt nicht").
- [x] Bitte in der Zeile der Kommiliton*innen (it1: bsuntkom) und Lehrende (it2: bsuntleh) jeweils das Antwortkästchen für mv/"nicht vorhanden" nicht einblenden.

Aktuell sieht es so aus: 

![image](https://user-images.githubusercontent.com/48087320/112297074-bcc56180-8c95-11eb-99d9-e53791646647.png)

**Comment by koopmann1896** [comment]
Andreaschu schrieb folgendes: "die radio buttons verteilen sich hier über die gesamte Skala automatisch. Wir können nicht einfach einzelne Antwortpunkte für einzelne Items ausblenden, weil dann genau das passiert, was passiert ist. Diesem Wunsch von fo2 können wir also nicht nachkommen."

Wie können wir jetzt mit dieser Frage umgehen? @karbecke @woisch @mcehrhardt

**Comment by woisch** [comment]
Kann man hier (technisch) 2 Fragen draus machen, die ersten beiden Items mit 6 Skalenpunkten und darunter eine neue Frage (ohne q) und den letzten 4 Items, die hat dann nur  5 Skalenpunkte? Dann sind die Radiobuttons aber vermutlich nicht übereinander...

**Comment by koopmann1896** [comment]
> Kann man hier (technisch) 2 Fragen draus machen, die ersten beiden Items mit 6 Skalenpunkten und darunter eine neue Frage (ohne q) und den letzten 4 Items, die hat dann nur 5 Skalenpunkte? Dann sind die Radiobuttons aber vermutlich nicht übereinander...

Dann müsste aber die erste Frage eben die entsprechenden visible Bedingungen haben, da diese beiden Items eben an Einblendbedingungen geknüpft sind...

**Comment by vdick** [comment]
![Screenshot_C2_11a](https://user-images.githubusercontent.com/30229065/112302509-75da6a80-8c9b-11eb-8594-f64f2ca2d618.png)

**Comment by vdick** [comment]
das ist der aktuelle Stand (bei mir lokal), würde es so passen?

**Comment by koopmann1896** [comment]
> das ist der aktuelle Stand (bei mir lokal), würde es so passen?

Das wäre genau das Richtige :)

**Comment by vdick** [comment]
Sehr gut! Die Verbindungslinien sind bei dieser Lösung leider nicht handlebar, daher müssen die vollständig wegbleiben. 
Sofern die Lösung ok ist, wäre die beim nächsten Rollout verfügbar

**Comment by koopmann1896** [comment]
Die Lösung wäre ok, wir würden uns das dann nach dem Rollout noch einmal anschauen und dann das Issue schließen :)

**Comment by vdick** [comment]
ab nächsten Rollout (#372 ) verfügbar

**Comment by koopmann1896** [comment]
Punkte wurden umgesetzt, vielen Dank. Ich schließe das Issue.
