### ISSUE TITLE
Exklusivkategorie absetzen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#375]
- [x] [KSM-fai16](https://presentation.dzhw.eu/sid-2021/KSM-fai16.html) 
- [x] [KSM-fai28](https://presentation.dzhw.eu/sid-2021/KSM-fai28.html)
- [x] [KSM-pol07](https://presentation.dzhw.eu/sid-2021/KSM-pol07.html)

**Comment by vdick** [comment]
@andreaschu KSM-fai25 existiert nicht/noch nicht
der Rest ist ab nächsten Rollout (#372 ) verfügbar

**Comment by andreaschu** [comment]
KSM-fai16 bis KSM-fai25 sind alle auf KSM-fai16. Mein Fehler.

**Comment by andreaschu** [comment]
@vdick im Issue #370 war noch eine abzusetzende Kategorie. Hab ich nicht hier gesammelt. Sorry. (ist aus meiner Sicht noch nicht gemacht.)
- [ ] [C1_7](https://presentation.dzhw.eu/sid-2021/C1_7.html)

**Comment by vdick** [comment]
ab nächsten Rollout (#378 ) verfügbar

**Comment by mcehrhardt** [comment]
Umsetzung geprüft, Issue geschlossen.
LG
Marie
