### ISSUE TITLE
2021 - Allgemeine Layoutpunkte: Akkordeon

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#376]
Liebes ZOFAR-Team,

bitte korrigiert das Layout hinsichtlich der **Ausklappmenü**: Das 1. Ausklappmenü auf der Seite bitte immer ausgeklappt darstellen. Ebenfalls sollen die Ausklappzeilen wie folgt angepasst werden:

![F3_7_neu](https://user-images.githubusercontent.com/46674616/112311563-22214e80-8ca6-11eb-97eb-1cea5128e133.PNG)

### Bitte folgende Seiten anpassen:

- [x] D1_2
- [x] D1_15
- [x] D1_16
- [ ] D3_19 --> bitte als Ausklappmenü umsetzen
- [x] F3_7
- [x] F3_8 --> Ausklappmenü vorhanden, jedoch 2./3. Menü zu breit dargestellt --> bitte wie 1. Menü umsetzen
- [x] F3_10 Ausklappmenü vorhanden, jedoch 2./3. Menü zu breit dargestellt --> bitte wie 1. Menü umsetzen

edit: Screenshot für 'zu breit dargestellt'.
![grafik](https://user-images.githubusercontent.com/30111489/112315061-0455e880-8caa-11eb-8486-8f064d8aa19f.png)

**Vielen Dank!**

**Comment by andreaschu** [comment]
bis auf D3_19 (siehe neues Issue) alles umgesetzt. Kann ab nächstem Roll-Out getestet werden.

**Comment by andreaschu** [comment]
@mcehrhardt wir klären, ob das erste Menü immer schon ausgeklappt sein kann. 
Allerdings kann das dazu führen, dass die anderen Menüs insb. für mobile Nutzer dann evtl. untergehen, da sie nicht mehr sofort zu sehen sind (siehe Screenshot). 
Das `(bitte ausklappen)` ist nun eingefügt. Da es sich um Text handelt, ist der auch da, wenn es ausgeklappt ist.

<img width="208" alt="Screenshot_D1_15_akkordeon" src="https://user-images.githubusercontent.com/30111489/112461891-b6e88280-8d60-11eb-8022-600de6e1afbf.png">

**Comment by mcehrhardt** [comment]
Liebe @andreaschu ,

wenn die anderen Episoden im responsiven Design verschwinden ist, das natürlich ungünstig. Wir haben uns eben mal beratschlagt.
Wir würden in dem Fall die Episoden dann doch lieber eingeklappt lassen. Der Hinweis "(bitte ausklappen)" soll allerdings beibehalten werden und wenn möglich kursiv gesetzt werden.

Entschuldigt das hin und her und vielen Dank im Voraus!

**Comment by andreaschu** [comment]
@mcehrhardt sie 'verschwinden' nicht wirklich. Sie sind nur nicht mehr auf den ersten Blick zu sehen, sondern erst, wenn die Befragten nach unten scrollen (was sie auf jeden Fall tun müssen). Bitte schau es dir mal in der Mobilansicht an wenn das erste Menü aufgeklappt ist und entscheide dann. Es wäre gut, wenn das dann ein eigenes Issue werden würde.

Das Italic von (bitte ausklappen) haben wir umgesetzt. Es ist ab dem nächsten RollOut sichtbar.

**Comment by andreaschu** [comment]
@vdick ich weiß nicht, ob Du schon fertig bist, aber den Pfeil finde ich optisch zum Design passend. Er lappt aber noch über dem Text und wenn es aufgeklappt ist gibt es zwei Pfeile.

![grafik](https://user-images.githubusercontent.com/30111489/112622700-ae10b300-8e2b-11eb-85fc-c9abeec478a9.png)

![grafik](https://user-images.githubusercontent.com/30111489/112622305-27f46c80-8e2b-11eb-91bf-502c34dbdec5.png)

**Comment by mcehrhardt** [comment]
> 
> 
> @vdick ich weiß nicht, ob Du schon fertig bist, aber den Pfeil finde ich optisch zum Design passend. Er lappt aber noch über dem Text und wenn es aufgeklappt ist gibt es zwei Pfeile.
> 
> ![grafik](https://user-images.githubusercontent.com/30111489/112622700-ae10b300-8e2b-11eb-85fc-c9abeec478a9.png)
> 
> ![grafik](https://user-images.githubusercontent.com/30111489/112622305-27f46c80-8e2b-11eb-91bf-502c34dbdec5.png)

@vdick bitte Pfeile nicht umsetzen. Siehe Issue #377

**Comment by andreaschu** [comment]
@mcehrhardt ich hatte dein Bild so verstanden und es ist eine zusätzliche optische Unterstützung für die Befragten.

![grafik](https://user-images.githubusercontent.com/30111489/112828306-d4cf2380-908f-11eb-8f36-aceb58c4a55c.png)

**Comment by mcehrhardt** [comment]
Liebe @andreaschu,

das ist grundsätzlich richtig. Zu Beginn war es so angedacht, im Zuge der Problematik mit den nicht-sichtbaren bzw. nicht sofort ersichtlichen anderen Episoden bei ausgeklapptem erstem Akkordeon haben wir uns jedoch für den wörtlichen Hinweis (bitte ausklappen) entschieden. Da zu diesem Zeitpunkt die Pfeile noch nicht umgesetzt waren, hatten wir diese nicht präsent und haben die Info nun nachgereicht.
Entschuldige bitte!
Ich schließe das Issue nun wieder.

LG 
Marie

**Comment by vdick** [comment]
Ab nächsten Rollout(#408 ) verfügbar
