### ISSUE TITLE
D3_19 als Akkordeon

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#377]
pro Erwerbstätigkeit eine Section.
Entsprechend #376 den Fragetexten "1. Erwerbstätigkeit" "(bitte ausklappen)" hinzufügen.

![grafik](https://user-images.githubusercontent.com/30111489/112315837-cefdca80-8caa-11eb-8c0b-5fc553ef8bf8.png)

**Comment by andreaschu** [comment]
@ParmidaZarei könntest Du das machen?

**Comment by ParmidaZarei** [comment]
> 
> 
> @ParmidaZarei könntest Du das machen?

changed and commited

**Comment by mcehrhardt** [comment]
Liebe @andreaschu & lieber @vdick,

- [ ] Bitte den Pfeil entfernen (ebenso bitte bei den Akkordeons auf #376 berücksichtigen).
- [ ] Bitte die Verbindungslinie zwischen aos der ersten Abfrage entfernen
- [ ] Bitte zweite Abfrage zur Fachnnähe vertikal umsetzen

LG
Marie

**Comment by mcehrhardt** [comment]
Liebe @SilinaSchirmer, 

vertikale Umsetzung geprüft. Nur zur Info ich assigne Viktor wieder wegen der offenen Layoutpunkte,

LG
Marie

**Comment by vdick** [comment]
ab nächsten Rollout(#408 ) verfügbar

**Comment by karbecke** [comment]
geprüft und geschlossen
