### ISSUE TITLE
Transition Promotionsvignette geändert

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#380]
Liebes ZOFAR-Team,

ich habe die PV im Modul **E2 Promotion** angepasst und eine Weiterleitung von den Vignetten zur Seite KSM-phd02 ergänzt: 

- [x] 1d7f13c

Passt das so?

Leider gibt es immernoch die Seite KSM-phd03, die es eigentlich nicht mehr geben sollte. Nach der Seite KSM-phd02 sollte man direkt zur Abschlussseite weitergeleitet werden.

**Comment by andreaschu** [comment]
@meyerja offensichtlich war die Seite schon vor der Aktualisierung nicht mehr in der Programmiervorlage. Da wir nur die Änderungen bearbeiten, ist das nicht aufgefallen.
Nur noch mal um sicher zu gehen. Die Seite KSM-phd03 soll ersatzlos gestrichen werden, richtig?

Ansonsten, das passt so.

**Comment by andreaschu** [comment]
Die Anpassunegn wurden geändert und sind ab dem nächsten RollOut verfügbar.

**Comment by meyerja** [comment]
Passt jetzt, vielen Dank :)
