### ISSUE TITLE
Weiterleitung zur Abschlussseite funktioniert nicht

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#381]
Liebes ZOFAR-Team,

bzgl. der Weiterleitung zur Abschlussseite öffne ich mal ein neues Issue. 
Auf folgenden Seiten wird man aktuell auf die Seite A_56 weitergeleitet, jedoch sollte die Weiterleitung eigentlich auf die Seite mit dem Namen "end" erfolgen. Das wurde in der PV über "GOTO Abschlussseite" kenntlich gemacht, was bei anderen Seiten bereits funktioniert (z.B. bei KSM-anf12). Das Problem betrifft die folgenden Seiten: 

- [x] KSM-pol07
- [x] KSM-fai28
- [x] KSM-fai29

Vielen Dank!

**Comment by andreaschu** [comment]
Die Änderungen wurden vorgenommen und sind ab dem nächsten RollOut verfügbar.
