### ISSUE TITLE
Filterung über bereits gesehene Fragen?

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#382]
Liebes ZOFAR-Team,

im der aktuellen Version des Fragebogens tauchen einige Fragen sozusagen doppelt auf. Jedoch ist die Idee, dass Befragte die jeweiligen Fragen nur einmal gestellt bekommen und je nachdem, ob sie die Frage schon mal "weiter oben" im Fragebogen gesehen haben, sollen sie anschließend "weiter unten" über die jeweilige Frage gefiltert werden. Hierfür ist mir jedoch nicht klar, wie ich die PV entsprechend anpassen kann. Es geht um die folgenden Fragen: 

- [ ] KSM-anf02 soll nicht gezeigt werden, wenn B2_8a2 bereits gesehen wurde
- [ ] KSM-anf03 soll nicht gezeigt werden, wenn D1_29 bereits gesehen wurde
- [ ] KSM-anf04 soll nicht gezeigt werden, wenn D1_7 bereits gesehen wurde
- [ ] KSM-anf05 soll nicht gezeigt werden, wenn D1_8 bereits gesehen wurde
- [ ] KSM-ma06 soll nicht gezeigt werden, wenn B2_9b bereits gesehen wurde

Wäre super, wenn ihr mir sagen könntet, wie man über Fragen filtert, je nachdem ob bereits eine andere Frage angezeigt wurde. Vielen Dank :)

**Comment by andreaschu** [comment]
@meyerja das ist eine gute Frage. Das hängt von der jeweiligen Bedingung ab, die dazu führt ob eine Person die Seite sehen soll, oder nicht. 
Generell würde ich sagen, dass das über die Negation der ursprünglichen Bedingung passieren sollte, sofern das geht.

Soweit ich informiert bin, wird die Filterführung generell noch diskutiert und wurde noch gar nicht in der Endfassung programmiert. @karbecke habt Ihr diese Seiten bei der Planung der Transitions im Blick?

**Comment by karbecke** [comment]
> 
> 
> @meyerja das ist eine gute Frage. Das hängt von der jeweiligen Bedingung ab, die dazu führt ob eine Person die Seite sehen soll, oder nicht.
> Generell würde ich sagen, dass das über die Negation der ursprünglichen Bedingung passieren sollte, sofern das geht.
> 
> Soweit ich informiert bin, wird die Filterführung generell noch diskutiert und wurde noch gar nicht in der Endfassung programmiert. @karbecke habt Ihr diese Seiten bei der Planung der Transitions im Blick?

--> An den transitions arbeiten wir aktuell noch

**Comment by lenamzimmer** [comment]
Liebe alle,

wir haben das Thema bereits mit Konstanz besprochen und sind zu einer guten Lösung gekommen. Die Befragten werden, wenn Sie im entsprechenden Mastersplit landen, "unsere" Fragen sehen und über die Fragen im Konstanzer-Modul hinweggefiltert.

**Comment by meyerja** [comment]
Habe das ganze in #409 übernommen. Daher schließe ich dieses Issue mal.
