### ISSUE TITLE
Layout von D1_15 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#383]
Das sieht noch nicht schön aus. @vdick bitte etwas hübscher anordnen alles.

<img width="208" alt="Screenshot_D1_15_akkordeon" src="https://user-images.githubusercontent.com/30111489/112464188-7a6a5600-8d63-11eb-8eb3-d15f44f0b5e7.png">

**Comment by vdick** [comment]
Ab nächsten Rollout(#408 ) verfügbar

**Comment by woisch** [comment]
getestet, kann zu!
