### ISSUE TITLE
Testseite - hilfsvar

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#384]
Eine Seite erstellen für die Definition von Testvariablen.
PRELOADS
- hsid
- standort
- geschlecht
- 

zufällig generierte
- mastersplit
- zusatzsplit
-

**Comment by andreaschu** [comment]
Ich habe eine Seite für die Testvariablen erstellt **_hilfsvar_**. Sie ist nicht Teil des Fragebogenflows, deshalb kann sie nur direkt über den Link angesteuert werden. 
Hier werden die (auf der index-Seite) zufällig generierten Variablen angezeigt, sie können aber auch noch mal verändert werden.
Bei Veränderung der Variablen muss die Seite über \<weiter\> verlassen werden, damit die Werte gespeichert werden. 

(Bildschirmbreite 2 und 3 gibt es noch nicht. Eventuell werden sie für die Spezial-Varianten einzelner Fragen erstellt und verwendet. Deswegen hab ich sie da schon mal eingebaut.)

**Comment by lenamzimmer** [comment]
Liebe Andrea,

die Geschlechter-Variable benötigen wir eigentlich nicht. Stattdessen wären die folgenden Variablen hilfreich:

- A_15 und C2_0 (zur Identifikation beeinträchtigt Studierender)
- A_12 (zur Identifikation Studierender mit Kind)
- A_1 (zur Identifikation internationaler Studierender)
- A_17 (zur Identifikation der Studienanfänger*innen)
- A_25 (zur Identifikation der Bachelor/Master-Studierenden)
- A_42 (zur Identifikation der erwerbstätig Studierenden)
- A_16 (zur Identifikation deutscher Studierender im Ausland)
- Fragen zur Identifikation der NRW-Leute...

Vielen Dank!

**Comment by andreaschu** [comment]
ab dem nächsten RollOut verfügbar.

**Comment by woisch** [comment]
Wir hätten noch ein paar kleine Änderungswünsche für die hilfsvar-Seite:

- [ ] Die Mastersplits 13 und 14 werden nicht mehr benötigt und müssen gelöscht werden (Wir benötigen die Mastersplits 1-12)
- [ ] Statt der variable Hochschulsemester brauchen wir die Fachsemester zur Auswahl (ssemfs)
- [ ] Wir brauchen noch die variable imausl zur Auswahl auf der hilfsvar Seite

**Comment by andreaschu** [comment]
ab dem nächsten RollOut verfügbar.

**Comment by koopmann1896** [comment]
Seite funktioniert, wird geschlossen
