### ISSUE TITLE
Hochschulliste für A_18, A_19, A_20, D1_10, D1_11

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#385]
Liebes ZOFAR-Team,

bitte arbeitet die angehängten Listen für folgende Seiten ein:
**ACHTUNG: Liste final aktualisiert:**
[HS-Listen_fur.A_18.A_19.A_20_D1_10.D1_11_2021_04_15_final.xlsx](https://github.com/dzhw/SiD/files/6343482/HS-Listen_fur.A_18.A_19.A_20_D1_10.D1_11_2021_04_15_final.xlsx)

- [x] A_18
- [x] A_19
- [x] A_20
- [x] D1_10 und
- [x] D1_11

ein.

**Vielen Dank!**

**Comment by SilinaSchirmer** [comment]
@karbecke: Mir ist beim bearbeiten der Liste aufgefallen, das die Standort-IDs nicht eineindeutig sind. Das heißt, dass die Hochschule ohne Standort die gleiche Standort-ID hat wie ein spezieller Standort. Ich befürchte, dass könnte für euch, aber auch für uns problematisch werden. 

Aus meiner Sicht, betrifft das (nur) folgende Fälle: 

370 | Dresden - Technische Universität   Dresden
-- | --
370 | Technische Universität Dresden


760 | Berlin - IB Hochschule Berlin
-- | --
760 | IB-Hochschule Berlin


1250 | Heidelberg -   Ruprecht-Karls-Universität Heidelberg
-- | --
1250 | Ruprecht-Karls-Universität Heidelberg


5270 | Berlin - Mediadesign -   Hochschule für Design und Informatik Berlin
-- | --
5270 | Mediadesign - Hochschule für Design und Informatik Berlin



5690 | Dortmund - International School   of Management Dortmund
-- | --
5690 | International School of Management Dortmund


5720 | Bad Honnef-Bonn - Internationale   Hochschule Bad Honnef-Bonn
-- | --
5720 | Internationale Hochschule Bad Honnef-Bonn


5731 | Bielefeld - Fachhochschule   Bielefeld
-- | --
5731 | Fachhochschule Bielefeld


5800 | Iserlohn - Hochschule für   angewandte Wissenschaften Europa Iserlohn
-- | --
5800 | Hochschule für angewandte Wissenschaften Europa Iserlohn



5820 | Bielefeld - Fachhochschule des   Mittelstandes Bielefeld
-- | --
5820 | Fachhochschule des Mittelstandes Bielefeld



5990 | Köln - Rheinische Fachhochschule   Köln
-- | --
5990 | Rheinische Fachhochschule Köln


6710 | Aalen - Hochschule Aalen -   Technik und Wirtschaft
-- | --
6710 | Hochschule Aalen - Technik und Wirtschaft


7190 | Ludwigsburg - Evangelische   Hochschule Ludwigsburg
-- | --
7190 | Evangelische Hochschule Ludwigsburg


7300 | Rosenheim - Technische   Hochschule Rosenheim
-- | --
7300 | Technische Hochschule Rosenheim

**Comment by SilinaSchirmer** [comment]
@karbecke: Auch bei den neuen Listen besteht das beschriebene Problem. Sind die gleichen IDs so gewollt?

**Comment by karbecke** [comment]
Liebe @SilinaSchirmer , 
wir benötigen 2 Variablen:
1 Variable enthält die Hochschule
1 Variable enthält den Standort der Hochschule

--> Damit sollte es dann eigentlich keine Probleme geben, oder?
Kann dies so programmiert werden?

**Comment by SilinaSchirmer** [comment]
Diese Standorte enthalten in der Excel-Liste keine Hochschul-ID und würden somit nie angezeigt. 

Hamburg   - Hochschule für angewandte Wissenschaften Europa Iserlohn |  
-- | --
Berlin - Hochschule für   angewandte Wissenschaften Europa Iserlohn |  
Iserlohn - Hochschule für   angewandte Wissenschaften Europa Iserlohn |  
Potsdam - University of Europe   Potsdam |

**Comment by karbecke** [comment]
> 
> 
> Diese Standorte enthalten in der Excel-Liste keine Hochschul-ID und würden somit nie angezeigt.
> Hamburg - Hochschule für angewandte Wissenschaften Europa Iserlohn 	 
> Berlin - Hochschule für angewandte Wissenschaften Europa Iserlohn 	 
> Iserlohn - Hochschule für angewandte Wissenschaften Europa Iserlohn 	 
> Potsdam - University of Europe Potsdam

@SilinaSchirmer: Diese Hochschulen gehören zur HS-ID: 11000  (University of Europe Potsdam)

**Comment by mcehrhardt** [comment]
Liebe @SilinaSchirmer,

die Einblendung des Hochschulnamens im Fragetext funktioniert derzeit noch nicht. Könntest du da mal draufschauen?

Vielen Dank und liebe Grüße,
Marie

**Comment by andreaschu** [comment]
@mcehrhardt das liegt daran, dass der Preload eine Zahl ist und der Name bisher als Preload noch gar nicht existiert. Vielleicht wäre es sinnvoll, wenn Ihr uns eine LIste mit allen benötigten Preload-Variablen gebt.

**Comment by andreaschu** [comment]
ich habe es hinzugefügt. Ab nächstem RollOut ist es testbar.

**Comment by karbecke** [comment]
@andreaschu @SilinaSchirmer : Die Preloads sind ja die hs_id und der Hochschulname dieser hs_id zugeordnet. Dies könnt ihr der Excel-Datei (s.o.) entnehmen, oder wird noch etwas anderes benötigt?

**Comment by SilinaSchirmer** [comment]
**Mal ein kleines Update:** 

Wir sind an dem Issue bzw. den Hochschullisten dran ;) 
Allerdings haben wir doch zu große Bedenken, die Auswahl der Hochschule und der Standort auf einer Seite mit Sichtbarkeitsbedinungen zu steuern. Ich würde vorschlagen, dass wir dafür zwei Seiten anlegen. Ansonsten könnten wir uns Probleme in Bezug auf die Fragebogensteuerung einhandeln und unplausible Werte provozieren. Falls das jemand genau wissen will, können wir dazu auch gerne noch einmal telefonieren. 

Zudem sind @andreaschu und ich uns noch unsicher, wie wir die Fragen programmieren können, damit möglichst wenig performance-Probleme auftreten können. Durch die vielen Sichtbarkeits- und Weiterleitungsbedingungen könnte das Laden der Seiten im Zweifel recht lange dauern.

**Comment by SilinaSchirmer** [comment]
@karbecke: Für die Sichtbarkeit der Hochschulen auf A_20 sind leider keine Bedingungen für ein Missing auf A_19 hinterlegt. Damit ich die Liste fertigstellen kann sollten wir darüber nochmal sprechen.

**Comment by SilinaSchirmer** [comment]
@karbecke: Diese beiden Hochschulen wurden in der Liste keiner Hochschule zugewiesen. Ich gehe mal davon aus, dass sie zur Evangelische Hochschule Dresden gehören. Der fehlende Code hat allerdings einen großen Fehler in unserer Liste produziert weshalb sie aktuell erstmal noch nicht zu testen ist. 

Ich werde die Daten einfügen und hoffe, dass es dann bald ausgerollt ist und funktioniert.






5111 | Dresden - Evangelische   Hochschule Dresden
-- | --
5112 | Moritzburg - Evangelische Hochschule Dresden

**Comment by karbecke** [comment]
@SilinaSchirmer : Liste final und mit Tokenliste abgeglichen. Bitte die oben neu hinterlegte Liste nun final einpflegen für die genannten Seiten., Vielen Dank!

**Comment by SilinaSchirmer** [comment]
@karbecker: Es fehlen leider noch Fragetexte für die neuen Seiten, also A_20b und D1_11b

**Comment by SilinaSchirmer** [comment]
Alle Hochschullisten wurden eingefügt und können getestet werden. 

Für die A_18 hat @andreaschu eine Alternative Seite A_18_test erstellt. Um diese zu testen muss wie folgt vorgegangen werden: 
Ansteuern der Seite "hilfsvar" > Verlassen der Seite über den Button "weiter" > Ansteuern der Index-Seite > Verlassen der Index-Seite über den Button "weiter" > Ansteuern der Seite A_18_test

**Comment by karbecke** [comment]
@SilinaSchirmer Bitte folgende Fragetexte verwenden:

- [ ] A_20b: Bitte geben Sie hier Ihren Hochschulstandort an.
- [ ] D1_11b: Bitte geben Sie hier Ihren Hochschulstandort an.

**Comment by karbecke** [comment]
@SilinaSchirmer: Soll die Seite "A_18" noch durch die "A_18_test" ersetzt werden?

**Comment by mcehrhardt** [comment]
@SilinaSchirmer Liste ist nun mit SQL-Datei abgeglichen. Keine Änderungen notwendig. Konntest du mit Christian nochmal gegenchecken, dass die Änderungen am Ende der SQL so durchlaufen wie gedacht?

**Comment by andreaschu** [comment]
@mcehrhardt was meinst Du mit  _"dass die Änderungen am Ende der SQL so durchlaufen wie gedacht?"_?

**Comment by andreaschu** [comment]
> @SilinaSchirmer: Soll die Seite "A_18" noch durch die "A_18_test" ersetzt werden?

@karbecke das müsstest Du entscheiden. Jetzt gibt es beide Versionen. Eine davon wird gelöscht.

**Comment by andreaschu** [comment]
A_18_test wurde zu A_18 geändert. Ist ab dem nächsten RollOut verfügbar.

**Comment by koopmann1896** [comment]
> @SilinaSchirmer Bitte folgende Fragetexte verwenden:
> 
> * [x]  A_20b: Bitte geben Sie hier Ihren Hochschulstandort an.
> * [x]  D1_11b: Bitte geben Sie hier Ihren Hochschulstandort an.
> * hat @koopmann1896 jetzt eingepflegt

verfügbar mit dem nächsten rollout
