### ISSUE TITLE
Reihenfolge für Vignettenmodule

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#387]
@meyerja und @annamarkn ich habe mal eine Frage zu den Mastervignetten. Die waren in der letzten Version sowohl im Deck randomisiert als auch in der Reihenfolge in der die Vignetten im Deck gesehen werden. Soll das wieder so sein?

**Comment by meyerja** [comment]
@andreaschu 

- Die decks sollen den Befragten zufällig zugespielt werden, die Zuspielung sollte bereits über die token erfolgen (und nicht erst bspw. beim Anklicken auf den Befragungslink)
- Die Reihenfolge der Vignetten (vignr) soll innerhalb der decks variieren

**Comment by andreaschu** [comment]
@meyerja vielen Dank für die Antwort.
Ich hatte danach noch mit Anna telefoniert und gesagt, dass wir das lieber - wie bisher - über die on-time generierten Zufallsvariablen machen. Das sind im Moment 
h_deck für die Zuordnung in den Mastervignetten und h_promo_deck für die Promotionsvignetten.

Welchen Wert Eurer verwendeter Testtoken hat könnt ihr auf der Seite für die Hilfsvariablen sehen und sie manipulieren. Zur Seite mit den Hilfsvariablen geht es hier: https://presentation.dzhw.eu/sid-2021/hilfsvar.html

**Comment by annamarkn** [comment]
@andreaschu  Die Zuspielung per Zufallsvariable ist dann für unsere Projektleitung in Ordnung. 
Nachfrage: Erfolgt die Zuspielung bereits beim Befragungsstart oder erst wenn man ins Promotions- oder Mastermodul gelangt? Wir würden auf jeden Fall bereits beim Befragungsstart präferieren. Danke!

**Comment by annamarkn** [comment]
@andreaschu 
Nach interner Absprache, haben sich ein paar Änderungen ergeben, die ich hier festhalten möchte: 

- Die decks sollen den Befragten **beim Befragungsstart** zufällig zugewiesen werden (und nicht erst beim Gelangen in das Vignettenmodul)
- Die Reihenfolge der Vignetten (vignr) soll innerhalb der decks **NICHT variieren**

Könntest Du das Andrea bitte anpassen? Danke! 
Die Excel Dateien schicke ich Dir hoffentlich bald und dann könnten wir final noch vor Befragungsstart einen Ausschnitt aus den Daten mit den Vignetten überprüfen.

**Comment by andreaschu** [comment]
Die Reihenfolge in den Mastervignetten habe ich korrigiert. Ab dem nächsten RollOut (#391) sind die Vignetten innerhalb eines Master-Decks nicht mehr randomisiert und beginnen mit V[deck]_1.

**Comment by andreaschu** [comment]
@annamarkn aus meiner Sicht könnte das Issue zu. Ich schließe mal.
