### ISSUE TITLE
Infield-Texte D3_6 & D3_8

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#388]
Liebe @andreaschu,

bitte in 

- [x] D3_6 und D3_8 die infield-Texte gemäß Githubvorlage umsetzen und dafür Postfix "€ pro Monat" entfernen.

LG
Marie

**Comment by SilinaSchirmer** [comment]
Ab nächstem Rollout (#386) verfügbar.

**Comment by karbecke** [comment]
Bitte noch die Infield-Texte bei 

- [ ] D3_6 Gesamteinnahmen
- [ ] D3_8 Gesamtausgaben
anpassen.

Vielen Dank!

**Comment by karbecke** [comment]
- [ ] @SilinaSchirmer @vdick : Habt ihr schon eine Lösung für die Gesamteinnahmen und -ausgaben Infield-Texte gefunden?

**Comment by SilinaSchirmer** [comment]
@karbecke: Für mich sieht es jetzt gut aus :) Habe von Viktor aber auch keine Info ob er daran gearbeitet hat. Du kannst dir die Fragen ja einfach mal anschauen.

**Comment by karbecke** [comment]
ja, die Infield-Texte passen nun. 

Die Infieldtexte der Seite "D3_8_r" müssen noch angepasst werden
![D3_8r_v2](https://user-images.githubusercontent.com/46674616/115837621-134ec880-a419-11eb-8d4d-83c42d0e70a7.PNG)

**Comment by woisch** [comment]
@karbecke: Ist hier noch was offen?
