### ISSUE TITLE
Aktualisierung Vignetten

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#389]
[vignetten-translation.zip](https://github.com/dzhw/SiD/files/6221627/vignetten-translation.zip)

**Comment by annamarkn** [comment]
Das sind leider nicht die richtigen Versionen (beide). Hier sind die aktuellen, allerdings noch nicht mit der englischen Übersetzung.
[github version.zip](https://github.com/dzhw/SiD/files/6222194/github.version.zip)

**Comment by andreaschu** [comment]
@christian-fr können wir morgen zur Aktualisierung der Vignetten telefonieren?

**Comment by annamarkn** [comment]
Liebe Andrea, hier kommen die beiden aktuellen Vignettendateien (Master, Promotion), inkl. Englischer Übersetzung: 

[github version.zip](https://github.com/dzhw/SiD/files/6265581/github.version.zip)

Wann könnten wir sie testen? 
Danke schön :)

**Comment by andreaschu** [comment]
@annamarkn vielen Dank für die Dateien. Ich habe sie mir kurz angesehen. Die Datei für die Master-Vignetten sieht auf dem ersten Blick gut aus. Die Vignetten bei den Promotionsvginetten stimmen im Deutschen nicht mit den von Dir gelieferten überein. Das müssen sie, sonst kann ich die Übersetzung nicht an die richtigen Vignetten knüpfen.


> Das sind leider nicht die richtigen Versionen (beide). Hier sind die aktuellen, allerdings noch nicht mit der englischen Übersetzung.
> [github version.zip](https://github.com/dzhw/SiD/files/6222194/github.version.zip)

**Comment by annamarkn** [comment]
Liebe Andrea, danke für den Hinweis. 
Ich habe nochmal nachgeschaut und leider ist es so, dass bei jeder Erstellung der Promotionsvignetten eine Zufallsvariable benötigt wird, weshalb die decks und vignr je nach Dateiversion anders ausfallen. Das kann ich leider anders nicht machen, da es von der Zufallsvariablen gesteuert wird. Bei Mastervignetten arbeitet man wegen des anderen factorial Designs mit einer vordefinierten setup Datei und braucht keine Zufallsvariable, weshalb die verschiedenen Dateiversionen in den Identifier identisch bleiben. 
Die Promotionsdatei muss daher leider neu zugespielt werden (bei der Masterdatei wird dann die Englischspalte kopiert, richtig?). Sorry für den zusätzlichen Aufwand bei den Promotionsvignetten, aber anders kriege ich es leider nicht hin.
Den Issue #406 braucht man eigentlich dann nicht mehr, oder?
Liebe Grüße
Anna

**Comment by christian-fr** [comment]
Promotionsvignetten sind geändert. Ab nächstem Rollout verfügbar.

**Comment by andreaschu** [comment]
ich habe die neuen Versionen in GitHub hochgeladen: [Master](https://github.com/dzhw/SiD/blob/master/vignette_master_layout_en.xls) und [Promotion](https://github.com/dzhw/SiD/blob/master/vignette_promo_layout_en.xls)

**Comment by annamarkn** [comment]
@andreaschu  Wir haben die Vignetten getestet.
Bei den **Promotionsvignetten** sind uns Layoutfehler aufgefallen, die aus unserem dofile hervorgehen. Könntest Du bitte folgende Fehler direkt in der programmierten Datei korrigieren? Dann brauchen wir keine neue Zuspielung der Excel Datei.

- [ ] - VigEN: Einen Punkt am Satzende einfügen: "commute for 2 hours"
- [ ] - VigEN & Vig: Neuen Absatz einfügen hinter: "...do not receive any funding from the academic system." Das gleiche bei der deutschen Version: "keine Finanzierung aus dem Wissenschaftssystem." 

Zusätzlich ist uns aber ein größeres Problem aufgefallen: 
Bei einer Unterbrechung der Befragung und Neuanmeldung mit dem gleichen Token werden andere Vignetten zugespielt. Falls man vorher die Vignetten bewertet hat, wird die Bewertung auch für die neu zugespielten Vignetten übernommen.  Das wollen wir natürlich nicht. Das liegt wahrscheinlich an der Zufallszuspielung der decks beim Befragungs(neu)anfang. 

- [ ] Wie könnte man es programmieren, dass die selben Vignetten auch bei Neuanmeldung zugespielt werden?

**Comment by meyerja** [comment]
@andreaschu 
Ich habe die Vignetten auch nochmal im responsiven Design getestet (am Smartphone). Dabei ist mir aufgefallen, dass der Hinweis "Bei mobilen Endgeräten bitte die horizontale Ansicht verwenden." nicht mehr angezeigt wird. Dieser Punkt wurde eigentlich bereits umgesetzt, jetzt aber wieder gelöscht. Könnt ihr das bitte wieder ergänzen? Danke :)

**Comment by christian-fr** [comment]
@meyerja

Die Bildschirmgröße wird auf der page
**KSM-ma01** (für die Master-Vignetten **V1_1, V1_2, V2_1, ...** 
bzw. 
**KSM-phd01** (für die Promotions-Vignetten **pvig1_1, pvig1_2...** 
erfasst.

Die solltest Du auf dem Smartphone besucht haben, bevor Du Dir die Vignetten anschaust.

**Comment by christian-fr** [comment]
> 
> 
> @andreaschu Wir haben die Vignetten getestet.
> Bei den **Promotionsvignetten** sind uns Layoutfehler aufgefallen, die aus unserem dofile hervorgehen. Könntest Du bitte folgende Fehler direkt in der programmierten Datei korrigieren? Dann brauchen wir keine neue Zuspielung der Excel Datei.
> 
>     * [x]  - VigEN: Einen Punkt am Satzende einfügen: "commute for 2 hours"
> 
>     * [x]  - VigEN & Vig: Neuen Absatz einfügen hinter: "...do not receive any funding from the academic system." Das gleiche bei der deutschen Version: "keine Finanzierung aus dem Wissenschaftssystem."
> 
> 

Diese Änderungen der englischen Übersetzung wurden übernommen und sind ab dem nächsten Rollout verfügbar. Sie wurden auch bereits [in die Übersetzungsdatei](https://github.com/dzhw/SiD/issues/395#issuecomment-817734620) eingefügt.

**Comment by andreaschu** [comment]
> - [x]  Wie könnte man es programmieren, dass die selben Vignetten auch bei Neuanmeldung zugespielt werden?

ist eingebaut und ab dem nächsten RollOut verfügbar.

**Comment by andreaschu** [comment]
@annamarkn habt ihr das gestestet und muss hier noch was gemacht werden? Ansonsten wäre es gut, wenn Du das Issue schließen würdest.

**Comment by annamarkn** [comment]
@andreaschu  wir schließen das Issue, nachdem wir die Umsetzung getestet haben. Ihr habt aber auf alles bisher reagiert. Danke!

**Comment by annamarkn** [comment]
@andreaschu Vielen Dank für die Umsetzung! Könntet Ihr bitte noch den einen Punkt umsetzen? 

- [ ] Vig (deutsche Version): Neuen Absatz einfügen hinter: "...keine Finanzierung aus dem Wissenschaftssystem."

**Comment by andreaschu** [comment]
@annamarkn welches Modul ist das?

**Comment by annamarkn** [comment]
Promotionsvignetten, sorry!

**Comment by annamarkn** [comment]
@andreaschu Promotionsvignetten, sorry!
