### ISSUE TITLE
D3_8: Variablennamen fehlen

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#39]
Damit die Frage [D3_8](https://github.com/dzhw/SiD/blob/master/Modul-D3_Wohnen_Finanzen_Ba%C3%B6fg_Erwerb.md#d3_8) als Mehrfachnennung programmiert werden kann, werden noch Variablennamen benötigt. 

Zunächst festipart1-festipart17 verwendet.

**Comment by karbecke** [comment]
besteht Problem weiterhin? Wenn nein, würde ich das Issue schließen

**Comment by SilinaKowalewski** [comment]
Frage wurde gelöscht. Das Problem besteht somit nicht mehr.
