### ISSUE TITLE
Layout - N-Modul

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#392]
Liebe @SilinaSchirmer & @vdick,

wie besprochen ziehe ich die Layoutpunkte aus dem ursprünglichen Issue raus.

- [ ] N_7 und N_8: missing bitte absetzen, bzw. die Linie nicht durchführen wenn möglich -->Vergleichsfrage, wo es so bereits umgesetzt ist: C1_12
- [ ] N_10: ao13 Exklusivkategorie bitte wenn möglich etwas absetzen -->Vergleichsfrage, wo es so bereits umgesetzt ist: C1_7

Liebe Grüße,
Marie

**Comment by andreaschu** [comment]
ich habe die seiten mal im Issue #403 gesammelt und schließe deswegen hier.
