### ISSUE TITLE
Lieferung Screenshots

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#393]
Hier findet ihr die versprochenen Screenshots in 4 verschiedenen Auflösungen. 

https://myshare.dzhw.eu/index.php/s/JHlihRsThUdar4e
Passwort: sid

**Hinweis**: @christian-fr hat für die Erstellung alle Sichtbarkeitsbedingungen "eingeschaltet". Ihr solltet also nun zum Teil auch Elemente sehen, die sonst nicht gleichzeitig zu sehen sind.

**Comment by karbecke** [comment]
Screenshots liegen auf dem Server, Issue closed
