### ISSUE TITLE
Übersetzungdatei

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#395]
Zu wann möchtet ihr die Übersetzungsdatei geliefert bekommen? 
Das Exportieren ist recht unkompliziert. 

Wir könnten auch also auch immer mal wieder aktuelle Versionen ziehen.

**Comment by andreaschu** [comment]
@karbecke und @lenamzimmer gestern wurde gesagt, dass Hendrik bereits an der Übersetzung arbeitet. Wir sind etwas verwirrt, da dieses Issue nie beantwortet wurde. Mit welcher Version arbeitet er denn?

**Comment by christian-fr** [comment]
Hier findet ihr die Übersetzungs-Datei:

[2021-04-12_translation_sid-2021.xlsx](https://github.com/dzhw/SiD/files/6296185/2021-04-12_translation_sid-2021.xlsx)

Bitte die Spalte `key` unbedingt unverändert lassen und die englische Übersetzung ergänzen.

Da uns die Übersetzung für die Vignetten-Texte (Master & Promo) bereits vorlag, habe ich diese jeweils schon eingefügt. Alle weiteren Zeilen dann bitte ergänzen.

**Comment by lenamzimmer** [comment]
Ich habe die Datei an Hendrik weitergeleitet - lieben Dank!

**Comment by HenSch90** [comment]
[2021-04-12_translation_sid-2021_2021_04_16.xlsx](https://github.com/dzhw/SiD/files/6326539/2021-04-12_translation_sid-2021_2021_04_16.xlsx)
Hier die „aufgefüllte“ Datei zurück.
Allerdings noch mit Lücken: Die Konstanzer Module fehlen noch, die Hochschulliste ist noch in Übersetzung.
Liebe Grüße & ein schönes Wochenende wünscht
Hendrik

**Comment by HenSch90** [comment]
Bitte wartet noch einen Moment mit der Bearbeitung der Übersetzung - ich ergänze die Datei gleich um die KSM Module! :)

**Comment by HenSch90** [comment]
[2021-04-12_translation_sid-2021_2021_04_19.xlsx](https://github.com/dzhw/SiD/files/6336846/2021-04-12_translation_sid-2021_2021_04_19.xlsx)
Hier nun die ergänzte Datei.

Liebe Grüße,
Hendrik

**Comment by andreaschu** [comment]
Ich mach hier mal zu. Am Montag machen wir ein neues Issue dazu auf.
