### ISSUE TITLE
Layoutprobleme (responsives Design): Module E2-E4

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#396]
Liebes ZOFAR-Team,

bei der Darstellung im responsiven Design (am Tablet und Smartphone) sind uns noch einige Punkte aufgefallen, die das Layout betreffen:

- [ ] Der Zähler des Karussells beginnt sonst immer bei 1, jedoch an zwei Stellen bei 0 (siehe Beispiel). Hier das Karussell bitte einheitlich bei 1 beginnen lassen. Dies betrifft folgende Fragen:

- KSM-phd02
- KSM-ma07

![grafik](https://user-images.githubusercontent.com/56591452/113150545-7db68380-9234-11eb-9447-874dca00aa1f.png)

- [ ] Bei den folgenden Fragen wird leider gar kein Zähler am Karussell eingeblendet. Diesen bitte noch ergänzen: 

- KSM-pol04
- KSM-fai04

![grafik](https://user-images.githubusercontent.com/56591452/113150776-b9514d80-9234-11eb-8948-8360207e09de.png)

- [ ] Der Text ragt an manchen Stellen ins offene Feld und wird dadurch verdeckt (jeweils letztes Item):

- KSM-anf04
- KSM-anf05
- KSM-ma07
- KSM-phd02

![grafik](https://user-images.githubusercontent.com/56591452/113151970-ec481100-9235-11eb-8ce6-3214f1b7a647.png)

- [ ] Die Skalenbeschriftung links wird an manchen Stellen abgeschnitten, wodurch die Skalenbeschriftung nicht richtig lesbar ist:

- Mastervignetten
- Promotionsvignetten
- KSM-ma04
- KSM-pol02
- KSM-fai06

![grafik](https://user-images.githubusercontent.com/56591452/113152198-2addcb80-9236-11eb-9f8b-bdbe6710b4d0.png)

- [ ] Bei der Darstellung am Tablet überschneidet sich der rechte Skalenpunkt „stimme voll und ganz zu“ teilweise mit der Beschriftung „kann ich nicht beurteilen“ bzw. "weiß ich nicht"

- KSM-pol03
- KSM-pol04 
- KSM-pol05
- KSM-fai05
- KSM-anf02 (siehe auch Screenshots)
- KSM-anf10 (siehe auch Screenshots)
- - KSM-anf11 (siehe auch Screenshots)

![grafik](https://user-images.githubusercontent.com/56591452/113152430-6b3d4980-9236-11eb-8093-5251a812ea2e.png)

Vielen Dank für die Überarbeitung :)

**Comment by andreaschu** [comment]
Die Issues sollten immer nur ein Problem behandeln, deshalb habe ich für jede der oben genannten Anmerkungen ein Issue erstellt und schließe dieses hier.
#410
#411 
#412 
#413
