### ISSUE TITLE
Karussell am Smartphone: generelle Frage

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#397]
Liebes ZOFAR-Team,

beim Testen des Fragebogens am Smartphone ist uns aufgefallen, dass alle Item-Karussells an sich kein Ende haben. 
Ist man beim letzten Item der Batterie angelangt, wird immer noch ein Pfeil nach rechts angezeigt, der dann schließlich wieder zum ersten Item zurückführt. An sich könnte das jedoch für die Befragten verwirrend sein. 

Daher die allgemeine Rückfrage, ob es möglich ist, jeweils beim letzten Item den rechten Pfeil auszublenden, der wieder zum ersten Item führt, um zu signalisieren, dass man am Ende der Frage angelangt ist? Ist dies technisch möglich? 

Wenn ja, @karbecke: Was haltet ihr von dieser Idee?

**Comment by karbecke** [comment]
Hey, ja, dass ist ein guter Vorschlag. @SilinaSchirmer könnt ihr diesen Vorschlag umsetzen?

**Comment by andreaschu** [comment]
@meyerja da es ein Karussell ist, ist es mitgedacht, dass es im Kreis dreht. Das Ausblenden können wir nicht einbauen. Zur Orientierung dient der Item-Indikator.
