### ISSUE TITLE
Kleinere Änderungen vorgenommen (Modul E4, E2 Master- und Promotionsvignetten)

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#398]
Liebes ZOFAR-Team,

ich habe nochmal einige kleinere Änderungen vorgenommen, die uns bei der Überprüfung des Layouts aufgefallen sind. Bitte arbeitet folgende Änderungen in die QML ein: 

- [x] 78798a6 am Modul E4
- [x]  65dd763 am Modul E2-Mastervignetten
- [x] fffb079 am Modul E2-Promotionsvignetten

Vielen Dank :)

**Comment by christian-fr** [comment]
Ist geändert. Ab nächstem Rollout verfügbar.

**Comment by meyerja** [comment]
@christian-fr : Vielen Dank für die Änderungen.
Könntest du auf der Seite KSM-fai26 den Fragetext optisch noch von dem Einleitungstext absetzen, also einen Absatz dazwischen einbauen?

**Comment by christian-fr** [comment]
Leerzeile ist ergänzt. Ab nächstem Rollout verfügbar.
