### ISSUE TITLE
Filterung Länderlisten - Modul A

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#399]
Liebes ZOFAR-Team,

in Modul A haben wir an 3 Stellen Länderlisten programmiert, die über eine vorangehende Frage vorgefiltert werden. Das betrifft folgende Seiten:
- A_4 (vorgefilttert über A_3)
- A_7 (vorgefilttert über A_6)
- A_36 (vorgefilttert über A_35)

Wenn auf der Filterseite keine Angabe gemacht werden, erscheinen auf der Folgeseite jeweils nur 3 Länder. Es sollte so umgesetzt sein, dass bei fehlender Angabe überhaupt nicht vorgefiltert und stattdessen die gesamte Länderliste vorgelegt wird. Könntet ihr das bitte noch so anpassen?

![grafik](https://user-images.githubusercontent.com/53002476/113260883-14378300-92cf-11eb-8f5f-623c0ddd1bf5.png)

**Comment by SilinaSchirmer** [comment]
Ab nächstem Rollout (#394) verfügbar.

**Comment by woisch** [comment]
danke, jetzt sind alle Länder drin!

wir haben jetzt allerdings das Problem, dass die Liste nicht komplett alphabetisch ist. Das dürfte an unserer Vorsortierung nach Kontinenten liegen (jeweils für die Kontinente ist die Liste immer von A-Z sortiert).
Habt ihr eine Lösung dafür, sodass bei den Fällen, die auf der Filtervariable ein Missing haben die Liste komplett alphabetisch sortiert ist, aber bei den vorgefilterten Listen alles so bleibt wie es jetzt ist? Oder müssten wir dann mit 2 unterschiedlichen Listen arbeiten?

**Comment by andreaschu** [comment]
@woisch wenn die Listen alphabetisch sortiert werden, müssten sie - unabhängig von Filterung - immer alphabetisch sein, oder?
Aber soll Deutschland dann wirklich irgendwo in der Liste auftauchen und nicht ganz oben?

**Comment by woisch** [comment]
Sorry, ich glaube ich stand auf dem Schlauch! 
Ja, eigentlich reicht es, wenn die Gesamtliste immer und komplett alphabetisch sortiert ist (dann wird ja einfach nur je nach Kontinent ausgeblendet und wenn auf der Filterfrage Missing ist, wird einfach die komplette Liste eingeblendet).
Deutschland muss nicht ganz oben stehen, sondern sollte immer an der "richtigen Stelle" einsortiert sein (alphabetisch).

**Comment by SilinaSchirmer** [comment]
Umgesetzt und ausgerollt.

**Comment by woisch** [comment]
geprüft, das sieht gut aus so! Danke!
