### ISSUE TITLE
Layout - A-Modul

### ISSUE THREAD

**Issue by mcehrhardt** [dzhw/SiD#401]
Liebes ZOFAR-Team,

in Modul A müsste das Layout bitte bei folgenden Fragen angepasst werden:

- [ ] A_9b ao4 bitte absetzen
- [ ] A_11ao6 bitte absetzen
- [ ] A_28 Radiobutton vor offener Angabe bitte ausblenden
- [ ] A_33 Radiobutton vor offener Angabe bitte ausblenden
- [ ] A_40 Radiobuttons vor offenen Angabe bitte ausblenden
- [ ] ~A_56 Spaltenbeschriftung bitte über Spalte zentrieren~ ist bereits im Issue 351

Vielen Dank und Liebe Grüße,
Marie

**Comment by andreaschu** [comment]
@mcehrhardt gilt das mit den ausgeblendeten RadioButtons auch für A_33?

**Comment by mcehrhardt** [comment]
@andreaschu, danke für den Hinweis! Ja, dort auch, hab ich in der Liste oben ergänzt.
