### ISSUE TITLE
Antwortoptionen absetzen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#403]
- [x] [A_9b](https://presentation.dzhw.eu/sid-2021/A_9b.html)
- [x] [A_11](https://presentation.dzhw.eu/sid-2021/A_11.html)
- [x]  [N_7](https://presentation.dzhw.eu/sid-2021/N_7.html)
- [x]  [N_8](https://presentation.dzhw.eu/sid-2021/N_8.html)
- [x] [N_10](https://presentation.dzhw.eu/sid-2021/N_10.html)
- [x] [A_8a](https://presentation.dzhw.eu/sid-2021/A_8a.html)
- [x] [A_27a](https://presentation.dzhw.eu/sid-2021/A_27a.html) 
- [x]  [A_32](https://presentation.dzhw.eu/sid-2021/A_32.html)

**Comment by mcehrhardt** [comment]
Liebe @andreaschu,

diese beiden Punkte sind bereits zusammen mit anderen Layoutpunkten im Issue #401 . Brauchen wir dieses separate Issue dann überhaupt?

LG
Marie

**Comment by andreaschu** [comment]
@mcehrhardt ich habe das getrennt nach den Aufgaben und daraus zwei Issues gemacht. Das 401 schließe ich jetzt.

**Comment by mcehrhardt** [comment]
@andreaschu alles klar, danke für die Info!

**Comment by vdick** [comment]
ab nächsten Rollout (#400 ) verfügbar

**Comment by mcehrhardt** [comment]
Bitte auch bei folgenden Fragen Antwortoptionen absetzen:

- [ ] A_8a ao5 absetzen
- [ ] A_27a ao4 absetzen
- [ ] A_32 mv absetzen

Vielen Dank und liebe Grüße,
Marie

**Comment by vdick** [comment]
ab nächsten Rollout (#400 ) verfügbar

**Comment by woisch** [comment]
geprüft. Einen Änderungswunsch hätten wir noch;

- [ ] N_7/N_8: könntet ihr die Verbindungslinie zur mv-Kategorie hier noch entfernen? Also dass nur die 5 Aos miteinander per Linie verbunden sind..

**Comment by andreaschu** [comment]
@vdick die Kategorien sind im qml als Missing deklariert. Da sie aber vorn stehen und nicht hinten, greift die Logik hier nicht.

**Comment by vdick** [comment]
ab nächsten Rollout (#408 ) verfügbar

**Comment by woisch** [comment]
geprüft, in Ordnung so!
