### ISSUE TITLE
Radiobuttons vor offenen Angabe ausblenden

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#404]
Vor den AO's mit offenen Feldern (attached open) sollen die Radio buttons ausgeblendet werden. Das gilt für die Seiten: 

- [x] [A_28](https://presentation.dzhw.eu/sid-2021/A_28.html)
- [x] [A_33](https://presentation.dzhw.eu/sid-2021/A_33.html)
- [x] [A_40](https://presentation.dzhw.eu/sid-2021/A_40.html)

**Comment by vdick** [comment]
ab nächsten Rollout(#400) verfügbar

**Comment by woisch** [comment]
@mcehrhardt Hab das mal getestet und für gut befunden! Genau so wollten wir das haben.
Issue kann also zu.
