### ISSUE TITLE
responsive Version für offene Matrizen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#405]
Für die drei Seiten ([B1_4a](https://presentation.dzhw.eu/sid-2021/B1_4a.html), [B1_6](https://presentation.dzhw.eu/sid-2021/B1_6.html) und [D3_8](https://presentation.dzhw.eu/sid-2021/D3_8.html)) sollen responsive Lösungen als eigene Seiten programmiert werden (jeweils mit Zusatz _r). 

- [x] eigene Seite bauen
- [ ] transition anpassen

Layout:
- [x] Bei B1_4a ist die100%-Zeile nach vorn gerutscht. @vdick wir haben den Fehler bisher nicht gefunden. Kannst Du mal bitte schauen?
- [x] Für B1_4a und B1_6 die 100%-'Zeile' deaktivieren bzw. unausfüllbar machen
- [x] das Carousel für die einzelnen Matrizen deaktivieren (Achtung, das sind immer mehrere auf der Seite)

**Comment by andreaschu** [comment]
@vdick Die Matrizen auf B1_4a und B1_6 sind für SmartPhones angepasst. Hier kann das Layout angefasst werden und die 100%-'Zeile' (die hier kein Item, sondern ein Title ist) deaktiviert werden. Falls das mit dem Title nicht geht, müssen wir eine andere Lösung suchen.

**Comment by vdick** [comment]
außer D3_8 ab Rollout(#445 ) verfügbar

**Comment by andreaschu** [comment]
D3_8 und D3_6 fehlen noch.

**Comment by SilinaSchirmer** [comment]
@karbecke: Die Transitions übernehmt ihr, oder?

**Comment by karbecke** [comment]
> 
> 
> @karbecke: Die Transitions übernehmt ihr, oder?

ja, @koopmann1896 : Kannst Du Dir das anschauen. Danke!

**Comment by koopmann1896** [comment]
Unterscheidet sich diese Issue von #467 ? Dort tauchen die drei Seiten ja bereits mit Transitions auf....

**Comment by koopmann1896** [comment]
läuft, wird geschlossene
