### ISSUE TITLE
Breakpoint Carousel - B2_9b und KSM-ma06

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#407]
Fall möglich, bitte das Carousel für die Fragen B2_9b und KSM-ma06 schon in der Tablet-Ansicht einschalten. 

https://github.com/dzhw/SiD/issues/313#issuecomment-809242705

@karbecke @mcehrhardt: Für alle Fragen lässt sich diese Einstellung leider nicht machen, sodass wir die Tablet-Ansicht nicht komplett rausnehmen können.

**Comment by andreaschu** [comment]
@karbecke und @mcehrhardt wir haben das mal getestet und sind zu dem Schluss gekommen, dass die Eingriffe zu tiefgreifend wären um den Breakpoint anders zu setzen. Die betreffenden Fragen müssten anders gelöst werden.

**Comment by karbecke** [comment]
@andreaschu: Bitte für diese beiden Seiten nicht in die Tablet-Ansicht, sondern die Fragen direkt als Carousel anzeigen lassen

**Comment by andreaschu** [comment]
@karbecke wie oben schon geschrieben ist der Eingriff dafür zu tiefgreifend. Hierfür muss eine andere Lösung gefunden werden.

**Comment by karbecke** [comment]
ok, Issue closed
