### ISSUE TITLE
Änderung transitions Module E2, E3 und E4

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#409]
Liebes ZOFAR-Team,

ich habe Änderungen an den transitions der Module E2, E3 und E4 vorgenommen. 

- [x] E2 (Studienanfang):  708792f

- [x] E2 (Master): ba82e94

- [x] E2 (Promotion): 7988887

- [x] E3 (Politik):  9159913

- [x] E4 (Fairness):  c32561b

Bitte arbeitet diese in die QML ein. Vielen Dank :)

**Comment by SilinaSchirmer** [comment]
Änderungen wurden umgesetzt und sind am nächstel Rollout (#423) verfügbar.

**Comment by meyerja** [comment]
@SilinaSchirmer 
Aufgrund einer Änderung am Splitdesign habe ich nochmals die transitions der E2-Module angepasst. 

- [ ] E2 (Studienanfang): 7cf4308
- [ ] E2 (Master):  2892a44
- [ ] E2 (Promotion):  da13216

Danke für die Umsetzung :)

**Comment by SilinaSchirmer** [comment]
Änderungen wurden umgesetzt und sind ab nächstem Rollout (#431) verfügbar.
