### ISSUE TITLE
Karussel-Zähler beginnt mit 0

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#410]
- [x] KSM-phd02
- [x] KSM-ma07

![grafik](https://user-images.githubusercontent.com/56591452/113150545-7db68380-9234-11eb-9447-874dca00aa1f.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#408 ) verfügbar

**Comment by meyerja** [comment]
Passt jetzt, Danke :)
