### ISSUE TITLE
label überschneidet sich mit offenem Feld (SmartPhone-Ansicht)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#412]
- [ ] KSM-anf04
- [ ] KSM-anf05
- [ ] KSM-ma07
- [ ] KSM-phd02

![grafik](https://user-images.githubusercontent.com/56591452/113151970-ec481100-9235-11eb-8ce6-3214f1b7a647.png)

**Comment by woisch** [comment]
das selbe Problem besteht auch auf F3_12 (bereits in Issue #474 erwähnt)

**Comment by mcehrhardt** [comment]
Ebenso besteht das Problem bei

- [ ] A_14
![Screenshot_20210426_100907_org mozilla firefox](https://user-images.githubusercontent.com/57707751/116075458-469c8c00-a693-11eb-9c57-9b901942a961.jpg)


- [ ] D1_8
![grafik](https://user-images.githubusercontent.com/57707751/116075517-54eaa800-a693-11eb-9d1e-7b703267a988.png)

**Comment by meyerja** [comment]
@mcehrhardt Da D1_7 der Frage KSM-anf04 entspricht, müsste das Problem auch hier auftreten.

**Comment by mcehrhardt** [comment]
@meyerja das ist bereits bekannt und steht im ersten Kommentar des Issues :)

**Comment by mcehrhardt** [comment]
Auch bei

- [ ] F2_14
![grafik](https://user-images.githubusercontent.com/57707751/116106857-c2f29780-a6b2-11eb-9dbb-1c80da81ebff.png)

**Comment by meyerja** [comment]
@mcehrhardt Das war auch als Hinweis gedacht, dass D1_7 in eurer Liste fehlt ;)

**Comment by vdick** [comment]
ab nächsten Rollout (#517) verfügbar

**Comment by woisch** [comment]
Für alle Seiten responsiv getestet (auch D1_7). ok so und kann geschlossen werden
