### ISSUE TITLE
zu lange Label in SingleChoiceMatrizen (Tablet-Ansicht)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#413]
- [x] [KSM-pol03](https://presentation.dzhw.eu/sid-2021/KSM-pol03.html)
- [x] [KSM-pol04](https://presentation.dzhw.eu/sid-2021/KSM-pol04.html) 
- [x] [KSM-pol05](https://presentation.dzhw.eu/sid-2021/KSM-pol05.html)
- [x] [KSM-fai05](https://presentation.dzhw.eu/sid-2021/KSM-fai05.html)
- [x] [KSM-anf02](https://presentation.dzhw.eu/sid-2021/KSM-anf02.html) (siehe auch Screenshots)
- [x] [KSM-anf10](https://presentation.dzhw.eu/sid-2021/KSM-anf10.html) (siehe auch Screenshots)
- [x] [KSM-anf11](https://presentation.dzhw.eu/sid-2021/KSM-anf11.html) (siehe auch Screenshots)

![grafik](https://user-images.githubusercontent.com/56591452/113152430-6b3d4980-9236-11eb-8093-5251a812ea2e.png)

**Comment by vdick** [comment]
ab nächsten Rollout(#408 ) verfügbar

**Comment by meyerja** [comment]
@andreaschu Leider ist die Ansicht auf den folgenden Seiten immer noch unleserlich und die Beschriftungen ragen am Tablet ineinander: 

- [ ] KSM-pol03
- [ ] KSM-pol05

Könntet ihr da nochmal drüber schauen?

**Comment by vdick** [comment]
ab nächsten Rollout (#455 ) verfügbar
