### ISSUE TITLE
Update Modul A (A_27)

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#414]
Liebe ZOFAR-Team,

bei Frage A_27 wurde ein Item entfernt, bitte anpassen: 7afadd4575dda4a21e1d7ed70dc7347ed99993aa

(Ich weiß, es gibt noch ein offenes Issue zu Modul A, da muss Marie aber noch andere Umsetzungen testen, daher habe ich ausnahmsweise mal ein neues Issue erstellt)

**Comment by andreaschu** [comment]
Ab dem nächsten RollOut verfügbar.

**Comment by woisch** [comment]
geprüft!
