### ISSUE TITLE
Skalenbeschriftung abgeschnitten (Modul E2, E3 und E4)

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#415]
Liebe Andrea,

vielen Dank für das Erstellen der einzelnen Issues bzgl. der Layoutprobleme im responsiven Design. 
Du hast jedoch einen Punkt aus der Liste vergessen, den ich gerne hier aufnehmen möchte:

An einigen Stellen ist die Skalenbeschrifrung links abgeschnitten und daher nicht richtig lesbar (siehe Screenshot). Das betrifft folgende Seiten:

- [x] Promotionsvignetten
- [x] Mastervignetten
- [x] KSM-ma04
- [x] KSM-pol02
- [x] KSM-fai06

![grafik](https://user-images.githubusercontent.com/56591452/113879037-70f8d900-97ba-11eb-869a-e9d7717b9971.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#423 ) verfügbar

**Comment by andreaschu** [comment]
@meyerja und @annamarkn konntet Ihr das schon testen? Wenn es korrekt ist, bitte das Issue schließen.
