### ISSUE TITLE
Modul E1: Filterfrage neu eingefügt

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#416]
Hallo zusammen,

im E1 Modul mussten wir eine Filterfrage neu einfügen, die diesbezüglichen Transition befinden sich noch in der Erstellung und werden dann nächste Woche zusammen mit allen Transition an euch übergeben.

Bitte übernehmt die folgende Seite neu in das qml:
- [x] E1_1a 6e29a132973d620f4c87758a9cb777aef53ba961

Beste Grüße
Jonas

**Comment by koopmann1896** [comment]
Mir ist dort ein Rechtsschreibfehler durchgerutscht, entschuldigt bitte:
19c5c083012534edea051a1388a3ca999091155c

**Comment by andreaschu** [comment]
Ist ab dem nächsten RollOut verfügbar

**Comment by koopmann1896** [comment]
Läuft, wird geschlossen.
