### ISSUE TITLE
Datenlieferung Pretest

### ISSUE THREAD

**Issue by annamarkn** [dzhw/SiD#417]
@andreaschu 
Liebe Andrea, danke fürs einpflegen der Vignetten! Wir werden sie jetzt gründlich testen und würden ca. 100 tokens verwenden um bei Vignetten Angaben zu machen. Könnten wir nächste Woche einen Datenausschnitt erhalten? Man kann einen Token zum Ausfüllen beider Vignetten (MA & PhD) verwenden, oder? (in der Tat sind es ja getrennte Pfade)

**Comment by annamarkn** [comment]
@andreaschu @christian-fr Könnte man bei den Vignetten die englische Version freischalten? Es wäre wichtig zu überprüfen, ob die Übersetzung mit der deutschen Version übereinstimmt.

**Comment by christian-fr** [comment]
> 
> 
> @andreaschu @christian-fr Könnte man bei den Vignetten die englische Version freischalten? Es wäre wichtig zu überprüfen, ob die Übersetzung mit der deutschen Version übereinstimmt.

Hallo Anna,
wir haben die Übersetzungen freigeschaltet - die sind ab dem nächsten Rollout verfügbar. 

Es sind derzeit die englischen Übersetzungen **ausschließlich** für die Vignetten verfügbar, da uns die restliche Übersetzung noch nicht vorliegt (siehe Screenshots unten).

Den Text der Vignetten könnt ihr damit aber überprüfen, der eigentliche Fragetext sowie die Wertelabel werden jedoch noch nicht angezeigt, weil die Übersetzung dort noch nicht vorliegt.

### deutsche Version
> ![grafik](https://user-images.githubusercontent.com/42959832/114023224-e7591200-9872-11eb-9765-afcd7d84d5e7.png)

### englische Version
> ![grafik](https://user-images.githubusercontent.com/42959832/114023438-29825380-9873-11eb-8325-a17a902d3690.png)

**Comment by andreaschu** [comment]
@annamarkn für die Übersetzung ist das Issue #406 da. Für die Testung bitte in diesem Issue arbeiten. Es wäre hilfreich, wenn wir in den Issues beim Thema des Issues blieben. Die Kommentare von oben habe ich in das andere Issue kopiert.

**Comment by andreaschu** [comment]
@annamarkn beim Testen können beide Module ausgefüllt werden. Es gibt jetzt übrigens mehr Token (siehe [Wiki](https://github.com/dzhw/SiD/wiki). 
Für das systematische Testen wäre es sinnvoll, wenn die Token Personen zugeordnet werden.

**Comment by annamarkn** [comment]
@andreaschu  Wir haben die Vignetten getestet und würden uns gerne die Daten anschauen. Folgende Tester haben wir genutzt: 100-179.
Wann könnten wir die Daten erhalten? Danke!

**Comment by andreaschu** [comment]
@annamarkn der Datenexport liegt in der Cloud. Du müsstest eine Mail bekommen haben.
Das Passwort ist: B34rb0ck

**Comment by annamarkn** [comment]
@andreaschu  Danke für die Daten. Eine Frage: Anhand welcher Variablen erkenne ich die Vignettennummer innerhalb decks? (in Excel "vignr"). Im Datensatz kann ich nur h_deck und h_promo_deck finden, die mich über die Vignettenbewertung und das deck informieren aber ich weiss nicht, um welche konkrete Vignette es sich innerhalb des decks handelt.
Danke!

**Comment by andreaschu** [comment]
@annamarkn die Vignetten sind folgendermaßen gebaut und aus dem Datensatz zu lesen. Aus der jeweiligen Hilfsvariable ist die Decknummer zu erkennen und die Variablen haben den Postfix _1 bis _4 aus denen jeweils erkennbar ist, welche Vignette die Person bewertet hat. Also bei h_deck == 35, enthält mabew_1 die Bewertung ersten Vignette des 35. Decks im Modul der Mastervignetten.

Aber ich habe gesehen, dass der Export fehlerhaft war und die Variablen gar nicht enthielt. Ich hab einen korrigierten Export in die Cloud geladen und dir wieder eine Mail geschickt. Das Passwort ist dasselbe wie beim ersten.


```
h_deck       : Decknummer Mastervignetten
mabew_1      : Bewertung der ersten Vignette im Deck [h_deck] Wie wahrscheinlich würden Sie sich auf diesen Masterstudiengang bewerben?
mabew_2      : Bewertung der zweiten Vignette im Deck [h_deck] Wie wahrscheinlich würden Sie sich auf diesen Masterstudiengang bewerben?
mabew_3      : Bewertung der dritten Vignette im Deck [h_deck] Wie wahrscheinlich würden Sie sich auf diesen Masterstudiengang bewerben?
mabew_4      : Bewertung der vierten Vignette im Deck [h_deck] Wie wahrscheinlich würden Sie sich auf diesen Masterstudiengang bewerben?

h_promo_deck : Decknummer Promotionsvignetten
prombew_1    : Bewertung der ersten Vignette im Deck [h_promo_deck] Diese Rahmenbedingungen für eine Promotion wären für mich …
prombew_2    : Bewertung der zweiten Vignette im Deck [h_promo_deck] Diese Rahmenbedingungen für eine Promotion wären für mich …
```
