### ISSUE TITLE
Update Modul A (A_42)

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#418]
Liebes ZOFAR-Team,
hier noch ein kleiner Anpassungswunsch für Modul A:

bitte q2 anpassen: ac959579da71cecbfaf1a9a8ca08dd8eea286783 

Danke!

**Comment by andreaschu** [comment]
ab dem nächsten RollOut verfügbar.

**Comment by woisch** [comment]
geprüft, in Ordnung.
