### ISSUE TITLE
Token für Hochschulen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#419]
- nur Großbuchstaben und Ziffern
- ohne 0 und O
- bestimmte Kombis ausschließen: SS, SA, KZ, HH, AH, 88, 18, HJ, WWG, WGA, XXX
- Prefix: S22

**Comment by lenamzimmer** [comment]
Liebes Zofar-Team,

hier nun die Hochschulliste zur (1) Erstellung der Token und (2) Erstellung der preloads PRELOADhs_tr, PRELOADhs_nrw und PRELOADhs_co

In Spalte A findet ihr die Hochschul-ID und in Spalte F die benötigte Anzahl an Token für die jeweilige Hochschule. Die Spalten G, H und I enthalten die nötigen Informationen um die preloads bilden zu können.

Solltete ihr Fragen haben, dann meldet euch gerne bei mir :-)

Liebe Grüße!

[Hochschulliste_preloads_token.xlsx](https://github.com/dzhw/SiD/files/6304445/Hochschulliste_preloads_token.xlsx)

**Comment by andreaschu** [comment]
@lenamzimmer wenn ich das richtig verstanden habe, hat sich die Liste verändert. Wenn am Donnerstag die Token bereit sein sollen, bräuchten wir die aktuelle Liste bzw. die Änderungen.
Da wir die Token nicht mehr komplett neu erstellen, bitte nicht einfach eine aktualisierte Liste hochladen. Für uns wären nur die Änderungen wichtig, in etwa so:
[hs_id]: [hochschulname alt] --> [hochschulname neu]
[hs_id] [hochschulname]: wird zu [hs_id] [hochschulname]

**Comment by karbecke** [comment]
Liebes ZOFAR-Team,

bitte folgende Anpassungen umsetzen: 


- [ ] [270] [Ernst-Moritz-Arndt-Universität Greifswald] wird zu --> [270] [Universität Greifswald]

- [ ] [820] [DHGS Hochschule für Gesundheit & Sport Berlin] wird zu --> [820] [DHGS Hochschule für Gesundheit und Sport]

- [ ] [1500] [Hochschule der Sparkasse-Finanzgruppe Bonn] wird zu --> [1500] [Hochschule für Finanzwirtschaft und Management]

- [ ] [1570] [Fachhochschule für Sport und Management  Potsdam]  wird zu --> [1570] [Fachhochschule für Sport und Management Potsdam] /// Leerzeichen entfernt

- [ ] [1760] [Business School Berlin - Hochschule für Management] wird zu --> [1760] [BSP Business and Law School - Hochschule für Management und Recht in Berlin]

- [ ] [1920] [Victoria Internationale Hochschule Berlin] wird zu --> [1920] [Victoria Internationale Hochschule]

- [ ] [2290] [Iternational University of Applied Sciences Berlin] wird zu --> [2290] [International University of Applied Sciences Berlin] /// Buchstabe fehlte

- [ ] [5110] [Evangelische Hochschule  Dresden] wird zu --> [5110] [Evangelische Hochschule Dresden] /// Leerzeichen entfernt

- [ ] [5720] [Internationale Hochschule Bad Honnef-Bonn] wird zu --> [1790] [IU Internationale Hochschule]; ***UND:*** PRELOADhs_nrw==0 /// Aufgrund von neuem Sitz in Erfurt keine NRW-Hochschule mehr

- [ ] [6720] [Hochschule Biberach ] wird zu --> [6720] [Hochschule Biberach] /// Leerzeichen entfernt

**Comment by dzhwmeisner** [comment]
erledigt.

**Comment by andreaschu** [comment]
@dzhwmeisner ich habs stichprobenartig getestet. Sieht gut aus.

**Comment by SilinaSchirmer** [comment]
Die Token wurden erstellt und alle Anpassungen vorgenommen. @karbecke hat die Liste mit Preload-Informationen welche an die jeweiligen Token angespielt wurden.
