### ISSUE TITLE
Aktualisierung der Startseite

### ISSUE THREAD

**Issue by lenamzimmer** [dzhw/SiD#420]
Hey,

Jonas und ich haben die Startseite aktualisiert. Die informed consent liegen aktuell noch nicht vor und müssen für die 35 NRW-Hochschulen ja individuell eingeblendet werden (wie besprochen).

https://github.com/dzhw/SiD/commit/d824cce7f388cf39f6bbc063e7faae0448685f23

**Comment by SilinaSchirmer** [comment]
Ist umgesetzt und ab nächstem Rollout verfügbar.
