### ISSUE TITLE
Trimester-Ergänzungen (Seite Tr_1 und Tr_2 + Modifikation A_17)

### ISSUE THREAD

**Issue by lenamzimmer** [dzhw/SiD#421]
Hey zusammen,

Jonas und ich haben nun zur Identifikation der Trimester-Orga-Studis die Seiten Tr_1 und Tr_2 ergänzt sowie die Anpassungen an A_17 vorgenommen. Es wäre toll, wenn ihr uns noch sagen könntet, @SilinaSchirmer @christian-fr @andreaschu , ob sich die Fachsemester dann trotzdem in einer Variable speichern lassen (und analog dann auch die Hochschulsemester).

Danke!

https://github.com/dzhw/SiD/commit/9a32c3c34a4593b5d9ed64037a3dab1c2da78932

**Comment by SilinaSchirmer** [comment]
@christian-fr: Ich habe die Seiten erst einmal gebaut und hoffe, dass sie so funktionieren. Kannst du mal schauen ob du dann Magic bzgl. der Eingabebedinungen machen kannst?

**Comment by lenamzimmer** [comment]
@SilinaSchirmer Super, vielen Dank. Denkt ihr auch dran, dass bei den nicht tr_1-Studis kein Komma auf A_17 zugelassen werden soll?! Danke. Freue mich jetzt auf die Magic von @christian-fr :-)

**Comment by koopmann1896** [comment]
Für die vc Bedingungen in A_17, die auf TR_1 zurückgreifen, haben ich missing-Bedingungen eingefügt, die bitte noch mit umgesetzt werden sollten. 06b6975fbb1609ad7ec494fd25e981020313acc5

Vielen Dank und beste Grüße

**Comment by SilinaSchirmer** [comment]
> Für die vc Bedingungen in A_17, die auf TR_1 zurückgreifen, habe ich missing-Bedingungen eingefügt, die bitte noch mit umgesetzt werden sollten. [06b6975](https://github.com/dzhw/SiD/commit/06b6975fbb1609ad7ec494fd25e981020313acc5)
> 
> Vielen Dank und beste Grüße

Ah! Hatte mich schon gefragt, wie wir das am sinnvollsten lösen und hatte die missing-Bedingung erstmal an die "normale" is gehangen. Ändere ich dann aber direkt.

**Comment by SilinaSchirmer** [comment]
Die Änderungen wurden umgesetzt und können getestet werden (#423). 

Zusätzliche habe ich auf der hilfsvar die PRELOADhs_tr eingebaut, damit die Sichtbarkeitsbedingungen auf der A_17 getestet werden können.

**Comment by koopmann1896** [comment]
Läuft alles, Transitions werden heute geliefert. Issue geschlossen.
