### ISSUE TITLE
Generierung von Zufallsvariablen

### ISSUE THREAD

**Issue by lenamzimmer** [dzhw/SiD#422]
Liebes Zofar-Team,

da wir einzelne Fragen gewichten möchten, wäre es toll, wenn ihr uns eine Reihe von Zusatzvariablen zu Beginn der Befragung definieren könntet. Und zwar hätten wir gerne 10 Variablen, die die Befragten zufällig und **jeweils unterschiedlich** in zwei Gruppen unterteilen (50%-Split, also 2 Ausprägungen), 10 Variablen, die die Befragten zufällig und **jeweils unterschiedlich** in vier Gruppen unterteilen (25%-Split, also 4 Ausprägungen) und 10 Variablen, die die Befragten zufällig und **jeweils unterschiedlich** in acht Gruppen unterteilen (12,5%-Split, also 8 Ausprägungen).
Für die Variablen-Benennung haben wir uns (bzw. Markus) folgende pfiffige Systematik überlegt: für die 10 x 50%-Split Variablen zwei_a, zwei_b, zwei_c,...., zwei_j; für die 10 x 25%-Split Variablen vier_a, vier_b, vier_c,...., vier_j;  für die 10 x 12,5%-Split Variablen acht_a, acht_b, acht_c,...., acht_j.

Ist das machbar? Wir würden mit diesen Variablen gerne schon jetzt in den Transition arbeiten :-)

**Comment by woisch** [comment]
Bitte diese neu generierten Zufallsvariablen dann auch auf die Seite mit den Hilfsvariablen aufnehmen, sodass wir die zum testen modifizieren können.

Danke und Grüße
Andreas

**Comment by andreaschu** [comment]
@lenamzimmer ja, das ist machbar.

**Comment by lenamzimmer** [comment]
Ach, super! Wir haben die Variabeln jetzt auch schon in die Transitions eingearbeitet! Cool!

**Comment by andreaschu** [comment]
Die Variablen sind eingebaut und können ab dem nächsten RollOut getestet werden. Sie werden auf der Index-Seite getriggert und werden auf der Seite hilfsvar angezeigt.

**Comment by woisch** [comment]
Liebes ZOFAR-Team,

fürs Testen brauchen wir noch ein paar Modifikationen der hilfsvar-Seite, da wir sonst immer wieder (unbeabsichtigt) unlogische Kombinationen von Preloads produzieren, die zu "Hängern" im Fragebogen führen:
Zum einen müssten die Variablen hs_tr, hs_nrw und hs_co auf den Wert 0 voreingestellt sein. Zum anderen hätten wir gerne alle Zufallsvariablen per Voreinstellung auf einen gültigen, aber zufälligen/gewürfelten Wert. Das betrifft alle Splitvariablen ab "zwei_a" bis "h_euro"

Das würde das Testen sehr viel einfacher machen, insbesondere für Tester*innen, die in der Transitionlogik nicht so drin sind und demnach nicht wissen (können), welche Variablen wie befüllt sein müssen, um einen plausiblen Fragebogendurchgang zu bekommen.

Ist das so möglich?

DANKE!
Andreas

**Comment by andreaschu** [comment]
@woisch die Trigger hatten bis jetzt nicht funktioniert. Sie werden jetzt gefüllt mit dem Verlassen der Index-Seite (siehe Screenshot). 
Damit sollte das Testen nun funktionieren. Die Preload-Variablen wie hs_tr, hs_nrw, hs_co würde ich nicht füllen. Da die Weiterleitungen auch funktionieren sollten, wenn die keinen Wert haben. Ich nehme an, das Hängenbleiben lag an den Zufallsvariablen.

![grafik](https://user-images.githubusercontent.com/30111489/115004223-df1e5980-9ea6-11eb-9517-bb53453420de.png)

**Comment by woisch** [comment]
Die drei Variablen hs_tr, hs_nrw, hs_co sind Preloads die immer den Wert 0 oder 1 haben werden. Daher haben wir andere Werte oder Missings auf diesen Variablen auch in den transitions nie mit definiert. Deswegen wäre die Voreinstellung auf 0 für uns zum Testen auch hilfreich, weil sonst unrealistische Testszenarien entstehen, die von den Transitions nicht erfasst werden.

**Comment by koopmann1896** [comment]
hilfsvariablen funktionieren, Issue wird geschlossen
