### ISSUE TITLE
A_40 aktualisiert

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#424]
In A_40 wurde ein zusätzlicher Frage Text mit vc Bedingung eingefügt. Bitte entsprechend umsetzen. f00814f07469d415f7cb731d4db660ae3eaed7c5

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ausgerollt.

**Comment by koopmann1896** [comment]
Läuft, ich schließe das Issue.
