### ISSUE TITLE
CSS Vignetten: Skala verschoben / lässt sich nicht exakt anklicken

### ISSUE THREAD

**Issue by christian-fr** [dzhw/SiD#427]
Bei den Vignetten (**pvig1_1, pvig1_2, ...**; **V1_1, V1_2, ...**) hatte ich die Größe der Antwortskala reduziert 
(siehe `additional.css`, Zeilen 4252-5015).

Bitte auch auf folgenden Pages: **KSM-fai06, KSM-ma04**

Nun passt die Zuordnung zur Position des Klicks nicht mehr zur ausgewählten Antwort.

**Comment by vdick** [comment]
ab nächsten Rollout(#425 ) verfügbar

**Comment by andreaschu** [comment]
sieht gut für mich aus. Ich mach hier mal zu.
