### ISSUE TITLE
Alternative Endseite für Promovierende (end_prom)

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#428]
Liebes ZOFAR-Team,

wir benötigen für eine Teilgruppe eine alternative Endseite. Diese soll "end_prom" heißen und folgenden Text beinhalten:

Herzlichen Dank, dass Sie sich die Zeit genommen haben, um an unserer Befragung teilzunehmen. Sie haben angegeben, dass Sie derzeit promovieren. Da wir mit unserer Befragung vor allem Studierende adressieren, richten sich alle weiteren Fragen lediglich an diese Gruppe.

Die Transitions haben wir bereits entsprechend angepasst für diese Teilgruppe, sodass die end_prom auch angesteuert wird.

Viele Grüße
Andreas

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab nächstem Rollout (#425) bzw. nach Anpassung der Transitions verfügbar.

**Comment by woisch** [comment]
getestet, kann zu
