### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by lenamzimmer** [dzhw/SiD#429]
Liebes Zofar-Team,
wie versprochen, untenstehend nun die Transitions - die wir nach bestem Wissen und Gewissen - erstellt haben. Wie abgesprochen findet ihr die Transitions der einzelnen Seiten in den jeweiligen "Modul-Dateien". Es kann sein, dass sich die Zuordnung einzelner Fragen zu Modulen geändert hat. D.h. dass Fragen in Github in einem anderen Modul stehen. Wenn Fragen aufkommen, dann sind @woisch , @koopmann1896 und ich aber die ganze Zeit ansprechbar!

Wie abgesprochen, werden wir die Transitions zur Dokumentation auch parallel in Github einpflegen!

- [x] [Transitionprüfung_A_2021.docx](https://github.com/dzhw/SiD/files/6303835/Transitionprufung_A_2021.docx)
- [x] [Transitionprüfung_B1_2021.docx](https://github.com/dzhw/SiD/files/6303837/Transitionprufung_B1_2021.docx)
- [x] [Transitionprüfung_B2_2021.docx](https://github.com/dzhw/SiD/files/6303838/Transitionprufung_B2_2021.docx)
- [x] [Transitionprüfung_C1_2021.docx](https://github.com/dzhw/SiD/files/6303839/Transitionprufung_C1_2021.docx)
- [x] [Transitionprüfung_C2_2021.docx](https://github.com/dzhw/SiD/files/6304744/Transitionprufung_C2_2021_v2.docx)
- [x] [Transitionprüfung_C3_2021.docx](https://github.com/dzhw/SiD/files/6303841/Transitionprufung_C3_2021.docx)
- [x] [Transitionprüfung_D1_2021.docx](https://github.com/dzhw/SiD/files/6303842/Transitionprufung_D1_2021.docx)
- [x] [Transitionprüfung_D2_2021.docx](https://github.com/dzhw/SiD/files/6303843/Transitionprufung_D2_2021.docx)
- [x] [Transitionprüfung_D3_2021.docx](https://github.com/dzhw/SiD/files/6303844/Transitionprufung_D3_2021.docx)
- [x] [Transitionprüfung_E1_2021.docx](https://github.com/dzhw/SiD/files/6303845/Transitionprufung_E1_2021.docx)
- [x] [Transitionprüfung_F1_2021.docx](https://github.com/dzhw/SiD/files/6303846/Transitionprufung_F1_2021.docx)
- [x] [Transitionprüfung_F2_2021.docx](https://github.com/dzhw/SiD/files/6303847/Transitionprufung_F2_2021.docx)
- [x] [Transitionprüfung_F3_2021.docx](https://github.com/dzhw/SiD/files/6303848/Transitionprufung_F3_2021.docx)
- [x] [Transitionprüfung_N_2021.docx](https://github.com/dzhw/SiD/files/6303849/Transitionprufung_N_2021.docx)

**Comment by koopmann1896** [comment]
Für folgende Module wurde die Transition von uns ebenfalls im Github eingepflegt:

- [ ] A 8714c5828a90cd831eaed78bba9a9617eef0c05d
- [ ] B1
- [ ] B2
- [ ] C1
- [ ] C2
- [ ] C3
- [ ] D1
- [ ] D2
- [ ] D3
- [ ] E1
- [ ] F1
- [ ] F2
- [ ] F3
- [ ] N

**Comment by SilinaSchirmer** [comment]
Diese Bedingung funktioniert so leider nicht...und ich verstehe sie auch nicht genug um sie selber zu fixen ;) 

**C2_1**

<zofar:transition target="C2_2" condition="zofar.asNumber(gbegrmob) ge 1 or condition="zofar.asNumber(gbegrseh) ge 1 or condition="zofar.asNumber(gbegrohr) ge 1 or condition="zofar.asNumber(gbegrspr) ge 1 or condition="zofar.asNumber(gbegrpsy) ge 1 or condition="zofar.asNumber(gbegrchron) ge 1 or condition="zofar.asNumber(gbegrtls) ge 1 or 
condition="zofar.asNumber(gbegrson) ge 1 or condition="zofar.asNumber(gbegrka) ge 1"/>

**Comment by SilinaSchirmer** [comment]
das gleiche Problem gilt für: 

**C2_5**
       <zofar:transition target="C2_7" condition="zofar.asNumber(beschwer)==2"/>
        <zofar:transition target="C2_7" condition="zofar.asNumber(gbegrmob) ge 1 or condition="zofar.asNumber(gbegrseh) ge 1 or condition="zofar.asNumber(gbegrohr) ge 1 or condition="zofar.asNumber(gbegrspr) ge 1 or condition="zofar.asNumber(gbegrpsy) ge 1 or condition="zofar.asNumber(gbegrchron) ge 1 or condition="zofar.asNumber(gbegrtls) ge 1 or 
condition="zofar.asNumber(gbegrson) ge 1 or condition="zofar.asNumber(gbegrka) ge 1"/>

**Comment by SilinaSchirmer** [comment]
... und: 

**C2_11a**

<zofar:transition target="C2_12" condition="zofar.asNumber(gbegrmob) ge 1 or condition="zofar.asNumber(gbegrseh) ge 1 or condition="zofar.asNumber(gbegrohr) ge 1 or condition="zofar.asNumber(gbegrspr) ge 1 or condition="zofar.asNumber(gbegrpsy) ge 1 or condition="zofar.asNumber(gbegrchron) ge 1 or condition="zofar.asNumber(gbegrtls) ge 1 or 
condition="zofar.asNumber(gbegrson) ge 1 or condition="zofar.asNumber(gbegrka) ge 1"/

**Comment by woisch** [comment]
das sieht nach copy paste Fehler aus und das condition ist immer wieder reingerutscht (Die Bedingung ist hier, dass mindestens eine der Variablen die Ausprägung größer/gleich 1 hat):

<zofar:transition target="C2_2" condition="(zofar.asNumber(gbegrmob) ge 1 or zofar.asNumber(gbegrseh) ge 1 or zofar.asNumber(gbegrohr) ge 1 or zofar.asNumber(gbegrspr) ge 1 or zofar.asNumber(gbegrpsy) ge 1 or zofar.asNumber(gbegrchron) ge 1 or zofar.asNumber(gbegrtls) ge 1 or
zofar.asNumber(gbegrson) ge 1 or "zofar.asNumber(gbegrka) ge 1)"/>

passt es so?

**Comment by SilinaSchirmer** [comment]
or "zofar.asNumber(gbegrka) ge 1)"

Die " vor zofar.asNumber(gbegrka) ge 1 sind noch zu viel. Ansonsten scheint es zu passen. 

Könntest du das bitte im Ü-Modus in dem Word-Dokument anpassen. Ich verliere sonst gleich komplett den Überblick.

**Comment by woisch** [comment]
das hätte ich jetzt eh vorgeschlagen. ich aktualisiere die Word direkt nochmal für alle Fragen!

**Comment by woisch** [comment]
Die Aktualisierung der Transitions in Modul C2 habe ich hier nochmal im Änderungsmodus festgehalten: 
[Transitionprüfung_C2_2021_v2.docx](https://github.com/dzhw/SiD/files/6304744/Transitionprufung_C2_2021_v2.docx)

**Comment by SilinaSchirmer** [comment]
Habe nun alle Transitions gecopied und gepasted. Folgendes ist mir dabei aufgefallen: 

**B1_3a** - war noch doppelt in unserer QML angelegt. Habe die gelöscht, die für mich weniger aktuell aussah. Schaut aber bitte noch einmal drüber sobald alles wieder ausgerollt ist. 

**C1_9** - ist in unserer QML angelegt (und auch im GitHub-Code) aber nicht in eurer Transition-Datei

**Generell** - für einige Seiten haben wir ja eine zusätzliche Responsive-Seite angelegt. Diese Transitions passen wir noch an.

**Comment by lenamzimmer** [comment]
Hallo Silina,

C1_9 kann aus QML gestrichen werden - die Frage ist rausgefallen.
B1_3a schauen wir uns an

Danke und lg

**Comment by woisch** [comment]
Die Transitions haben wir jetzt vollständig auch in den Github Code übertragen. Sollten sich in nächster Zeit noch Änderungen ergeben, pflegen wir das entsprechend ein, damit der Code immer auf Stand ist!

**Comment by andreaschu** [comment]
Es fehlt eine Bedingung für den Eurostudent-Fragebogen. Die erste Seite ist hier p01_01. Die Bedingung müsste auf der Index-Seite kommen, denke ich.

**Comment by koopmann1896** [comment]
@SilinaSchirmer Hier ist unsere Übersicht der Pfade durch den Fragebogen und in einem zweiten Tabellenblatt, für welche Splits in welche Module gegangen wird.

[SiD_Ablaufplan_2021_Transition_Testing.xlsx](https://github.com/dzhw/SiD/files/6310849/SiD_Ablaufplan_2021_Transition_Testing.xlsx)

**Comment by woisch** [comment]
@SilinaSchirmer: Hier die Änderung in den Transitions C2-Modul cbd4606768b3929643d0ff0ada64ec847c70abcd

**Comment by woisch** [comment]
> 
> 
> Es fehlt eine Bedingung für den Eurostudent-Fragebogen. Die erste Seite ist hier p01_01. Die Bedingung müsste auf der Index-Seite kommen, denke ich.

Die Transition zu Eurostudent kommt auf der index-Seite, ja. Wir liefern das schnellstmöglich noch nach!

**Comment by meyerja** [comment]
Liebes ZOFAR-Team, 

bitte beachtet auch die geänderten Transitions, die noch im Issue #409 hinterlegt sind. Um den Ablauf des gesamten Fragebogen testen zu können, sind diese ebenfalls notwendig.
Danke :)

**Comment by SilinaSchirmer** [comment]
Danke für dein Hinweis, die Änderungen sind ab nächstem Rollout #431 verfügbar.

**Comment by lenamzimmer** [comment]
> 
> 
> Es fehlt eine Bedingung für den Eurostudent-Fragebogen. Die erste Seite ist hier p01_01. Die Bedingung müsste auf der Index-Seite kommen, denke ich.

Liebe @andreaschu , stimmt, das ist uns durch gegangen. Ziel ist es, dass jeder 18. Befragte im Eurostudents-Strang landet. D.h. wir bräuchten vermutlich eine Zählvarible, die für alle Befragten gleich zu Beginn generiert wird. Und dann muss die Transition jedes 18. auf p01_01 erfolgen. Wollen wir uns über die technische Umsetzung noch einmal austauschen? Ich bin hier leider völlig überfragt. Wichtig ist, dass die Umleitung wirlich über die gesamte Feldphase erfolgt, da wir ansonsen ein völlig verzerrtes Sample in Eurostudent haben. Es tut mir total leid, dass ich das nicht früher bedacht habe :-(

**Comment by woisch** [comment]
@SilinaSchirmer: die Transitions auf den Seiten index und offer waren noch falsch: 3d8340019c770dacaf78ea853200d9f36ca14f1e 

wäre super, wenn ihr das noch zeitnah ändern könntet, da die Befragten momentan noch auf einer falschen Seite in die Befragung einsteigen

**Comment by andreaschu** [comment]
> @SilinaSchirmer: die Transitions auf den Seiten index und offer waren noch falsch: 3d83400
> 
> wäre super, wenn ihr das noch zeitnah ändern könntet, da die Befragten momentan noch auf einer falschen Seite in die Befragung einsteigen

Ab dem nächsten RollOut verfügbar.

**Comment by woisch** [comment]
@andreaschu: Leider ist mir in dem Zusammenhang noch was durchgerutsch: von der Seite hilfsvar wird momentan auch auf A_1 weitergeleitet. Das müsste auch korrigiert werden in den Transitions, dass man auf die A_18 kommt (wie von index und offer aus), oder zumindest von der hilfsvar auf die index gehen, von da aus stimmen die Transitions ja auch schon dann.

**Comment by andreaschu** [comment]
@woisch das ist wirklich nicht notwendig. Diese Seite spielt für die Befragung selbst keine Rolle und ist nur zum Testen da.
