### ISSUE TITLE
Kleine Anpassung E2-Modul (Master)

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#430]
Liebes ZOFAR-Team,

auf Rücksprache mit dem DZHW-Team habe ich eine kleine Änderung im Modul E2 (Master) vorgenommen. Bitte übernehmt diese in die QML. Danke :)

- [x]  07358c1

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab nächstem Rollout (#431) verfügbar.
