### ISSUE TITLE
D1_4 vc

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#435]
- [ ] bitte für D1_4 die vc noch gemäß GitHub-Code anpassen
(Show q4 AND q5 AND is2 AND ao3 AND ao4a AND ao4b if (vsbtyp10 = 1) )

Vielen Dank

**Comment by andreaschu** [comment]
@karbecke das ist so programmiert. Aber die Variable finde ich nicht. Kannst Du mir sagen, auf welcher Seite sie erhoben werden soll?

**Comment by andreaschu** [comment]
Fehler gefunden. Ist korrigiert und ab dem nächsten RollOut verfügbar.

**Comment by karbecke** [comment]
geprüft und geschlossen
