### ISSUE TITLE
Modul-D1: doppelte Variable

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#44]
Die Variable vausbzpka (weiß ich nicht) sind für die Fragen  [4](https://github.com/dzhw/SiD/blob/master/Modul-D1_Bildungsbiographie_individuelle%20Merkmale.md#4) und [5](https://github.com/dzhw/SiD/blob/master/Modul-D1_Bildungsbiographie_individuelle%20Merkmale.md#5) identisch. Bitte vergebt hier neue Namen.

Zudem fehlt bei dieser Variable in Frage 4 das Value.

**Comment by pbornkessel** [comment]
Sollte sich erledigt haben, da ich gestern/heute beide "weiß ich nicht"-Optionen im QML rausgenommen habe und das entsprechend auch im GitHub-Code angepasst habe https://github.com/dzhw/SiD/commit/b340e2dc6ded3ca88e96ae380e330dcba0753943

Okay?
