### ISSUE TITLE
D1_21 Layout Gesamtseite

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#440]
Bitte das Layout für die gesamte Seite nochmals optimieren

- [ ] kein Kasten um andere Sprachen und zwar
- [ ] Länge und Positionierung (linksbündig) der offenen Felder bitte überarbeiten
- [ ] Items linksbündig

Vielen Dank

**Comment by andreaschu** [comment]
> kein Kasten um andere Sprachen und zwar

@karbecke das ist in der PV so angegeben. Wir könnten es höchstens noch vor jedem offenen Feld schreiben.

**Comment by woisch** [comment]
@andreaschu Das Problem mit dem Kasten bei "andere und zwar" haben wir auf dem Schirm, und werden unseren Lösungsvorschlag nochmal mit einem neuen Issue präsentieren (das kommt dann mit den ersten Änderungen aus dem Testen heute).

@karbecke sind denn die anderen Punkte sonst gelöst? Dann könnte das Issue geschlossen werden

**Comment by karbecke** [comment]
@woisch: Items sind nun linksbündig, Das Thema mit dem Kasten können wir gern morgen nochmal besprechen

ansonsten: checked and Issue closed
