### ISSUE TITLE
Transition Bug A_1 -> end_prom

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#446]
Aufgrund eines Fehlers in unserer Transition laufen aktuell alle Befragten mit deutscher HZB direkt von A_1 auf die Endseite End_prom. Das ist natürlich denkbar schlecht und ich habe die Transition entsprechend angepasst.  26023aeaa99e4097f8acbebf016fe08530928d1a

Wenn möglich, übernehmt dies bitte schnellstmöglich in das QML und in den nächsten Rollout. Vielen Dank!!

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab nächstem Rollout (#445) verfügbar.

**Comment by woisch** [comment]
geprüft, weiterleitung funktioniert jetzt korrekt!
