### ISSUE TITLE
Änderung Transition Modul E4

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#448]
Liebes ZOFAR-Team,

beim Testen ist mir ein Fehler (meinerseits) bei einer Transition im E4 Modul aufgefallen. Hier wird man von der Seite KSM-fai28 direkt auf die Endseite weitergeleitet, anstatt auf die Seite A_56. Habe es im Code angepasst, bitte übertragt es in die QML. 
Danke :)

- [x]  4aebecd

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab nächstem Rollout (#445) verfügbar.
