### ISSUE TITLE
D3_8: Transition aktualisiert

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#450]
Hier fehlte eine Transition, die nur diejenigen auf die D3_8a leitet, die auf d3_8 angegeben haben von anderen Personen finanziert zu werden. Ich habe die nun entsprechend eingefügt. 74511582c8ec58f38c1e30ba1ee666a371f87ab0

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab dem nächsten Rollout (#445) verfügbar.

**Comment by koopmann1896** [comment]
funktioniert, Issue wird geschlossen.
