### ISSUE TITLE
Endseite

### ISSUE THREAD

**Issue by lenamzimmer** [dzhw/SiD#451]
Liebes Zofar-Team,

kann es sein, dass wir aktuell keine End-Seite haben? Werden die Daten jetzt gerade dann überhaupt gspeichert (also die Testdaten)?

**Comment by koopmann1896** [comment]
Also zumindest funktioniert die Transition nicht. Ich bekomme da den Apache Fehler mit der Message:  javax.el.PropertyNotFoundException: /A_57.xhtml @122,87 value="#{null.valueId}": Target Unreachable, identifier [null] resolved to null.

Die Seite end kann man allerdings eingeben und aufrufen., habe ich Lena falsch weitergegeben.

**Comment by andreaschu** [comment]
Fehler gefunden. Ab dem nächsten RollOut verfügbar.
Dieser Fehler gilt auch für die end_prom und wurde dort auch behoben.

**Comment by andreaschu** [comment]
> Werden die Daten jetzt gerade dann überhaupt gspeichert (also die Testdaten)?

@lenamzimmer die Daten werden mit Verlassen jeder Seite gespeichert. Insofern wurden auch vorher alle Daten gespeichert.

**Comment by woisch** [comment]
leider funktioniert die Weiterleitung von A_57 auf "end" immer noch nicht:

![grafik](https://user-images.githubusercontent.com/53002476/115200722-d02ce680-a0f4-11eb-9e4f-b0eca5115e26.png)

**Comment by SilinaSchirmer** [comment]
Das Problem ist behoben und die Weiterleitung funktioniert nun.

**Comment by woisch** [comment]
danke, klappt jetzt! ich schließe dann hier.
