### ISSUE TITLE
Update vcs bei Frage A_36

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#452]
Liebes ZOFAR Team,

auf Seite A_36 haben wir vergessen, vcs zu programmieren. Fragetexte und Dropdownmenü für Vater und Mutter sind hier ja auf einer Seite programmiert, müssen aber zum Teil ausgeblendet werden (je nach dem ob nur ein Elternteil oder beide im Ausland geboren sind).

bitte umsetzen: 8fc37110f56fc4a81ecf61ea4d3f4989a5a09806

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab nächstem Rollout (#445) verfügbar.

**Comment by woisch** [comment]
geprüft, 
die ao2 (An dieser Stelle können Sie das Geburtsland auch offen angeben:) ist allerdings jeweils (sowohl bei Vater als auch bei Mutter) immer noch zu sehen, wenn die vc eigentlich greifen sollte, es wird momentan nur das dropdown augeblendet.

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab nächstem Rollout (#454) verfügbar.

**Comment by woisch** [comment]
danke, funktioniert jetzt wie es soll! Ich schließe..
