### ISSUE TITLE
Layoutfehler Modul E4

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#453]
Liebes Zofar-Team,

beim Testen ist uns aufgefallen, dass es einen Layoutfehler auf den folgenden Seiten gibt:

- [x] KSM-fai16
- [x] KSM-fai17
- [x] KSM-fai18
- [x] KSM-fai19

Das Wort "Geisteswissenschaften" wird im Einleitungstext jeweils fett gedruckt angezeigt, sollte jedoch kursiv dargestellt sein. Auf den restlichen Seiten (fai20-fai25) werden die Fächernamen jeweils richtig angezeigt (beide kursiv). Im Code ist das nicht hinterlegt, so dass der Fehler an einer anderen Stelle entstanden sein muss. Könntet ihr dazu nochmal in der QML nachschauen? 
Vielen Dank :)

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab nächstem Rollout (#454) verfügbar.

**Comment by meyerja** [comment]
@SilinaSchirmer Fehler besteht auf der Seite KSM-fai19 leider immer noch...

**Comment by SilinaSchirmer** [comment]
@meyerja: Sollte jetzt behoben sein. 

Zur Info: Die Seiten KSM-fai17 - KSM-fai19 sind nicht mehr als richtige Seiten angelegt. Auf der KSM-fai16 werden die verschiedenen Fragetexte über entsprechende Sichtbarkeitsbedingungen angelegt.

**Comment by andreaschu** [comment]
@meyerja die Seitenbezeichnung habe ich in der PV entsprechend der Programmierung angepasst und noch einen Layout-Fehler gefunden und korrigiert, was beim nächsten RollOut zur getestet werden kann.

**Comment by meyerja** [comment]
@andreaschu @SilinaSchirmer Danke für die Anpassungen. Leider hat sich auf der Seite KSM-fai19 ein neuer Fehler eingeschlichen: Jetzt ist der komplette Text nach dem Wort Geisteswissenschaften kursiv gedruckt (siehe Screenshot).
![grafik](https://user-images.githubusercontent.com/56591452/115400452-97bb0480-a1e9-11eb-9e45-ba77aa62e036.png)

**Comment by andreaschu** [comment]
@annamarkn ja, das war der Layout-Fehler, den ich behoben hatte und der mit dem RollOut 025 korrigiert sein sollte.
