### ISSUE TITLE
EUROSTUDENT-Listen

### ISSUE THREAD

**Issue by HenSch90** [dzhw/SiD#459]
- [x] [Hochschulliste_für_p01_04b.xlsx](https://github.com/dzhw/SiD/files/6341415/Hochschulliste_fur_p01_04b.xlsx)
- [x] [Länderliste_für_p01_08, p04_25, p05_03, p06_04.xlsx](https://github.com/dzhw/SiD/files/6341416/Landerliste_fur_p01_08.p04_25.p05_03.p06_04.xlsx)
- [x] [Semesterliste_für_p02_05, p02_06.xlsx](https://github.com/dzhw/SiD/files/6341417/Semesterliste_fur_p02_05.p02_06.xlsx)

Liebes ZOFAR-Team,
hier sind die aktualisierten Listen für den EUROSTUDENT-Befragungsstrang!
Beste Grüße,
Hendrik

**Comment by andreaschu** [comment]
@HenSch90 ist das gewollt, dass die Hochschulliste nicht mit der von 
[Listenvergleich_Hochschullisten.xlsx](https://github.com/dzhw/SiD/files/6342608/Listenvergleich_Hochschullisten.xlsx)

**Comment by HenSch90** [comment]
Natürlich nicht - vielen Dank für den Hinweis. :)
Hier die Liste für **p01_04b** (identisch mit derjenigen für A_18):
[Hochschulliste_für_p01_04b.xlsx](https://github.com/dzhw/SiD/files/6343562/Hochschulliste_fur_p01_04b.xlsx)

**Comment by SilinaSchirmer** [comment]
@HenSch90: 

p02_05 und p02_06 sind aktuell also normale Single Choice Frage programmiert. Wenn ich das richtig verstehe sollten es aber Dropdowns sein, oder?

**Comment by SilinaSchirmer** [comment]
@HenSch90: Sollen für die p01_08, p04_25, p05_03, p06_04 die Infield-Texte "please select" bleiben? Zudem sind bisher Missing-Kategorien vorgesehen. Sollen die gelöscht werden?

**Comment by HenSch90** [comment]
> @HenSch90:
> 
> p02_05 und p02_06 sind aktuell also normale Single Choice Frage programmiert. Wenn ich das richtig verstehe sollten es aber Dropdowns sein, oder?

@SilinaSchirmer: Genau, p02_05 und p02_06 sollen Dropdowns sein.

**Comment by HenSch90** [comment]
> @HenSch90: Sollen für die p01_08, p04_25, p05_03, p06_04 die Infield-Texte "please select" bleiben? Zudem sind bisher Missing-Kategorien vorgesehen. Sollen die gelöscht werden?
> 
> Habe die Liste zudem alphabetisch sortiert. Ist das richtig so?

@SilinaSchirmer : Kannst du bitte bei p01_08, p04_25, p05_03, p06_04 die Infield-Texte „please select“ durch „Bitte auswählen“ ersetzen und die Missing-Kategorien entfernen? Und lieben Dank für die alphabetische Sortierung! :)

**Comment by SilinaSchirmer** [comment]
@HenSch90: 

- entsprechend der Fragen A_20/A_20b und D1_11/D1_11b habe ich für die Seite p01_04b2 angelegt, da die Abfrage der Hochschule stufenweise erfolgt. Die Variable V1_4_2 enthält also eine Info über die V1_4_22 (habe ich neu angelegt) Hochschule und die enthält die Info über den Standort, falls die Hochschule der V1_4_2 einen Standort hat. Wenn du noch Fragen dazu hast, können wir gerne kurz skypen. 
- Die Infiledtexte der Dropdown sehen nun wie folgt aus: Hochschulliste = Hochschul-Standort; Länderliste = Bitte auswählen; Semsterliste = Semester/Fachsemester

**Comment by SilinaSchirmer** [comment]
Änderungen wurden umgesetzt und sind ausgerollt.

**Comment by SilinaSchirmer** [comment]
@andreaschu @christian-fr: Die Einblendung der Hochschulen auf p01_04b funktioniert leider nicht. Erkenne gerade aber keinen Fehler. Kann jemand von euch da mal drauf schauen?
