### ISSUE TITLE
Modul-D1: Fehlende Dropdownliste - Frage 13

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#46]
Für die Frage [13](https://github.com/dzhw/SiD/blob/master/Modul-D1_Bildungsbiographie_individuelle%20Merkmale.md#13) fehlt eine vollständige Liste der Dropdown-Elemente sowie deren Values.

**Comment by pbornkessel** [comment]
@SilinaKowalewski 
Im Prinzip soll die Liste vom Sommersemester 2020 bis zum Sommersemester einfach fortgeführt werden:

Sommersemester 2020 
Wintersemester 2020/21 
Sommersemester 2021 
Wintersemester 2021/22 
Sommersemester 2022 
Wintersemester 2022/23 
Sommersemester 2023 
Wintersemester 2023/24 
Sommersemester 2024 
Wintersemester 2024/25 
Sommersemester 2025 
Wintersemester 2025/26 
Sommersemester 2026 
Wintersemester 2026/27 
Sommersemester 2027 
Wintersemester 2027/28 
Sommersemester 2028 
Wintersemester 2028/29 
Sommersemester 2029 
Wintersemester 2029/30 
Sommersemester 2030

Reicht das so, so dass ich das issue schließen kann?

**Comment by SilinaKowalewski** [comment]
Die neue Dropdownliste wurde umgesetzt. Kann später geprüft und das Issue geschlossen werden.
