### ISSUE TITLE
EUROSTUDENT-Textänderungen

### ISSUE THREAD

**Issue by HenSch90** [dzhw/SiD#460]
Liebes ZOFAR-Team,
im EUROSTUDENT-Befragungsstrang müssten folgende Fragen und Items hinsichtlich ihrer Formulierung geändert werden:

- p01_02 (p01_02.b.sc.q_0) – Fragetext ersetzen durch „**Abgesehen von der besonderen Studiensituation durch die Corona-Pandemie: Handelt es sich bei Ihrem derzeitigen Studium formal um ein Fernstudium?**“ (Englisch: „**Apart from the special study situation caused by the Corona pandemic: Is your current main study programme formally defined as a distance learning programme?**”)
- p01_07 (p01_07.b.qo.q_0) – Fragetext ersetzen durch „**Bitte geben Sie ihr (Haupt-)Studienfach an.**“ (Englisch: „**What is your current (main) study programme?**“), mit Ergänzung um die Ausfüllanweisung (kursiv) „_Bitte schreiben Sie das Studienfach aus (z. B. Wirtschaftsinformatik, Soziale Arbeit)._“ (Englisch: „_Please write the name of your subject (e.g. business informatics, social work)._”)
- p03_03 (p03_03.b.msc.q_0) – Fragetext ersetzen durch „**In welchem Maße stimmen Sie folgenden Aussagen zu Ihrem derzeitigen Studiengang im Allgemeinen zu?**“ (Englisch: „**Generally, to what extent do you agree with the following statements with regard to your current (main) study programme?**”)
- p03_07 (p03_07.b.msc.rd.i2.qi2_0) – Item „Lerninfrastruktur (z.B. Bibliothek, Computerräume, Arbeitsplätze)“ ersetzen durch „**Lerninfrastruktur im Allgemeinen (z.B. Bibliothek, Computerräume, Arbeitsplätze)**“ (Englisch: „**General provision of learning facilities (e.g. library, computer centre, work places)**“)
- p04_04 (p04_04.b.qo.q_0) – Fragetext ersetzen durch „**Wieviel Zeit benötigen Sie im Allgemeinen durchschnittlich für den einfachen Weg von Ihrer Wohnung zur Hochschule?**“ (Englisch: „**How much time does it generally take you to get from your home to your higher education institution?**”)
- p05_01 (p05_01.b.mc.rd.ao1.label) – Item „Auslandsstudium/Auslandssemester during a study programme in the Netherlands (e.g. semester abroad)” ersetzen durch „**Auslandsstudium/Auslandssemester**“ (Englisch: „**Temporary study period abroad**”)

Vielen Dank und liebe Grüße,
Hendrik

**Comment by andreaschu** [comment]
@HenSch90 soweit ich mich erinnern kann, hatten wir abgesprochen, dass Du die Änderungen vornimmst. Deswegen hatten wir den QML-Code hochgeladen ([siehe hier](https://github.com/dzhw/SiD/blob/master/questionnaire20.xml)).

**Comment by HenSch90** [comment]
Die Änderungen sind umgesetzt.

Gruß,
Hendrik

**Comment by SilinaSchirmer** [comment]
Die Änderungen sind umgesetzt und ausgerollt.
