### ISSUE TITLE
Transition C2_8 auf C2_10

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#461]
Transition wurde korrigiert, hier stand im Pfad zu C2_10 "and" statt "or", sodass zu wenig weitergeleitet wurden.
Bitte entsprechend umsetzen: 81bc72712ebd4c7fa0c45645d0b02ebac0c890ca

**Comment by SilinaSchirmer** [comment]
Änderung wurde umgesetzt und ist ab dem nächsten Rollout (#462) verfügbar.

**Comment by koopmann1896** [comment]
läuft :) -> geschlossen
