### ISSUE TITLE
Updates Fragebogen Teil 1

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#463]
Bitte noch folgende Anpassungen vornehmen:

- [x] E1_6: vc anpassen: 5fa548d 
- [x] E1_7: it 13 hat 5 statt 4 Skalenpunkte
- [ ] C2_11a: Hier blenden wir in der Desktop-Ansicht bei it1 und it2 die ao "nicht vorhanden" aus (das ist der mv). Bitte für die responsive Ansicht auch umsetzen, sort sind sie im Karussel zu sehen

**Comment by SilinaSchirmer** [comment]
Die inhaltlichen Änderungen wurden umgesetzt und sind verfügbar.

**Comment by woisch** [comment]
@SilinaSchirmer schaue ich mir nach dem Rollout an!
@vdick: Den Punkt zu C2_11a habe ich ins passende Issue mit Änderungen am responsiven Design verschoben (#470), kann hier also ignoriert werden. das ging hier im Issue leider durcheinander!

**Comment by woisch** [comment]
geprüft, kann geschlossen werden
