### ISSUE TITLE
Updates Fragebogen Teil 2

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#464]
Bitte noch folgende Änderungen umsetzen:

- [x] A_17: vcs geändert: https://github.com/dzhw/SiD/commit/d66c2164d0451d134fc525949eb7452fb08c0535 https://github.com/dzhw/SiD/commit/c7dc83eca6b1d341fe46c7690a2f4bdf10654d51 (@andreaschu Über den Punkt, dass die hs_tr=0 Fälle alle Einblendungen sehen, hattet ihr heute mit Lena/Jonas gesprochen, eventuell ist es auch schon korrekt umgesetzt inzwischen, bitte aber nochmal prüfen!)
- [x] A_38b: vc5 greift aktuell nicht, das it5 wird momentan immer auf der Seite angezeigt
- [x] A_53: ao5 bitte nur einen Punkt am Ende, bei ao3 einen Punkt ergänzen: https://github.com/dzhw/SiD/commit/1ec4c80bab9e16ddd961209469138f32d7fd0432
- [x] B2_8a2: vc angepasst: 0bee0e09ba18618c339cac7e3a8b189704353197
- [x] D2_17: als number umsetzen wie in PV, hier können noch Buchstaben angegeben werden
- [ ] A_12b, C2_3, D2_19. C2_5: hier kann noch ein Komma oder Buchstabe zusammen mit einer Zahl eingegeben werden (z. B. "2,"). kann man das unterbinden (und jeweils die kh einblenden)?

**Comment by SilinaSchirmer** [comment]
Die abgehakten Änderungen wurden umgesetzt und sind ab dem nächsten Rollout (#462) verfügbar.

**Comment by SilinaSchirmer** [comment]
@vdick @dzhwmeisner @christian-fr: Könnte jemand von euch den folgenden Punkt übernehmen, falls ihr etwas Luft habt? 

> * [ ]  A_12b, C2_3, D2_19. C2_5: hier kann noch ein Komma oder Buchstabe zusammen mit einer Zahl eingegeben werden (z. B. "2,"). kann man das unterbinden (und jeweils die kh einblenden)?

**Comment by woisch** [comment]
geprüft, 
@koopmann1896: das zu A_53 kannst du direkt ändern

Dann ist nur noch der letzte Punkt offen, das setze ich aber auf Prio3

**Comment by koopmann1896** [comment]
> geprüft,
> @koopmann1896: das zu A_53 kannst du direkt ändern
> 
> Dann ist nur noch der letzte Punkt offen, das setze ich aber auf Prio3

ab nächstem rollout verfügbar

**Comment by woisch** [comment]
> 
> 
> > geprüft,
> > @koopmann1896: das zu A_53 kannst du direkt ändern
> > Dann ist nur noch der letzte Punkt offen, das setze ich aber auf Prio3
> 
> ab nächstem rollout verfügbar

geprüft, passt jetzt.
Ich lasse aber noch offen, wegen dem einen offenen Punkt

**Comment by koopmann1896** [comment]
> * [ ]  A_12b, C2_3, D2_19. C2_5: hier kann noch ein Komma oder Buchstabe zusammen mit einer Zahl eingegeben werden (z. B. "2,"). kann man das unterbinden (und jeweils die kh einblenden)?

Auch hier ist nur noch ein Punkt offen, bevor ich schließen kann. Leider kann ich den nicht umsetzen @andreaschu @SilinaSchirmer .

**Comment by christian-fr** [comment]
> 
> 
> > * [ ]   A_12b, C2_3, D2_19. C2_5: hier kann noch ein Komma >>> **oder Buchstabe** <<< zusammen mit einer Zahl eingegeben werden (z. B. "2,"). kann man das unterbinden (und jeweils die kh einblenden)?
> 
> Auch hier ist nur noch ein Punkt offen, bevor ich schließen kann. Leider kann ich den nicht umsetzen @andreaschu @SilinaSchirmer .

@koopmann1896 
Kleine Korrektur des Obenstehenden: in der aktuellen Version auf dem Presentation-Server können auf all diesen pages **keine Buchstaben** eingegeben werden, dies ist schon umgesetzt. 

Falls doch, wird ein Korrekturhinweis angezeigt:
> ![grafik](https://user-images.githubusercontent.com/42959832/116050680-0da2ee00-a678-11eb-80d8-5c2212aa9057.png)

Die Eingabe von Kommas oder Punkten kann unterbunden werden, dies geschieht jedoch auf einer anderen Ebene der Befragung: nicht in der QML, sondern per JavaScript. 

Bei einer solchen Eingabebeschränkung gilt es jedoch zu bedenken, dass sie zum einen nur bei aktiviertem JavaScript funktioniert (ist in der Regel der Fall, jedoch nicht immer). Und dass sie zum anderen dann trotz Tastendruck kein Zeichen (`,.:;`) in das Textfeld schreibt. Dies kann eine mögliche Fehlerquelle darstellen, wenn Befragte ihre eingetippten Zahlen (in die sie bspw. Kommas gesetzt haben) nicht noch einmal prüfen.

@lenamzimmer @karbecke
Soll eine solche Eingabebeschränkung für die vier pages  **A_12b, C2_3, D2_19, C2_5** auf die o.g. Art und Weise umgesetzt werden?

**Comment by mcehrhardt** [comment]
Lieber @christian-fr ,

entschuldige die späte Rückmeldung. Ich habe mir die Fragen nochmal inhaltlich angeguckt und mit Ausnahme von D2_19 wäre es schön eine solche Eingabebeschränkung zu haben. Allerdings sollte dies nur noch umgesetzt werden, wenn es kein Zeitfresser oder großer technischer Aufwand ist. Da haben andere Dinge Priorität.

Liebe Grüße,
Marie

**Comment by andreaschu** [comment]
@mcehrhardt ich würde auch sagen, dass wir haben andere Prioritäten. Das wird nicht mehr angefasst.

**Comment by woisch** [comment]
Das ist ok, wir schließen dann hier und konzentrieren uns auf anderes!
