### ISSUE TITLE
NRW-Sample Zusatzfilter

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#465]
Liebes ZOFAR-Team,

für das Sample der im dritten und vierten Fachsemester an NRW-Hochschulen Studierenden benötigen wir zusätzliche Transition und um diese setzen zu können eine zusätzliche Variable **'nrw_sample'**. Diese Variable soll auf der Seite N_2 generiert werden, welche nur von den Studierenden gesehen wird, die auf dem PRELOADhs_nrw eine 1 haben, somit also nur Studierende aus NRW Hochschulen, im dritten oder vierten Fachsemester (ssemfs==3 or ssemfs ==4; in der Transition von A_56 angepasst). Für alle Befragten in diesem Pfad soll die neue Variable den Wert 1 annehmen. Mithilfe dieser Variable wird dann vom N_2 Pfad zurück auf Module gelenkt, die aufgrund der Splitführung noch nicht von diesem NRW-Sample gesehen wurden, aber für dieses besondere Sample von großer Bedeutung sind.

- [x] Variable nrw_sample einfügen 
Beispiel: nrw_sample ==1 if (semfs==3 or ssemfs ==4) and PRELOADhs_nrw ==1 (was an der Stelle der Fall ist)

Darüber hinaus werden die Transitions in den Modulen entsprechend angepasst, um die Befragten noch einmal "zurück" zu leiten.

**A_Modul**https://github.com/dzhw/SiD/commit/c515eb8ed6e1649f5c7b295c4bc428d3bf5b13be
- [x] A_56 

**N_Modul** https://github.com/dzhw/SiD/commit/08a5a7cf662c19709dac5119986a357344acd650
- [x] N_7
- [x] N_8
- [x] N_12

**D1_Modul**https://github.com/dzhw/SiD/commit/8d981c9d6919a4198ab41b31776f07bb998361d3 
- [x] D1_7
- [x] D1_20 _hier musste die Transition noch einmal erweitert werden:_ https://github.com/dzhw/SiD/commit/d574d419bf386abd66b648db76480a91056e02e5

**D2_Modul** https://github.com/dzhw/SiD/commit/abe7d2befae7002f1236854d5234448a8542e073
- [x] D2_2
- [x] D2_3
- [x] D2_4
- [x] D2_21
- [x] D2_17

**D3_Modul** https://github.com/dzhw/SiD/commit/0f7bea6b855d34b472fa82f700d19c4e8f0ce879

- [x] D3_11
- [x] D3_22

**E2_Modul** https://github.com/dzhw/SiD/commit/c3f45a0ee62be741d2ea87fd8150474d7f576eb1
- [x] KSM-ma05 _ich habe hier den qmlcode über der "Zofar_Sprache" eingefügt, die Transition soll bitte über den bestehenden als erste TRansition eingefügt werden._

**Comment by SilinaSchirmer** [comment]
Änderungen wurden umgesetzt und sind ab nächstem Rollout (#462) verfügbar. 

@andreaschu: Lass uns deswegen bitte mal Slacken. Ich bin mir nicht ganz sicher ob ich alles richtig eingebaut habe :octocat:

**Comment by SilinaSchirmer** [comment]
@koopmann1896

**Ein kleiner Hinweis:** Beim Kopieren und Einfügen hat sich ein mini Fehler eingeschlichen. Die Endung der jeweils ersten Transition ist in deinen Änderungen immer ein anderes Anführungszeichen als es sein sollte. Eclipse besteht aber darauf, dass es so ein "gerades Anführungszeichen" ist. 

condition="zofar.asNumber(nrw_sample)==**1”**

**Comment by koopmann1896** [comment]
> @koopmann1896
> 
> **Ein kleiner Hinweis:** Beim Kopieren und Einfügen hat sich ein mini Fehler eingeschlichen. Die Endung der jeweils ersten Transition ist in deinen Änderungen immer ein anderes Anführungszeichen als es sein sollte. Eclipse besteht aber darauf, dass es so ein "gerades Anführungszeichen" ist.
> 
> condition="zofar.asNumber(nrw_sample)==**1”**

Oh, vielen Dank für den Hinweis und für das Umsetzen :)

**Comment by koopmann1896** [comment]
Liebes Zofar_Team, 
aktuell funktioniert zwar die Umleitung in die D_Module, die Variable wird aber wohl noch nicht gefüllt, zumindest bleibt man in den Modulen hängen. Ihr habt hier ja aber auch eigentlich noch nicht auf testing gestellt. Ich bin einfach beim Testen umgeleitet worden.

**Comment by koopmann1896** [comment]
Liebes Zofar-Team,
da diese Transitionpfade gestern komplett neu an mich heran getragen wurden, habe ich mit der KSM-ma05 leider eine falsche Variable in diese Transitions eingebaut. Ich habe dies korrigiert und entsprechend comitted. Bitte setzt dies zusammen mit der Variable in N_2 entsprechend um. Entschuldigt das Durcheinander.

- [ ] KSM-ma05 Transition entfernt https://github.com/dzhw/SiD/commit/cfeddd678d67f429072102ea36996d5a1c95643c
- [ ] KSM-anf08 die falsch eingebaute Transition wurde hier eingefügt 53e5acb28b2c1fd06ea77198c590c84897b122ac
- [ ] D1_20 Das Ziel wurde aktualisiert ee54850c50180324c5e89f5aa37abef2e3124ea3
- [ ] D2_17 Das Ziel wurde aktualisiert 33d10d294266c7e029634cd687df09a384cfe804
- [ ] D3_22 Das Ziel wurde aktualisiert cd7c9c81ec09d507b867cc391b04156a9f3fd977

Wenn die Variable läuft müsste der Pfad somit funktionieren.

**Comment by andreaschu** [comment]
die Änderungen an den transitions sind eingebaut und ab dem nächsten RollOut testbar.

**Comment by koopmann1896** [comment]
Guten Morgen und vielen Dank fürs Umsetzen. 
Die Variable scheint sich in N2 nicht selbstständig zu füllen. Ich komme an den entsprechenden Fragen wie beispielsweise D1_7 nur weiter wenn ich auf der hilfsvar Seite nrw_sample =1 setze.
Ab D1_20 bekomme ich dann eine Fehlermeldung, die auf falsche Zeichen hinsetzt und ich glaube das sind wieder die falschen ". 
Ich hoffe, dass das der Fehler ist, könnt ihr da schauen, ob meine Änderungen der " den Fehler lösen, bzw. ob euch bei bspw. D1_20 ein anderer Fehler in der neuen NRW Transition auffällt?
Hier meine Commits für die "  : https://github.com/dzhw/SiD/commit/d1d6c4ad278988f057992c5e27da7d2f495a091d
https://github.com/dzhw/SiD/commit/b2e8e3139b7a823d91e84c5d9ceb9fca4e3710d6
https://github.com/dzhw/SiD/commit/036da0e090d09d29a837b99f435d89d461fd3f84
https://github.com/dzhw/SiD/commit/abf3622f2b150161e2d994302df179e17b3808e2

Vielen Dank für die Umsetzung :)

**Comment by koopmann1896** [comment]
@andreaschu @SilinaSchirmer ich habe noch einmal geprüft, der Transition Fehler ist nur von D1_20 und die Fehlermeldung lautet: _Message Encountered " ")" ") "" at line 1, column 349_. 
Ich kann mir leider ja die qml nicht angucken und habe in meinem Github Code keinen Fehler außer den genannten mit den Anführungszeichen gefunden. Ich hoffe wir finden den Fehler zusammen schnell :)

**Comment by andreaschu** [comment]
@koopmann1896 bei D1v20 gab es einen Kammerfehler. Den habe ich korrigiert.
Bei N_2 war die Bedingung falsch (ssemfs==4 fehlte). Unabhängig davon wird die Variable nur verändert, wenn `(PRELOADhs_nrw)==1`.
Die Änderungen sind ab dem nächsten RollOut verfügbar.

**Comment by koopmann1896** [comment]
Vielen Dank @andreaschu,

wie ich dir bereits in einer Mail beschrieben habe, gibt es leider noch eine Änderung, da ich durch die neue Zielvariable KSM-anf08 ja auch die entsprechenden Bedingungen für dieses Modul in der Transition der drei Variablen anpassen muss, und das leider übersehen habe. Letztendlich kommen zu sabsan==1 nur noch weiter sabsan hinzu. 
https://github.com/dzhw/SiD/commit/a6742af870f1b380a576063ba070323758003d00
https://github.com/dzhw/SiD/commit/5b854fc474b54dbc5ffed971c64b5fbfd2b5fac3
https://github.com/dzhw/SiD/commit/87598e25139c28a7960ef7eec1b54b6724383d77
Noch einmal vielen vielen Dank für diese schnelle und gute Umsetzung.

**Comment by koopmann1896** [comment]
läuft, wird geschlossen

**Comment by koopmann1896** [comment]
NRW_Sample Variable aufgrund einer ungewollten Schleife überarbeitet-> ab dem nächsten Rollout verfügbar

**Comment by koopmann1896** [comment]
Transition D1_20, D2_17, D3_22  auf Githubstand gebracht->  ab nächstem Rollout verfügbar

**Comment by koopmann1896** [comment]
läuft und wird geschlossen
