### ISSUE TITLE
D3_8_r - Seite wird nicht angezeigt

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#466]
Liebes ZOFAR-Team,
die responsive Seite von D3_8, also die D3_8_r ist aktuell **leer** (s.u.). 

Bitte vervollständigt diese responsive Seite zeitnah. 
Vielen Dank!

![D3_8_r](https://user-images.githubusercontent.com/46674616/115504723-a8668b80-a278-11eb-961b-0fe651586f06.PNG)

**Comment by SilinaSchirmer** [comment]
Die Frage, genau so wie die D3_6, sind auch noch nicht final programmiert. Wir sind da aber dran.  

https://github.com/dzhw/SiD/issues/405

**Comment by andreaschu** [comment]
Ich schließe hier mal. Wenn das Issue #405 fertig ist, setzen wir das auf testing.
