### ISSUE TITLE
Liste Zusatzseiten responsives Design

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#467]
Liebes ZOFAR-Team,

bitte listet hier die responsiven Zusatzseiten auf, damit wir a) die transitions für und b) das responsive Design dieser Seiten nochmals detailliert testen können. Vielen Dank!

- B1_4a_r
- B1_6_r
- D3_8_r
- D3_6_r
- D1_19_r
- F1_15_r
- F1_2_r1
- F1_2_r2

**Comment by SilinaSchirmer** [comment]
Ich habe nun alle zusätzlichen Seiten für eine responsive Ansicht angelegt und oben in der Liste nachgetragen. Einige Transitions habe ich auch schon angepasst, habe aber natürlich keinen Überblick an welchen Stellen das noch notwendig wird. 

Die Bedingungen sehen zum Beispiel so aus: 
<zofar:transition target="D3_8" condition="width.value ge 768"/>
<zofar:transition target="D3_8_r" condition="width.value lt 768"/>

**Comment by karbecke** [comment]
> 
> 
> Ich habe nun alle zusätzlichen Seiten für eine responsive Ansicht angelegt und oben in der Liste nachgetragen. Einige Transitions habe ich auch schon angepasst, habe aber natürlich keinen Überblick an welchen Stellen das noch notwendig wird.
> 
> Die Bedingungen sehen zum Beispiel so aus:
> <zofar:transition target="D3_8" condition="width.value ge 768"/>
> <zofar:transition target="D3_8_r" condition="width.value lt 768"/>

@koopmann1896 : Kannst Du bitte die tr`s für die responsiven Seiten Dir anschauen?

**Comment by koopmann1896** [comment]
Die Transition sind geprüft, allerdings ist dort manchmal width.value manchmal zofar.asNumber(width) und manchmal beides eingetragen. Es scheint keinen Unterschied zu machen, Die Transition läuft laut presenter. Aber ein kurzer Kommentar ob das so richtig ist wäre gut @SilinaSchirmer @andreaschu

**Comment by koopmann1896** [comment]
Läuft, wird geschlossen
