### ISSUE TITLE
EUROSTUDENT-Zusatzfragen

### ISSUE THREAD

**Issue by HenSch90** [dzhw/SiD#471]
Liebes ZOFAR-Team,

der EUROSTUDENT-Befragungsstrang müsste um zwei zusätzliche Fragen erweitert werden:

- Zwischen p04_10 und p04_11 _an alle Befragten des EUROSTUDENT-Strangs_ gerichtet bitte die Frage „Hat sich die Corona-Pandemie auf Ihre Erwerbstätigkeit ausgewirkt?“ hinzufügen; genau wie **CO_9** aus der Corona-Befragung ([https://github.com/dzhw/SiD/blob/master/sid-sonderbefragung.md](https://github.com/dzhw/SiD/blob/master/sid-sonderbefragung.md)). 
- Nach p07_02 _an alle Befragten des EUROSTUDENT-Strangs_ gerichtet bitte die Frage „Halten Sie eine Verlängerung Ihres Studiums aufgrund der Corona-Pandemie für wahrscheinlich?“ (1=„nein, sehr unwahrscheinlich“ bis 5=„ja, sehr wahrscheinlich“) hinzufügen; genau wie **CO_1** aus der Corona-Befragung ([https://github.com/dzhw/SiD/blob/master/sid-sonderbefragung.md](https://github.com/dzhw/SiD/blob/master/sid-sonderbefragung.md)). 

Vielen Dank und beste Grüße,
Hendrik

**Comment by andreaschu** [comment]
https://media.giphy.com/media/Tit8CFFaFncoAgYFc4/giphy.gif

**Comment by SilinaSchirmer** [comment]
Die Fragen sind eingebaut und sind ab nächstem Rollout (#477) verfügbar
