### ISSUE TITLE
Transitiontest: Änderungen Transition und Einblendbedingungen

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#472]
Liebes ZOFAR-Team, im Folgenden liste ich euch Änderungen bezüglich Transition und Einblendbedingungen auf:

Transition:
- [x] D3_6 d60dc73148bb51bc866b20b7ff6bcd1bb564da61
- [x] C2_11 https://github.com/dzhw/SiD/commit/53b1b2d385d64ee55c98e29f955c0675e2e09d4a 

Einblendbedingung
- [x] C1_6 it2 soll nur eingeblendet werden, wenn (ehe-)Partner angegeben ist oder auf A_11 die ka angegeben wurde. https://github.com/dzhw/SiD/commit/f8bcc0c7604ded56f7b17a00b64480aa46ee4e3a Bitte auch Bedingung dass it2 angezeigt wird für den missing Fall einfügen: muss hier für jedes item (!demofamehe.value and !demofamka.value etc.) gemacht werden oder geht das über die Stammvariable? bitte das machbare umsetzen
- [x] C2_1 https://github.com/dzhw/SiD/commit/606cb55655440c2faf982563721a58f4a361e62e q3 und vc12 neu eingefügt
- [x] D1_4 https://github.com/dzhw/SiD/commit/a3e1ab4b1424a30d0941a27a904b4de48050d6a2 vc erweitert
- [x] D3_2 vc bitte auf aktuellen githubd Stand bringen https://github.com/dzhw/SiD/commit/0ad9df3b579f36c262274f89309f60cfbba441e2 vor diesem commit erfolgten zwei andere, somit bitte den gesamten aktuellsten Stand übernehmen
- [x] D3_1 247f774 bitte die vc entfernen
- [x] D3_6 bfed0a5  vc für gartka hinzugefügt
- [x] D3_8 2b4b172 ebenfalls vcs aktualisiert
- [x] E1_2 5d0002a ebenfalls vcs aktualisiert
- [x] F2_6 5d51f52790fb77ba4b8000fba4bb525d2eebfd42 vc2 neu eingefügt

**Comment by koopmann1896** [comment]
Alle abgehakten Fälle sind mit dem nächsten Rollout #477 verfügbar. @andreaschu zwei sind noch übrig.

**Comment by andreaschu** [comment]
vc auf D3_2 (hoffentlich) korrigiert. Ist auch ab dem RollOut #477 verfügbar.

**Comment by koopmann1896** [comment]
> vc auf D3_2 (hoffentlich) korrigiert. Ist auch ab dem RollOut #477 verfügbar.

D3_2 vc für missing fall eingefügt -> ab nächstem Rollout verfügbar

**Comment by andreaschu** [comment]
vc für C1_6 aktualisiert. Auch ab rollout #484 verfügbar.

**Comment by koopmann1896** [comment]
vc C1_6 funktioniert leider nicht, ich weiß aber auch nicht warum.

**Comment by andreaschu** [comment]
@koopmann1896 ich fürchte ich hatte es vergessen zu comitten, bevor ich den RollOut gestartet habe. Ich verlinke noch mal im nächsten RollOut-Issue.

**Comment by koopmann1896** [comment]
habemus visible, läuft und wird geschlossen :)
