### ISSUE TITLE
responsive Seiten oder responsive Seitenversionen

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#473]
Liebes ZOFAR-Team,

für folgende Seiten benötigen wir noch responsive Seitenversionen oder neu angelegte responsive Seiten ("_r"):

- [x] D1_19 | hier müsste eine responsive Seite mit  vertikalen Skalen im Karussel angelegt werden
- [ ] D2_21 | Die Karussells auf eigene Seiten programmieren
- [x] D3_6 | Seite muss responsiv wahrscheinlich neu angelegt werden
- [x] D3_8_r | Seite muss noch gefüllt werden
- [ ] E1_6 | aufgrund mehrerer Itemkarussells sinnvoll diese auf extra responsive   Seiten legen  --> je Itemkarussell responsive Seite
- [ ] E1_7 | aufgrund mehrerer Itemkarussells sinnvoll diese auf extra responsive Seiten legen --> je Itemkarussell responsive Seite
- [x] F1_15 | responsive Seite mit vertikalen Skalen
- [x] F1_2 | responsiv sollten 2 Seiten programmiert werden (s. SiD-Corona-Befragung) --> 1 Seite "für Auslandsaufenthalt", 1 Seite "gegen Auslandsaufenthalt"

Vielen Dank!

**Comment by andreaschu** [comment]
@karbecke wenn Ihr das Projekt nicht gefährden wollt, solltet Ihr euch jetzt auf zentrale Funktionalitäten konzentrieren.
Wir können jetzt nicht anfangen für mobile Geräte neue Seiten zu bauen. Dafür gab es genug Zeit und wir haben Euch für diesen Test die Screenshots erstellt. Jetzt sollte das nur noch passieren, wo die Funktionalität nicht gewährleistet ist.

Ich denke, dass Filterfehler hier eher Prio1 entsprechen, oder? Vielleicht wäre es sinnvoll, wenn nur @lenamzimmer die Prioritäten vergibt.

**Comment by lenamzimmer** [comment]
Liebe Andrea,

es tut uns leid, dass wir euch da gerade etwas zuspamen. @karbecke und ich hatten uns tatsächlich abgesprochen und dachten, dass es sinnvoll ist - weil sich die Programmierarbeiten ja zum Teil überschneiden - alle Probleme mit dem responsiven Design in ein Issue zu packen. Wir können aber natürlich auch hier gerne noch einmal priorisieren!

Für die Funktionalität wäre es wichtig, wenn die folgenden Punkte umgesetzt werden könnten:

 D1_19 + F1_15 | hier müsste eine responsive Seite mit vertikalen Skalen im Karussel angelegt werden 
D3_6 | Seite muss responsiv wahrscheinlich neu angelegt werden
 D3_8_r | Seite muss noch gefüllt werden
 F1_2 | responsiv sollten 2 Seiten programmiert werden (s. SiD-Corona-Befragung) --> 1 Seite "für Auslandsaufenthalt", 1 Seite "gegen Auslandsaufenthalt"

Vermutlich müssen auch nicht für alle Punkte neue Seiten gebaut werden - wir stecken da leider nicht tief genug drin.

Es tut mir wirklich leid, dass wir jetzt so unter Druck arbeiten müssen. Ich finde, dass der Fragebogen aber insgesamt schon wirklich gut ausschaut!

1000 Dank!
Lena

**Comment by SilinaSchirmer** [comment]
Die abgehakten Änderungen sind schon mal umgesetzt und ab nächstem Rollout (#477) verfügbar. 

An der D3_8_r und D3_6_r sind wir dran und müssen uns noch an einigen Stellen eine mögliche Umsetzung überlegen.

**Comment by mcehrhardt** [comment]
Liebes ZOFAR-Team

- [ ] D3_6_r Die infield-Texte werden fehlerhaft dargestellt und bei weiteren Einnahmen wird nicht deutlich, welches Feld für den Text und welches für den Betrag ist. Zudem steht dort als infield-Text weitere Ausgaben.
![grafik](https://user-images.githubusercontent.com/57707751/116077138-6cc32b80-a695-11eb-9ca7-156268eae510.png)


- [ ] D3_8_r ebenfalls fehlerhafte Darstellung der infield-Texte und auch hier wird nicht deutlich, welches Feld bei weiteren Ausgaben für den Text und den Betrag gedacht ist
![grafik](https://user-images.githubusercontent.com/57707751/116077365-b4e24e00-a695-11eb-9e2d-52bb07134b97.png)
![grafik](https://user-images.githubusercontent.com/57707751/116077396-bb70c580-a695-11eb-9f10-5e363a9e7195.png)

**Comment by dzhwmeisner** [comment]
Bugfix für D3_6_r und D3_8_r im nächsten Rollout verfügbar

**Comment by woisch** [comment]
Danke für die Umsetzung, das sieht jetzt schon besser aus! 

Einen kleinen Änderungswunsch für D3_6_r (und unbedingt auch D3_6!) hätten wir noch:
it11: (feinandq) hat noch den falschen Itemtext (weitere Ausgaben, und zwar), es muss heißen: Weitere Finanzierungsquelle(n), und zwar: 
(wie in der PV)

**Comment by andreaschu** [comment]
ab nächstem RollOut verfügbar

**Comment by woisch** [comment]
geprüft, Items bei D3_6_r jetzt korrekt umgesetzt. Closed.
