### ISSUE TITLE
Fehler Transition von A_49a zu E2-Modulen

### ISSUE THREAD

**Issue by meyerja** [dzhw/SiD#475]
Liebes Zofar-Team,

leider besteht beim Übergang der Seite A_49a zu den E2-Modulen im Moment ein Fehler:

Zum einen werden die Befragten mit sabsan==7 (anderer Abschluss) komplett über die E2-Module gefiltert (unabhängig von dem Fachsemester) und landen direkt bei A_50. Laut transition sollten diese aber, je nach Fachsemester, entweder bei KSM-anf01 bzw. KSM-phd01 landen. Im Moment wird sabsan 7 jedoch bei der Weiterleitung komplett ignoriert. Könnt ihr uns sagen woran das liegen könnte? Hier der dazugehörige Code:
![grafik](https://user-images.githubusercontent.com/56591452/115562743-16ca3e80-a2b7-11eb-8a32-f5bbfc5f9feb.png)
![grafik](https://user-images.githubusercontent.com/56591452/115562835-2d709580-a2b7-11eb-9eec-61e358d2b7b3.png)

Außerdem werden alle, die zwar einen Abschluss (sabsan) angegeben haben, jedoch ein missing beim Fachsemester (ssemfs) haben, in das Modul E2 Studienanfänger (also zu KSM-anf01) geleitet. Jedoch sollten Befragte (alle außer den Masterstudierenden) ohne Angabe beim Fachsemester eigentlich über das Modul gefiltert werden und direkt bei A_50 landen. Wir sind nämlich davon ausgegangen, dass in diesem Fall die letzte Zeile der transition "<zofar:transition target="A_50"/>" greift. 
Kann es sein, dass mit "zofar.asNumber(ssemfs) le 3" auch missings angesprochen werden? Also die Bedingung kleiner gleich 3 auch missings beinhaltet?

Danke für eure Hilfe :)

**Comment by andreaschu** [comment]
@meyerja da die beiden transitions auch von mastersplit und zusatzsplit abhängen, wäre es sinnvoll, wenn Du die Testcases komplett mitliefern würdest oder direkt den Screenshot von der Seite hilfsvar.

**Comment by meyerja** [comment]
@andreaschu Das Problem besteht bei allen ungeraden Mastersplits, also bei allen, die in die E-Module leiten und zusätzlich den Zusatzsplit 2 haben, da ja das Modul E2 angesteuert werden soll. Hier mal ein Beispiel:
![grafik](https://user-images.githubusercontent.com/56591452/115601353-f9f53180-a2dd-11eb-9ec9-39d5b72d9774.png)

**Comment by andreaschu** [comment]
Fehler gefunden. Die Werte bei sabsan stimmten nicht. Ist korrigiert und ab dem nächsten RollOut verfügbar.

**Comment by meyerja** [comment]
@andreaschu Das Problem scheint für die anderen Abschlüsse (sabsan=7) behoben zu sein. 
Leider haben wir weiterhin einen Fehler, was die missings betrifft. Wenn das Fachsemester ein missing aufweist, werden die Befragten von A_49a auf KSM-anf01 weitergeleitet, anstatt auf A_50. Warum greift für diese Fälle die letzte Zeile "<zofar:transition target="A_50"/>" nicht? Muss man die Fälle mit missings extra in der transition "beschreiben", wie diese gefiltert werden sollen?

**Comment by andreaschu** [comment]
@meyerja wir haben die Bedingung hier angepasst und stichprobenartig getestet. Ich setze das Issue deswegen wieder auf testing.

**Comment by woisch** [comment]
@meyerja: wie vorhin besprochen: das haben wir ja nun durchgetestet. Ich mache das Issue daher mal zu!
