### ISSUE TITLE
Update Fragebogen Teil 4

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#478]
Bitte noch folgende Änderungen umsetzen:

- [x]  A_12a: Da wir hier drop Down und Einfachauswahl nicht kombinieren können, dies aber zur eindeutigen Identifkation von Missings notwendig, müssen wir hier aus dem Dropdown wieder ein offenes Textfeld machen, auf eine 2-Stellige Zahl begrenzt (so war es vorher auch schon). 0947aee07c949121cd6c70d3d9ea9800929c9fcc 
- [x] D1_21: Den zweiten Fragetext über dem 2. Kasten für „andere und zwar“ austauschen durch folgenden Text: Falls Sie noch weitere Sprachen beherrschen, tragen Sie diese bitte im Folgenden ein. 3f8b372052af81fe4c93f82703d46b65216eb0dd
- [x] D3_8: Items „Semesterbeitrag“ und „Studiengebühren“ sollte sich die Infieldbedingung auf „pro Semester“ beziehen. So steht es auch in der PV

Vielen Dank!

**Comment by koopmann1896** [comment]
D1_21 und D3_8 ab dem nächsten Rollout verfügbar. A_12a ist noch offen, kannst du dich darum kümmern?  @SilinaSchirmer

**Comment by koopmann1896** [comment]
D1_21 und D3_8 funktionieren.

**Comment by koopmann1896** [comment]
Hier fehlt nur noch ein Punkt,dann kann geschlossen werden. Den möchte ich aber nur sehr ungern selbst versuchen, da ich aus dem neu/ bzw. umbauen doch paar Jahre raus bin @SilinaSchirmer @andreaschu

**Comment by andreaschu** [comment]
A12a ist nun angepasst. Ab dem nächsten RollOut verfügbar.
@woisch  und @koopmann1896 Da es auf A12b visible conditions dazu gibt, müsste noch mal getestet werden, ob die noch funktionieren.

**Comment by woisch** [comment]
A_12a getestet. Auch die Einblendbedingungen auf A_12b und B2_10. Kann geschlossen werden

**Comment by woisch** [comment]
zu früh geschlossen. die vc4 auf A_12a greift nicht, wenn dsibanz=Missing.

**Comment by koopmann1896** [comment]
Vc A_12b und Wertebereich A12a angepasst. Ab nächstem Rollout verfügbar

**Comment by woisch** [comment]
Jetzt funktioniert auch der Missing-Fall von gestern! Wertebereiche ebenfalls geprüft. Kann zu

**Comment by woisch** [comment]
Wenn auf A_12a "ja" angegeben wird aber dsibanz=Missing wird ein Dropdown nicht eingeblendet (dsibsex2). Bitte nochmal die Umsetzung der vc prüfen (vc4: SHOW q3 AND is AND ka2-ka4 AND it1-it6 IF dsibanz=missing):

![grafik](https://user-images.githubusercontent.com/53002476/116363295-43c0a900-a803-11eb-913b-dd3407ff2725.png)

**Comment by woisch** [comment]
Wenn ich das richtig verstehe, liegt es an folgender Zeile in der qml, dass das Dropdown nicht eingeblendet wird: 

<zofar:questionSingleChoice uid="qsc2" visible="zofar.asNumber(dsibanz) gt 1">

in den anderen visibles steht immer noch: or zofar.isMissing(dsibanz)

Jonas ist die nächsten 1-2 Stunden nicht da, falls jemand anders das nochmal in der qml checken und ggf. ändern kann: 1000 Dank!

**Comment by koopmann1896** [comment]
> Wenn ich das richtig verstehe, liegt es an folgender Zeile in der qml, dass das Dropdown nicht eingeblendet wird:
> 
> <zofar:questionSingleChoice uid="qsc2" visible="zofar.asNumber(dsibanz) gt 1">
> 
> in den anderen visibles steht immer noch: or zofar.isMissing(dsibanz)
> 
> Jonas ist die nächsten 1-2 Stunden nicht da, falls jemand anders das nochmal in der qml checken und ggf. ändern kann: 1000 Dank!

@andreaschu @SilinaSchirmer ich könnte das umsetzen, will da aber nicht ohne euer Go noch an der QML rumtüfteln...

**Comment by andreaschu** [comment]
@koopmann1896 mach mal. Ich würde es nur kaputt machen.

**Comment by koopmann1896** [comment]
wurde umgesetzt, ab nächstem Rollout verfügbar

**Comment by woisch** [comment]
jetzt ist alles korrekt zu sehen, closed.
