### ISSUE TITLE
Update Fragebogen Teil 5

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#479]
Bitte noch folgende Änderungen umsetzen:

- [x] D3_8: "Andere bezahlen für mich" -> Die ersten Anführungsstriche unten setzen
- [x] A_25: q angepasst: https://github.com/dzhw/SiD/commit/687d135374347cc0352136e40f935d2cca03f601
- [ ] D3_7: Hier müssen die ao1-ao3 als Exklusivkategorien gesetzt werden, gegenüber den ao4-10: cdf2939e0a15e5180e3b3ca4e8f4fe0419ff8e05
- [x] C1_2: erste Anführungszeichen der is unten platzieren

Vielen Dank!

**Comment by koopmann1896** [comment]
Ausser A_25  kann ich leider nichts umsetzen.

**Comment by andreaschu** [comment]
@koopmann1896 drei Exklusivkategorien gehen nicht. Der Punkt wird nicht geändert. Die Anführungszeichen habe ich geändert.

**Comment by woisch** [comment]
> 
> 
> @koopmann1896 drei Exklusivkategorien gehen nicht. Der Punkt wird nicht geändert. Die Anführungszeichen habe ich geändert.

@andreaschu: danke, dann lassen wir es so!
