### ISSUE TITLE
Layout B2_9b: Skalenbeschriftungen überlappen

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#480]
Bei Frage B2_9b überlappen die Skalenüberschriften und sind kaum lesbar:
![grafik](https://user-images.githubusercontent.com/53002476/115677330-aa038280-a350-11eb-948b-f5ec0133d2b3.png)

**Comment by meyerja** [comment]
@woisch Das hängt mit der Schriftgröße zusammen, die eingestellt ist. Hatte es auch bei der Frage KSM-ma06, die ja identisch ist. Bei kleinerer Schriftgröße wird die Frage nämlich richtig angezeigt...

**Comment by lenamzimmer** [comment]
Liebes Zofar-Team,
wir sehen nun endgültig ein, dass wir bei dieser Frage mit Dropdown-Menüs arbeiten müssen, damit es einigermaßen funktioniert. Ich habe den Github-Code schon versucht anzupassen und die Kategorien habe ich auch noch einmal geändert - dies müssen wir natürlich auch bei der englischen Übersetzung kommende Woche bedenken!

https://github.com/dzhw/SiD/commit/b6335e87e7102b21a555a64b83ee17abb76f0d88

Lieben Dank!

**Comment by meyerja** [comment]
Bitte auch entsprechend für die Frage KSM-ma06 übernehmen.

- [ ]  d3e06fa

**Comment by andreaschu** [comment]
Ab dem nächsten RollOut testbar.

**Comment by woisch** [comment]
Aus meiner Sicht sieht das mit den Dropdowns gut aus so! @lenamzimmer ich schließe schon mal, kannst ja später beim Testen mal draufschauen..
