### ISSUE TITLE
Update Fragebogen Teil 3 (Layout)

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#481]
Bitte noch folgende Änderungen umsetzen

- [x] Tr_1_ Verbindungslinie zwischen den ao entfernen
- [ ] A_14: Verbindungslinie zur abgesetzten ao0 entfernen und bitte Schriftgröße Freitextfeld erhöhen
- [ ] A_32: Spaltenüberschrift weiter von Radiobutton abrücken
- [ ] A_34: Spaltenüberschrift weiter von Radiobutton abrücken
- [ ] A_45: Dropdowns bitte nebeneinander anordnen, wenn das nicht gehen sollte dann bitte linksbündig untereinander
- [x] B1_2: linksbündig umsetzen
- [x] B1_5: linksbündig umsetzen
- [x] B1_3a: it1, it3, it4, it5 bitte linksbündig 
- [x] B1_3b: it1 und it3 linksbündig umsetzen
- [ ] B1_6: bei fehlerhafter Eingabe in mehreren Feldern einer Spalte überlappen die kh die Felder und die Seite muss für jede Änderung einzeln abgeschickt werden. Kann man die Einblendungen der khs irgendwie anders anordnen, sodass alle Felder ausfüllbar sind?
- [ ] B1_7: „trifft nicht zu“ absetzen
- [x] B2_5: linksbündig umsetzen
- [x] C1_2: Layout bei Item „Teilleitungsstörung“: 1. Skalierungspunkt etwas versetzt.
![grafik](https://user-images.githubusercontent.com/53002476/115699734-38363380-a366-11eb-87d7-7d6454c45883.png)
- [x] D1_7: linksbündig umsetzen
- [x] D1_8: linksbündig umsetzen
- [ ] D1_21: Die Freitextfelder etwas größer und auch die Schriftgröße darin etwas erhöhen
- [x] D1_23: linksbündig umsetzen
- [x] D1_24: linksbündig umsetzen
- [x] D1_25: linksbündig umsetzen
- [x] D1_27: linksbündig umsetzen
- [ ] D1_28: Bitte Skalen zu Itemtexten zentrieren
- [x] D2_21: Verbindungslinie zu mv ("kann ich nicht beurteilen") entfernen
- [ ] D2_5:  „trifft nicht zu“ absetzen
- [x] D3_5: linksbündig umsetzen
- [x] D3_11: it1 und it3 bitte linksbündig umsetzen
- [x] D3_22: linksbündig umsetzen
- [x] D3_25: linksbündig umsetzen
- [x] D3_6: Infieldtext bei feininsg: "€ pro Monat" statt "Betrag"
- [x] D3_8: Infieldtext bei fausinsg und feininsg2 ändern: "€ pro Monat" 
- [x] E1_0: Verbindungslinie zwischen ao entfernen
- [x] E1_1: Verbindungslinie zwischen ao entfernen
- [x] E1_1a: Verbindungslinie zwischen ao entfernen
- [x] E1_1: Items linksbündig ausrichten
- [x] E1_2: Items linksbündig ausrichten
- [x] E1_3: Items linksbündig ausrichten
- [x] E1_6: Items linksbündig ausrichten
- [x] E1_7: Items linksbündig ausrichten
- [x] E1_11: Items linksbündig ausrichten
- [x] F3_11: Items linksbündig ausrichten
- [x] CO_10: Items linksbündig ausrichten

Vielen Dank!

**Comment by andreaschu** [comment]
Die abgehakten Punkte wurden angepasst und sind nach dem nächsten RollOut testbar.

**Comment by andreaschu** [comment]
> C2_1: Layout bei Item „Teilleitungsstörung“: 1. Skalierungspunkt etwas versetzt.

Hier fehlte ein Skalenpunkt. Ist korrgiert und ab dem nächsten RollOut verfügbar.

**Comment by woisch** [comment]
> 
> 
> > C2_1: Layout bei Item „Teilleitungsstörung“: 1. Skalierungspunkt etwas versetzt.
> 
> Hier fehlte ein Skalenpunkt. Ist korrgiert und ab dem nächsten RollOut verfügbar.

super, Danke! Habs oben schon mal abgehakt!

**Comment by woisch** [comment]
> 
> 
> > C2_1: Layout bei Item „Teilleitungsstörung“: 1. Skalierungspunkt etwas versetzt.
> 
> Hier fehlte ein Skalenpunkt. Ist korrgiert und ab dem nächsten RollOut verfügbar.

Der Punkt bei C2_1 ist erledigt. Hab die oben abgehakten Punkte mal stichprobenartig geprüft, das scheint größtenteils noch nicht umgesetzt zu sein (Cache ist geleert), kann das sein?

was mir aber noch aufgefallen ist:
- [ ] D2_21 die Verbindungslinie zur mv ist weg wie gewünscht. Allerdings sind jetzt hier wieder die Skalen nach unten verrutscht:

**Comment by woisch** [comment]
abgehakte Punkt geprüft, das stimmt alles jetzt!

Issue bleibt erstmal offen, wegen noch offener Punkte

**Comment by woisch** [comment]
D2_21 passt jetzt, habe ich schon mal abgehakt (das hatte @vdick in Issue #509 schon gelöst)

**Comment by woisch** [comment]
Die verbleibenden Punkte können wir in Anbetracht der Zeit ignorieren. closed.
