### ISSUE TITLE
EUROSTUDENT-Layoutanpassungen

### ISSUE THREAD

**Issue by HenSch90** [dzhw/SiD#482]
Liebes ZOFAR-Team,
auf folgenden Seiten im EUROSTUDENT-Befragungsstrang müssten Layoutanpassungen vorgenommen werden:

- p04_11:

![p04_11](https://user-images.githubusercontent.com/82670162/115703313-46864e80-a36a-11eb-8b38-a2793760437e.png)

- p04_12:

![p04_12](https://user-images.githubusercontent.com/82670162/115703315-471ee500-a36a-11eb-9a5a-efd329fdf538.png)

Vielen Dank und Grüße,
Hendrik

**Comment by vdick** [comment]
ab nächten Rollout (#484 ) verfügbar

**Comment by HenSch90** [comment]
@vdick @andreaschu  Klasse, sieht jetzt super aus! :)

**Comment by andreaschu** [comment]
@HenSch90 wenn Du damit zufrieden bist, dann liegt es an Dir das issue zu schließen. ;o)
