### ISSUE TITLE
le Anzahl Fachsemester-Bug

### ISSUE THREAD

**Issue by lenamzimmer** [dzhw/SiD#483]
Liebes Zofar-Team,

wie im JF besprochen hier nun die Sammlung an Fragen, die vom le X Fachsemester-Bug betroffen sind:

- bei A_42 und A_49a (letzteres wurde ja bereits umgesetzt) https://github.com/dzhw/SiD/commit/819ae2ac1f95b238daf5429936e571792cf0566f
- bei F3_6 https://github.com/dzhw/SiD/commit/2db697b5bdf38bf286b41b2870addbb31fa657fb
- bei D1_28 https://github.com/dzhw/SiD/commit/257f5308398c87c66f798973b56fe5bada8d03df

**Comment by andreaschu** [comment]
@koopmann1896 kannst Du das evtl. gleich mit korrigieren?

**Comment by koopmann1896** [comment]
ab dem nächsten Rollout verfügbar

**Comment by koopmann1896** [comment]
Die Transitions laufen, wird geschlossen
