### ISSUE TITLE
vc auf B2_10 

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#486]
Auf B2_10 fubktioniert die vc nicht. in der PV steht "vc: SHOW it3 IF dsib = 2 (OR (dsibo > 0 & dsibo !=.))"

Hier wird offenbar die falsche Variable angesprochen aus einer alten Version der Frage. Die Variable Geschwisterzahl heißt "dsibanz" auf A_12a.  Kann also nicht funktionieren, es muss nur die Variable ausgetauscht werden (dsibanz>0 & disbanz!=missing).
@koopmann1896: Kannst du das anpassen oder brauchen wir dafür Unterstützung?

**Comment by koopmann1896** [comment]
ab dem nächsten Rollout verfügbar :)

**Comment by woisch** [comment]
> 
> 
> ab dem nächsten Rollout verfügbar :)

**Comment by koopmann1896** [comment]
@woisch kannst du da einmal prüfen?

**Comment by woisch** [comment]
funktioniert traumhaft gut. schließe hier.
