### ISSUE TITLE
Änderung berufsbegleitend Studierende

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#490]
Bitte folgende Änderungen in vc und q anpassen:

- [x] D3_20: 51aa69f
- [x] A_42:  6fdb714

Vielen Dank!

**Comment by koopmann1896** [comment]
ab nächstem Rollout verfügbar.

**Comment by koopmann1896** [comment]
@andreaschu @SilinaSchirmer leider funktioniert die Einblendbedingung nicht für die berufsbegleitend Studierenden. Wenn man das angibt, erscheint bei beiden Fragen einfach kein Fragetext, den ich ja für diese Gruppe neu hinzugefügt habe, also die q3 im Fall von A_42. Könnt ihr da helfen? ich habe jetzt schon zweimal die Bedingung geändert, aber komme nicht drauf.

**Comment by andreaschu** [comment]
@koopmann1896 was wir gerade gemacht haben, ist ausgerollt und kann getestet werden.

**Comment by woisch** [comment]
hab grad schon nebenbei getestet, jetzt klappt es. DANKE!!
