### ISSUE TITLE
EUROSTUDENT-QML Überarbeitung

### ISSUE THREAD

**Issue by HenSch90** [dzhw/SiD#491]
Liebes ZOFAR-Team, @andreaschu @SilinaSchirmer 
Ich habe am EUROSTUDENT-Strang …

- … ein paar Textänderungen vorgenommen (d88a14e / 29d5e78 / e0dfb50),
- … die Transition einiger Subgruppen so geändert, dass sie nicht direkt aus dem Fragebogen geführt werden (fe5f6ee),
- … und versucht, ein zusätzliches Item in p05_08 (962f851) einzubauen.

Liebe Grüße,
Hendrik

**Comment by andreaschu** [comment]
Ab dem nächsten RollOut verfügbar.

**Comment by HenSch90** [comment]
Funktioniert, lieben Dank! :)
