### ISSUE TITLE
Bug B1_6_r Items werden doppelt angezeigt

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#496]
Items werden doppelt angezeigt. Bitte Fehler beheben. 
Vielen Dank!

![B1_6_r](https://user-images.githubusercontent.com/46674616/115915427-9b61bc00-a473-11eb-9f4d-ca8190bce98e.PNG)

**Comment by woisch** [comment]
In der Tablet-Ansicht (iPad2, Safari Browser) sind bei dieser Frage zudem die Überschriften verschoben:
![grafik](https://user-images.githubusercontent.com/53002476/116036274-b6e0e880-a666-11eb-9ed5-a8a6d1f96721.png)

**Comment by woisch** [comment]
Das selbe Problem haben wir auch in der responsiven Ansicht von A_56:
![grafik](https://user-images.githubusercontent.com/53002476/116048732-c582cc00-a675-11eb-8f93-dc98e2c15d01.png)

**Comment by woisch** [comment]
Auch bei B1_4a:
![grafik](https://user-images.githubusercontent.com/53002476/116052125-a0905800-a679-11eb-96f4-857dd8311b2f.png)

**Comment by andreaschu** [comment]
ab dem nächsten RollOut verfügbar.
@woisch die Seite B1_6_r wurde für Smartphones erstellt und wird nicht angesteuert mit großem Bildschirm. Deswegen wird es dafür auch nicht weiter optimiert.

**Comment by woisch** [comment]
> 
> 
> ab dem nächsten RollOut verfügbar.
> @woisch die Seite B1_6_r wurde für Smartphones erstellt und wird nicht angesteuert mit großem Bildschirm. Deswegen wird es dafür auch nicht weiter optimiert.

@andreaschu: Mein Fehler, sorry! ich hab den Screenshot vom Tablet ins falsche Issue gestellt, das kann hier also ignoriert werden, da es ja in der Tat um die responsive Version der B1_6 geht!

**Comment by woisch** [comment]
@vdick: Hier ist uns noch was durchgerutscht glaube ich. Die o.g. Probleme sind behoben, bis auf B1_4a_r, da sind die Items immer noch doppelt eingeblendet (siehe Screenshot oben)

**Comment by vdick** [comment]
ab nächsten Rollout (#515 ) verfügbar

**Comment by woisch** [comment]
Auf B1_4a_r passt es jetzt auch! 
closed.
