### ISSUE TITLE
A_40 Wertebereich anpassen

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#499]
Bei Frage A_40 müsste noch der zulässige Wertebereich für das Jahr der Hochschulzugangsberechtigung angepasst werden: 2012e900f072ae94105597847164b5f83f8caef3 

Vielen Dank

**Comment by koopmann1896** [comment]
Ab dem nächsten Rollout verfügbar

**Comment by koopmann1896** [comment]
läuft, geschlossen
