### ISSUE TITLE
B1_4a: Layout 

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#5]
Ganze Layout stimmt noch nicht. Freitextfelder sind viel zu klein und überlappen sich mit den Antwortboxen

**Comment by dzhwmeisner** [comment]
renderer fixed and provisionally css commited to svn

**Comment by andreaschu** [comment]
Frage ist nun **B1_4a**.html. Sieht besser auch, aber titles überlappen stark.

![grafik](https://user-images.githubusercontent.com/30111489/66498936-2f9d4580-eabf-11e9-9792-af8cf1aa6c8d.png)

**Comment by SilinaKowalewski** [comment]
Layout wurde angepasst und kann nun gestestet werden.

**Comment by SilinaKowalewski** [comment]
![image](https://user-images.githubusercontent.com/48087320/67091141-2d687480-f1ac-11e9-9822-a074c895ada7.png)
