### ISSUE TITLE
C2_8 und C2_9 im responsiven Design nicht ausfüllbar!

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#500]
Wenn in der mobilen Ansicht in C2_7 Items der Kategorien "Lehre und Lernen" oder "Prüfungen/Leistungsnachweise"  auswählt, werden diese (nur im responsiven Design) in C2_8 nicht eingeblendet, das selbe gilt für C2_9.

![C2_8](https://user-images.githubusercontent.com/50742367/116045954-de3db280-a672-11eb-8273-afeaba8fbf80.jpg)

**Comment by SilinaSchirmer** [comment]
Geht jetzt :) Habe dafür die Seiten C2_8_r und C2_9_r angelegt und die Transitions entsprechend angepasst.

**Comment by woisch** [comment]
Danke! 
Problem ist jetzt noch folgendes:
Wir haben ja auf C2_7 3 Bereiche (jeweils in nem Kasten), über die hier gemachten Angaben wird dann auf der folgenden Seite C2_8 gefiltert. Wenn ich in einem Kasten nichts auswähle, sehe ich auf C2_8 trotzdem die Rechts/Links-Pfeile vom Karussel:

![grafik](https://user-images.githubusercontent.com/53002476/116092489-232f0c80-a6a6-11eb-9452-32bc09dcf0db.png)

Auf auf C2_9 dann wieder das selbe Problem, je nach Filterung auf C2_8:
![grafik](https://user-images.githubusercontent.com/53002476/116092740-5a9db900-a6a6-11eb-9d66-216dedfb326a.png)

**Comment by andreaschu** [comment]
@woisch ich hatte noch trigger für die Bldschirmbreite (auf C2_7 und C2_8) eingefügt, was aber noch nicht mit ausgerollt wurde. Wenn Du testest, geh bitte sicher, ob deine Bildschirmbreite kleiner als 768 ist. Getriggert wird sie auf jeden Fall auf der Index-Seite (mit betreten). Auf der Seite hilfsvar wird sie angezeigt.
Die Weiterleitung funktioniert darüber, das habe ich gerade gestet.

![grafik](https://user-images.githubusercontent.com/30111489/116096455-9a19d480-a6a9-11eb-8a3b-8c7182c05565.png)

**Comment by woisch** [comment]
Hab es jetzt nochmal responsiv am Smartphone getestet, es funktioniert jetzt!
