### ISSUE TITLE
D1_4 vc fehler

### ISSUE THREAD

**Issue by koopmann1896** [dzhw/SiD#502]
VC bedingung geändert, da falscher VAriablenname. https://github.com/dzhw/SiD/commit/8cb419f2331797a19b92814735d0e6536dd1510e
Ab nächstem Rollout verfügbar

**Comment by koopmann1896** [comment]
läuft -> geschlossen

**Comment by koopmann1896** [comment]
vc für ao ebenfalls angepasst
ab nächstem Rollout verfügbar und dann auch wirklich :)

**Comment by woisch** [comment]
bei mir klappt es jetzt wie es sollte (Szenario von gestern nochmal durchgetestet), mache mal zu
