### ISSUE TITLE
A_45 vc funktioniert nicht

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#503]
q2 wird immer angezeigt, dort steht nur: SHOW q2 if Internationale Studierende

Müsste so gehen (bitte nochmal checken):
SHOW q1 if vsbdeba!=2 or  if vsbdeba=Missing
SHOW q2  if vsbdeba==2

**Comment by koopmann1896** [comment]
ab dem nächsten Rollout verfügabr

**Comment by woisch** [comment]
habs eben noch in der PV ergänzt, hatte ich vergessen: 0b39a45f363b67db61f84272e67289fb50c5ac0d

**Comment by koopmann1896** [comment]
läuft
