### ISSUE TITLE
Layout Unit - Itemcounter

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#507]
- [x] D1_7 
- [x] C2_8_r
- [x] C2_9_r
- [x] F1_2_r1
- [x] F1_2_r2

**Comment by vdick** [comment]
ab nächsten Rollout (#504 ) verfügbar

**Comment by woisch** [comment]
geprüft, die Itemcounter sind jetzt alle sichtbar! Vielen Dank!

was mir noch aufgefallen ist. Bei Fragen wie C2_8_r und C2_9_r ist die Fragebatterie ja in mehrere optisch voneinander getrennte "Blöcke" aufgeteilt, die Itemcounter werden aber gesamt über alle auf der Seite eingeblendeten Items gezählt.
Kannst man das auf einfachem Wege anpassen, dass die Itemcounter je "Frageblock" zählen? Wenn es da ne schnelle Lösung gäbe, könnte ich noch mal eine Liste machen, welche Fragen das betrifft. Ansonsten müssen wir mit der jetzigen Lösung leben.

**Comment by andreaschu** [comment]
@vdick die Counter funktionieren jetzt correct. Nur bei den folgenden beiden Seiten ist der Unit-Text verschwunden.

- [ ] F1_2_r1
- [ ] F1_2_r2

**Comment by vdick** [comment]
ab nächsten Rollout (#515 ) verfügbar

**Comment by woisch** [comment]
hier funktioniert jetzt alles, Danke! 
Issue wird geschlossen.
