### ISSUE TITLE
Layout Unit - Textfelder zu klein/überlappend

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#508]
- [ ] KSM-ma07
- [ ] KSM-phd02
- [ ] D1_7 und KSM-anf04
- [ ] D1_8 und KSM-anf05

**Comment by vdick** [comment]
ab nächsten Rollout (#517 ) verfügbar

**Comment by woisch** [comment]
D1_7 und D1_8 geprüft. 
@meyerja: Kannst du mal die KSM-Fragen checken?

**Comment by woisch** [comment]
Hab jetzt doch alle Fragen durchgesehen aufm dem iPhone. Sieht alles gut aus! Du kannst aber gerne nochmal prüfen, @meyerja. Ich schließe das Issue trotzdem schon mal
