### ISSUE TITLE
Layout Unit - Desktopansicht

### ISSUE THREAD

**Issue by SilinaSchirmer** [dzhw/SiD#509]
- [x] D2_2
- [x] D2_3
- [x] D2_21
- [x] D1_8

**Comment by vdick** [comment]
ab nächsten Rollout (#504) verfügbar

**Comment by woisch** [comment]
geprüft, es gibt noch ein Problem auf Seite D1_8 mit überlappenden Skalenüberschriften, genauso sieht auch die D1_7 aus aktuell):
![grafik](https://user-images.githubusercontent.com/53002476/116198777-ab5cf280-a736-11eb-8729-6e3f335bbc4c.png)

responsiv sieht es in Ordnung aus.

**Comment by vdick** [comment]
ab nächsten Rollout (#515 ) verfügbar

**Comment by woisch** [comment]
geprüft. Bei D1_8 und D1_7 war es tatsächlich nur das besprochene Java-Problem und hat sich beim aktualisieren des Browsers aufgelöst.
Issue kann geschlossen werden!
