### ISSUE TITLE
Layout D1_29/KSM-anf03

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#516]
Bei Frage D1_29/KSM-anf03 werden die Items in 3 Blöcken zufällig rotiert. Diese Blöcke werden jeweils in einem Kasten dargestellt, haben aber auch eine "leere" Überschriftenbox in grau. Kann man die entfernen? Oder bekommen wir dann wieder Probleme mit den Itemcountern in der responsiven Ansicht (dann lieber kein Risiko eingehen).
(Ich vermute das Problem resultiert aus den Anpassungen bei den Itemcountern, es scheint mir jedenfalls neu zu sein seit gestern.)

![grafik](https://user-images.githubusercontent.com/53002476/116371275-8b4b3300-a80b-11eb-9e7a-ab4bb604fa01.png)

**Comment by vdick** [comment]
sorry, mein Fehler, war gestern etwas übermüdet/unkonzentriert, ab nächsten Rollout verfügbar

**Comment by vdick** [comment]
Habe noch ein paar weitere Fälle endeckt und gefixt

**Comment by woisch** [comment]
super, dann schauen wir nach dem Rollout nochmal durch, danke!

**Comment by woisch** [comment]
das sieht jetzt gut aus, kann zu!
