### ISSUE TITLE
D3_9 Infield Text

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#518]
Bei Frage D3_9 soll der Text „€ pro Monat“ als infield-Text umgesetzt werden und „€“ als Postfix. Momentan ist der ganze text als Präfix umgesetzt, was fürs Ausfüllen sehr ungünstig ist.

**Comment by woisch** [comment]
@SilinaSchirmer: Hab das zwar als Layout-Punkt gelabelt, aber kannst du hier eventuell deine Magie walten lassen?

**Comment by andreaschu** [comment]
@woisch ich glaube wirklich, dass wir wichtigeres zu tun haben.

**Comment by woisch** [comment]
@andreaschu: das verstehe ich und ich wollte damit keinesfalls (ohne Frage) wichtigere Arbeiten blockieren oder unnötige neue Baustellen aufmachen! Wenn es nicht mehr geht, dann ist es so.

Nur aber nochmal zur Erläuterung, warum ich das Issue vorhin überhaupt noch erstellt habe: Das ist ein Bug, den wir vermutlich erst seit gestern oder heute haben. Wir sind der Meinung, dass die Frage bisher korrekt umgesetzt war als Infield und ich bin mir auch nicht sicher, woher das kommt, da wir an der D3_9 zuletzt m.E. nichts geändert haben. Habe auch nochmal in die Screenshots von vor ein paar Wochen geschaut und da war das Infield auch korrekt umgesetzt. 

![grafik](https://user-images.githubusercontent.com/53002476/116430424-1e558e80-a847-11eb-9205-9a4ff1399892.png)
![grafik](https://user-images.githubusercontent.com/53002476/116429806-85bf0e80-a846-11eb-8d1b-ce80a49ac76e.png)

**Comment by woisch** [comment]
Ich schließe dann hier, hat sich erledigt.

**Comment by andreaschu** [comment]
@dzhwmeisner ich denke, dass Du das heut wegen D3_6_r und D3_8_r eingebaut hattest. Kannst Du da noch mal gucken, dass diese Lösung nur für die beiden Seiten gilt und nicht für andere?

**Comment by SilinaSchirmer** [comment]
> @dzhwmeisner ich denke, dass Du das heut wegen D3_6_r und D3_8_r eingebaut hattest. Kannst Du da noch mal gucken, dass diese Lösung nur für die beiden Seiten gilt und nicht für andere?

Habe vorhin mit @woisch drauf geschaut und jetzt sieht es wieder gut aus.
