### ISSUE TITLE
C2_11a Skalenüberschrift nicht zu sehen

### ISSUE THREAD

**Issue by woisch** [dzhw/SiD#520]
die Skalenüberschrift der mv ("nicht vorhanden") ist nicht mehr zu sehen in der Desktop version (responsiv funktioniert es allerdings):
![grafik](https://user-images.githubusercontent.com/53002476/116444819-709dac00-a855-11eb-8f8a-5c8e26357384.png)

**Comment by vdick** [comment]
ab nächsten Rollout (#519 ) verfügbar

**Comment by woisch** [comment]
geprüft, Skalenüberschrift ist wieder da! closing..
