### ISSUE TITLE
EUROSTUDENT Listen-Bug

### ISSUE THREAD

**Issue by HenSch90** [dzhw/SiD#527]
Liebes ZOFAR-Team,

im EUROSTUDENT-Strang gibt es auf p02_02 noch ein Listenproblem: die Monate tauchen am Ende der Jahresliste nochmal auf. Könnt ihr die bitte noch rausnehmen und am Anfang der Liste noch das Jahr 2020 ergänzen?

![image](https://user-images.githubusercontent.com/82670162/116692880-5e3e8200-a9bd-11eb-97c8-4cf81fe56c82.png)

Vielen Dank und liebe Grüße,
Hendrik

**Comment by andreaschu** [comment]
die AO wurde eingefügt (inkl. Übersetzung).

**Comment by andreaschu** [comment]
Das wurde übrigens ausgerollt und kann getestet werden. Diese korrigierte Version haben wir auch übergeben. Das heißt diese Korrektur wurde mit auf den externen Servern angewendet und ausgerollt und kann dort ebenfalls noch mal getestet werden.

**Comment by HenSch90** [comment]
@andreaschu Super, ganz lieben Dank! :)
