### ISSUE TITLE
Modul F2: Modul dt Studierende im Ausland (first draft)

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#53]
Modul F2 wurde programmiert. Bitte prüfen.

**Comment by karbecke** [comment]
Seite F2_1 nicht programmiert

- [ ] Bitte programmieren

**Comment by SilinaKowalewski** [comment]
@karbecke: 

Die Frage kann, aufgrund von falscher Variablennamen, nicht programmiert werden. Hierzu hatte ich bereits letzte Woche ein Issue #52 geschrieben.

**Comment by karbecke** [comment]
Code angepasst, bitte umsetzen --> eeec2a6

**Comment by SilinaKowalewski** [comment]
Frage 2_1 wurde programmiert.
