### ISSUE TITLE
Modul C2: gesundheitliche Beeinträchtigung (first draft)

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#54]
neues Modul zum Programmieren: [C2](https://github.com/dzhw/SiD/blob/master/Modul-C2_Gesundheitliche_Beeintr%C3%A4chtigung.md)

**Comment by SilinaKowalewski** [comment]
Modul C2 programmiert. Bitte prüfen.

**Comment by andreaschu** [comment]
Das issue kann wohl geschlossen werden, oder?
