### ISSUE TITLE
CMI3: Staatenliste_DBI fehlt

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#57]
In der Frage [CMI3](https://github.com/dzhw/SiD/blob/master/Modul_Grundprogramm.md#cmi3) wird _Staatenliste_DBI_ erwähnt. Diese fehlt bisher noch. 

Bitte reicht die Staatenliste_DBI nach.

**Comment by SilinaKowalewski** [comment]
Das gleiche gilt für die Frage [CMI6](https://github.com/dzhw/SiD/blob/master/Modul_Grundprogramm.md#cmi6).

**Comment by karbecke** [comment]
[Staatenliste_nach Kontinenten_SiD.xlsx](https://github.com/dzhw/SiD/files/3735224/Staatenliste_nach.Kontinenten_SiD.xlsx)

**Comment by karbecke** [comment]
Bitte Reiter "Sid" verwenden

**Comment by SilinaKowalewski** [comment]
Für die Staaten der **Antarktis** können keine Sichtbarkeitsbedingungen geschrieben werden, da in der vorherigen Frage lediglich Europa, Afrika, Amerika, Asien und Australien und Ozeanien abgefragt werden. 

Sollen diese Staaten immer eingeblendet werden?

**Comment by SilinaKowalewski** [comment]
Zunächst so umgesetzt wie geliefert. Bitte prüfen.

**Comment by karbecke** [comment]
Bitte auf Seite A_7 ebenfalls programmieren. Danke

**Comment by karbecke** [comment]
Bitte auf Seite A_35 ebenfalls umsetzen

**Comment by karbecke** [comment]
@SilinaKowalewski  Bitte die Staatenliste_nach_Kontinenten auch für Seite A_7 verwenden.
Danke!
