### ISSUE TITLE
SDK-NEU: Frage kann so nicht umgesetzt werden.

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#58]
Die Frage [SKD-NEU](https://github.com/dzhw/SiD/blob/master/Modul_Grundprogramm.md#sdk-neu) kann in der Form nicht umgesetzt werden. Da ein DropDown-Menü technisch gesehen bereits eine SingleChoice-Frage ist, kann es nicht mit Antwortoptionen kombiniert werden. 

Aktuell so umgesetzt:
https://presentation.dzhw.eu/sid/SDK-NEU.html

**Comment by andreaschu** [comment]
Die Seitennamen haben sich geändert. Bitte schaut, ob es noch aktuell ist und schließt es, wenn es oder passt die Seitenzahl an.
