### ISSUE TITLE
SDK_NEU3: PV unklar

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#59]
Mir ist nicht klar, was bei der Frage [SDK_NEU3](https://github.com/dzhw/SiD/blob/master/Modul_Grundprogramm.md#sdk-neu3) programmiert werden soll. 

Soll dies lediglich eine Frage mit vier offenen Textfeldern sein oder jeweils Checkboxen davor programmiert werden? Für den Fall, dass hier lediglich Textfelder gewünscht sind, reichen und insgesamt vier Variablen.

**Comment by SilinaKowalewski** [comment]
Zudem fehlt ein Variablenname für die ao4 "Ort"

**Comment by SilinaKowalewski** [comment]
Die richtigen Sichtbarkeitsbedingungen wären hier: 

> SHOW hsstandhso IF hsstandbl=1 – 16 OR hsstandbl=17 AND ainfasia=1-2
> SHOW hsstandsto IF hsstandbl=1 – 16 OR hsstandbl=17 AND ainfasia=1-2 OR hsstandbl=17 AND ainfasia=3-8
> SHOW hsstandlao IF hsstandbl=17 AND ainfasia=1-2 OR hsstandbl=17 AND ainfasia=3-8

So wie in der PV angegeben sind die Bedingungen nur sehr schwer verständlich.

**Comment by karbecke** [comment]
bitte erstmal so umsetzen

**Comment by SilinaKowalewski** [comment]
Wurde umgesetzt. Bitte prüfen.

**Comment by andreaschu** [comment]
Seitenzahlen stimmen nicht mehr. Bitte prüfen und schließen oder Seitenzahl anpassen.
