### ISSUE TITLE
B2_9a: Variablen uneinheitlich

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#60]
Die Variablen der Frage [B2_9a](https://github.com/dzhw/SiD/blob/master/Modul-B2_Kultur.md#b2_9a) sind uneinheitlich. Bitte anpassen.

**Comment by karbecke** [comment]
angepasst --> 02bfcde

**Comment by SilinaKowalewski** [comment]
Variablen wurden entsprechend des Updates angepasst.

**Comment by lenamzimmer** [comment]
Bei dieser Frage überschneiden sich die Antwortkategorien (Spalten) völlig, so dass man nichts lesen kann -> Spalten müssen deutlich breiter werden und die Zeilen deutlich schmaler.

Danke!
