### ISSUE TITLE
B2_9a: Widersprüchliche Sichtbarkeitsbedingungen

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#61]
Die Sichtbarkeitsbedingungen der Frage [B2_9a](https://github.com/dzhw/SiD/blob/master/Modul-B2_Kultur.md#b2_9a) widersprechen sich untereinander bzw. machen nur wenig Sinn. 

> SHOW it1 and it4 and it5 and it6 if sabsan=3 [SDK-stu#05] Grundprogramm
> SHOW it1 and it2 and it3 and it6 if sabsan!=3 [SDK-stu#05] Grundprogramm

Bisher nicht umgesetzt.

**Comment by SilinaKowalewski** [comment]
Das gleiche filt für die Frage [B2_9b](https://github.com/dzhw/SiD/blob/master/Modul-B2_Kultur.md#b2_9b)

> SHOW ao1 and ao4 and ao5 and ao6 if sabsan=3 [SDK-stu#05] Grundprogramm
SHOW ao1 and ao2 and ao3 and ao6 if sabsan!=3 [SDK-stu#05] Grundprogramm

**Comment by lenamzimmer** [comment]
Okay, für B2_9a gilt:

SHOW it4 and it5 if sabsan=3 [SDK-stu#05] Grundprogramm
SHOW it2 and it3 if sabsan!=3 [SDK-stu#05] Grundprogramm

Ich nehme an, dass die Logik so ist, dass in den Einblendbedingungen explizit nicht erwähnte Items immer angezeigt werden, richtig?

**Comment by lenamzimmer** [comment]
Habe ich angepasst:
https://github.com/dzhw/SiD/commit/6fab6eb504319ba9faf8b85c1effec3d92dcc4c8

**Comment by lenamzimmer** [comment]
Habe es nun auch für B2_9b angepasst: https://github.com/dzhw/SiD/commit/c3fbf18d5ffef13cf2031ee720278c952c92b045

**Comment by SilinaKowalewski** [comment]
> Ich nehme an, dass die Logik so ist, dass in den Einblendbedingungen explizit nicht erwähnte Items immer angezeigt werden, richtig?

Ganz genau :)

**Comment by SilinaKowalewski** [comment]
Habe beide Änderungen umgesetzt. Sind nach dem nächsten Roll-Out (hoffentlich heute Abend) sichtbar.
