### ISSUE TITLE
B2_9b: fehlende Variable

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#62]
Bei der Frage [B2_9b](https://github.com/dzhw/SiD/blob/master/Modul-B2_Kultur.md#b2_9b) fehlt bisher noch eine Variable für die Antwortoption "weiß ich nicht"

**Comment by karbecke** [comment]
angepasst --> 3f18807

**Comment by SilinaKowalewski** [comment]
@karbecke: 

Der Variablenname fehlt hier leider immer noch.

**Comment by karbecke** [comment]
Sry, 94cb374 neuer Versuch

**Comment by lenamzimmer** [comment]
Bei dieser Frage müssen noch mehrere Dinge angepasst werden:

- [ ] die Items werden doppelt hintereinander dargestellt: Bitte Doppelung jeweils löschen.
- [ ] "€/Monat" bitte Infield darstellen und nicht hinter den offenen Feldern.
- [ ] Bitte "weiß nich nicht"-Option entfernen.
- [ ] Kästchen bitte so programmieren, dass lediglich Zahlen zwischen 0 und 15000 eingetragen werden können. Korrekurhinweis: "Bitte schätzen Sie das durchschnittliche monatliche Nettoeinkommen in Euro (0 bis 15000)."

Danke!
