### ISSUE TITLE
F1_5: Falscher Variablenname?

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#63]
Die Sichtbarkeitsbedingung der Frage [F1_5](https://github.com/dzhw/SiD/blob/master/Modul-F1_internationale_Studierende.md#f1_5) kann so nicht programmiert werden, da die Variable "aauszeitlebbame" nicht in der Frage auftaucht.

> vc: SHOW aauszeitlebbame IF sabsan=2

**Comment by karbecke** [comment]
Tippfehler Variablenname: Habe Code ba70dd5 angepasst

**Comment by SilinaKowalewski** [comment]
Wurde angepasst. Bitte prüfen.
