### ISSUE TITLE
F1_10: Fragetyp - Klärungsbedarf

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#64]
Die Frage [F1_10](https://github.com/dzhw/SiD/blob/master/Modul-F1_internationale_Studierende.md#f1_10) kann nicht, wie in der PV vorgesehen, umgesetzt werden. Mehrere Dropdown-Menüs können lediglich nebeneinander, aber nicht untereinander dargestellt werden.

**Comment by karbecke** [comment]
Ok, dann bitte nebeneinander programmieren

**Comment by SilinaKowalewski** [comment]
Habe mich hier scheinbar verschrieben. Sorry! 

Wir können die Drop-Down-Menüs eben nicht, wie gewünscht, nebeneinander darstellen sondern nur untereinander. Also untereinander geht, nebeneinander nicht.

**Comment by karbecke** [comment]
ok, dann bitte erstmal untereinander programmieren, hier müssen wir eine gute Lösung noch finden

**Comment by SilinaKowalewski** [comment]
Wurde nun, entsprechend einer anderen Frage, untereinander programmiert. Über eine alternative Darstellung können wir uns gerne unterhalten.
