### ISSUE TITLE
F3_6 Exklusivkategorie

### ISSUE THREAD

**Issue by karbecke** [dzhw/SiD#66]
Bitte in Frage [F3_6](https://github.com/dzhw/SiD/blob/master/Modul-F3_Mobilit%C3%A4t.md#F3_6) das Item "nein" als Exklusivkategorie umsetzen

**Comment by SilinaKowalewski** [comment]
Wurde umgesetzt. Bitte in Programmiervorlage dokumentieren.

**Comment by karbecke** [comment]
ist in PV dokumentiert -> steht in eckigen Klammern hinter dem entsprechenden Item. Oder soll es anders vermerkt werden?

**Comment by SilinaKowalewski** [comment]
Super, danke! Ist richtig so :)
