### ISSUE TITLE
F1_20/F1_19: doppelte Variable

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#67]
Bei der Frage [F1_19](https://github.com/dzhw/SiD/blob/master/Modul-F1_internationale_Studierende.md#f1_19) und [F1_20](https://github.com/dzhw/SiD/blob/master/Modul-F1_internationale_Studierende.md#f1_20) wird die gleiche Variable (bdedarhsoba) genutzt. 

Bitte anpassen. Kann so nicht umgesetzt werden.

**Comment by karbecke** [comment]
Bitte in [F1_20](https://github.com/dzhw/SiD/blob/master/Modul-F1_internationale_Studierende.md#f1_20) die Variable "bhiitecba" benutzen und nicht "bdedarhsoba"

**Comment by karbecke** [comment]
siehe Update --> af35209
