### ISSUE TITLE
sammel-issue: seitennummern für Studiensituation

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#7]
in der [PV](https://github.com/dzhw/SiD/blob/master/Modul-D2_Studiensituation.md) fehlen noch Seitenzahlen

**Comment by andreaschu** [comment]
Seitennummern wurden ergänzt: 0281d3f

**Comment by SilinaKowalewski** [comment]
Seitennummern wurden angepasst. Bitte prüfen.
