### ISSUE TITLE
Lenkungs-/Splitvariable erstellen

### ISSUE THREAD

**Issue by markusloe** [dzhw/SiD#72]
Liebe ZOFAR-Programmierer,

könntet Ihr uns bitte zu Beginn der Befragung für jeden Befragten zwei Variablen generieren?

(1. Variable) "mastersplit" soll eine Zufallsvariable sein, die Werte zwischen 1-14 annehmen kann.
(2. Variable) "zusatzsplit" soll eine Zufallsvariable sein, die Werte zwischen 1-4 annehmen kann.

Anhand dieser beiden Variablen würde ich gerne die verschiedenen Fragen/Module ansteuern.

Vielen Dank und beste Grüße,
Markus

**Comment by andreaschu** [comment]
kannst Du das in der PV der Index-Seite einbauen, wie ich es geschrieben habe?

> 1.	Für einen 50:50 Split mit einmaliger Zuweisung (der Zufallswert wird den Befragten einmalig zugewiesen und beibehalten):
> sv: s_split_[name] = 0, 1 (einmalige Randomisierung; 0= 50%; 1= 50 %)
> 2.	Für einen 3er- Split mit einmaliger Zuweisung
> sv: s_split_[name] = 1, 2, 3 (einmalige Randomisierung; 1= 33%; 2= 33 %, 3= 33%)
> 3.	Für einen 3er-Split mit wiederholter Zuweisung (bei neuem Laden der Seite erfolgt eine neue Zuweisung)
> sv: s_split_[name] = 1, 2, 3 (wiederholte Randomisierung; 1= 33%; 2= 33 %, 3= 33%)
> 4.	Für einen 80:20 Split mit einmaliger Zuweisung:
> sv: s_split_[name] = 0, 1 (einmalige Randomisierung; 0= 80%; 1= 20 %)
> 

Das wäre dann:
```
sv: mastersplit = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 (einmalige Randomisierung; gleichmäßige Chance)
sv: zusatzsplit = 1, 2, 3, 4 (einmalige Randomisierung; gleichmäßige Chance)
```

**Comment by andreaschu** [comment]
Habe Index-Seite mit Steuerungvariablen in PV angelegt

**Comment by SilinaKowalewski** [comment]
Steuerungsvariablen wurden erstellt. Sie werden nun bei Verlassen der Index-Seite zufällig gebildet.

**Comment by SilinaKowalewski** [comment]
@markusloe: 
Wir könnten die Steuerungsvariablen an einigen Stellen einblenden um ein Testen zu erleichtern. Falls gewünscht, gib mir einfach Bescheid, auf welchen Seiten eine Einblendung gesetzt werden soll. Für den Live-Betrieb wird die Einblendung dann wieder entfern.
