### ISSUE TITLE
Modul Politik: Fehlende Antwortoptionen bei KSM-pol07

### ISSUE THREAD

**Issue by SMajer** [dzhw/SiD#74]
Sollte Mehrfachauswahlmatrix mit Ja/Nein sein. Neben jedem Items sollte ja/nein als Antwortoptionen angezeigt werden. Angepasst (siehe 8bfa5e0)

**Comment by andreaschu** [comment]
Sicher? Eine Ja/Nein-Skala macht aus meiner Sicht wenig Sinn, da man jede Antwortoption wählen und abwählen kann. Das würde bedeuten, dass man hier sowohl _ja_ als auch _nein_ antworten könnte. Zudem würde die doppelte Anzahl an Variablen notwendig sein, da hinter jeder Checkbox eine Variable steht (also jeweils eine für ja und nein).
Hier noch mal zur Klärung:

**einfache Multiple Choice-Question**
![grafik](https://user-images.githubusercontent.com/30111489/66823312-4374fb80-ef46-11e9-855c-04613f4a0bd6.png)

**Multiple Choice-Matrix**
![grafik](https://user-images.githubusercontent.com/30111489/66823696-0b21ed00-ef47-11e9-8fb3-3092818b963c.png)

**Single Choice-Matrix**
![grafik](https://user-images.githubusercontent.com/30111489/66822594-ceed8d00-ef44-11e9-824c-a74bb791dc6c.png)

**Comment by SMajer** [comment]
> 
> 
> Sicher? Eine Ja/Nein-Skala macht aus meiner Sicht wenig Sinn, da man jede Antwortoption wählen und abwählen kann. Das würde bedeuten, dass man hier sowohl _ja_ als auch _nein_ antworten könnte. Zudem würde die doppelte Anzahl an Variablen notwendig sein, da hinter jeder Checkbox eine Variable steht (also jeweils eine für ja und nein).
> Hier noch mal zur Klärung:
> 
> **einfache Multiple Choice-Question**
> ![grafik](https://user-images.githubusercontent.com/30111489/66823312-4374fb80-ef46-11e9-855c-04613f4a0bd6.png)
> 
> **Multiple Choice-Matrix**
> ![grafik](https://user-images.githubusercontent.com/30111489/66823696-0b21ed00-ef47-11e9-8fb3-3092818b963c.png)
> 
> **Single Choice-Matrix**
> ![grafik](https://user-images.githubusercontent.com/30111489/66822594-ceed8d00-ef44-11e9-824c-a74bb791dc6c.png)

@andreaschu : Stimmt, hab es gerade nochmal angesehen, das macht keinen Sinn mit ja/nein. Wie muss die einfach multiple choice Frage dann programmiert werden? Merhfachauswahlmatrix ohne Beschriftung der Antwortoptionen?

**Comment by SilinaKowalewski** [comment]
@SMajer: 

Für diese Frage müsste ledglich eine Mehrfachauswahl angegeben werden. Die einzelnen "Items" wären dann Antwortoptionen die jeweils eine Variable erhalten. Diese wird dann entsprechend mit 0/1 gefüllt. 


> KSM-pol07
> tc:
> 
> vn: beteil1; beteil2; beteil3; beteil4; beteil5; beteil6; beteil7; beteil8; beteil9
> 
> qt: **Mehrfachauswahl**
> 
> hl:
> 
> in:
> 
> q: An welcher der folgenden Tätigkeiten in Gruppen oder Organisationen sind Sie selbst beteiligt?
> 
> is: Mehrfachantworten sind möglich
> 
> it:
> 
> **ao1**: (beteil1): Beteiligung an Bürger*inneninitiativen
> 
> **ao2**: (beteil2): Mitarbeit in politischen Parteien
> 
> **ao3**: (beteil3): Beteiligung an Umwelt-, Natur-, Tierschutzorganisationen
> 
> **ao4**: (beteil4): Mitarbeit im sozialen Bereich (Jugendarbeit, Hilfen, Wohlfahrt)
> 
> **ao5**: (beteil5): Trainer*in / Übungsleiter*innentätigkeit im Sportverein
> 
> **ao6**: (beteil6): Mitarbeit in Friedens-, Menschenrechts-, Asylgruppen
> 
> **ao7**: (beteil7): Studierendenvertretungen
> 
> **ao8**: (beteil8): Student*innenverbindungen
> 
> **ao9**: (beteil9): Engagement in anderen politischen oder sozialen Gruppierungen
> 
> st:
> 
> mv:
> 
> ka:
> 
> vc:
> 
> av:
> 
> kh:
> 
> fv:
> 
> hv:
> 
> fo:
> 
> tr: end
> 
> hi:

**Comment by SilinaKowalewski** [comment]
Habe die PV bereits angepasst c89ad44

**Comment by SMajer** [comment]
> 
> 
> Habe die PV bereits angepasst [c89ad44](https://github.com/dzhw/SiD/commit/c89ad440a7598fac493c31c4c604ddcc79fc4746)

Super, funktioniert. danke!
