### ISSUE TITLE
Modul F1: internationale Studierende (first draft)

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#75]
Modul wurde programmiert. Bitte prüfen.

**Comment by karbecke** [comment]
Vielen Dank für die Umsetzung. Bitte folgendes anpassen:

- [ ] Anpassung F1_1

F1_1 | *** ist es möglich in das offene   Feld "anderes, und zwar" als hellgrauen Text bereits   hineinzuschreiben? Wenn ja, bitte umsetzen
-- | --

- [ ] Anpassung F1_2

F1_2 | *** Skalenendpunktbeschriftungen   werden nicht unter, sondern über dem Fragetext dargestellt, bitte anpassen
-- | --
  | *** Darstellung im responsiven   Design: Items "für einen Auslandsaufenthalt" werden angezeigt,   "gegen einen Auslandsaufenthalt" steht immer ganz unten, Items   werden aber nicht angezeigt
  | *** Bitte nur die passende   Item-Überschrift je Item im responsiven Design anzeigen, sonst funktioniert   die Frage in dieser Form nicht --> sieh Screenshot     Lösungsvorschlag im responsiven Design: Fragetext: "Was spricht Ihrer   Meinung nach für einen Auslandsaufenthalt" mit entsprechenden Items und   danach in einem neuen Karoussell "Was spricht Ihrer Meinung nach gegen   einen Auslandsaufenthalt" mit entsprechenden Items
  | *** im responsiven Design fehlt   die Karoussell-Nummerierung der Items

- [ ] Anpassung F1_3


F1_3 | *** graue Verbindungslinie der   vertikalen Skala entfernen (generell bei diesem Fragetyp)
-- | --

- [ ] Anpassung F1_4

F1_4 | *** statt   "Mehrfachauswahl" bitte einfügen "Bitte alles Zutreffende   auswählen"
-- | --

- [ ] Anpassung F1_5

F1_5 | *** Schreibfehler in Frage   "...(mehr als 3 Monate) IM Ausland" --> Bitte "im" mit   kleinem i schreiben
-- | --
  | *** ob hier - wenn   MA-Studierende mit BA-Abschluss - Einblendung    des Items "ja, zwischen meinem Bachelor- und Masterstudium"   eingeblendet wird, kann aktuell nicht geprüft werden
  | *** Bitte statt "Bitte   alles Zutreffende ankreuzen." --> "Bitte alles Zutreffende   auswählen" schreiben


- [ ] Anpassung F1_6

F1_6 | *** hier fehlt Infobox (Wenn Ihr   ausländischer Schulabschluss in Deutschland nicht als Studienberechtigung   anerkannt wird, müssen Sie vor Studienbeginn ein Studienkolleg besuchen)   --> fehlte in Programmiervorlage
-- | --
  | *** graue Verbindungslinie der   vertikalen Skala entfernen (generell bei diesem Fragetyp)



- [ ] Anpassung F1_7

F1_7 | *** hier falscher Fragetext,   muss heißen: Hatten Sie Schwierigkeiten bei der Anerkennung Ihrer Vorbildung   in Deutschland?
-- | --
  | *** Item "weiß ich   nicht" als Exklusivkategorie und ohne vertikale Verbindung mit den   anderen Antwortoptionen



- [ ] Anpassung F1_8

F1_8 | *** Schreibfehler im 1. Item   (Studienberechtigung)
-- | --
  | *** Bitte Item "weiß ich   nicht" durch eine Leerzeile absetzen



- [ ] Anpassung F1_9

F1_9 | *** Schreibfehler in Überschrift   (... als Studienland   entschieden?)
-- | --
  | *** Zwischenüberschrift über   Itemliste fehlt: "Ich habe mich für ein Studium in Deutschland   entschieden, ..."
  | *** Schreibfehler im Item (auf   der Möglichkeit, nach Studienabschluss in Deutschland zu arbeiten) -->   muss heißen "aufgrund..."



- [ ] Anpassung F1_10

F1_10 | *** Items 1 und 2 (Art des   Auslandsaufenthalts) muss lauten     1: … Auslandsstudium mit angestrebten Abschluss in   Deutschland; 2: ... Auslandsstudium/-semester ohne   angestrebten Abschluss in Deutschland
-- | --
  | Überschrift über 1.   Dropdown-Menü fehlt: "Art des Auslandsaufenhalts"
  | *** Zwischenüberschrift zwischen   Monat/Jahr fehlen: "Start des Auslandsaufenthalts" und   "voraussichtliches Ende des Auslandsaufenthalts"
  | *** im oberen Teil (Start des   Auslandsaufenthalts) fehlt das Jahr 2010
  | *** Alternierende   Hintergrundfarben bei "Jahr" entfernen
  | *** Bitte die Dropdown-Menüs mit   Menüberschrift-Kategorie programmieren:     1. Dropdown: Bitte "Art des Auslandsaufenthalts" an 1. Stelle des   Dropdown-Menüs ergänzen --> Wert "0"     2. Dropdown-Menü: Bitte "Start des Auslandsaufenthalts" an 1.   Stelle des Dropdown-Menüs ergänzen    --> Wert "0"     3. Dropdown-Menü: Bitte "vrstl. Ende des Auslandsaufenthalts" an   1. Stelle des Dropdown-Menüs ergänzen    --> Wert "0"



- [ ] Anpassung F1_11

F1_11 | *** Schreibfehler: "Ja, ich   plane den Abschluss eines Studiums in Deutschland (z. BA...) -->   Satzendzeichen fehlt
-- | --
  | *** Schreibfehler: "Ja, ich   plane einen Doppelabschluss in Deutschland und in meinem..."
  | *** graue Verbindungslinie der   vertikalen Skala entfernen (generell bei diesem Fragetyp)
  | *** Bitte Item "weiß ich   noch nicht" durch eine Leerzeile absetzen



- [ ] Anpassung F1_12

F1_12 | *** Überschrift: Wissen Sie   bereits..., z. B. in Form VON ECTS-Punkten?
-- | --
  | *** graue Verbindungslinie der   vertikalen Skala entfernen (generell bei diesem Fragetyp)
  | *** Bitte offene Felder bündig   setzen
  | *** Item "weiß ich noch   nicht" fehlt; wenn programmiert: Bitte Item "weiß ich noch   nicht" durch eine Leerzeile absetzen
  | *** ist es möglich in beide   offene Felder "Anzahl ECTS-Punkte" als hellgrauen Text bereits   hineinzuschreiben? Wenn ja, bitte umsetzen



- [ ] Anpassung F1_13

F1_13 | *** statt   "Mehrfachnennungen sind möglich" bitte einfügen "Bitte alles   Zutreffende auswählen"
-- | --
  | *** vorletztes Item muss   heißen"ja, Programm einer internationalen Organisation"
  | *** ist es möglich in das offene   Feld "und zwar:" als hellgrauen Text bereits hineinzuschreiben?   Wenn ja, bitte umsetzen

- [ ] keine Anpassung F1_14 nötig

- [ ] Anpassung F1_15

F1_15 | *** Schreibfehler zweiter   Frageteil: Wie sicher fühlen Sie sich bislang in...
-- | --

- [ ] keine Anpassung F1_16 nötig

- [ ] keine Anpassung F1_17 nötig

- [ ] Anpassung F1_18

F1_18 | *** Bitte zweiten Frageteil:   "Würden Sie Ihren Freunden/Bekannten empfehlen, ein Studium in   Deutschland durchzuführen?" in nächster Zeile beginnen
-- | --


- [ ] Anpassung F1_19

F1_19 | *** offene Angabefelder bitte   etwas breiter darstellen
-- | --
  | *** Bitte statt "   Ort/Hochschule" --> "Stadt/Hochschule" schreiben
  | Bitte Fragetext anpassen   "...in welchem Land, an welchem Ort bzw. an welcher   Hochschule hätten Sie..."
  | *** Bitte 2. Teil der Frage in   nächste Zeile beginnen "Hinsichtlich Ihres Auslandsaufenthalts:     Wenn Sie die freie Wahl gehabt hätten, in welchem Land, an welchem Ort bzw.   an welcher Hochschule hätten Sie am liebsten studiert?"
  | *** graue Verbindungslinie der   vertikalen Skala entfernen (generell bei diesem Fragetyp)
  | *** ist es möglich in das 1.   offene Feld "Land" und in das 2. offene Feld   "Ort/Hochschule" als hellgrauen Text bereits hineinzuschreiben?   Wenn ja, bitte umsetzen
  | *** Bitte Item "weiß ich   noch nicht" durch eine Leerzeile absetzen


- [ ] Anpassung F1_20

F1_20 | *** statt   "Mehrfachnennungen sind möglich" bitte einfügen "Bitte alles   Zutreffende auswählen" programmierne
-- | --
  | *** Fragetext falsch. Muss   heißen: "Welche der Hilfestellungen für Studierende   haben Sie bisher genutzt?"
  | *** Bitte Item "kein   Angebot" durch eine Leerzeile absetzen. Exklusivkategorie
  | *** Schreibfehler 2. Item:   .../BegrüßungsveranstaltungEN


- [ ] Anpassung F1_21

F1_21 | *** Schreibfehler im Fragetext   "...direkt…"
-- | --
  | *** Item "weiß ich noch   nicht" fehlt (abgetrennt durch Leerzeile)


- [ ] keine Anpassung F1_22 nötig

- [ ] Anpassung F1_23

F1_23 | *** Schreibfehler 2. Item:   "Ich verstehe …"   (ohne n)
-- | --


- [ ] Anpassung F1_24

F1_24 | *** Bitte transition prüfen:   Weiterleitung zum nächsten Modul und nicht ans Ende der Befragung
-- | --
  | *** "kann ich nicht   beurteilen" etwas absetzten und als Missing-Kategorie programmieren,   d.h. keine graue Verbindungslinie zur Skala
  | *** Schreibfehler   "überhaupt nicht gut"
