### ISSUE TITLE
Seiten im Grundprogramm (Modul A) verschoben

### ISSUE THREAD

**Issue by markusloe** [dzhw/SiD#76]
Liebe Alle,

ich habe im Grunprogramm (Modul A) an 4 Stellen Seiten verschoben:

(1) Seiten SDK-sde01 bis SDK-gub01 (Zeilen 1663-1964) verschoben nach Seite B16 (Zeile 659)
(2) Seiten SDK-stu14 und SDK-stu15 (Zeilen 1363-1412) verschoben nach Seite SDK-scr03 (Zeile 706)
(3) Seite SDK-stu4 (Zeile 976-1029) verschoben nach Seite SDK-stu6 (Zeile 1187)
(4) Seiten SDK-fin01 und SDK-fin04 (Zeilen 3711-3840) verschoben nach Seite SDK-vbi1001 (Zeile 3024)

Im nächsten Schritt würde ich gerne Seiten zusammenfassen - bitte Änderungen prüfen/akzeptieren und kurz Rückmeldung geben. Dann würde ich mit dem nächsten Schritt beginnen.

Beste Grüße,
Markus

**Comment by karbecke** [comment]
siehe --> 727563f

**Comment by SilinaKowalewski** [comment]
Wir haben die Seitenreihenfolge angepasst und committed. 

Du kannst nun mit dem nächsten Schritt beginnen.
