### ISSUE TITLE
SDK-sde10: Fragetyp - Klärungsbedarf

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#77]
Die Frage [SDK-sde10](https://github.com/dzhw/SiD/blob/727563feb56d66ad86431c9bbb8b670b1bc9b793/Modul_Grundprogramm.md#sdk-sde10) kann nicht, wie in der PV vorgesehen, umgesetzt werden. 

Mehrere Fragetypen können nicht in einer Frage kombiniert werden.

**Comment by SilinaKowalewski** [comment]
als zwei Fragen (pro Item Vater/Mutter) programmieren - offen und boolisch

**Comment by andreaschu** [comment]
ist nun [A_33](https://github.com/dzhw/SiD/blob/master/Modul_Grundprogramm.md#a_33).
