### ISSUE TITLE
SDK-stu17: Klärungsbedarf

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#78]
Die Frage [SDK-stu17](https://github.com/dzhw/SiD/blob/727563feb56d66ad86431c9bbb8b670b1bc9b793/Modul_Grundprogramm.md#sdk-stu17-2) tritt aktuell exakt, oder in etwa gleich, insgesamt drei mal im Grundmodul auf. Soll das so sein? 

[SDK-stu17-1](https://github.com/dzhw/SiD/blob/727563feb56d66ad86431c9bbb8b670b1bc9b793/Modul_Grundprogramm.md#sdk-stu17-1)
[SDK-stu17-3](https://github.com/dzhw/SiD/blob/727563feb56d66ad86431c9bbb8b670b1bc9b793/Modul_Grundprogramm.md#sdk-stu17-3)

**Comment by markusloe** [comment]
Hi Silina,

ja SDK-stu17-3 ist doppelt - würde ich in der nächsten Korrekturrunde des Grundprogramms rausnehmen

**Comment by andreaschu** [comment]
SDK-stu17-1 --> [A_49a](https://github.com/dzhw/SiD/blob/master/Modul_Grundprogramm.md#a_49a)
SDK-stu17-3 --> [A_49b](https://github.com/dzhw/SiD/blob/master/Modul_Grundprogramm.md#a_49b)

**Comment by markusloe** [comment]
Siehe transition in A_48 
- Studierende mit Bachelorabschluss kommen auf Seite A_49a
- Studierende mit Master u.a. kommen auf Seite A_49b
