### ISSUE TITLE
Seiten in Grundprogramm (Modul a) gelöscht/eingefügt/verändert

### ISSUE THREAD

**Issue by markusloe** [dzhw/SiD#79]
Liebe Alle,

ich habe nun im Grundprogamm (Modul A) folgende Seiten gelöscht (a), eingefügt (b) und verändert (c) (8b6eb07 ):

(a) gelöscht:
SDK-vbi3 bis SDK-vbi3_1 (Zeile 2539-2641)
SDK-vbi5 (Zeile 2696-2753)
SDK-stu06 (Zeile 1373-1426)
SDK-stu06 (Zeile 1481-1530)

(b) eingefügt aus Modul B1 (Geschlecht)
B1_9 und B1_10 (Zeile 900-1014)

(c) verändert:
Frageformulierung in SDK-vbi_1 (Zeile 2767-2769)
Antwortformat auf 2 offene Fachangaben in SDK-stu07 

Bitte prüfen und akzeptieren - sobald ich von euch Rückmeldung habe, würde ich mich an den dritten Schritt machen und die Seiten neu benennen (A_1 bis A_X).

Vielen Dank und beste Grüße,
Markus

**Comment by SilinaKowalewski** [comment]
Änderungen wurden umgesetzt. 

@markusloe: Du kannst nun neue Seitenzahlen vergeben.

**Comment by markusloe** [comment]
Grazie!

Von: SilinaKowalewski [mailto:notifications@github.com]
Gesendet: Donnerstag, 17. Oktober 2019 09:11
An: dzhw/SiD
Cc: Lörz, Markus; Mention
Betreff: Re: [dzhw/SiD] Seiten in Grundprogramm (Modul a) gelöscht/eingefügt/verändert (#79)


Änderungen wurden umgesetzt.

@markusloe<https://github.com/markusloe>: Du kannst nun neue Seitenzahlen vergeben.
