### ISSUE TITLE
Sammelissue: Graue Verbindungslinien bei SingleChoice-Fragen entfernen

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#82]
Bitte die **graue Verbindungslinie** der Skala entfernen. 

Dies gilt zunächst für folgende Fragen: 

- [ ] F1_3
- [ ] F1_6
- [ ] F1_11
- [ ] F1_12
- [ ] F1_19

**Comment by SilinaKowalewski** [comment]
@pbornkessel: Da hatten wir wohl die gleiche Idee :) Werde dieses Issue nun schließen und deins anpassen.

**Comment by pbornkessel** [comment]
Vor allem waren wir exakt gleich vom timing ^^
Ich fange heute damit an, erste issues zu erstellen und führe das dann über die nächste Woche weiter…

Danke fürs Anpassen. Daran orientiere ich mich dann für die weiteren issues.

Von: SilinaKowalewski [mailto:notifications@github.com]
Gesendet: Freitag, 18. Oktober 2019 10:52
An: dzhw/SiD
Cc: Bornkessel, Philipp; Mention
Betreff: Re: [dzhw/SiD] Sammelissue: Graue Verbindungslinien bei SingleChoice-Fragen entfernen (#82)


@pbornkessel<https://github.com/pbornkessel>: Da hatten wir wohl die gleiche Idee :) Werde dieses Issue nun schließen und deins anpassen.
