### ISSUE TITLE
Sammelissue: Graue Verbindungslinie entfernen bei vertikalen/horizontalen Nominal-/Ordinalskalen

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#83]
Bitte vertikale/horizontale Nominal-/Ordinalskalen **ohne** graue Verbindungslinie der items/Antwortkategorien.

Für die Module C1, D1, D3, F1 betrifft das die folgenden Seiten:

- [x] C1_1
- [x] C1_5
- [x] C1_9
- [x] C1_14
- [x] D1_1
- [x] D1_6
- [x] D1_9
- [x] D1_10a
- [x] D1_28
- [x] D3_1
- [x] D3_13
- [x] D3_14
- [x] D3_15
- [x] D3_17
- [x] F1_3
- [x] F1_6
- [x] F1_11
- [x] F1_12
- [x] F1_19

Für die anderen Module werden die entsprechend zu ändernden Seiten als Antwort auf dieses issue hierunter sukzessive ergänzt.

**Comment by vdick** [comment]
nach nächsten Rollout verfügbar

**Comment by karbecke** [comment]
Bitte für die Module F2, F3, C3 folgende Seiten ergänzen:

- [ ] C3_3

- [ ] F2_3
- [ ] F2_9
- [ ] F2_10
- [ ] F2_18

- [ ] F3_3
- [ ] F3_9
- [ ] F3_17
- [ ] F3_18
- [ ] F3_21
- [ ] F3_23
- [ ] F3_24

**Comment by soheiss** [comment]
Bitte auch für C2 auf folgenden Seiten umsetzen:

- [ ] C2_4
- [ ] C2_5
- [ ] C2_6
- [ ] C2_8
- [ ] C2_12

Liebe Grüße& vielen Dank

**Comment by vdick** [comment]
Ab nächsten Rollout verfügbar

**Comment by lenamzimmer** [comment]
Bitte auch für B1 und B2 für folgende Fragen umsetzen:

- [ ] B1_1

- [ ] B1_8

- [ ] B2_4

- [ ] B2_5

Vielen Dank!

**Comment by vdick** [comment]
Ab nächsten Rollout verfügbar

**Comment by soheiss** [comment]
- [ ] C2_3

**Comment by vdick** [comment]
Ab nächsten Rollout verfügbar

**Comment by karbecke** [comment]
in Modul A bitte für folgende Seiten anpassen:

- [ ] A_1
- [ ] A_2
- [ ] A_3
- [ ] A_5
- [ ] A_6
- [ ] A_11
- [ ] A_12
- [ ] A_13
- [ ] A_16
- [ ] A_24
- [ ] A_25
- [ ] A_28
- [ ] A_35
- [ ] A_38
- [ ] A_40
- [ ] A_41
- [ ] A_42
- [ ] A_44
- [ ] A_46
- [ ] A_47
- [ ] A_48
- [ ] A_54
- [ ] A_55

**Comment by vdick** [comment]
A_35 nicht vorhanden

**Comment by vdick** [comment]
Ab nächsten Rollout verfügbar
