### ISSUE TITLE
Sammelissue: Skalentitel bei Matrix-Fragen anpassen. 

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#84]
Bei einigen Matrix-Fragen sind die Skalentitel sehr weit von der eigentlichen Skala entfernt. Bitte, wie im Issue #24 für folgende Fragen anpassen. 

- [x] F1_2
- [x] F1_14

 
 
 
**Hier ein Beispiel:** 

![image](https://user-images.githubusercontent.com/48087320/67080848-5120c000-f196-11e9-8e15-37c20439115b.png)

**Comment by pbornkessel** [comment]
Die Bezeichnung der Skalenendpunkte/-titel bitte näher an Skala rücken. Mindestens auf den "Rahmen" des jeweils ersten Items, der sich beim mouse-over zeigt (vielleicht sogar noch ein bisschen weiter rein - müsste man sich mal beides anschauen).

Anschließend bitte darauf achten, dass der Abstand zur Frageformulierung/Ausfüllanweisung nicht zu groß geworden ist. Das muss dann ggf. anschließend angepasst werden.

Für die Module C1, D1, D3 betrifft das die folgenden Fragen/pages:

- [ ]  C1_6
- [ ]  C1_7
- [ ]  C1_9
- [ ]  C1_10
- [ ]  C1_11
- [ ]  C1_12
- [ ]  D1_7
- [ ]  D1_8
- [ ]  D1_17
- [ ]  D1_18
- [ ]  D1_20
- [ ]  D1_21
- [ ]  D1_22
- [ ]  D1_23
- [ ]  D1_24
- [ ]  D1_25
- [ ]  D1_27
- [ ]  D1_28
- [ ]  D3_11
- [ ]  D3_12
- [ ]  D3_21
- [ ]  D3_22

**Comment by lenamzimmer** [comment]
Betrifft für B1 und B2 die folgenden Fragen:

- [ ] B1_2
- [ ] B1_8
- [ ] B2_5
- [ ] B2_6
- [ ] B2_8a
- [ ] B2_8b

Bei diesen Fragen sind Skalenendpunkte/-titel  in die erste Zeile Skala gerutscht. Bitte wieder nach oben ziehen:

- [ ] B2_1
- [ ] B2_2a
- [ ] B2_2b
- [ ] B2_3a
- [ ] B2_3b

**Comment by vdick** [comment]
wie bereits geschriben, B2_2a,B2_2b,B2_3a, B2_3b müssen erst umgebaut werde..
Der Rest ist ab nächten Rollout verfügbar

**Comment by karbecke** [comment]
in E1 betrifft das die folgenden Seiten

- [ ] E1_7
