### ISSUE TITLE
Sammelissue: Skalenbreite fixieren

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#86]
@vdick: 

Ist es möglich die Breite einer horizontalen Skala zu fixieren? Bei der Browseransicht sich Skalen häufig sehr breit gezogen und haben einen großen Abstand zwischen den einzelnen Skalenpunkten.

![image](https://user-images.githubusercontent.com/48087320/67081317-300c9f00-f197-11e9-8f22-7e18855369ac.png)

Das Projekt wünscht sich, dass die Skala hier "schmaler" wird bzw. nicht über den gesamten Bildschirm gezogen wird. Ist dies (zeitnah) umsetzbar?

**Comment by pbornkessel** [comment]
Trifft für die Module C1, D1 und D3 auf folgende Fragen zu:

- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by karbecke** [comment]
trifft für die Module C3, F1-F3 auf folgende Fragen zu:

- [ ] keine Frage in C3

- [ ] F1_1
- [ ] F1_2
- [ ] F1_9
- [ ] F1_14
- [ ] F1_16
- [ ] F1_17
- [ ] F1_22
- [ ] F1_23
- [ ] F1_24
 
- [ ] F2_1
- [ ] F2_2
- [ ] F2_8
- [ ] F2_13
- [ ] F2_14
- [ ] F2_15
- [ ] F2_16
- [ ] F2_19
- [ ] F2_20

- [ ] F3_1
- [ ] F3_2
- [ ] F3_11
- [ ] F3_12
- [ ] F3_13
- [ ] F3_14
- [ ] F3_22
- [ ] F3_25
