### ISSUE TITLE
Sammelissue: Infield text/Placeholder von offenen Fragen

### ISSUE THREAD

**Issue by SilinaKowalewski** [dzhw/SiD#87]
Für einige Fragen sollen Pre- bzw. Postfixes als infield text angezeigt werden und dafür die Pre- und Postfixes ausgeblendet werden. 

Dies gilt zunächst für folgende Fragen: 
- [ ] F1_1
- [ ] F1_12
- [ ] F1_13
- [ ] F1_19

@vdick: Bitte die Möglichkeit für infield texte "anschalten". 

Werde dann anhand der genannten Fragen testen ob alles wie gewünscht funktioniert.

**Comment by pbornkessel** [comment]
Es folgen die Fragen und Texte, die infield stehen sollen für die Module C1, D1, D3. Die Pre-/Postfixes dann bitte i. d. R. entfernen, es sei denn hier wurde explizit etwas anderes kommentiert.

- [ ] C1_2 --> "Alter Kind"; "Alter 1. Kind"; "Alter 2. Kind"; "Alter 3. Kind"; "Alter 4. Kind" in den jeweils eingeblendeten Eingabefeldern. Das Postfix "Jahre" hier bitte jeweils hinter dem jeweils eingeblendeten Eingabefeld stehen lassen.

- [ ] C1_4 --> "Anzahl Kinder" im Eingabefeld

- [ ] D1_2 --> "1. Prüfungsfach"; "2. Prüfungsfach"; "3. Prüfungsfach"; "4. Prüfungsfach"; "5. Prüfungsfach"; "Stunden je Woche"; "Note"; "Geschlecht" jeweils in den Drop-Downs

- [ ] D1_4 --> "Jahr"; "Monat" in je einem Eingabefeld
- [ ] D1_5 --> "gelernter Beruf" im Textfeld
- [ ] D1_6 --> "Note (z. B. 2,5)" im Eingabefeld
- [ ] D1_10 --> "Bundesland" im Drop-Down
- [ ] D1_11 --> "Hochschule" jeweils im Drop-Down und Textfeld
- [ ] D1_12 --> "Studienfach" im Eingabefeld
- [ ] D1_13 --> "Semester" im Drop-Down
- [ ] D1_14 --> "Anzahl" in allen Drop-Downs
- [ ] D3_2 --> "Personenzahl" in das Eingabefeld
- [ ] D3_3 --> "PLZ" in erstes Eingabefeld und "Ort" in zweites Eingabefeld
- [ ] D3_4 --> "m²" in beide Eingabefelder
- [ ] D3_6 "Betrag" in Eingabefelder; Postfix "€ im Monat" aber bitte alle stehen lassen. 
- [ ] D3_8 "Betrag" in Eingabefelder; Postfix "€ im Monat" aber bitte alle stehen lassen. 
- [ ] D3_9 "€" in Eingabefeld
- [ ] D3_10 "€" in Eingabefelder

**Comment by karbecke** [comment]
Dies betrifft für die Module C3, F2, F3 die folgenden Fragen:

- [ ] C3_1

- [ ] F2_1
- [ ] F2_7
- [ ] F2_8
- [ ] F2_10
- [ ] F2_11
- [ ] F2_14
- [ ] F2_18
- [ ] F3_1
- [ ] F3_8
- [ ] F3_9
- [ ] F3_12
- [ ] F3_17
- [ ] F3_19
- [ ] F3_21
- [ ] F3_23

**Comment by karbecke** [comment]
Bitte in den Modulen C3, F1,F2,F3 die Drop-Down-Menüs um die Postfix-Kategorie ergänzen

- [ ] betrifft keine Frage in C3

- [ ] F2_6 --> 1. Drop-Down-Menü bitte "Art des Auslandsaufenthalts" an erste Stelle setzen / Bitte in den entsprechenden Drop-Down-Menüs "Monat" und "Jahr" an erster Stelle ergänzen (Wert jeweils = "0")
- [ ] F3_7 --> wenn Seite programmiert, dann bitte Drop-Down-Menüs analog zu "F2_6" umsetzen
- [ ] F1_10 --> bitte Drop-Down-Menüs analog zu "F2_6" umsetzen

**Comment by dzhwmeisner** [comment]
> Es folgen die Fragen und Texte, die infield stehen sollen für die Module C1, D1, D3. Die Pre-/Postfixes dann bitte i. d. R. entfernen, es sei denn hier wurde explizit etwas anderes kommentiert.
> 
>     * [x]  C1_2 --> "Alter Kind"; "Alter 1. Kind"; "Alter 2. Kind"; "Alter 3. Kind"; "Alter 4. Kind" in den jeweils eingeblendeten Eingabefeldern. Das Postfix "Jahre" hier bitte jeweils hinter dem jeweils eingeblendeten Eingabefeld stehen lassen.
> 
>     * [x]  C1_4 --> "Anzahl Kinder" im Eingabefeld
> 
>     * [x]  D1_2 --> "1. Prüfungsfach"; "2. Prüfungsfach"; "3. Prüfungsfach"; "4. Prüfungsfach"; "5. Prüfungsfach"; "Stunden je Woche"; "Note"; "Geschlecht" jeweils in den Drop-Downs
> 
>     * [x]  D1_4 --> "Jahr"; "Monat" in je einem Eingabefeld
> 
>     * [x]  D1_5 --> "gelernter Beruf" im Textfeld
> 
>     * [x]  D1_6 --> "Note (z. B. 2,5)" im Eingabefeld
> 
>     * [ ]  D1_10 --> "Bundesland" im Drop-Down
> 
>     * [x]  D1_11 --> "Hochschule" jeweils im Drop-Down und Textfeld
> 
>     * [x]  D1_12 --> "Studienfach" im Eingabefeld
> 
>     * [ ]  D1_13 --> "Semester" im Drop-Down
> 
>     * [ ]  D1_14 --> "Anzahl" in allen Drop-Downs
> 
>     * [x]  D3_2 --> "Personenzahl" in das Eingabefeld
> 
>     * [x]  D3_3 --> "PLZ" in erstes Eingabefeld und "Ort" in zweites Eingabefeld
> 
>     * [x]  D3_4 --> "m²" in beide Eingabefelder
> 
>     * [x]  D3_6 "Betrag" in Eingabefelder; Postfix "€ im Monat" aber bitte alle stehen lassen.
> 
>     * [x]  D3_8 "Betrag" in Eingabefelder; Postfix "€ im Monat" aber bitte alle stehen lassen.
> 
>     * [x]  D3_9 "€" in Eingabefeld
> 
>     * [x]  D3_10 "€" in Eingabefelder

Dropdowns können keine Platzhalter enthalten.

**Comment by pbornkessel** [comment]
Wenn Drop-Downs keine extra infield-Platzhalter enthalten können, dann bitte für die Drop Downs in D1 Folgendes umsetzen:

- [ ]  D1_10 --> "Bundesland:" vor das Drop Down setzen und "im Ausland" nicht als voreingestellten Platzhalter anzeigen. Es soll also keine Kategorienvorauswahl im Drop-Down eingestellt sein bzw. sollte die Voreinstellung dann blank sein.

- [ ]  D1_13 --> "Semester:" vor das Drop Down setzen und "Sommersemester 2020" nicht als voreingestellten Platzhalter anzeigen. Es soll also keine Kategorienvorauswahl im Drop-Down eingestellt sein bzw. sollte die Voreinstellung dann blank sein.

- [ ]  D1_14 --> "einmal" nicht als voreingestellten Platzhalter anzeigen. Es soll also keine Kategorienvorauswahl im Drop-Down eingestellt sein bzw. sollte die Voreinstellung dann blank sein.

**Comment by SilinaKowalewski** [comment]
> Wenn Drop-Downs keine extra infield-Platzhalter enthalten können, dann bitte für die Drop Downs in D1 Folgendes umsetzen:
> 

@pbornkessel: Doch, dass geht. Das sind dann allerdings keine infield-Texte sondern Antwortoptionen. Deswegen hat Christian diese hier nicht mit bearbeitet.

**Comment by pbornkessel** [comment]
> Doch, dass geht. Das sind dann allerdings keine infield-Texte sondern Antwortoptionen. Deswegen hat Christian diese hier nicht mit bearbeitet.

@SilinaKowalewski 

Wäre es dann möglich die genannten infield-Texte als Antwortoption zu integrieren und ihnen keinen value bzw. euren missing-value für "Seite gesehen aber nicht geantwortet" zuzuordnen? Wir möchten nämlich vermeiden, dass eine gültige Antwortoption/ein gültiger Wert dort voreingestellt sind.

Sollte das so umsetzbar sein (mit der Antwortoption bzw. keinen/missing value), dann wäre es super, wenn ihr das auch für die infield-Texte der Drop-Downs umsetzen könntet.

**Comment by karbecke** [comment]
wie oben bereits geschrieben, dann bitte in den Modulen C3, F1,F2,F3 die Drop-Down-Menüs um die Antwort-Kategorie ergänzen:

- [ ] F2_6 --> 1. Drop-Down-Menü bitte "Art des Auslandsaufenthalts" an erste Stelle setzen / Bitte in den entsprechenden Drop-Down-Menüs "Monat" und "Jahr" an erster Stelle ergänzen (Wert jeweils = "0")

- [ ] F3_7 --> wenn Seite programmiert, dann bitte Drop-Down-Menüs analog zu "F2_6" umsetzen

- [ ] F1_10 --> bitte Drop-Down-Menüs analog zu "F2_6" umsetzen

Danke :-) !

**Comment by karbecke** [comment]
betrifft in E1

- [ ] keine Frage in E1
