### ISSUE TITLE
Sammelissue: Itemtexte bei Matrix-Fragen/Skalen/Itembatterien linksbündig

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#89]
Bitte bei Skalen mit mehreren Items, die Itemtexte linksbündig formatieren. Zum Teil ist auf einzelnen programmierten Seiten links (sehr) viel Platz, so dass die Frage insgesamt auch etwas rübergezogen werden kann.

Für die Module C1, D1, D3 trifft das auf folgende Fragen/pages zu

- [x] C1_6
- [x] C1_7
- [x] C1_9
- [x] C1_10
- [x] C1_11
- [x] C1_12
- [x] D1_7
- [x] D1_8
- [x] D1_17
- [x] D1_18
- [x] D1_20
- [x] D1_21
- [x] D1_22
- [x] D1_23
- [x] D1_24
- [x] D1_25
- [x] D1_27
- [x] D1_28
- [x] D3_11
- [x] D3_12
- [x] D3_21
- [x] D3_22

**Comment by karbecke** [comment]
Für die Module C3, F1, F2, F3 betrifft dies folgende Fragen:

- [ ] C3_2
- [ ] F1_1
- [ ] F1_2
- [ ] F1_9
- [ ] F1_14
- [ ] F1_16
- [ ] F1_17
- [ ] F1_23
- [ ] F2_1
- [ ] F2_2
- [ ] F2_8
- [ ] F2_13
- [ ] F2_15
- [ ] F2_16
- [ ] F3_1
- [ ] F3_2
- [ ] F3_11
- [ ] F3_13
- [ ] F3_22

**Comment by lenamzimmer** [comment]
Für Modul B1 und B2 bitte für folgende Fragen umsetzen:

- [ ] B1_2
- [ ] B1_3a
- [ ] B1_3b
- [ ] B1_5
- [ ] B1_8
- [ ] B2_1
- [ ] B2_2a
- [ ] B2_2b
- [ ] B2_3a
- [ ] B2_3b
- [ ] B2_4
- [ ] B2_5
- [ ] B2_6
- [ ] B2_7
- [ ] B2_8a
- [ ] B2_8b

Vielen Dank!

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by karbecke** [comment]
bitte auch folgende Frgen E1 diesbezüglich anpassen:

- [ ] E1_1
- [ ] E1_2
- [ ] E1_3
- [ ] E1_4
- [ ] E1_6
- [ ] E1_7
- [ ] E1_9
- [ ] E1_10
- [ ] E1_11
- [ ] E1_12

**Comment by vdick** [comment]
E1_12 existiert nicht
Ab nächsten Rollout verfügbar
