### ISSUE TITLE
F1: Textänderungen

### ISSUE THREAD

**Issue by andreaschu** [dzhw/SiD#91]
- [x] **F1_4:** statt "Mehrfachauswahl" bitte einfügen "Bitte alles Zutreffende   auswählen"
- [x] **F1_5:** Bitte statt "Bitte   alles Zutreffende ankreuzen." --> "Bitte alles Zutreffende   auswählen" schreiben
- [x] **F1_5:** Schreibfehler in Frage "...(mehr als 3 Monate) **I**m Ausland" --> Bitte "im" mit kleinem i schreiben
- [x] **F1_8:** Schreibfehler im 1. Item   (Studienberechtigung)
- [x] **F1_9:** Schreibfehler in Überschrift   (... als Studienland entschieden?)
- [x] **F1_9:** Schreibfehler im Item (auf der Möglichkeit, nach Studienabschluss in Deutschland zu arbeiten) --> muss heißen "aufgrund..."
- [x] **F1_9:** Zwischenüberschrift über Itemliste fehlt: "Ich habe mich für ein Studium in Deutschland entschieden, ..."
- [x] **F1_10:**  Item 1  (Art des Auslandsaufenthalts) muss lauten … Auslandsstudium mit angestrebten Abschluss in   Deutschland
- [x] **F1_10:** Item 2 (Art des Auslandsaufenthalts) muss lauten ... Auslandsstudium/-semester ohne   angestrebten Abschluss in Deutschland
- [ ] **F1_10:** Bitte die Dropdown-Menüs mit Menüberschrift-Kategorie programmieren: "Art des Auslandsaufenthalts" --> Wert "0"
- [ ] **F1_10:** Bitte die Dropdown-Menüs mit Menüberschrift-Kategorie programmieren: "Start des Auslandsaufenthalts" --> Wert "0"
- [ ] **F1_10:** Bitte die Dropdown-Menüs mit Menüberschrift-Kategorie programmieren: "vrstl. Ende des Auslandsaufenthalts" an   1. Stelle des Dropdown-Menüs ergänzen    --> Wert "0"
- [x] **F1_11:** Satzendzeichen fehlt: "Ja, ich plane den Abschluss eines Studiums in Deutschland (z. BA...) 
- [ ] **F1_12:** Antwortoption "weiß ich noch nicht" fehlt
- [x] **F1_13:** statt "Mehrfachnennungen sind möglich" bitte einfügen "Bitte alles Zutreffende auswählen"
- [x] **F1_15:** Schreibfehler zweiter Frageteil: Wie sicher fühlen Sie sich bislang in...
- [x] **F1_19:** Bitte Fragetext anpassen "...in welchem Land, an welchem Ort bzw. an welcher   Hochschule hätten Sie..."
- [x] **F1_20:** Schreibfehler 2. Antwortoption:   .../BegrüßungsveranstaltungEN
- [x] **F1_21:** Schreibfehler im Fragetext   "...direkt…"
- [x] **F1_23:** Schreibfehler 2. Item:   "Ich verstehe …"   (ohne n)
- [x] **F1_24:** "kann ich nicht beurteilen" als _mv:_ definieren
- [x] **F1_24:** Schreibfehler Skala "überhaupt nicht gut"

**Comment by karbecke** [comment]
@SilinaKowalewski noch offen aus der obigen Liste ist:  
- [ ] F1_12: Antwortoption "weiß ich noch nicht" fehlt

Bitte ergänzen. Danke!

**Comment by SilinaKowalewski** [comment]
> @SilinaKowalewski noch offen aus der obigen Liste ist:
> 
> * [ ]  F1_12: Antwortoption "weiß ich noch nicht" fehlt
> 
> Bitte ergänzen. Danke!

Wo soll denn diese Antwortoption stehen und welches Value haben? Ist in der PV nicht drin.

**Comment by karbecke** [comment]
siehe --> 926a831
