### ISSUE TITLE
Sammelissue: Positionierung von items und Skalenpunkten zueinander in Matrixfragen/Skalen/Itembatterien

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#92]
Bei den meisten Matrixfragen/Skalen/Itembatterien sind zumindest einzeilige Itemformulierungen nicht bündig zu/in einer Linie mit den Skalenpunkten/buttons. Dies kommt sowohl bei Fragen vor, bei denen alle Items einzeilig formuliert sind, als auch bei Fragen, bei denen ein-, zwei- und/oder dreizeilige Items formuliert sind. Ist es nicht möglich die Items individuell auf passender Höhe zu den buttons zu positionieren?

Für die Module C1, D1, D3 trifft das auf folgende Fragen/pages zu:

- [x] C1_6
- [x] C1_7
- [x] C1_9
- [x] C1_10
- [x] C1_11
- [x] C1_12
- [x] D1_7
- [x] D1_8
- [x] D1_17
- [x] D1_18
- [x] D1_20
- [ ] D1_21
- [ ] D1_22
- [ ] D1_23
- [ ] D1_24
- [ ] D1_25
- [ ] D1_27
- [ ] D1_28
- [ ] D3_11
- [ ] D3_12
- [ ] D3_21
- [ ] D3_22

**Comment by karbecke** [comment]
Für die Module C3, F1, F2, F3 

- [ ] C3 nicht betroffen
- [ ] F1_1
- [ ] F1_2
- [ ] F1_9
- [ ] F1_14
- [ ] F1_16
- [ ] F1_17
- [ ] F1_22
- [ ] F1_23
- [ ] F1_24
- [ ] F2_1
- [ ] F2_2
- [ ] F2_8
- [ ] F2_13
- [ ] F2_14
- [ ] F2_15
- [ ] F2_16
- [ ] F2_19
- [ ] F2_20
- [ ] F3_1
- [ ] F3_2
- [ ] F3_11
- [ ] F3_12
- [ ] F3_13
- [ ] F3_14
- [ ] F3_22
- [ ] F3_25

**Comment by lenamzimmer** [comment]
Für die Module B1 und B2 bitte für folgende Fragen anpassen:

- [ ] B1_2
- [ ] B1_3a
- [ ] B1_3b
- [ ] B1_5
- [ ] B1_8
- [ ] B2_4
- [ ] B2_5
- [ ] B2_6
- [ ] B2_7
- [ ] B2_8a
- [ ] B2_8b

Vielen Dank!

**Comment by karbecke** [comment]
aktuell nicht priorität: 
Für E1 bitte die folgenden Seiten diesbezüglich anpassen

- [ ] E1_1
- [ ] E1_2
- [ ] E1_3
- [ ] E1_6
- [ ] E1_7
- [ ] E1_9
- [ ] E1_10
- [ ] E1_11
