### ISSUE TITLE
Sammelissue: Zeilenumbrüche von Skalenendpunkten

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#95]
Bei Matrixfragen/Skalen/Itembatterien kommt es vor, dass einer der belabelten Skalenendpunkte nicht in die zweite Zeile umbricht, der andere aber schon. Es wäre gut, dies zu vereinheitlichen, also das entweder beide Skalenendpunkte umbrechen oder keiner (gilt generell für Skalenpunkte)

Aus den Modulen C1, D1, D3 betrifft das die folgenden Fragen/pages:

- [x] C1_10 
- [x] C1_11
- [x] D1_17
- [x] D1_18
- [x] D1_22
- [x] D1_23
- [x] D1_24
- [x] D1_25
- [x] D3_11
- [x] D3_12
- [x] D3_21
- [x] D3_22

**Comment by SilinaKowalewski** [comment]
> * [ ]  F2_8 --> Umbrauch der Skalenbeschriftung bitte einheitlich umsetzen, wenn möglich
> * [ ]  F2_15 --> Umbrauch der Skalenbeschriftung bitte einheitlich umsetzen, wenn möglich
> * [ ]  F2_20 --> Umbrauch der Skalenbeschriftung bitte einheitlich umsetzen, wenn möglich
> * [ ]  F3_1 --> Umbrauch der Skalenbeschriftung bitte einheitlich umsetzen, wenn möglich
> * [ ] F3_13 --> Umbrauch der Skalenbeschriftung bitte einheitlich umsetzen, wenn möglich

**Comment by karbecke** [comment]
betrifft:

- [ ] nicht C3

- [ ] F1_1
- [ ] F1_9
- [ ] F1_16
- [ ] F1_23
- [ ] F1_24
- [ ] F2_1
- [ ] (F2_8) s.o.
- [ ] (F2_15) s.o.
- [ ] (F2_20) s.o.
- [ ] (F3_1) s.o.
- [ ] (F3_13) s.o.

**Comment by lenamzimmer** [comment]
Gilt in den Modulen B1 und B2 für folgende Fragen:

- [ ] B1_2
- [ ] B1_5
- [ ] B2_4
- [ ] B2_6

**Comment by vdick** [comment]
ab nächsten Rollout verfügbar

**Comment by karbecke** [comment]
für E1 betrifft dies:

- [ ] E1_3
- [ ] E1_4 --> weiß ich {break} nicht
- [ ] E1_11 --> interessiert {break} mich nicht

**Comment by SMajer** [comment]
Gilt in den Modulen  Fairness, Politik und Master-Vignetten für:

- [ ] KSM-fai03
- [ ] KSM-pol05
- [ ] KSM-pol06
- [ ] KSM-ma09
