### ISSUE TITLE
Sammelissue: Abstände Antwortoptionen/Items

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#97]
Bei verschiedenen Fragen/Skalen stehen die jeweiligen Antwortoptionen/Items etwas weit auseinander. Das Ganze wirkt dann sehr 'luftig'.  Wäre es möglich, die Antwortoptionen zumindest ein wenig näher zusammenzurücken bzw. die Abstände zueinander ein wenig zu verringern?  Für Matrixfragen/Itembatterien hängt das wahrscheinlich auch mit issue #92 zusammen.

Für die Module C1, D1, D3 sind folgende Fragen/pages betroffen: 

- [x] C1_1
- [x] C1_5
- [x] C1_6
- [x] C1_7
- [x] C1_9
- [x] C1_10
- [x] C1_11
- [x] C1_12
- [x] C1_14
- [x] D1_7
- [x] D1_8
- [x] D1_9
- [x] D1_17
- [x] D1_18
- [x] D1_19
- [x] D1_20
- [x] D1_21
- [x] D1_24
- [x] D1_25
- [x] D1_27
- [x] D1_28
- [x] D3_1
- [x] D3_11
- [x] D3_12
- [x] D3_13
- [x] D3_14
- [x] D3_15
- [x] D3_17
- [x] D3_21
- [x] D3_22

**Comment by lenamzimmer** [comment]
Für die Module B1 und B2 bitte für folgende Fragen anpassen:

- [ ] B1_1
- [ ] B1_2
- [ ] B1_5
- [ ] B1_8
- [ ] B2_1
- [ ] B2_2a
- [ ] B2_2b
- [ ] B2_3a
- [ ] B2_3b
- [ ] B2_4
- [ ] B2_5
- [ ] B2_6
- [ ] B2_7
- [ ] B2_8a
- [ ] B2_8b

Vielen Dank

**Comment by vdick** [comment]
@pbornkessel  wie gerade besprochen,
die Fragen B2_2a, B2_2b, B2_3a, B2_3b  können leider nicht umgesetzt werden, bitte einen alterniven Vorschlag machen. 
Alle anderen Fragen sind ab nächsten Rollout verfügbar

**Comment by karbecke** [comment]
für E1 siehe #92
