### ISSUE TITLE
Sammelissue: Abstände Antwortkategorien/Items usw. zu Fragen/Ausfüllanweisungen

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#98]
Auf einzelnen pages ist viel Platz zwischen der ersten Antwortoption/dem ersten Item/Eingabefeld/Drop-Down usw. und der dazugehörigen Frage/Ausfüllanweisung. Es wäre schön, wenn der Abstand ein wenig verringert werden könnte. Dieses issue hängt wahrscheinlich auch mit dem issue #84  zusammen, jedenfalls für Matrixfragen/Itembatterien.

Für die Module C1, D1, D3 sind folgenden Fragen/pages betroffen:

- [x] C1_1
- [x] C1_3
- [x] C1_4
- [x] C1_5
- [x] C1_14
- [x] D1_3
- [x] D1_4
- [x] D1_5
- [x] D1_9
- [x] D1_10a
- [x] D1_10
- [x] D1_11
- [x] D1_14
- [x] D3_1
- [x] D3_2
- [x] D3_3
- [x] D3_4
- [x] D3_7
- [x] D3_9
- [x] D3_10
- [x] D3_13
- [x] D3_14
- [x] D3_15
- [x] D3_17
- [x] D3_18

**Comment by karbecke** [comment]
in den Fragen C3, F1, F2, F3 mMn. nicht relevant

**Comment by andreaschu** [comment]
@karbecke was heißt "mMn. nicht relevant"? Geht das an uns oder ist das eine teaminterne Diskussion? Bitte so etwas an Personen richten und Labels ändern, sonst können wir das nicht einschätzen. Wir müssen wissen, was umgesetzt werden soll.
