### ISSUE TITLE
Sammelissue: Positionierung Text-/Eingabefelder

### ISSUE THREAD

**Issue by pbornkessel** [dzhw/SiD#99]
Bitte, wenn möglich, für die folgenden Fragen/pages die darauf befindlichen Eingabe-/Textfelder in einer gemeinsamen Zeile hinter die dazugehörige Antwortoption/das dazugehörige Item setzen (insbesondere bei den ganzen "Anderes-Kategorien"). Falls nötig, die Eingabefelder optisch auch gerne etwas kleiner ziehen (aber bitte nicht die Zeichenanzahl verringern), damit es passt.

Für die Module C1, D1, D3 betrifft das die folgenden Fragen/pages:

- [ ] C1_6
- [ ] C1_7
- [ ] C1_9
- [ ] D1_7
- [ ] D1_8
- [ ] D1_21
- [ ] D3_6 -> bitte nur für die Nennung der weitere(n) Finanzierungsquelle(n)
- [ ] D3_8 ->  bitte nur für die Nennung weiterer Ausgaben

**Comment by SMajer** [comment]
Gilt in den Modulen Fairness, Politik, Studienanfang, Master-Vignetten, Promotion-Vignetten für:

- [ ] KSM-fai05
- [ ] KSM-fai17
- [ ] KSM-pol03
- [ ] KSM-pol04
- [ ] KSM-pol05
- [ ] KSM-pol06
- [ ] KSM-anf02 --> nach derzeitiger **Fragebogenvorschau** (25.10.19)
- [ ] KSM-anf03 --> nach derzeitiger **Fragebogenvorschau** (25.10.19)
- [ ] KSM-anf04 --> nach derzeitiger **Fragebogenvorschau** (25.10.19)
- [ ] KSM-anf05 --> nach derzeitiger **Fragebogenvorschau** (25.10.19)
- [ ] KSM-ma05
- [ ] KSM-ma07
- [ ] KSM-ma08
- [ ] KSM-phd02
- [ ] KSM-phd03
